### ISSUE TITLE
Red paperclip error when clustering

### ISSUE THREAD

**Issue by danoo1** [UKPLab/sentence-transformers#1003]
Hi, I have been trying to implement your clustering example here https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/clustering/fast_clustering.py
I have a dataset of about 200k lines that I am trying to cluster but I am getting an error when encoding the corpus as shown in the picture uploaded then the kernal dies. What does the error mean? Is it likely that I am running out of ram? Thanks.

![Screenshot 2021-06-14 at 14 54 05](https://user-images.githubusercontent.com/49159654/121903898-a7a22100-cd20-11eb-986e-29249100754a.png)

**Comment by nreimers** [comment]
I think you run out out ram.

Clustering currently takes quadratic number of memory, i.e. 200k * 200k * 4 bytes to compute the cosine similarity.

I hope I can add a more memory efficient clustering soon. Until then, it makes sense to run it on smaller chunks of your data (e.g. just 50k data).

**Comment by danoo1** [comment]
Thanks.
