### ISSUE TITLE
Data augmentation script : 'LoggingHandler' is not defined

### ISSUE THREAD

**Issue by ClementViricel** [UKPLab/sentence-transformers#1014]
Well, it's a pretty easy fix but i let you do it.

I think you forgot to import LoggingHandler from sentence_transformer so it throw an error : 

`python3 train_sts_qqp_crossdomain.py
Traceback (most recent call last):
  File "train_sts_qqp_crossdomain.py", line 40, in <module>
    handlers=[LoggingHandler()])
NameError: name 'LoggingHandler' is not defined`

EDIT : You also forgot to add SentenceTransformer
quick fix at line 20 : 
`from sentence_transformers import models, losses, util, LoggingHandler, SentenceTransformer`

**Comment by nreimers** [comment]
Thanks for pointing this out.
