### ISSUE TITLE
Does the magnitude of embeddings encode anything meaningful?

### ISSUE THREAD

**Issue by kddubey** [UKPLab/sentence-transformers#1015]
My guess (and hope) is no b/c we're usually just taking cosine similarities, which are insensitive to magnitude.

The reason I ask is that taking means of unnormalized embeddings is sensitive to magnitude (as in, the mean of unnormalized embeddings can point in a different direction than the mean of normalized embeddings), and there are places in the repo where this is done. Two examples are [k-means](https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/clustering/kmeans.py) (which relies on Euclidean distance, which is also sensitive to magnitude) and [mean-pooling across tokens](https://www.sbert.net/docs/package_reference/models.html#sentence_transformers.models.Pooling).

**Comment by nreimers** [comment]
Hi @kddubey 
The magnitude is not really interpretable. 

This can be indeed an issue for k-means.

**Comment by kddubey** [comment]
Is it sensible to normalize embeddings before taking means?

Thanks!

**Comment by nreimers** [comment]
It tested both, training models with and without normalized embeddings: There was not large difference for clustering with k-means, both performed about on-par. The normalized embeddings where slightly worse (but not really much, like 0.1 points across many tasks and train setups)

**Comment by kddubey** [comment]
Great, thanks for the experiment! I was indeed hoping to run k-means, and this gives me some reassurance.
