### ISSUE TITLE
Changing output Pooling option

### ISSUE THREAD

**Issue by spectraldoy** [UKPLab/sentence-transformers#1029]
I am currently unfamiliar with how to change the output Pooling method of a loaded SentenceTransformer, which I know would be problematic in a fine-tuning use-case, but would be very useful in a simple transfer learning use-case, as I would be able to pick the Pooling method that provides the highest accuracy. If anyone could show me how to do that, or direct me to any resources that could, it would be much appreciated. If changing the Pooling method of a loaded SentenceTransformer can't be done currently, I wanted to ask if this could be included in the `model.encode` function as an option for the `output_value` key.

Thank you.

**Comment by nreimers** [comment]
This code works:
```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-MiniLM-L6-v2')
model._modules["1"].pooling_mode_mean_tokens = False
model._modules["1"].pooling_mode_cls_token = True
print(model._modules["1"])

```
