### ISSUE TITLE
Using adapter-transformers model with sbert to obtain sentence embedding

### ISSUE THREAD

**Issue by jithu-chandran** [UKPLab/sentence-transformers#1031]
Hi, I am working with adapter-transformer architecture. I trained an adapter on a classification task and loaded it into a roberta-base model. I want to extract sentence embedding from this adapter-transformer model using sbert. These sentence embedding is further passed into [Bertopic ](https://github.com/MaartenGr/BERTopic) to generate important topics. The idea is to visualize the cluster of topics formed by the adapter-transformer model fine tuned on a classification task. Below is the code provided.

```python
tmp_pwd = %pwd
full_model_path = os.path.join(tmp_pwd, 'models' ,'full_adapter_transformer_model')

model.save_pretrained(full_model_path)

tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
tokenizer.save_pretrained(full_model_path)

###############################

from sentence_transformers import SentenceTransformer, models as s_models

word_embedding_model = s_models.Transformer(full_model_path)
# pooling_model = s_models.Pooling(word_embedding_model.get_word_embedding_dimension())
pooling_model = s_models.Pooling(word_embedding_model.get_word_embedding_dimension(),pooling_mode='mean')
st_model = SentenceTransformer(modules=[word_embedding_model, pooling_model])


###################################


topic_model = BERTopic(embedding_model=st_model,calculate_probabilities=True)

topics, probs = topic_model.fit_transform(docs)
topic_model.get_topics()
```

The code is executing well, however, there is a warning message stating that the adapters are not activate for forward pass. The warning messages are as below:

```
Some weights of RobertaModel were not initialized from the model checkpoint at /content/drive/MyDrive/practicum/interpretability/models/full_adapter_transformer_model and are newly initialized: ['roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
There are adapters available but none are activated for the forward pass.
There are adapters available but none are activated for the forward pass.
.....
```
Additionally, the number of topics produced by Bertopic using my fine tuned model is reasonable when pooling_mode='mean', though not very good as compared to the default configuration of Bertopic. However, the performance of the Bertopic model is extremely poor when I use pooling_mode='cls' or pooling_mode='max'. What could be the reason for this under performance? Is it something to do with the fact that sbert is not able to correctly extract sentence embedding from an adapter-transformer model?

**Comment by nreimers** [comment]
I'm not too familiar with adapter-transformer, but likely you must replace the models.Transformer class with your specific adapter-transformer class.

Otherwise this class loads AutoModel from the transformers repository, i.e. without adapters

**Comment by jithu-chandran** [comment]
> 
> 
> I'm not too familiar with adapter-transformer, but likely you must replace the models.Transformer class with your specific adapter-transformer class.
> 
> Otherwise this class loads AutoModel from the transformers repository, i.e. without adapters

Thanks for the reply. Yeah, I just modified model.Transformer to set the adapters active via the set_active_adapters() command that the adapters are now getting used in the forward pass.
