### ISSUE TITLE
[2.0] Bug with `.fit` model card - `json.dumps` fails when `callback` is not None

### ISSUE THREAD

**Issue by chiragjn** [UKPLab/sentence-transformers#1034]
https://github.com/UKPLab/sentence-transformers/blob/2e7e20880f9a4a9969bc1684eec393263fb697bc/sentence_transformers/SentenceTransformer.py#L612

Fails because python functions by default are not JSON serializable. I thought of submitting a fix with `fullname` but that seems to be only for methods on a class.

**Comment by nreimers** [comment]
Thanks for reporting. Will try to fix it asap.

**Comment by lukesalamone** [comment]
This issue is fixed in https://github.com/UKPLab/sentence-transformers/pull/1133
