### ISSUE TITLE
A dependence issue when I install by pip

### ISSUE THREAD

**Issue by Zeng1998** [UKPLab/sentence-transformers#1046]
I install pytorch(cpu 1.7.1) first

```
pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

And when I install sentence-transformers by pip, it automatically download and install pytorch==1.9.0. Why? Can I just use the local installed pytorch==1.7.1

```
Collecting torch>=1.6.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d2/a9/b3cea4a97ffabd6639e71608814dbd08081e202e8ac9580250273c0541ff/torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
```

**Comment by nreimers** [comment]
Yes, you can use it.

maybe run pip with --no-deps as command when installing sentence  transformers
