### ISSUE TITLE
Performance issues with paraphrase-MiniLM-L6-v2

### ISSUE THREAD

**Issue by joseph-macraty** [UKPLab/sentence-transformers#1050]
Hi, 

I am currently using ```paraphrase-MiniLM-L6-v2``` for semantic search with cosine similarity. However, I am not sure if this is the expected performance. Here is a query I used: 
```
careers
```
The search results gave a higher score to ```Academic life``` than ```Work with us``` for the query. I also tested it [here](https://huggingface.co/sentence-transformers/paraphrase-MiniLM-L6-v2), yielding the same result. Is the expected? Most of my queries are 1-4 words and the data to be searched is also generally 1-5 words on average. Am I using the wrong model/Is there a better model suited for this length? My data is pretty general without any field-specific text. Thanks!

**Comment by nreimers** [comment]
You can try to use the MSMARCO models.

But you will also find, for any model, examples that appear to don't make sense, especially when you work on such short data

**Comment by joseph-macraty** [comment]
Hmm. Do you think that there are any other models that will be good other than sentence transformers?

**Comment by nreimers** [comment]
You can try Universal Sentence Encoder, it it performs worse in most cases, especially for search.

As mentioned, the pre-trained MS MARCO models work best for search.

**Comment by joseph-macraty** [comment]
Perfect. Thanks!
