### ISSUE TITLE
Token embeddings with encode_multi_process

### ISSUE THREAD

**Issue by clairemcwhite** [UKPLab/sentence-transformers#1051]
I can get token embeddings with model.encode(sentences, output_value = "token_embeddings")

Is there a way to use encode_multi_process to get token embeddings, or is it limited to just getting the sentence-level embeddings?

Thanks

**Comment by nreimers** [comment]
It only works with sentence embeddings.

But you could create your own process pool if needed (and if your are familiar with multiprocessing in python)

**Comment by clairemcwhite** [comment]
Thanks, I'll do that
