### ISSUE TITLE
Remove progress bar logging

### ISSUE THREAD

**Issue by gionapaolini** [UKPLab/sentence-transformers#1053]
How can I deactivate the logging information like the example below?

```
Batches: 100%|██████████| 1/1 [00:00<00:00, 45.51it/s]
```

**Comment by nreimers** [comment]
By setting the parameter show_progress_bar to False

**Comment by gionapaolini** [comment]
Amazingly fast, thank you

**Comment by gionapaolini** [comment]
@nreimers Sorry, where do you exactly set this parameter?
