### ISSUE TITLE
Best way to train a zero-shot classifier

### ISSUE THREAD

**Issue by typercast** [UKPLab/sentence-transformers#1055]
What would be the right choice to train a model like that? I was thinking about following this script (https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/nli/training_nli_v2.py) with some added datasets, but is it the right approach? Would I be able to load it on Hugging Face pipeline? And if not, how could I use it with this library, without incurring in loss of accuracy?

Thanks!

**Comment by nreimers** [comment]
You need a cross encoder with this script
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/cross-encoder/training_nli.py

**Comment by typercast** [comment]
@nreimers 

Thanks!

I ran the script, but every evaluation during training returns 0 accuracy.
<img width="920" alt="Captura de Tela 2021-07-08 às 18 49 58" src="https://user-images.githubusercontent.com/79237128/124995155-533b4a00-e01d-11eb-8d3a-b1e24243d9f3.png">

Seems like I could be doing something wrong, but I am literally just copy pasting the code.

**Comment by ScottishFold007** [comment]
> @nreimers
> 
> Thanks!
> 
> I ran the script, but every evaluation during training returns 0 accuracy.
> <img alt="Captura de Tela 2021-07-08 às 18 49 58" width="920" src="https://user-images.githubusercontent.com/79237128/124995155-533b4a00-e01d-11eb-8d3a-b1e24243d9f3.png">
> 
> Seems like I could be doing something wrong, but I am literally just copy pasting the code.

I have exactly the same situation as you, I don't know what caused it, the verification results are 0.
So, have you found out why now?

**Comment by nreimers** [comment]
The example used the wrong evaluator. You have to use CESoftmaxAccuracyEvaluator, but it used CEBinaryAccuracyEvaluator (and this evaluator was outputting the wrong name).

Fixed the example. Now it should work.
