### ISSUE TITLE
Question about Distillation setting

### ISSUE THREAD

**Issue by mrpeerat** [UKPLab/sentence-transformers#1062]
Hello, I'm wondering about pre-trained distillation
1. For `distiluse-base-multilingual-cased-v1` and v2 How many parallel sentences that you used in the training step? In the full paper, I only saw the name of the dataset but did not tell the number exactly.
2. Can we do distillation with USE by using sentence-transformers framework? I didn't see any USE model in the teacher list?

Thank you for taking the time to answer my question.

**Comment by nreimers** [comment]
1) I have a large corpus of sentences and let it train for some amount of time until MSE does not decrease significantly any more. Don't know how many parallel sentences these are

2) Yes, But you need tensorflow and must wrap the tensorflow USE model to be compatible with your distillation setup.
