### ISSUE TITLE
Training time with long seq length 

### ISSUE THREAD

**Issue by gchandra49** [UKPLab/sentence-transformers#1065]
HI , 

we trained bi-encoder and cross-encoder on our domain specific data with seq length==64 and it took around 2.5 hours per epoch. we used our own Bert MLM trained model as base model for bi-encoder and cross-encoder 

Now our sentence length are increased and if we increase the seq len == 128 our training time increased to 9 hours per epoch. Is there any possible way to reduce training time ?

**Comment by nreimers** [comment]
Training time increases quadratic with the text length. Currently there is no other way if you want to use BERT or other transformers networks

**Comment by gchandra49** [comment]
Thank you
