### ISSUE TITLE
Question: May I bring my own fine-tuned BERT?

### ISSUE THREAD

**Issue by vecorro** [UKPLab/sentence-transformers#1071]
Hi,

I'd like to train a semantic search model using SBERT but bringing a BERT model I have already trained with special vocabulary (product and code names, for example). Can I just from my BERT model at the instruction

`model = SentenceTransformer('stsb-distilbert-base')`

from the example https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/quora_duplicate_questions/training_multi-task-learning.py ?

Thanks

**Comment by nreimers** [comment]
Yes, you can use your own BERT model

**Comment by vecorro** [comment]
Thanks!
