### ISSUE TITLE
InputExample raise TypeError when torch.utils.data.DataLoader get _next_data

### ISSUE THREAD

**Issue by GodsDusk** [UKPLab/sentence-transformers#1079]
when I want to print the data in DataLoader , it raise TypeError : 
> TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'sentence_transformers.readers.InputExample.InputExample'>

code here
```python
from sentence_transformers import SentenceTransformer, InputExample
from torch.utils.data import DataLoader

model = SentenceTransformer('distilbert-base-nli-mean-tokens')
train_examples = [InputExample(texts=['My first sentence', 'My second sentence'], label=0.8),
   InputExample(texts=['Another pair', 'Unrelated sentence'], label=0.3)]
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)
for t in train_dataloader :
    pinrt(t)
```

but it works fine while training. If I want check data in DataLoader, how can I do?

**Comment by nreimers** [comment]
You need to add this line before your loop:
```
train_dataloader.collate_fn = model.smart_batching_collate
```

**Comment by GodsDusk** [comment]
> You need to add this line before your loop:
> 
> ```
> train_dataloader.collate_fn = model.smart_batching_collate
> ```

wow, it works, thank you.
