### ISSUE TITLE
cannot install sentence-transformers

### ISSUE THREAD

**Issue by tempbrucefu** [UKPLab/sentence-transformers#108]
no matter using master branch on local or directly pip from server.
same error message: "cannot find //version"

**Comment by nreimers** [comment]
Is that the complete error message? Any other details giving by pip?

**Comment by tempbrucefu** [comment]
ERROR: Command errored out with exit status 1:
     command: '......python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'$AppData\\Local\\Temp\\pip-install-u8nf12ay\\sentencepiece\\setup.py'"'"'; __file__='"'"'$AppData\\Local\\Temp\\pip-install-u8nf12ay\\sentencepiece\\setup.py'"'"'
	 ;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');
	 f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' 
	 egg_info --egg-base '$AppData\Local\Temp\pip-install-u8nf12ay\sentencepiece\pip-egg-info'
         cwd: $AppData\Local\Temp\pip-install-u8nf12ay\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "$AppData\Local\Temp\pip-install-u8nf12ay\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nreimers** [comment]
Have a look here:
https://github.com/huggingface/transformers/issues/1090

**Comment by dheerajiiitv** [comment]
Have you checked your python version?

**Comment by tempbrucefu** [comment]
yes, it is py35. i will try py36.

**Comment by tempbrucefu** [comment]
py36 does not have this issue.
