### ISSUE TITLE
Load model from IO Stream

### ISSUE THREAD

**Issue by NicolaiSchmid** [UKPLab/sentence-transformers#1081]
Is there a possibility, or if not can we support loading models directly from an IO Stream into memory? 
Pytorch already supports this (check https://www.philschmid.de/scaling-machine-learning-from-zero-to-hero for an example), so I would assume it wouldn't take much work to adapt this library as well.
I'm open for a dicussion and would contribute to such a feature.

**Comment by nreimers** [comment]
Hi @NicolaiSchmid 
I so far have no experiences with IO streams and AWS lambda. 

Do you know if you can load huggingface transformers model with it?

Best
Nils

**Comment by NicolaiSchmid** [comment]
I couldn't find a way to do it in Huggingface...
