### ISSUE TITLE
Connection timed out

### ISSUE THREAD

**Issue by AMChierici** [UKPLab/sentence-transformers#109]
Are these models still available to download? I am trying out the Semantic Similarity example, but when I download the model:

`embedder = SentenceTransformer('bert-base-nli-mean-tokens')`,

I get a Connection Error:

> ConnectionError: HTTPSConnectionPool(host='public.ukp.informatik.tu-darmstadt.de', port=443): Max retries exceeded with url: /reimers/sentence-transformers/v0.2/bert-base-nli-mean-tokens.zip (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x151808128>: Failed to establish a new connection: [Errno 60] Operation timed out',))

I checked my network settings, and everything looks fine: no proxies, I can download models from other packages, no firewall.

Anyone had the same issue?

**Comment by nreimers** [comment]
Hi @AMChierici 
If the automatic download does not work, you can find all models here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

Download it, unzip it and then you can get the embedder like this:
```
embedder = SentenceTransformer('path/to/unzipped/model')
```

**Comment by AMChierici** [comment]
Thanks, @nreimers !

**Comment by jzheng13** [comment]
> Hi @AMChierici
> If the automatic download does not work, you can find all models here:
> https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/
> 
> Download it, unzip it and then you can get the embedder like this:
> 
> ```
> embedder = SentenceTransformer('path/to/unzipped/model')
> ```

Actually, I believe the server was down for a period of time yesterday, which was why the download didn't work. It was back up in a while though.

**Comment by yaronguro** [comment]
Hi,
I have a similar problem now, the models are not accessible from automatic nor with the given link above.
Can you please check is the server is up?

Thanks.

**Comment by nreimers** [comment]
There is currently a power outage. I hope the server is back up soon.

You can also access the models via huggingface 
https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens

This is how you load them from huggingface 
https://sbert.net/docs/training/overview.html#creating-networks-from-scratch

As model name put sentence-transformers/bert-...
