### ISSUE TITLE
Using Medical BERT like BioBERT in cross-encoder?

### ISSUE THREAD

**Issue by KailashDN** [UKPLab/sentence-transformers#1093]
Hi,
I want to use BioBERT model trained on medical data in a cross-encoder for the question-answering tasks.
Earlier I was using the 'ms-marco-electra-base' model.

Does it make sense to use BioBERT, PubMedBERT etc. in cross-encoder architecture, which are trained more like a Bi-encoder than cross-encoder.

**Comment by nreimers** [comment]
Hi @KailashDN 
Yes, when your task is on the medical domain, then it makes sense to use a model that was pre-trained on that domain.

**Comment by KailashDN** [comment]
Thank you @nreimers
