### ISSUE TITLE
Generating negative samples for CrossEncoder

### ISSUE THREAD

**Issue by owlmp** [UKPLab/sentence-transformers#1094]
Is there a preferred approach for generating negative samples for a binary cross encoder problem? I was going to use random non-positive pairing, top cosine similarities between query and non-positive samples, or BM25 between query and non-positive to get top lexical samples. Or is there something like hard triplet loss where the hard samples get generated during training?

**Comment by nreimers** [comment]
Sadly hard triplet loss is not possible, as the computation of the CE score is too expensive.

Using BM25 negatives is a good way. You can also mix several techniques.

**Comment by owlmp** [comment]
Amazing, thanks for the quick reply!
