### ISSUE TITLE
Label range.

### ISSUE THREAD

**Issue by HyeyeonKoo** [UKPLab/sentence-transformers#1095]
Hello. 

I try to train model using sentence-transformers with customized sentence pair data.
Meanwhile, I am cunfused about how to set label range.

I read the document, then find some examples in Training Overview section. 
In the example, It looks like most of labels have float label between 0 - 1.
And also there is an explanation which is "The most simple way is to have sentence pairs annotated with a score indicating their similarity, e.g. on a scale 0 to 1. "

Firstly, I thought to set the label range 0-5 like STS dataset.
In this case, should I normalize the labels to be between 0-1?

Please give me an answer. Thank you.

**Comment by nreimers** [comment]
When you use cosine similarity loss, label range has to be in -1 to 1. Setting the range to 0-1 works quite well.

**Comment by HyeyeonKoo** [comment]
Thank you.
