### ISSUE TITLE
More details about Benchmarks

### ISSUE THREAD

**Issue by joaogui1** [UKPLab/sentence-transformers#1110]
Hi! Can you add more details about your benchmarks [here](https://www.sbert.net/docs/pretrained_models.html#sentence-embedding-models)? Like what are the datasets used, how is the metric computed, what is the metric and so on

**Comment by ietz** [comment]
Is there any current way to see which tasks and metrics the model overview table aggregates? Hovering over the info icon, I only see that the e.g. the "Performance Sentence Embeddings" score averages "over 14 diverse tasks."

**Comment by nreimers** [comment]
It contains some benchmarks. I still work on finalizing it
