### ISSUE TITLE
parameter update

### ISSUE THREAD

**Issue by wsh2836741** [UKPLab/sentence-transformers#1119]
Thank you for outstanding job ! Could you tell me where the encoder-model's parameter update ? I just see the loss-model's parameter updated . Thx .
![image](https://user-images.githubusercontent.com/21173914/129690436-fd588f86-57b0-4401-916e-f6862c8fe40e.png)

**Comment by nreimers** [comment]
Hi @wsh2836741 
The loss model includes the sentence-transformer model, i.e. all weights are updated in that step
