### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by paulbricman** [UKPLab/sentence-transformers#1120]
I'm running on:
- a fresh Raspberry Pi 4 (8GB RAM)
- Ubuntu 21.04
- Python 3.9

I specifically installed the latest **aarch64** versions of the `torch` and `torchvision` packages. However, the following fails:

```python
>>> from sentence_transformers import SentenceTransformer
>>> model = SentenceTransformer('clip-ViT-B-32')
>>> model.encode('hi')
Illegal instruction (core dumped)
```

Things I tried which failed:
- using a different model (e.g. paraphrase-MiniLM-L3-v2)
- using unofficial community-based aarch64 `torch` and `torchvision` builds

Note that simply importing `sentence_transformers` or `torch` doesn't cause any issues. Neither does loading the model in memory as shown above.

Also, I used the `pdb` package to step through and found that the crash appears to be caused by the `self.forward(...)` call. Might there be some sbert-specific issues outside calls to torch stuff? Or maybe some other package is causing those issues?

**Comment by nreimers** [comment]
Have you tried to run the models without sentence-transformers:
https://huggingface.co/sentence-transformers/paraphrase-MiniLM-L3-v2#usage-huggingface-transformers

Sadly not too familiar with aarch64 and how compatible torch is with this architecture.

**Comment by paulbricman** [comment]
Thanks for the quick response! Indeed, the error still shows up when using `transformers`. Guess I'll have to go down the ladder of abstraction now.

**Comment by paulbricman** [comment]
It turned out to be a `torch` problem. I solved it by:
- downloading https://github.com/ljk53/pytorch-rpi/blob/master/torch-1.9.0a0%2Bgitd69c22d-cp39-cp39-linux_aarch64.whl
- `python3 -m pip install <just downloaded file>`
