### ISSUE TITLE
paraphrase-mpnet-base-v2's BERT for a cross-encoder

### ISSUE THREAD

**Issue by martindkaz** [UKPLab/sentence-transformers#1123]
Hi, If we wanted to have a cross-encoder whose BERT was trained up on datasets like paraphrase-mpnet-base-v2, does it make sense to pull out the BERT unit and add a classification layer on top that we then train on custom data? In other words, how reusable would the BERT paraphrase weights knowledge be across the two architectures? Thanks!

**Comment by nreimers** [comment]
Yes, you could do that

**Comment by martindkaz** [comment]
Thanks. Just curious, do you plan on releasing any cross-encoders trained on the paraphrase-like dataset mixes?

**Comment by nreimers** [comment]
There will be a Multi-QA cross-encoder. But CE Training is quite different to bi-encoder training, so it is not possible to be trained on large datasets with in-batch negatives.
