### ISSUE TITLE
Evaluation metric for paraphrase model 

### ISSUE THREAD

**Issue by Punchwes** [UKPLab/sentence-transformers#1124]
Hi, we are currently training a sentence encoder that would be suitable for paraphrase identification. Take QQP dataset as an example, if we want to use contrastive learning objective like the MultipleNegativesRankingLoss, it would be a little bit tricky to choose the evaluation metric for dev set. If we use QQP_dev set, the most straightforward metric would be average precision (AP), or the optimal_F1 you have in the BinaryEval code, because in a contrastive learning scenario, we could only output similarity scores/probabilities. However, as in your paraphrase example, you directly use STS-B as the dev evaluation set and decide model based on the spearman correlation. May I ask which strategy you think is more reasonable, why in the paraphrase scenario, you do not choose to evaluate on their own/combined dev set with AP or optimal F1.

Many thanks,

**Comment by nreimers** [comment]
Hi @Punchwes 
Yes, using AP / optimal_F1 makes sense for the task of paraphrase identification. It is also used in this example:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/quora_duplicate_questions/training_MultipleNegativesRankingLoss.py
