### ISSUE TITLE
IndexError: list index out of range after calling model.fit()

### ISSUE THREAD

**Issue by claytoncohn** [UKPLab/sentence-transformers#1126]
Here is the code followed by the error:

```
cb0_sents = cb_0["sentence"].to_numpy()
cb1_sents = cb_1["sentence"].to_numpy()

cb0_sents[:5]
'''
array(['Coral and zooxanthellae depend an each other in order to live.',
       'Or the other way around.',
       'In the text Shifting Trade Winds, it talks about how sometimes water temperature can rise anywhere from 3 degrees F to 10 degrees F.',
       'When trade winds weaken, sea levels rises inchess to feet.',
       'Which is bad for coral and zooxanthellae because coral reefs need to be in shallow waters so the zooxanthellae can get light for photosynthesis.'],
      dtype=object)
'''

!pip install -qU transformers sentence-transformers;

from sentence_transformers import SentenceTransformer, InputExample, losses;
from torch.utils.data import DataLoader;

cb_model = SentenceTransformer('bert-base-nli-mean-tokens')
cb_train_examples = [InputExample(texts=cb1_sents, label=0.8), InputExample(texts=cb0_sents, label=0.1)
cb_train_dataloader = DataLoader(cb_train_examples, shuffle=True, batch_size=16)
cb_train_loss = losses.CosineSimilarityLoss(cb_model)

cb_model.fit(train_objectives=[(cb_train_dataloader, cb_train_loss)], epochs=4, warmup_steps=100)
```

Then I get the following error:

IndexError                                Traceback (most recent call last)
<ipython-input-22-2455f0f43f54> in <module>()
----> 1 cb_model.fit(train_objectives=[(cb_train_dataloader, cb_train_loss)], epochs=4, warmup_steps=100)

4 frames
/usr/local/lib/python3.7/dist-packages/sentence_transformers/SentenceTransformer.py in smart_batching_collate(self, batch)
    522         for example in batch:
    523             for idx, text in enumerate(example.texts):
--> 524                 texts[idx].append(text)
    525 
    526             labels.append(example.label)

IndexError: list index out of range

Any ideas?

**Comment by nreimers** [comment]
You have your InputExamples wrong. They have too look like:
InputExample(texts=["text1", "text2"], label=0.8)

So each example must have exactly two texts

**Comment by claytoncohn** [comment]
Ohh ok got it. Thanks!
