### ISSUE TITLE
model.start_multi_process_pool() never returns.

### ISSUE THREAD

**Issue by jmwoloso** [UKPLab/sentence-transformers#1127]
Hi! 

Awesome library! I'm trying to use the `start_multi_process_pool` method, however, the call to the method never returns. I'm running this in a notebook environment (databricks) with a 2-node (4 GPUs per node) environment. Any thoughts? Thanks!

**Comment by nreimers** [comment]
Never tried it with notebook, not sure if forking new processes works in notebooks well.

Also it is advisable to have everything of your code within an if __name__ == '__main__'. Don't know if this works with notebooks. Is running standard python scripts an option?

**Comment by jmwoloso** [comment]
Yeah i could probably put the code in a script and then use some cell magic to run the script. I'll try that and potentially re-open if I'm still having the issue. Thanks!
