### ISSUE TITLE
NLI accuracy of siamese models

### ISSUE THREAD

**Issue by yakazimir** [UKPLab/sentence-transformers#1129]
Just a quick question that I wasn't able to answer by looking at your original EMNLP19 paper. What kind of accuracy numbers do you get on SNLI and/or MNLI using your original siamese BERT model trained on NLI? I would expect the numbers to be a bit below an ordinary transfer with full attention, is this the case, or can you still get SOTA/near SOTA?

**Comment by nreimers** [comment]
Hi @yakazimir 
Never measured the numbers on SNLI / MNLI. They are not really relevant, as you want to use the model for text embeddings, and not to do NLI. If you are interested in NLI, a cross encoder is better and will also achieve higher scores.

**Comment by yakazimir** [comment]
Right, I'm was just curious, clearly, in the siamese model you are learning good sentence representations (your main goal), I'm wondering what the relationship is between learning good representations (via NLI training) and getting high NLI accuracy, whether you noticed any trade-offs (I'm trying to do something very similar and paying close attention to NLI accuracy, which is somewhat behind even pre-BERT/transformer-based cross encoder models).

Anyways, I will close, thank you for the quick response.
