### ISSUE TITLE
Automatic threshold detection in BinaryClassificationEvaluator

### ISSUE THREAD

**Issue by Mogady** [UKPLab/sentence-transformers#1135]
Hi, I have a couple of questions about the method you use for determining the best threshold.

- first I think it is a cool method, is there are any references talking about doing it that way?

- If I have a case like that [ [0.9,1], [0.85,1], [0.7,1], [0.2,1], [0.01,1]] where the model misclassify the last two points however given the implementation the accuracy will increase since positive_so_far += 1 still valid and the threshold will be 0.1, so isn't making the best threshold constrained on only the current and next point can result in weird values? in my problem, I have a good model(even if it has a bad calibration) but the eval metrics I get don't make sense. is this an intentional behavior??

- What if we take an exponential average for the scores, can this serve the purpose of getting the best threshold automatically?

**Comment by nreimers** [comment]
Yes, if all examples are positive it gives wrong results. It assumes that there at least some negative examples, then it will work correctly

**Comment by Mogady** [comment]
no, i understand this, sorry my example was bad, but this will happen when there is also negative examples, at some point the acc will be increased since it found the missing positives but it will be with low scores so will lead to smaller threshold

**Comment by nreimers** [comment]
Sadly don't know what you mean.

It will find the threshold that provides the best accuracy when you classify anything above the threshold as 1 and anything below the threshold as 0.

**Comment by Mogady** [comment]
yes but the threshold will be constrained by the current sample and the next one, `best_threshold = (rows[i][0] + rows[i+1][0]) / 2` so if those two samples were miss classified that they are actually 1 but the model gave them a low score, then the threshold will be the average of those two numbers which is very low 0.1 or something. and this only happened because of those two samples while before that the model scores and the threshold were ok.
