### ISSUE TITLE
Problems in fast clustering 

### ISSUE THREAD

**Issue by aaronliu7** [UKPLab/sentence-transformers#1146]
When fast clustering is used for clustering, some text will be filtered, because when removing overlapping clusters, all text in the overlapping clusters will be filtered, which will reduce the number of texts.

**Comment by nreimers** [comment]
Yes, this is the intended behavior

**Comment by aaronliu7** [comment]
When min_community_size is set to 1, all text should be displayed in the clustering results, but now only part of the text is displayed.

**Comment by nreimers** [comment]
You could call it iteratively and remove  the items that are already clustered

**Comment by aaronliu7** [comment]
Thanks for your reply, I will try your suggestions

**Comment by surdoag** [comment]
> When min_community_size is set to 1, all text should be displayed in the clustering results, but now only part of the text is displayed.

@nreimers this also gets worse and so many clusters/text is dropped in the current `community_detection` logic. It appears that several valid `clusters` & in turn texts are also dropped when removing overlapping clusters.

Wouldn't it be a safer logic to just remove the overlapping items in a cluster (after sorting by cluster size) and dropping all communities that are smaller than `min_comunity_size`??
