### ISSUE TITLE
Forming similarity pairs from clusters

### ISSUE THREAD

**Issue by kddubey** [UKPLab/sentence-transformers#1149]
My labeled sentence pairs come from clusters. So from n sentences I have n choose 2 training examples. I was wondering how much of a problem it is that these n choose 2 examples are not all statistically independent of each other.

As an example, say 5 sentences were clustered like this:

cluster A: sentence1, sentence2, sentence3
cluster B: sentence4, sentence5

Then the training dataset (where y = 1 denotes similarity) is:

example1 = (sentence1, sentence2, 1)
example2 = (sentence2, sentence3, 1)
example3 = (sentence1, sentence3, 1)
example4 = (sentence1, sentence4, 0)
...

A potential problem is that, e.g., example1 and example2 determines example3.

Does training on non-independent examples hurt performance? I'm thinking these (positive?) associations between examples would make the SGD estimator have high variance, which would result in unstable optimization. I'm going to try it anyway. But it'd be great to hear if you have experience with sampling examples from clustered sentences, and your thoughts on whether / how much of a problem this is.

Thanks!

**Comment by kddubey** [comment]
Nvm I don't think the variance is higher b/c it's a function of pairs of examples, and there are also negative associations. Still wondering if there are important considerations before training on pairs derived from clusters.

**Comment by nreimers** [comment]
Hi @kddubey 
Have a look at the BatchHardTripletLoss functions:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/other/training_batch_hard_trec.py

They work on clustered data and triplets are created automatically. I.e., you just provide the info that sent1, sent2, sent3 are in cluster 0,   and that sent4, sent5 are in cluster 1 and so on.

**Comment by kddubey** [comment]
Thanks for the info and script! Will try it out
