### ISSUE TITLE
Feature Request: AWS Neuron SDK compatibility

### ISSUE THREAD

**Issue by carschno** [UKPLab/sentence-transformers#1151]
I've been trying to compile a `SentenceTransformer` model into a AWS Neuron model using the [AWS Neuron SDK](https://aws.amazon.com/machine-learning/neuron/), roughly following [this tutorial for HuggingFace BERT models](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.html):

```
import torch.neuron
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("my_model")
tokenized = model.tokenize("text")
example_input = tokenized["input_ids"], tokenized["attention_mask"], tokenized["token_type_ids"]

torch.neuron.trace(model, example_input)

[...]
TypeError: forward() takes 2 positional arguments but 4 were given
```

After loading the same model with `AutoModelForSequenceClassification.from_pretrained("my_model", return_dict=False)` as shown in the tutorial, the compilation works fine.

I understand the APIs differ slightly between `SentenceTransformer` and `BertModel`, so it might be a small change to enable `SentenceTransformers` for AWS Neuron SDK.

**Comment by nreimers** [comment]
Hi,
you must pass it as a dict, i.e.:
```
torch.neuron.trace(model, tokenized)
```
should already do the trick.

Otherwise you can also use most models directly with transformers:
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2#usage-huggingface-transformers

**Comment by carschno** [comment]
Thanks, you are right.
