### ISSUE TITLE
Italian semantic search

### ISSUE THREAD

**Issue by AlexRossi6** [UKPLab/sentence-transformers#1153]
Hi, I'm trying to use some of the models already trained for symmetric semantic search but for asymmetric search (by training them on my personal data) since there are no multilingual msmarco models for asymmetric search. 

Is there some technique to make them perform better for asymmetric search or is there a way to use one of the msmarco model for italian?

**Comment by nreimers** [comment]
Hi @AlexRossi6 
There are sadly no models yet.

You can find a machine translated version of MS MARCO to Italian here:
https://github.com/unicamp-dl/mMARCO

Then you can use the code here:
https://www.sbert.net/examples/training/multilingual/README.html

To transfer an existing model to Italian.

**Comment by Tkd-Alex** [comment]
Hi @AlexRossi6
Have you a trained model to share?

**Comment by peppocola** [comment]
This cool guy has some italian sentence transformer models https://huggingface.co/efederici
also there's another I've found https://huggingface.co/nickprock/sentence-bert-base-italian-uncased

**Comment by nickprock** [comment]
Thanks @peppocola for the mention. 
I fine tuned my sentence transformers using this [post on huggingface blog](https://huggingface.co/blog/how-to-train-sentence-transformers).

I also fine tuned others models with different methods (you can find it on my hugging face profile), here a little schema, the test set is STSb multilingual dataset.

![img](https://media.discordapp.net/attachments/1040357950985875539/1113484166588268596/table_benchmark.png?ex=65708e70&is=655e1970&hm=08fc44300b4558baa93306d6c29849c6abefd1b6526441d3da9ea7df1e9aceac&=&format=webp)
