### ISSUE TITLE
Difference between original SPECTER and SBert-SPECTER

### ISSUE THREAD

**Issue by afdezt** [UKPLab/sentence-transformers#1157]
Provided that SPECTER was already devised to compare documents ("long sentences") and incorporates a triplet-loss during training similar to the siamese network used in SBert, I was wondering which are the differences between the original specter model and the one provided here. Concretely, I have these 3 questions:

**1. Are there any differences between SPECTER and SBert-SPECTER?** 

**2. How is the sentence pooling done?** According to SPECTER github documentation: "_...each token representation is a scalar mix of all layer representations. To get aggregate representation of the input in a single vector, average pooling is used._"**

**3. If they are different, is there any benchmark comparing both of them?**

Many thanks!

**Comment by nreimers** [comment]
Hi,
it is the same model. The SBERT-SPECTER just adds the information on top for the pooling, to make the usage easier.

According to here:
https://github.com/allenai/specter#1--through-huggingface-transformers-library

They use CLS pooling on their model. Same for the SBERT-SPECTER model, i.e. both produce the same embeddings.

**Comment by afdezt** [comment]
Understood! Thanks!!
