### ISSUE TITLE
LaBSE fine-tuning on parallel corpora

### ISSUE THREAD

**Issue by averkij** [UKPLab/sentence-transformers#1159]
Hallo zusammen!

I'm using the LaBSE to find the translation pairs across different languages and it's working just fine.
However for some language pairs it's not going very well. For example the model was not trained on Bashkir language, but it had "seen" Tatar language which is relative to Bashkir. Model is still working for the Russian-Bashkir texts, but I want to improve the quality.

I already have the parallel corpora (Russian-Bashkir) about 200K sentences long. So the question is — can I fine-tune the LaBSE on this data?

**Comment by nreimers** [comment]
Yes. You can fine-tune it using MultipleNegativesRankingLoss
