### ISSUE TITLE
How can I eval cross_encoder on MS Marco Dev to reproduce these results? 

### ISSUE THREAD

**Issue by BugApe** [UKPLab/sentence-transformers#1160]
![image](https://user-images.githubusercontent.com/48090275/132821889-034082c5-a273-434a-a298-89556320d122.png)

**Comment by BugApe** [comment]
When I used the following code for my evaluation, the code was unusually high, with MRR@10 over 95. I think something went wrong.
`"""
This script runs the evaluation of an SBERT msmarco model on the
MS MARCO dev dataset and reports different performances metrices for cossine similarity & dot-product.
Usage:
python eval_msmarco.py model_name [max_corpus_size_in_thousands]
"""

from sentence_transformers import (
    LoggingHandler,
    SentenceTransformer,
    evaluation,
    util,
    models,
    CrossEncoder,
)
from sentence_transformers.cross_encoder.evaluation import CERerankingEvaluator
import logging
import sys
import os
import tarfile

#### Just some code to print debug information to stdout
logging.basicConfig(
    format="%(asctime)s - %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    level=logging.INFO,
    handlers=[LoggingHandler()],
)
#### /print debug information to stdout

# Name of the SBERT model
model_name = sys.argv[1]
taskname = sys.argv[2]
# You can limit the approx. max size of the corpus. Pass 100 as second parameter and the corpus has a size of approx 100k docs
corpus_max_size = int(sys.argv[3]) * 1000 if len(sys.argv) >= 4 else 0


####  Load model

model = CrossEncoder(model_name)

### Data files
data_folder = "msmarco-data"
os.makedirs(data_folder, exist_ok=True)

collection_filepath = os.path.join(data_folder, "collection.tsv")
dev_queries_file = os.path.join(data_folder, "queries.dev.small.tsv")
qrels_filepath = os.path.join(data_folder, "qrels.dev.tsv")

### Download files if needed
if not os.path.exists(collection_filepath) or not os.path.exists(dev_queries_file):
    tar_filepath = os.path.join(data_folder, "collectionandqueries.tar.gz")
    if not os.path.exists(tar_filepath):
        logging.info("Download: " + tar_filepath)
        util.http_get(
            "https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz",
            tar_filepath,
        )

    with tarfile.open(tar_filepath, "r:gz") as tar:
        tar.extractall(path=data_folder)


if not os.path.exists(qrels_filepath):
    util.http_get(
        "https://msmarco.blob.core.windows.net/msmarcoranking/qrels.dev.tsv",
        qrels_filepath,
    )

### Load data

corpus = {}  # Our corpus pid => passage
dev_samples = {}
dev_rel_docs = {}  # Mapping qid => set with relevant pids
needed_pids = set()  # Passage IDs we need
needed_qids = set()  # Query IDs we need

# Read passages
with open(collection_filepath, encoding="utf8") as fIn:
    for line in fIn:
        pid, passage = line.strip().split("\t")
        passage = passage

        if pid in needed_pids or corpus_max_size <= 0 or len(corpus) <= corpus_max_size:
            corpus[pid] = passage.strip()

# Load the 6980 dev queries
with open(dev_queries_file, encoding="utf8") as fIn:
    for line in fIn:
        qid, query = line.strip().split("\t")
        dev_samples[qid] = {
            "query": query.strip(),
            "positive": set(),
            "negative": set(),
        }


# Load which passages are relevant for which queries
with open(qrels_filepath) as fIn:
    for line in fIn:
        qid, _, pid, neg_id = line.strip().split("\t")

        if qid not in dev_samples:
            continue

        if qid not in dev_rel_docs:
            dev_rel_docs[qid] = set()
        dev_rel_docs[qid].add(pid)
        dev_samples[qid]["positive"].add(corpus[pid])
        dev_samples[qid]["negative"].add(corpus[neg_id])


## Run evaluator
evaluator = CERerankingEvaluator(dev_samples, name="msmarco dev")
# ir_evaluator = evaluation.InformationRetrievalEvaluator(dev_queries, corpus, dev_rel_docs,
#                                                         show_progress_bar=True,
#                                                         corpus_chunk_size=100000,
#                                                         precision_recall_at_k=[10, 100],
#                                                         name="msmarco dev")

_, scores = evaluator(model)
with open(
    os.path.join("./predict", taskname + "_label_predict.txt"),
    "a",
) as writer:
    for qid, score in scores.items():
        writer.write("{0} {1}\n".format(qid, score * 100))
`

**Comment by ofirzaf** [comment]
Hi, I wondered how to do the same, did you find what is the correct process?
