### ISSUE TITLE
Pretrained SentenceTransformer model for clinical text

### ISSUE THREAD

**Issue by bwang482** [UKPLab/sentence-transformers#1171]
I want to ask the community here if there is a pretrained SentenceTransformer model for clinical text (e.g. EHR notes)? Its application would still be symmetric semantic search 

Thanks!

**Comment by nreimers** [comment]
Sadly not as far as I'm aware of

**Comment by bwang482** [comment]
Thanks for the reply @nreimers !

What would be the appropriate training data here? [MedNLI](https://physionet.org/content/mednli/1.0.0/)?

**Comment by nreimers** [comment]
Could be, I don't know. Not too familiar. You would need some large dataset that matches your text domain and task.

You can also test the all-* models, they perform quite good on many datasets as they have been trained on so much data.

**Comment by bwang482** [comment]
Thanks!

**Comment by bwang482** [comment]
Apologies for asking again. Do you know if John Snow Labs use your SentenceTrasnformer architecture at all? They have released a few sentence BERT variants, however, I cannot seem to find any info on how they are learnt and the difference between these models and simply using BERT to encode and pool embedding for each sentence. 

https://nlp.johnsnowlabs.com/2020/09/19/sent_biobert_discharge_base_cased.html
https://www.reddit.com/r/scala/comments/j3ua8g/john_snow_labs_sparknlp_262_new/

**Comment by nreimers** [comment]
@bwang482 As far as I have checked it, they just take the pre-trained BERT models and do some pooling to get the sentence embedding. But this does not work well when you want to find similar text in your vector space (as it has been shown various times, including in the SBERT paper). Models have to be fine-tuned to produce meaningful text embeddings.

**Comment by bwang482** [comment]
That's what I suspected as well. Thanks!

**Comment by abhinav-kashyap-asus** [comment]
Even if you want to trained this model on MedNLI, there are only 12k samples, which is pretty small compared to what is available in the general domain.

**Comment by germanenik** [comment]
i tried all-mpnet-base-v2 on medical abstracts and it seemed to work quite well! just don't forget to check the max allowed length of input texts a model you use allows
