### ISSUE TITLE
Hard negatives for MultipleNegativesRankingLoss

### ISSUE THREAD

**Issue by mathislucka** [UKPLab/sentence-transformers#1178]
Hi,

I was trying to train a question/sentence retrieval model with the MultipleNegativesRankingLoss and I got the following error:

```
IndexError                                Traceback (most recent call last)
<ipython-input-47-ad5779dd7476> in <module>()
      8 model_name = 'distilroberta-base'
      9 
---> 10 train_asn2_mnrr_loss(train_data_path=save_path, eval_data_path=wiki_qa_save_path, model_name=model_name, hyperparams=hyperparams, model_save_path=model_save_path)

5 frames
/usr/local/lib/python3.7/dist-packages/sentence_transformers/SentenceTransformer.py in smart_batching_collate(self, batch)
    522         for example in batch:
    523             for idx, text in enumerate(example.texts):
--> 524                 texts[idx].append(text)
    525 
    526             labels.append(example.label)

IndexError: list index out of range
```

My training samples sometimes have a hard negative (q1, p1, n1) but sometimes there is no hard negative (q1, p1). Is it possible to mix training samples which have hard negatives with samples where no negatives are provided?

I tried using the `SentencesDataset` as described in the example snippet in https://www.sbert.net/docs/package_reference/losses.html#multiplenegativesrankingloss but this yields an error. I can see that the class is deprecated, but it also doesn't work when directly passing the training samples to the dataloader. The training script runs fine when no hard negatives are provided.

Do you have any idea what is happening here?

Thanks for your help.

**Comment by mathislucka** [comment]
Thanks! Very helpful.

And if I split my samples into two datasets (one with length 2 and one with length 3) and use the MulitDatasetsDataloader, would that work?

**Comment by nreimers** [comment]
Yes. You can also create a custom dataset or DataLoader class that produces batches with a consistent format. Check the DataLoader in the examples training paraphrase folder.

**Comment by mathislucka** [comment]
Alright, thanks for the pointer :)
