### ISSUE TITLE
How to return token and sentence embeddings at the same time?

### ISSUE THREAD

**Issue by phosseini** [UKPLab/sentence-transformers#1179]
**What's the problem?** Given a set of `sentences` in my task, I need both token embeddings and sentence embedding for each sentence in one call. By default, when I call the `model.encode(sentences)` it will return the embeddings for the `sentences`. As mentioned earlier, to compute the similarity among pairs of tokens in my task, I also need to have the token embeddings. I know that I can set the `output_value='token_embeddings'` and get the token embeddings, but this way I need to call the model separately which is not efficient (correct me if I'm wrong). 

**Question:** So, I wonder if there's any way to have sentence and token embeddings for a sentence at the same time with one call? Or, should I just get the token embeddings and use a pooling method myself to compute the sentence embeddings without calling the model?

**Comment by nreimers** [comment]
Yes, I think that is the easiest solution to output the token embeddings and then perform mean pooling by yourself.
