### ISSUE TITLE
question abour Cross-Encoder.fit save_best_model

### ISSUE THREAD

**Issue by ewayuan** [UKPLab/sentence-transformers#1181]
Hi, I'm working on training Cross-Encoder right now, and I found that the save_best_model default as True, and I did two experiment.

1. model.fit (...,save_best_model = True, ...)
2. model.fit (..., ...) (without save_best_model, so save_best_model  would be True as well)

but the accuracy of two experiments are different, May I know what cause this problem?

**Comment by nreimers** [comment]
Hi @ewayuan 
Training of neural networks is not deterministic: The weights are randomly initialized, the batches are randomly drawn. This impacts the performance.

More details here:
https://aclanthology.org/D17-1035/
