### ISSUE TITLE
Force execution on CPU?

### ISSUE THREAD

**Issue by SebiSebi** [UKPLab/sentence-transformers#119]
What would be the recommended way to force inference to be executed on CPUs (even when GPUs are available)?

I am looking for a clean solution if possible, that is not changing CUDA_VIDIBLE_DEVICES.

Thanks!

**Comment by nreimers** [comment]
Hi,
when instantiating the SentenceTransformer class, you can pass the device:
model = SentenceTransformer('bert-base-nli-mean-tokens', device='cpu')

Then, the execution should be carried out on your CPU.

Best
Nils Reimers

**Comment by SebiSebi** [comment]
Awesome!  Thank you, Nils!
