### ISSUE TITLE
Question: Up to how many new terms is effective to use to fine tune a SBERT model?

### ISSUE THREAD

**Issue by vecorro** [UKPLab/sentence-transformers#1192]
Hi,

I'm training a model for an IR task to find duplicates on Bugzilla records. My text has a lot of software industry lingo and some terms are not in the pre-trained model vocabulary. I wonder up to how many new terms I could add using the instructions from the "Adding Special Tokens" section in https://www.sbert.net/docs/training/overview.html. My vocabulary may have hundreds of words not in the pre-trained model. Thanks

**Comment by vecorro** [comment]
On the same vein. If I wanted to follow the cited procedure, all I have to do is to add a list of new terms to the 'tokens' variable. Correct?

```
from sentence_transformers import SentenceTransformer, models
model = SentenceTransformer('all-MiniLM-L6-v2')
word_embedding_model = model._first_module()

tokens = ["[DOC]", "[QRY]"]
word_embedding_model.tokenizer.add_tokens(tokens, special_tokens=True)
word_embedding_model.auto_model.resize_token_embeddings(len(word_embedding_model.tokenizer))
```

**Comment by nreimers** [comment]
There is not a clear answer on it. Do you have training data? 

I'm not aware of any systematic study if vocab extension is helpful to improve performance. BERT has a vocab ob 30k token, while RoBERTa has a vocab of 50k tokens. Some multilingual models even have vocabs of 250k or more.

So if you have training data, then adding several hundred new words is no issue if these appear frequently in your training dataset.

Without training data, adding new words will not help as the model has no idea what these words mean

**Comment by vecorro** [comment]
Thanks @nreimers. I have around 200k training positive pairs to train the IR task using the MultipleNegativesRankingLoss.

Back to my question, once I add the list of new vocab elements. My current understanding is that I should do this:

```
from sentence_transformers import SentenceTransformer, models
model = SentenceTransformer('all-MiniLM-L6-v2')
word_embedding_model = model._first_module()

tokens = list_of_new_vocab_terms
word_embedding_model.tokenizer.add_tokens(tokens, special_tokens=True)
word_embedding_model.auto_model.resize_token_embeddings(len(word_embedding_model.tokenizer))
```

Then, I assume I need to 'take the word_embedding_model' object and use it this way to define the new model to fine tune, right?

```
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension())
model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

Thanks again!

**Comment by nreimers** [comment]
It is not needed to create a new Sentence Transformers object.

**Comment by vecorro** [comment]
Ok, thanks for the clarification. Just to be sure I got it correctly. Do you mean that after this line:
`word_embedding_model.auto_model.resize_token_embeddings(len(word_embedding_model.tokenizer))`

the 'model' object has been updated with the additional tokens and that I can keep using it as the examples illustrate, for example:

```
train_examples = [InputExample(texts=['Anchor 1', 'Positive 1']),
    InputExample(texts=['Anchor 2', 'Positive 2'])]
train_dataset = SentencesDataset(train_examples, model)
train_dataloader = DataLoader(train_dataset, shuffle=True, batch_size=train_batch_size)
train_loss = losses.MultipleNegativesRankingLoss(model=model)
```

**Comment by nreimers** [comment]
Yes, the model object has been updated.

**Comment by vecorro** [comment]
many thanks @nreimers have a great week!
