### ISSUE TITLE
Why is it a continual training on NLI For STS Task

### ISSUE THREAD

**Issue by chikubee** [UKPLab/sentence-transformers#12]
I fail to understand the reason behind the continual training needed.
Why could the Bert model be not fine tuned end to end for semantic similarity using STS benchmark dataset only.

It is just because the data is less or is there some other leverage that continual training on NLI provides us?

**Comment by nreimers** [comment]
Hi @chikubee 
You can train the model only on the STS benchmark. This yields a performance of about 84.30 (BERT base).

If you first train on NLI, then on STS benchmark, you get a performance of about 85.35.

The performance improvement is not that large that it is really needed.

The "issue" with STSb is, that it is rather small.

As shown in various papers (like RoBERTa, MT-DNN, ERNIE 2.0), training on multiple datasets can improve the performance. A similar affect can be observe here: Training first on NLI, then on STSb slightly increases the performance. But this is not necessary.
