### ISSUE TITLE
Using downloaded model from your own s3 bucket for application?

### ISSUE THREAD

**Issue by PaperLuigiMario** [UKPLab/sentence-transformers#1205]
Hi there,

I'm trying to make an api that makes use of sentence_transformers. I went ahead and downloaded the model from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/ (using distilbert-base-nli-stsb-mean-tokens) and uploaded to my own s3 bucket. However it doesn't seem clear cut on how to use it from there? Should it not just be model= SentenceTransformer('pathtomys3bucket/distilbert-base-nli-stsb-mean-tokens')  ?

I can get this to work as expected downloading locally and running in a notebook: 
model= SentenceTransformer('Downloads/distilbert-base-nli-stsb-mean-tokens') 

In the api, I can obviously get things working with :model=SentenceTransformer('distilbert-base-nli-stsb-mean-tokens') but as I understand this is downloading from elsewhere, and I'm concerned about the latency it may add to my endpoint. Would this add any more latency vs downloading it from an s3 bucket of my own? Is there some special formatting needed for an s3 bucket path?

 Any help or guidance would be very appreciated! Thanks!

**Comment by PaperLuigiMario** [comment]
Hi there,

Thank you so much for getting back to me!
1) Thanks for letting me know about this-- I am constrained by the stakeholder here to use this model, but will certainly suggest upgrading for a potential V2!
2) Thanks for explaining this. Are there any potential security issues that you're aware of from using the model this way? Is there any chance for example, this model might be taken down within time for the repo, thus necessitating I use my own copy?
3) I'm looking into this right now and will let you know. I think you need to use something like the s3fs library to get open to work. I'll update you if I learn more!

Thanks again!

**Comment by PaperLuigiMario** [comment]
Hey thank you again so much -- it seems to be working now. It appeared to be more of a quirk of our api template vs downloading things. IE, if anyone else has this issue, it seems you really just need to do model=SentenceTransformer('pathtomodelfolder') and point it at the general folder like you'd do for a local download. If you're having issues otherwise check in with your architecture lol. Thank you again for your help debugging this!

**Comment by ydennisy** [comment]
@PaperLuigiMario @nreimers seems I found the answer in another thread:

https://github.com/UKPLab/sentence-transformers/issues/352
