### ISSUE TITLE
concern about code examples in `CT_In-Batch_Negatives/*`

### ISSUE THREAD

**Issue by baeseongsu** [UKPLab/sentence-transformers#1210]
First, I'd like to thank you for serving the awesome library.

My issue is that some examples didn't seem to work as I understood, so I'd like to double-check.

In `/examples/unsupervised_learning/CT/*`, sample codes use the specific data loader to construct batches with the desired properties. However, in `/examples/unsupervised_learning/CT_In-Batch_Negatives/*`, samples codes use just the basic data loader. 

In the latter case, from my point of view, it should be changed to the class `ContrastiveTensionDataLoader` to construct batches.

**Comment by nreimers** [comment]
No, it is correct as it is.

In the second case, it uses the sentences from the other pairs as negatives, while in the first case you have to specifically pass positives and negatives

**Comment by baeseongsu** [comment]
Thank you for the quick reply :D

Yes, that's what I thought. In [here](https://github.com/UKPLab/sentence-transformers/blob/master/examples/unsupervised_learning/CT_In-Batch_Negatives/train_stsb_ct-improved.py#L39), the training sentences are injected as the only positive pairs. 
I cannot find the exact part that constructs negative-batch in this code.

**Comment by nreimers** [comment]
It is in  the loss function
https://github.com/UKPLab/sentence-transformers/blob/afee883a17ab039120783fd0cffe09ea979233cf/sentence_transformers/losses/ContrastiveTensionLoss.py#L62

**Comment by baeseongsu** [comment]
Thank you for the explanation!
Now I catch up the point. Sorry for my misinterpretation.
