### ISSUE TITLE
Do we have the feature <local_files_only> like Hugging face?

### ISSUE THREAD

**Issue by pratikchhapolika** [UKPLab/sentence-transformers#1211]
When using this code:

```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')
```

I have already downloaded the model when creating Docker image.
But when I use that docker in Linux where there is no internet, it throws error.

In Hugging face, we had this parameter : `local_files_only=True`  which search for files in local before downloading.

IS there similar feature in `sentence-transformers`?

If not can we include this?

**Comment by pratikchhapolika** [comment]
> I will need to test it.
> 
> As work-around, you can download the model to a specific path, like /model/all-MiniLM-L6-v2
> 
> and then load it from that path with:
> 
> ```
> model = SentenceTransformer('/model/all-MiniLM-L6-v2')
> ```
> 
> In that case no check is done if the model exists on the hub

I do not want to do this as I have already downloaded model when creating docker image. I work with 5-6 models so its feasible to zip the file and then pass the path.

**Comment by mirekphd** [comment]
The option is now available in the `SentenceTransformer` class constructor:
https://github.com/UKPLab/sentence-transformers/blob/52162f3f0b984a2032667a2332bf95f6aabcf033/sentence_transformers/SentenceTransformer.py#L83

If it fails wit `TypeError`, then you probably need to upgrade `sentence_transformers` to at least v3.0.

So I think this issue can be probably closed now.

**Comment by tomaarsen** [comment]
Indeed, thanks @mirekphd!
