### ISSUE TITLE
CrossEncoder for three sentence input

### ISSUE THREAD

**Issue by ironllamagirl** [UKPLab/sentence-transformers#1222]
Hi, 
I would like to use sbert for an automated grading system homework. 

I have a dataset with a bunch of questions. For each question I have multiple (or 1) reference answer(s). I have the student's answer, with the grade (4 classes: correct, incorrect, correct but incomplete and incorrect) 

I would like to create a model which given a student's answer and the question + reference answers, gives me as output the grade. 

How should I go about implementing this? I would like to use semantic similarity for this, but I am not sure how to prepare and in which format would I feed this data into an sbert model? 

Thanks

**Comment by akankshapawar1** [comment]
Hello @ironllamagirl, were you able to get this project working? I am having some trouble with it and honestly use some references.
