### ISSUE TITLE
Dask with Bert

### ISSUE THREAD

**Issue by MaheshChandrra** [UKPLab/sentence-transformers#123]
I'm trying to build a semantic search engine for a  data set of size  5 M Text Paragraphs, and wanted to pre-compute all the similarities for a paragraph with remaining rest of all paragraphs in 5 M, to speed up the process I used Dask instead of regular data frames,and was getting the below error NotImplementedError while trying to create embeddings , May please know if there is any way to fix this, or an easy way to get compute similarities for each record with rest of all the records in linear time?

```
import pandas as pd
import dask.dataframe as dd
df = pd.read_pickle('dataset.pkl')
ddf = dd.from_pandas(df, npartitions=8)
from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer('bert-base-nli-mean-tokens')
encodings=embedder.encode(ddf['Text'],show_progress_bar=True)



---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-70e5d9106827> in <module>
----> 1 encodings=embedder.encode(ddf['Text'],show_progress_bar=True)

~\AppData\Local\Continuum\anaconda3\lib\site-packages\sentence_transformers\SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar)
    123 
    124             for idx in length_sorted_idx[batch_start: batch_end]:
--> 125                 sentence = sentences[idx]
    126                 tokens = self.tokenize(sentence)
    127                 longest_seq = max(longest_seq, len(tokens))

~\AppData\Local\Continuum\anaconda3\lib\site-packages\dask\dataframe\core.py in __getitem__(self, key)
   2726             return Series(graph, name, self._meta, self.divisions)
   2727         raise NotImplementedError(
-> 2728             "Series getitem in only supported for other series objects "
   2729             "with matching partition structure"
   2730         )

NotImplementedError: Series getitem in only supported for other series objects with matching partition structure

```

Thanks in advance.

**Comment by nreimers** [comment]
Hi @MaheshChandrra 

The encode() method expects a list with sentences (strings). It performs some sorting operations so that the embeddings can be computed quickly.

I'm afraid that it does not work out of the box with pandas dataframes. So you would need to convert it to a list and than back to a data frame.

Best
Nils Reimers

**Comment by MaheshChandrra** [comment]
Yes, I get it but the pandas data frame was too heavy to be handled by RAM,so was looking to see if I can do anything with Dask ,Thanks for the quick response.
