### ISSUE TITLE
Is there documentation on how to interpret sentence BERT?

### ISSUE THREAD

**Issue by KailashDN** [UKPLab/sentence-transformers#1235]
I am using SBERT for question answering task. I want to see how the model is performing and which tokens(words) are getting attention.

**Comment by eating-chen** [comment]
Hello, I also encounter this question and thank @nreimers supporting an example: https://colab.research.google.com/drive/1-FFAeV6_HWsstX2dBfbQdqELxODei9H6?usp=sharing 
But on this `colab`, I have a question is in the **Hypothesis 3** that he use 1 - cosine similarity as importance.
Could anyone can tell me why `1 - cosine similarity` can be importance.
Thank you~

**Comment by jamesahnjoonchul** [comment]
@eating-chen I think you pointed out a potential error. It should be calculated as cosine similarirty instead of (1-cosine similarity)
