### ISSUE TITLE
Usage of SBERT 

### ISSUE THREAD

**Issue by MaheshChandrra** [UKPLab/sentence-transformers#124]
Hi , May I know if SBERT  is available with sentence transformers for ready to use.

**Comment by nreimers** [comment]
Yes, there are several pre-trained models you can choose from:
https://github.com/UKPLab/sentence-transformers#pretrained-models

**Comment by MaheshChandrra** [comment]
@nreimers ,Thanks for the quick response, I've actually used the models you've mentioned above,but when I'm trying to apply the semantic search on corpus of 5M embedding's ,the machine couldn't take it and I read some where that SBERT uses Siamese networks to make the computations faster,so what you meant is that all the models present in  by default use Siamese Networks?

Can you suggest any other way in which Semantic search happens in just seconds for a corpus of this size.

Thanks in advance.

**Comment by nreimers** [comment]
Hi @MaheshChandrra 
the siamese network structure is only relevant for training. It doesn't play a role for inference. 

See here an example for semantic search:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/application_semantic_search.py

However, with 5 Million sentences, it is a bit different.

You need to embedded all 5 Million texts to vectors. This requires 5 Million embedding computations. BERT is rather slow, so even on a GPU you can only compute about 1000 - 2000 sentences per second. So embedding the 5 Million sentences takes about 2000 - 5000 seconds.

But this is only a one-time operation.


For querying the index, you only need to compute one embedding for the query and the compare it against all embeddings in your index. To speed things up, it can make sense to use special index structures for dense vectors. Faiss is a framework that allows to index millions of vectors and to query them efficiently (within milliseconds).

Best
Nils Reimers

**Comment by MaheshChandrra** [comment]
Thanks,it worked!!
