### ISSUE TITLE
Unexpected Error when sequence length = 1

### ISSUE THREAD

**Issue by Muennighoff** [UKPLab/sentence-transformers#1252]
Running the below gives:
```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-distilroberta-v1")
model.max_seq_length = 1
embeddings = model.encode(["X\n" * 600])
```

`Expanded size of the tensor (1201) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 1201].  Tensor sizes: [1, 514]`

sentence-transformers version: 2.1

Probably there is some newline splitting happening somewhere or squeezing, which messes up the sequence length...

**Comment by nreimers** [comment]
Why would you set it to 1, it doesn't make any sense as the first token is reserved for the CLS token, so all embeddings will be identical

**Comment by Muennighoff** [comment]
For low-compute testing purposes; Also users might have a model without `CLS` token, but if its too much of an edge case, feel free to close - I'll use max_seq_len = 2 for my testing. Just wanted to raise it in case of interest :)

**Comment by nreimers** [comment]
It is an interesting error. But is is an extrem edge case. All existing models use an CLS token. For other models, you could just replace them with a dictionary lookup when you have `max_seq_length=1`, so not really needed to compute the embeddings on-the-fly. Just store the final output for all possible input words.
