### ISSUE TITLE
Embeddings of small paragraph (<128 Tokens)

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [UKPLab/sentence-transformers#1258]
Hi,

What is the best way of computing embeddings for a small paragraph of 2-3 sentences totalizing less than 128 tokens?:

1/ Computing the embeddings with sentence-transformer directly on this small paragraph.

2/ Computing the embeddings with sentence-transformer on each sentence of this paragraph, then take the mean of this list of embeddings.

Thanks!

**Comment by nreimers** [comment]
You can take the whole paragraph and compute the embedding

**Comment by Matthieu-Tinycoaching** [comment]
Thanks @nreimers for your feedback!

Would computing the embedding of the whole paragraph take into account dependencies between sentences constituting it? (Coreferences to the same subject, etc.)

**Comment by nreimers** [comment]
Yes

**Comment by Matthieu-Tinycoaching** [comment]
Thanks!
