### ISSUE TITLE
Using sentence transformers to monitor social media comments?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#1263]
Hi @nreimers ,
do you think it would be possible to use sentence transformers (trained on stsb for example)
to encode and aggregate social media comments to average or concatenate the vectors and 
do some supervised classification with them?

Or are there other alternatives?

As input I have a verying number of short postings / comments, I want to somehow "aggregate them into a vector" to do supervised learning.

Thanks
Philip

**Comment by nreimers** [comment]
Yes, aggregation (like average) should be possible.

Alternatively, you can also classify each posting / comment individually and predict a label for each of them. Then have an aggregation step on top like 'max label = take the label that appeared the most frequent'.

**Comment by PhilipMay** [comment]
ok thanks, closing this
