### ISSUE TITLE
Multi-GPU support for CrossEncoder

### ISSUE THREAD

**Issue by nirmal2k** [UKPLab/sentence-transformers#1265]
I tried using DataParallel 

Model init
`model = CrossEncoder("model")`
`model = nn.DataParallel(model, device_ids=[0,1,2])`

Train :
`model.module.fit(data_loader)`
Dataloader created using InputExample as per documentation

While training, one only GPU is being used.

**Comment by nreimers** [comment]
You would need to wrap the `model` instead the CrossEncoder in an nn.DataParallel, i.e.
```
model = CrossEncoder()
model.model = nn.DataParalell(model.model, ...)
```

**Comment by nirmal2k** [comment]
> You would need to wrap the `model` instead the CrossEncoder in an nn.DataParallel, i.e.
> 
> ```
> model = CrossEncoder()
> model.model = nn.DataParalell(model.model, ...)
> ```
Thanks!
In that case model.save() won't work and would throw an error with nn.Dataparallel object having no function named save_pretrained()

model.model.module.save_pretrained() should work

**Comment by thusinh1969** [comment]
Until now, no code change to multi-GPU save_pretrained !!!

Steve
