### ISSUE TITLE
paraphrase-multilingual-mpnet-base-v2: tokenizer 

### ISSUE THREAD

**Issue by koen-dejonghe** [UKPLab/sentence-transformers#1266]
Hi,

https://www.sbert.net/_static/html/models_en_sentence_embeddings.html
states that Max Sequence Length is 128 for paraphrase-multilingual-mpnet-base-v2
However, the tokenizer obtained as follows:
```
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')
```
yields vectors of size 512:
```python
encoded_input = tokenizer(texts, padding=True, truncation=True, return_tensors='pt')
encoded_input['input_ids'].shape, encoded_input['attention_mask'].shape

>>> (torch.Size([32, 512]), torch.Size([32, 512]))
```
Maybe I misunderstand, but shouldn't the default vector size of the tokenizer be the max sequence length? Or is the documentation wrong?

Thank you.

**Comment by nreimers** [comment]
This is not configured in the tokenizer itself, bit in a different file that is then passed as max_length parameter to the tokenizer.
In principle it can encode passages up to 512 tokens, but as it was not trained on such it yields bad embeddings. So the input is truncated after 128 tokens

**Comment by koen-dejonghe** [comment]
Thank you.
