### ISSUE TITLE
About the Tatoeba results on zsm, jpn, wuu and yue of LASER in paper "Making Monolingual Sentence Embeddings Multilingual using Knowledge Distillation"

### ISSUE THREAD

**Issue by Mao-KU** [UKPLab/sentence-transformers#1267]
Hello,

When reading your paper entitled "Making Monolingual Sentence Embeddings Multilingual using Knowledge Distillation", I found that the results of LASER on wuu, yue and jpn are different from those in "Massively Multilingual Sentence Embeddings for Zero-Shot Cross-Lingual Transfer and Beyond".

Specifically, refer to Table 9 and 10 of your paper, the results of wuu, yue, and jpn are 87.7, 90.0, and 90.7, which are different from the error rates shown in Table 1 of https://arxiv.org/pdf/1812.10464.pdf (LASER paper), 74.5, 62.1, 95.4, respectively. Other results in the 2 papers are totally the same.

And zsm is not included in LASER, how can it yield the ACC of 96.4 (in Table 9 of your paper)?

Did I miss some important information? Thank you in advance.

Best,
Mao

**Comment by nreimers** [comment]
Hi Mao,
I computed the results with the provided LASER model. There can be differences as the authors changed the code (or one of the dependencies changed)

ZSM: It can also work for other languages if e.g. the languages are similar and the character set are known by the model

**Comment by Mao-KU** [comment]
I see. Thanks for your reply!
