### ISSUE TITLE
A strange change in the behavior of all-mpnet-base-v2 

### ISSUE THREAD

**Issue by AbdallahHefny** [UKPLab/sentence-transformers#1270]
I have been using 'all-mpnet-base-v2 model' for some weeks to encode millions of sentences. 

I am now using a different machine, so installed everything again (a typical copy of my old machine).
Of course the model is downloaded again. However, the model is giving totally different embeddings than I used to get!

I am wondering why did the model embeddings changed? Is there a way to download the model that I had few weeks ago? I cannot afford to re-do the embeddings for the millions of sentences.

**Comment by nreimers** [comment]
There was no change in the model in the last 3 months 

https://huggingface.co/sentence-transformers/all-mpnet-base-v2/tree/main

Did you maybe use sentence Transformers v1 on the one machine? It might be that the normalization layer was not downloaded that normalizes all embeddings to length 1.

What is the cosine similarity between your old and your new embeddings?

**Comment by AbdallahHefny** [comment]
On both machines I am using sentence-transformers==1.0.4. 

I hope this helps: One week ago on the old machine, I started to get an error (without changing anything).
The error is in this line (112 in SentenceTransfomer.py):
```
if config['__version__'] > __version__:
     logger.warning("You try to use a model that was created with version {},
```

the configuration file does not have '__version__'

So I think this is the root of the problem; i.e. Earlier, the code was not entering either of the if conditions in lines 106 and 109. and suddenly, it seems that it enters both of them.

What I did is that I commented the if condition in 112 (as I did not need it!). And the model performed well. Then I did the same on the new machine, but I am getting totally different embeddings.

**Comment by nreimers** [comment]
That model is not really compatible with 1.0.4, version 1.2.1 or v2 would be better.

I assume that the embeddings have been created without normalization. When you compute cosine similarity it does not make a difference

**Comment by AbdallahHefny** [comment]
Hello Nils,

Thanks for pointing this out. Yes the old embeddings were not L2 normalized. But the new ones are automatically L2 normalized (although I specify  normalize_embeddings = False).

Also thanks for guiding to use the cosine simialirty as it implictyly normalize the vectors.
But, is there a way to disable normalizing the embeddings? I need to store them in a non-normalized format.

**Comment by nreimers** [comment]
Why would you want to store them unnormalized?

You would need to remove the normalization layer. You could create a SentenceTransformer object from scratch just consisting of models.Transformer and models.Pooling

**Comment by AbdallahHefny** [comment]
- I do not want to change the code for similarity metric (currently using Euclidean distance). That's why I need to generate the new embeddings also un-normalized to be able to use the same similarity as before.


- I think what fixes the problem for me  is to continue to use `sentence-transformers==1.0.4` && to call it as `model = SentenceTransformer("sentence-transformers/all-mpnet-base-v2")`  The downloaded model and config file will not contain the normalization layer.

P.S. Using `sentence-transformers==1.0.4` OR  `model = SentenceTransformer("all-mpnet-base-v2")` will result in downloading the version that contains the normalization layer.

Thanks Nils for the support

**Comment by nreimers** [comment]
Yes, that works.

The model has been trained with cosine similarity and yields the best results with cosine similarity. When you normalize the embeddings, eucl. distance is proportional to cosine similarity.

So normalizing your embeddings would improve the results when you use eucl. distance in your application.

Thats the reason why the new all-* models produce normalized embeddings
