### ISSUE TITLE
How to determine the max_length of tokens for each pre-trained model

### ISSUE THREAD

**Issue by Matthieu-Tinycoaching** [UKPLab/sentence-transformers#1274]
Hi,

Is there a way to know for each pre-trained bi-encoder or cross-encoder model, the maximum number of tokens the model would accept according to the max number it was pre-trained on?

Thanks!

**Comment by nreimers** [comment]
For the bi encoder you can find it here:
https://www.sbert.net/docs/pretrained_models.html

For the cross-encoders it is not documented.

**Comment by Matthieu-Tinycoaching** [comment]
Thanks @nreimers!
