### ISSUE TITLE
Update conda-forge feedstock to include missing dependencies

### ISSUE THREAD

**Issue by sugatoray** [UKPLab/sentence-transformers#1279]
I have already pushed a [**PR** :star:](https://github.com/conda-forge/sentence-transformers-feedstock/pull/21) against [this **issue** :memo:  ](https://github.com/conda-forge/sentence-transformers-feedstock/issues/22) to https://github.com/conda-forge/sentence-transformers-feedstock. It has been almost a week now, but the maintainers have not responded yet.

All that is necessary is to accept and merge the PR (which passed all the CIs).

cc: @ndmaxar, @oblute, @rluria14

**Comment by nreimers** [comment]
Yes, the maintainers were also quite slow with the last PRs updating the version:
https://github.com/conda-forge/sentence-transformers-feedstock/issues/17

Sadly I cannot merge them, or is there I way I can take care of that?

**Comment by sugatoray** [comment]
I guess, it's best to update the maintainers' list. I have asked to add myself to it. And I personally feel that it is always a good strategy to include one of the maintainers of the original package as a maintainer of the corresponding conda-forge feedstock.

**Comment by sugatoray** [comment]
@nreimers The [PR](https://github.com/conda-forge/sentence-transformers-feedstock/pull/21) has been merged now. And I am one of the maintainers for [conda-forge/sentence-transformers-feedstock](https://github.com/conda-forge/sentence-transformers-feedstock) now.

[![Conda (channel only)](https://img.shields.io/conda/vn/conda-forge/doubtlab?logo=anaconda&style=flat&color=orange)][#conda-forge-sentense-transformers]

[#conda-forge-sentense-transformers]: https://anaconda.org/conda-forge/sentense-transformers

**Comment by nreimers** [comment]
Great, thank you so much for this :)

**Comment by glemaitre** [comment]
@tomaarsen I think this PR could be closed as well.

**Comment by sugatoray** [comment]
> @tomaarsen I think this PR could be closed as well.

Yes, please close this PR. Thank you, @glemaitre for your conda-forge PR. I have merged it.

**Comment by tomaarsen** [comment]
Awesome, I see v3.1.1 is now live: https://anaconda.org/conda-forge/sentence-transformers
Thanks for this @glemaitre @sugatoray 

- Tom Aarsen
