### ISSUE TITLE
Converting SentenceTransformers paraphrase-mpnet-base-v2 to ONNX

### ISSUE THREAD

**Issue by abhibisht89** [UKPLab/sentence-transformers#1283]
it's just a query is there a way to convert  SentenceTransformers model to ONNX.
I tried things from hugging face :
https://huggingface.co/transformers/serialization.html

however when I did it for "bert-base-cased" as below , it works 

**!python -m transformers.onnx --model=bert-base-cased onnx/bert-base-cased/**

Some weights of the model checkpoint at bert-base-cased were not used when initializing BertModel: ['cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Using framework PyTorch: 1.9.0+cpu
Overriding 1 configuration item(s)
	- use_cache -> False
Validating ONNX model...
	-[✓] ONNX model outputs' name match reference model ({'pooler_output', 'last_hidden_state'}
	- Validating ONNX Model output "last_hidden_state":
		-[✓] (2, 8, 768) matches (2, 8, 768)
		-[✓] all values close (atol: 0.0001)
	- Validating ONNX Model output "pooler_output":
		-[✓] (2, 768) matches (2, 768)
		-[✓] all values close (atol: 0.0001)
All good, model saved at: onnx/bert-base-cased/model.onnx

but for the below cmd 

**!python -m transformers.onnx --model=sentence-transformers/paraphrase-mpnet-base-v2 onnx/paraphrase-mpnet-base-v2/**

having issues, like it is not supported

Traceback (most recent call last):
  File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/ml_app/envs/bbert/lib/python3.7/site-packages/transformers/onnx/__main__.py", line 71, in <module>
    main()
  File "/ml_app/envs/bbert/lib/python3.7/site-packages/transformers/onnx/__main__.py", line 52, in main
    model_kind, model_onnx_config = FeaturesManager.check_supported_model_or_raise(model, feature=args.feature)
  File "/ml_app/envs/bbert/lib/python3.7/site-packages/transformers/onnx/features.py", line 145, in check_supported_model_or_raise
    f"{model.config.model_type} ({model_name}) is not supported yet. "
KeyError: "mpnet () is not supported yet. Only {'albert': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.albert.configuration_albert.AlbertOnnxConfig'>>, task='default')}, 'bart': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.bart.configuration_bart.BartOnnxConfig'>>, task='default')}, 'mbart': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.mbart.configuration_mbart.MBartOnnxConfig'>>, task='default')}, 'bert': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.bert.configuration_bert.BertOnnxConfig'>>, task='default')}, 'camembert': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.camembert.configuration_camembert.CamembertOnnxConfig'>>, task='default'), 'causal-lm': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.camembert.configuration_camembert.CamembertOnnxConfig'>>, task='causal-lm'), 'sequence-classification': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.camembert.configuration_camembert.CamembertOnnxConfig'>>, task='sequence-classification'), 'token-classification': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.camembert.configuration_camembert.CamembertOnnxConfig'>>, task='token-classification'), 'question-answering': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.camembert.configuration_camembert.CamembertOnnxConfig'>>, task='question-answering')}, 'distilbert': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.distilbert.configuration_distilbert.DistilBertOnnxConfig'>>, task='default')}, 'gpt2': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.gpt2.configuration_gpt2.GPT2OnnxConfig'>>, task='default')}, 'longformer': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.longformer.configuration_longformer.LongformerOnnxConfig'>>, task='default')}, 'roberta': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.roberta.configuration_roberta.RobertaOnnxConfig'>>, task='default')}, 't5': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.t5.configuration_t5.T5OnnxConfig'>>, task='default'), 'default-with-past': functools.partial(<bound method OnnxConfigWithPast.with_past of <class 'transformers.models.t5.configuration_t5.T5OnnxConfig'>>, task='default'), 'seq2seq-lm': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.t5.configuration_t5.T5OnnxConfig'>>, task='seq2seq-lm'), 'seq2seq-lm-with-past': functools.partial(<bound method OnnxConfigWithPast.with_past of <class 'transformers.models.t5.configuration_t5.T5OnnxConfig'>>, task='seq2seq-lm')}, 'xlm-roberta': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.xlm_roberta.configuration_xlm_roberta.XLMRobertaOnnxConfig'>>, task='default')}, 'gpt-neo': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='default'), 'causal-lm': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='causal-lm'), 'sequence-classification': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='sequence-classification'), 'default-with-past': functools.partial(<bound method OnnxConfigWithPast.with_past of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='default'), 'causal-lm-with-past': functools.partial(<bound method OnnxConfigWithPast.with_past of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='causal-lm'), 'sequence-classification-with-past': functools.partial(<bound method OnnxConfigWithPast.with_past of <class 'transformers.models.gpt_neo.configuration_gpt_neo.GPTNeoOnnxConfig'>>, task='sequence-classification')}, 'layoutlm': {'default': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.layoutlm.configuration_layoutlm.LayoutLMOnnxConfig'>>, task='default'), 'masked-lm': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.layoutlm.configuration_layoutlm.LayoutLMOnnxConfig'>>, task='masked-lm'), 'sequence-classification': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.layoutlm.configuration_layoutlm.LayoutLMOnnxConfig'>>, task='sequence-classification'), 'token-classification': functools.partial(<bound method OnnxConfig.from_model_config of <class 'transformers.models.layoutlm.configuration_layoutlm.LayoutLMOnnxConfig'>>, task='token-classification')}} are supported. If you want to support (mpnet) please propose a PR or open up an issue."

**Comment by nreimers** [comment]
As the message says, mpnet models are not yet supported in the conversion.

**Comment by abhibisht89** [comment]
Thanks @nreimers. however these model are in huggingface model hub:
https://huggingface.co/sentence-transformers/paraphrase-mpnet-base-v2
So I thought they will be eligible for ONNX conversion. My assumption is wrong then :(

**Comment by loretoparisi** [comment]
@abhibisht89 are this model ONNX conversion not supported yet?
