### ISSUE TITLE
Restricting specific language across multi-language transformer

### ISSUE THREAD

**Issue by Tortoise17** [UKPLab/sentence-transformers#1284]
I have to ask that is it possible to restrict some languages across multi-language transformer usage or in other words allow some languages to get under usage? If you can guide me how to handle such issue.

**Comment by nreimers** [comment]
This is not possible

**Comment by Tortoise17** [comment]
Can we adjust as target language , and source language or ? any case like this after detection of language using multi - language sentence transformer? or that is also not possible.?

**Comment by nreimers** [comment]
I don't understand what you mean

**Comment by Tortoise17** [comment]
Multi-lingual transformer model has the ability to detect the language. after detection, can we define that please accept input as this language  and results from only these languages. 

I have data and I don't want the results from all languages from my search in query.

**Comment by nreimers** [comment]
No, these models cannot detect the language. For that you need to use some language detection models like the one from fastText

**Comment by Tortoise17** [comment]
This is great help. Thank you. I think this will help me in making conditional input and output before and after the multi-transformer usage. Thank you so much.
