### ISSUE TITLE
Model is not downloading as per example

### ISSUE THREAD

**Issue by notiqq** [UKPLab/sentence-transformers#1297]
Hello,
It looks like there is new issue, while trying to run code from example:
So just executing next few lines:
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

And getting error:
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/a4ce9694439b000ffd9ef4fe8becf6f62621689e/.gitattributes

I was thinking initially that it might be an issue with the amount of downloads per some period of time, and that's why the IP address was blocked. However, I have tried on multiple environments with different IP addresses and everywhere the same issue.
FYI this code has been working for months, but it just stopped to work couple hours ago. So something has definitely has been changed today on sentence-transformers side.

**Comment by etiennedi** [comment]
Running into the same problem, also stopped working suddenly:

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/clip-ViT-B-32/resolve/afe976e3f4ea04b633edb0089a7e5088ddbe9212/.gitattributes
```

**Comment by etiennedi** [comment]
Not sure if this would rather belong to huggingface/transformers, but I'm currently only running into this issue when using the `SentenceTransformers` library, not when using it directly.

**Comment by notiqq** [comment]
Experiencing the same issue with keybert package https://pypi.org/project/keybert/ as well. It looks like an issue on   huggingface/transformers side :(

**Comment by etiennedi** [comment]
I've cross-posted this issue to them to make them aware.

**Comment by nreimers** [comment]
All models are also hosted here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

You can download from there and unzip them.

We currently look into this

**Comment by shashank-sensehq** [comment]
Running into the same problem from last 3 hours
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/bert-base-nli-mean-tokens/resolve/940b797366fedff0e361664b655910c1d37edf76/.gitattributes`

**Comment by dfaram7** [comment]
Same issue also, tried from several IPs and a few different models. Initially thought I had hit the download limit but I think this might be a server problem.

**Comment by nreimers** [comment]
@shashank-sensehq @dfaram7 
Yes, it is a server problem at huggingface model hub. We are currently working on fixing it.

All models are also hosted here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

You can download from there and unzip them.

**Comment by nreimers** [comment]
The download from the hub should be working again.

Let me know if you still have issues.

**Comment by julien-c** [comment]
Post-mortem: AWS WAF (Web Application Firewall) had a new ruleset merged today (https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html) that didn't like our URL structure

**Comment by DavidARivkin** [comment]
Still down but with a 504 error.  So the question then is:  How do we change the URL used to fetch the models without having to edit the KeyBert code itself, or lacking that ability, where would copy the model files to in our local system and which files are actually needed from the long list above?

**Comment by augchan42** [comment]
Seems there's issues again: 
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested file '.gitattributes' in the cache directory '/home/hosermage/.cache/torch/sentence_transformers/intfloat_e5-base-v2'. Please try again or make sure your Internet connection is on.
