### ISSUE TITLE
Sentence Embedding of a product catalogue

### ISSUE THREAD

**Issue by mangleddata** [UKPLab/sentence-transformers#1301]
First off, Thank you so much for publishing the package! This is so exciting and has so many possibilities to use in real world. I have a question and hope someone could provide pointers. I would like to use sentence embedding for a product catalogue. Each product looks like 
```
{
	"product_description": "",
	"product_categories": ""
	"seller_name": "",
	"price": "",
	"review": ""
}
```

I am trying to see how I could evaluate a user search (which could be a combination of product description, keywords, seller name etc) based on sentence embedding. One crude way would be to concatenate every text data I have and build an embedding to match with the query. Another would be to create separate embedding for each of those fields (product description, category etc) and do some kind of weighted sum comparison (for example, seller name would carry large weight over category). Appreciate if anyone has any pointers ?

**Comment by nreimers** [comment]
I would do different embeddings for the different fields. And then combine the scores in a certain way. It can also be helpful to work with thresholds, e.g. you compare the query to the seller_name, if there is no math with a score larger threshold t, you ignore this field (as you assume that the user did not search for a specific seller).

**Comment by mangleddata** [comment]
Thanks. Another related question is, would sentence embedding work for queries like "`show laptops with price > 1000$"` (Assuming I have `"price is X$"` as part of my corpus for each of my product).

**Comment by nreimers** [comment]
Not really. Transformer models are not that great for arithmetic. Here it is better to store  the price as field and then do a boolean filter (either pre-filter entries on the price or do a post-filtering of the results).

**Comment by mangleddata** [comment]
ok got it. Closing this as I have enough to work with these answers.
