### ISSUE TITLE
Multi GPU for finetuning 

### ISSUE THREAD

**Issue by tunner007** [UKPLab/sentence-transformers#132]
Can we use multiple GPUs for finetuning the models ?

**Comment by nreimers** [comment]
Not yet. I tried to add the Data Parallel wrapper, but it lead to a significant slow down if more than one GPU was used.

Best 
Nils Reimers

**Comment by tunner007** [comment]
Thanks for prompt response ! 
Actually I am trying to train xlmRoberta for multi lingual similarity task but with 1 gpu nd 16 batch size I get memory error... Can you suggest something which I can try ?

**Comment by chaochaoSZ** [comment]
@nreimers Any progress? Thanks.

**Comment by nreimers** [comment]
Hi @chaochaoSZ 
sadly no progress (didn't have  time).
