### ISSUE TITLE
CUDA out of memory error when using fast clustering

### ISSUE THREAD

**Issue by randomgambit** [UKPLab/sentence-transformers#1323]
Hello and thanks for this amazing package. The encoding is really blazing fast and this is great.

I am trying to cluster my sentences using the `fast_clustering.py` algorithm. Unfortunately, I get the classic error `CUDA out of memory. Tried to allocated 37 GiB` when my GPU card has (only) `24GB` available. 

Are there other alternatives to get the clustering done? Can the computation be performed on the CPU and the (non-GPU) RAM? I have 200GB of RAM available...

Thanks!!

**Comment by nreimers** [comment]
Yes, can be done on CPU. Move the tensors to cpu (`.to('cpu')`)

**Comment by randomgambit** [comment]
@nreimers , thanks! just a quick follow up: did you come up with the algorithm behind the fast clustering .py file? Or this is a standard one?
