### ISSUE TITLE
No Copyright Owner?

### ISSUE THREAD

**Issue by pmbaumgartner** [UKPLab/sentence-transformers#1325]
I was curious about the license while I was making a package with sentence transformers as a dependency, so I went to browse the `LICENSE` file, and noticed you hadn't filled in the name or year for the copyright.

[Line 189](https://github.com/UKPLab/sentence-transformers/blob/master/LICENSE#L189)
```
   Copyright {yyyy} {name of copyright owner}
```

I'm not a lawyer so I'm not sure what the implications are, but it might be good to fill it in.

Thanks for all the great work with sentence-transformers. It's one of my most used packages!

**Comment by nreimers** [comment]
Thanks, updated it.
