### ISSUE TITLE
How are different inputs for pretrained models handled?

### ISSUE THREAD

**Issue by NavanshGoel** [UKPLab/sentence-transformers#1327]
I have been using the pre-trained models involving 'all-mpnet-base-v2' model. I have been testing some different inputs that can be handled by the model. There are two scenarios I wanted to discuss;

Scenario 1:
For a list of lists such as: 

para = [["This is a line","sent2 is the second line","sent3 is also a line "]] 
The  embedding  generated is of length (1,768) 

Scenario 2:
but for input like :

para = ["This is a line","sent2 is the second line","sent3 is also a line "]
The output is of length (3,768)

I wanted to understand how the model is handling such variations of input and whether one approach is superior to the other. Is the first Scenario generating better embeddings in some way? And if so, what is the logic behind it?

Further, for Scenario 1, the model is not able to handle a case where there is only 1 string inside the list. 
Example:
para = [["This is a line","sent2 is the second line","sent3 is also a line "], ["The is a dummy line"]]
ans = model.encode(para,convert_to_numpy=True)

For this example, I get the following error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/tmp/ipykernel_18086/2688938991.py in <module>
      1 para = [["This is a line","sent2 is the second line","sent3 is also a line "], ["The is a dummy line"]]
----> 2 ans = model.encode(para,convert_to_numpy=True)

/data/shubham/PCR/FIRE2017-IRLeD-track-data/Code/SBERT/sentence-transformers/sentence_transformers/SentenceTransformer.py in encode(self, sentences, batch_size, show_progress_bar, output_value, convert_to_numpy, convert_to_tensor, device, normalize_embeddings)
    151         for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):
    152             sentences_batch = sentences_sorted[start_index:start_index+batch_size]
--> 153             features = self.tokenize(sentences_batch)
    154             features = batch_to_device(features, device)
    155 

/data/shubham/PCR/FIRE2017-IRLeD-track-data/Code/SBERT/sentence-transformers/sentence_transformers/SentenceTransformer.py in tokenize(self, texts)
    309         Tokenizes the texts
    310         """
--> 311         return self._first_module().tokenize(texts)
    312 
    313     def get_sentence_features(self, *features):

/data/shubham/PCR/FIRE2017-IRLeD-track-data/Code/SBERT/sentence-transformers/sentence_transformers/models/Transformer.py in tokenize(self, texts)
     86             for text_tuple in texts:
     87                 batch1.append(text_tuple[0])
---> 88                 batch2.append(text_tuple[1])
     89             to_tokenize = [batch1, batch2]
     90 

IndexError: list index out of range
--------------------------------------------------------------------------------

**Comment by nreimers** [comment]
Only the second scenario makes sense:
para = ["This is a line","sent2 is the second line","sent3 is also a line "]

You pass it as a list of strings. Each string can be a phrase, a sentence or a complete paragraph. No need to separate your sentences if you want to encode a paragraph.

The first option is for a special type of models, that supports 2 inputs which are joint together like this:
text[0]+" [SEP] "+text[1]

But the provided models have not been trained for this type of input. But you could train your own models to encode two text inputs that are connected (like title + body of an article).

**Comment by NavanshGoel** [comment]
Thanks for the quick reply, I just wanted to understand how the different input in the scenario is handled. Since it's not giving an error for the input:
para = [["This is a line","sent2 is the second line","sent3 is also a line "]]

What exactly is the logic behind giving the embedding of size (1,768)?

I computed the mean for the sentence embeddings created for :
["This is a line","sent2 is the second line","sent3 is also a line "]
and compared it to the embedding generated for:
para = [["This is a line","sent2 is the second line","sent3 is also a line "]]

But even these are not the same. 

Since I have been working on some collaborative work, a colleague had put in the input as:
para = [["This is a line","sent2 is the second line","sent3 is also a line "], ["A different line", "A unique line"]]
And this gave some embeddings. 
If you could give some insight on the handling of this type of input it would be really helpful.

Thanks again!

**Comment by nreimers** [comment]
As mentioned, you can train a model that takes 2 inputs, e.g. paper title & paper abstract.
You would represent your data then like this:
```
text = [
   ["Title1", "Abstract1"],
  ["Title2", "Abstract2"],
  ["Title3", "Abstract3"]
]
```

Anything more than 2 inputs in a list are ignored.

Here you would get 3 embeddings, each with 768 dimensions. Each embeddings would represent one paper. 

But the provided pre-trained models are not trained to take more than 1 input.

**Comment by NavanshGoel** [comment]
Ok, Thanks a lot for the reply!

**Comment by brucewlee** [comment]
@nreimers 

> Each string can be a phrase, a sentence or a complete paragraph.

I wonder if there'd be a performance decrease (let's say cosine semantic similarity measure) when encoding a complete paragraph, which is many more tokens than a sentence. After all, the performance metrics given by UKPLab bases on a sentence-length number of tokens, doesn't it?

**Comment by nreimers** [comment]
@brucewlee We test models with 2 types of tasks: Sentence similarity tasks and semantic search tasks (short query searching for docs up to 500 tokens). Models perform well for both settings. But of course representing paragraphs is more challenging than representing sentences

**Comment by brucewlee** [comment]
@nreimers thanks for confirming!
