### ISSUE TITLE
Is there a way to download a pretrained model in a different location?

### ISSUE THREAD

**Issue by sagar1025** [UKPLab/sentence-transformers#133]
Hello,

Initially, when this is run,
`model = SentenceTransformer('name_of_model')`
the model is downloaded and saved in the path `~/.cache/torch/sentence_transformers/`

Is there a way I can specify a custom path (such as `/tmp`) where I can save the pretrained model instead?

Thanks

**Comment by peacej** [comment]
@sagar1025 Hi Sagar, you can tweak the code in the `__init__` method in  https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py to save at a different path.

**Comment by nreimers** [comment]
Hi @sagar1025 
Currently this is not implement. But I will add it as a to do so that it will be added in the next version.

Best
Nils Reimers

**Comment by sagar1025** [comment]
Thank you both for the answers! I guess I'll just update the `__init__` method
