### ISSUE TITLE
Cannot load models - SentenceTransformer('all-MiniLM-L12-V2')

### ISSUE THREAD

**Issue by qcdyx** [UKPLab/sentence-transformers#1332]
Hello,

I got an HTTPError when I ran all-MiniLM-L12-V2 and all-MiniLM-L6-V2 pre-trained SBert models. 

model = SentenceTransformer('all-MiniLM-L12-V2')
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L12-V2

Similarly,
model = SentenceTransformer('sentence-transformers/all-MiniLM-L12-V2')
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L12-V2

I've checked that this url (https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L12-V2) is no longer available and the correct one seems to be https://huggingface.co/sentence-transformers/all-MiniLM-L12-v2.

I also tried all-mpnet-base-v2, sometimes it's found, and sometimes it's not.

Could you take a look at this issue?
---------------------------------------------------------------------------
My environment is
python 3.8
pytorch 1.10.0
sentence-transformers 4.11.3

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-18-a73087cb93fa> in <module>
      3 #all-MiniLM-L12-v2 --- efficient (fast & small)
      4 #model = SentenceTransformer('all-mpnet-base-v2')
----> 5 model = SentenceTransformer('all-MiniLM-L12-V2')
      6 
      7 

/users/jingsi_lu/anaconda3/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device, cache_folder)
     78 
     79                 # Download from hub with caching
---> 80                 snapshot_download(model_name_or_path,
     81                                     cache_dir=cache_folder,
     82                                     library_name='sentence-transformers',

/users/jingsi_lu/anaconda3/lib/python3.8/site-packages/sentence_transformers/util.py in snapshot_download(repo_id, revision, cache_dir, library_name, library_version, user_agent, ignore_files)
    424 
    425     _api = HfApi()
--> 426     model_info = _api.model_info(repo_id=repo_id, revision=revision)
    427 
    428     storage_folder = os.path.join(

/users/jingsi_lu/anaconda3/lib/python3.8/site-packages/huggingface_hub/hf_api.py in model_info(self, repo_id, revision, token, timeout)
    515         )
    516         r = requests.get(path, headers=headers, timeout=timeout)
--> 517         r.raise_for_status()
    518         d = r.json()
    519         return ModelInfo(**d)

/users/jingsi_lu/anaconda3/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    941 
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 
    945     def close(self):

HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/models/sentence-transformers/all-MiniLM-L12-V2

**Comment by nreimers** [comment]
The V2 must be in lower case: v2

**Comment by qcdyx** [comment]
Ok, thank you! I close this issue.
