### ISSUE TITLE
Fast(?) clustering

### ISSUE THREAD

**Issue by dopc** [UKPLab/sentence-transformers#1335]
Hey and thanks for the great work!

I just copy-pasted the `community detection` function and I am trying to use fast clustering method with 100D fasttext embeddings. The dataset I worked is about 42k sized and the algorithm takes almost 18 mins. on 2018 MacBook pro to run in total.

- Could be any point I am missing with just using the `community detection` function?

- Should I run it on GPU to get less execution time or is there another possibility?

Thanks.

**Comment by nreimers** [comment]
This is way too long, should be faster. On my server, it just takes a few seconds.

Is memory maybe an issue? Currently the algorithm has quadratic memory requirement, as 42k * 42k * 4 bytes must be stored.

Otherwise the hyperparameters are maybe not optimal. Do you get really large clusters which include nearly all points?

**Comment by dopc** [comment]
I do not think so the problem is about the memory.

> Do you get really large clusters which include nearly all points?

Actually this is the result of the algorithm with a parameter set: `{0: 42518, 1: 24}`. 

So the problem for me is that the runtime might be huge if you use wrong parameters. In my scenario user choose the parameters and they need to wait to see the result. Thus, I cannot take that risk at this point.

**Comment by nreimers** [comment]
Likely the threshold was too small. In that case, it creates 40k clusters, each with 40k entries. And then starts to remove overlapping clusters so you only end-up with 1 cluster.

You could check how large is the largest cluster. If it is too large, throw an exception that you need to use a larger threshold.

**Comment by dopc** [comment]
Yeah your guess is correct. Thanks for your help!
