### ISSUE TITLE
502 Server Error: Bad Gateway for huggingface URL. Can I make SentenceTransformers available offline?

### ISSUE THREAD

**Issue by MattesR** [UKPLab/sentence-transformers#1336]
Hi, 
When starting my code which loads a SBert-Model via `embedding_model = SentenceTransformer('paraphrase-mpnet-base-v2')`,
I sometimes get the following stacktrace, even though I've loaded the model several times:
```
  File "<loading_code>", line 14, in <module>
    embedding_model = SentenceTransformer('paraphrase-mpnet-base-v2')
  File "<local_env>/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 80, in __init__
    snapshot_download(model_name_or_path,
  File <local_env>/lib/python3.9/site-packages/sentence_transformers/util.py", line 454, in snapshot_download
    path = cached_download(
  File "<local_env>/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 352, in cached_download
    r.raise_for_status()
  File "<local_env>/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://huggingface.co/api/models/sentence-transformers/paraphrase-mpnet-base-v2
```
sometimes, the response from huggingface throws a different error: 
`requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://huggingface.co/sentence-transformers/paraphrase-mpnet-base-v2/resolve/505b5e8760cf767978564f4e77b544b37593ec84/modules.json
`

Isn't the entire model loaded when I first download the model? I saw that the loading a SentenceTransformer model doesn't even work when my internet connection is turned off.

**So my question**: What do I have to do in order to make a SentenceTransformer Model work, without a request to some server?  

By the way, I just noticed this by accident, since huggingface seems to be overburdened with requests from time to time.

**Comment by MattesR** [comment]
Hi @nreimers,
Thanks for the fix/workaround for the issue. Seems to be the best course of action if it happens more often. Good to know, that I'm not the only one running into this issue.

Kind Regards!

**Comment by Avenge-PRC777** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/48017720/150074638-e2837a8e-7f07-4e4d-92ec-498f2756c61e.png">
Faced similar issue, checked sentence-transformers at huggingface, I see they have mentioned to append "sentence-transformers/" to model name. I tried it and it works, the model got downloaded whereas initially it was facing 504 Gateway Error.
