### ISSUE TITLE
Multilingual Distilation PCA - which dataset to use?

### ISSUE THREAD

**Issue by rogeriochaves** [UKPLab/sentence-transformers#1339]
Hello,

I'm trying to follow the tutorial of model distillation [here](https://github.com/UKPLab/sentence-transformers/blob/42c1d69a96a75ce6594da6335b535cac99ee91d3/examples/training/distillation/dimensionality_reduction.py) but I'm using the pre-trained `paraphrase-multilingual-MiniLM-L12-v2` model, and I don't want to bias it to english, would it be the case if I use AllNLI as the example do? Which dataset do you recommend instead for paraphrase-multilingual?

Thanks!

**Comment by nreimers** [comment]
In the best case you do it on the corpus you want to work on

**Comment by rogeriochaves** [comment]
thanks, but I don't have the corpus ahead of time, it will be user generated content, maybe after a couple months I could collect it. Meanwhile, whould the same corpus used to train `paraphrase-multilingual` be enough (with 50 languages as said in the description)? Which dataset was it trained on?

**Comment by nreimers** [comment]
The distillation was done using this data:
https://huggingface.co/datasets/sentence-transformers/parallel-sentences

**Comment by rogeriochaves** [comment]
Thank you very much! This was very useful, I could reduce the size and my accuracy is still very good
