### ISSUE TITLE
recognition of a negated sentence.

### ISSUE THREAD

**Issue by snape6666** [UKPLab/sentence-transformers#134]
Hi,
Is there a way to recognize a negated sentence?

e.g.
I like pizza.
I dont like pizza.

Or does this implementation only can find similar sentences?

**Comment by nreimers** [comment]
Hi @snape6666 
This information might be somewhere hidden in the 768 dimensions, but it is unclear where and how it is hidden. So I'm afraid there is currently no straight forward solution to find / recognize negated sentences.


Best
Nils Reimers

**Comment by snape6666** [comment]
That's a pity, but if anyone has already made attempts to do so, I would be happy to hear from you!

**Comment by nreimers** [comment]
Hi @snape6666 
I am not aware of any available research. It is a rather hard research problem, as negation depends on the two input sentences.


Depending on the size of your data, maybe a classical classification would work for you. NLI (like SNLI https://nlp.stanford.edu/projects/snli/) has the following setup: Given sentence A and B, decide whether entailment / contradiction / neutral.

What you are looking for is the contradiction label. Using a NLI classifier (for example based on BERT), you could classify if two sentence are contradictions.

If you now want to retrieve negated sentences, you could use the following setup:
Given a sentence: 'I like pizza'.

1) Retrieve top 100 similar sentences  (s1, ..., s100)
2) For each  sentence, classify whether Negated('I like pizza', si) == 1
3) Use the results with the highest confidence, they should be the negated versions of 'I like pizza'.

Best
Nils

**Comment by snape6666** [comment]
@nreimers do you know something similar for german sentences?

**Comment by nreimers** [comment]
Hi @snape6666 
Something that works quite well is to translate sentences. Either you translate training data to your target language (German) or your translate at test time your sentences to English and you use an English model.

**Comment by snape6666** [comment]
You're right, for this application, that should be enough. Thx! =)
