### ISSUE TITLE
multitask training time

### ISSUE THREAD

**Issue by oooooolr** [UKPLab/sentence-transformers#1343]
Hi nreimers, i have two tasks .
When seperately train them one costs 3hours ,another costs 8hours, but when i use `training_multi-task.py` to train them, the whole training time is about 6hours. Is it normal?

**Comment by nreimers** [comment]
1 epoch is defined over the iteration over the shortest dataset. So 2*3h is expected

**Comment by oooooolr** [comment]
Read the code again, got it. Thank you!
