### ISSUE TITLE
Unable to download model

### ISSUE THREAD

**Issue by JackGao09** [UKPLab/sentence-transformers#1344]
I copied and ran the example code shown in https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2, but 502 Server Error occurred. The code was running in python3.7 conda env.

![无标题](https://user-images.githubusercontent.com/85552544/147444519-6ec93fd3-c866-41b2-bff7-fbad6561c951.png)

 Any solutions?

**Comment by nreimers** [comment]
Download by hand or update to version 2 of sentence Transformers

**Comment by JackGao09** [comment]
> Download by hand or update to version 2 of sentence Transformers

Solved. Thank you for your suggestion!
