### ISSUE TITLE
How to boost the speed of one sentence (no batches)?

### ISSUE THREAD

**Issue by AbdallahHefny** [UKPLab/sentence-transformers#1347]
Is there a way to increase the speed of inferring one sentence? I mean that I do not have batches.
Is there any software or hardware solution?

For example:
1) Will changing either (or both) interop and intraop threads have an effect?
2) Using GPU did not boost the speed of one sentence at a time? Am I doing something wrong?

Thanks a lot.

**Comment by nreimers** [comment]
Encoding on about 4-8 cores is optimal.

GPU will boost the encoding speed.  But when you encode your first sentence, the model must be transferred to GPU which is quite slow. Subsequent encodings are faster

**Comment by AbdallahHefny** [comment]
Thanks Nils for the reply.

About CPU:
For those 4-8 cores, how shall I divide them between inter and intra threads?
Also, won't increasing the number of cores above 8 boost the speed more?

About GPU,
Is that done automatically through the package? Or I need to do that? 
I am using a sentence translator model, and running the sentences through a for loop. The speed is similar for both CPU and GPU. 


Thanks.

**Comment by thejaswiraya** [comment]
@AbdallahHefny : You can increase the inference speed on GPUs by serving your model using torchserve. With torchserve the models are loaded onto the GPU and ready to serve. I have loaded several bi-encoders and cross-encoders models from sentence-transformers and they work like a charm. You should see significant improvement in inference speed for encoding sentences on GPU when compared to CPU. 

https://github.com/pytorch/serve/blob/master/README.md#serve-a-model

**Comment by AbdallahHefny** [comment]
@thejaswiraya Thanks a lot for such a nice suggestion. I will go with implementing it.
