### ISSUE TITLE
How to save the new corpus embeddings? and anyway to speed up the encoding process?

### ISSUE THREAD

**Issue by RohanYedagiri** [UKPLab/sentence-transformers#135]
Thank you for this awesome library., you made my life a whole lot easier.

On to the questions...
1.
```
from sentence_transformers import SentenceTransformer
embedder = SentenceTransformer('roberta-large-nli-stsb-mean-tokens')

new_corpus = df['field'].values
new_corpus_embeddings = embedder.encode(new_corpus)
```

Is there a way we could save `new_corpus_embeddings` into a file? so that we could load it like this
`embedder = SentenceTransformer('new_corpus_embeddings')`
 next time we run it (I'm using colab, so to encode new corpus every time is a very time consuming)

2. 
```
new_corpus_embeddings = embedder.encode(new_corpus)
```
anyway we could speed up the encoding process? `new_corpus` contains list of ~60k sentences (again I'm using colab)

**Comment by bimhud** [comment]
Just pickled it and reload when needed

**Comment by nreimers** [comment]
Hi,
the embeddings are returned as a numpy matrix. You can use numpy pickle to store and load these embeddings:
https://stackoverflow.com/questions/52444921/save-numpy-array-using-pickle

2) Are you using a GPU? On a GPU, around 1000 sentences / sec should be processed. On a CPU, transformer models is sadly quite slow.

You could also use the DistilBERT model. It is only about half the size of the full BERT model.

**Comment by RohanYedagiri** [comment]
Thank you, it worked.

I was using CPU, but now I changed notebook settings to use GPU., as expected process is faster.

**Comment by rjurney** [comment]
@nreimers @bimhud How do you send a string to the GPU? I can't figure this out.
