### ISSUE TITLE
PAUSE - Positive and Annealed Unlabeled Sentence Embedding

### ISSUE THREAD

**Issue by sorenmc** [UKPLab/sentence-transformers#1354]
Are there future plans for implementing PAUSE training into the framework? According to their paper they achieve very good results with very little annotated data.

[code](https://github.com/EQTPartners/pause)
[paper](https://aclanthology.org/2021.emnlp-main.791.pdf)

**Comment by nreimers** [comment]
I sadly will not have the time to implement this. But a PR would be appreciated.

The tests of this method in the paper are not that extensive, so it would be interesting to see better / more extensive tests of the approach and comparison to other learning approaches.

**Comment by sorenmc** [comment]
Okay, thank you for your reply. If i have time for implementing it during my thesis, i will make a PR.
