### ISSUE TITLE
Support for model repository revisions

### ISSUE THREAD

**Issue by Muennighoff** [UKPLab/sentence-transformers#1373]
I'm facing some difficulties of using this repository in production due to its limited support for commit strings / revisions. Would it be possible to implement the below two changes:

a) Allow the huggingface `revision` kwarg to be fed into `SentenceTransformer(..)` which is then fed into `snapshot_download` to know for sure a certain model version is downloaded? 
b) Not overwrite the default huggingface filename in [snapshot_download](https://github.com/UKPLab/sentence-transformers/blob/2158fff3aa96651b10fe367c41fdd5008a33c5c6/sentence_transformers/util.py#L410)? By default huggingface [seems to keep the revision](https://github.com/huggingface/huggingface_hub/blob/eeeb0d1b352fb3249541bb62f1f57f41ae3ab4e0/src/huggingface_hub/constants.py#L32) in the filename. This can then be used to detect the revision downloaded from the environment. Overwriting it with `force_filename=relative_filepath` causes us to lose this piece of information... :(

Thanks for this amazing repo!

**Comment by JohnPaton** [comment]
+1, right now I guess the workaround would be to use huggingface to download the model with revision and then load it in sentence-transformers from disk, but it's not really nice.

**Comment by tomaarsen** [comment]
Implemented in #2419, it will be included in the next release.
