### ISSUE TITLE
Typo? GPU vs. CPU

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#1375]
Should this better be `Hence, WKPooling runs on the CPU, which makes it rather in-efficient.`?

https://github.com/UKPLab/sentence-transformers/blob/2158fff3aa96651b10fe367c41fdd5008a33c5c6/examples/evaluation/evaluation_stsbenchmark_sbert-wk.py#L7

**Comment by nreimers** [comment]
Yes, it should mean CPU
