### ISSUE TITLE
Sentence Similarities and New network

### ISSUE THREAD

**Issue by kimgimkigi** [UKPLab/sentence-transformers#1377]
Hi

I'm just starting to use SentenceTransformers and thanks for your helpful tools.
I have a simple problem when I try sentence similarities examples and new network examples.

Now I'm trying to follow below examples
Sentence similarities : https://www.sbert.net/docs/training/overview.html
New network : https://www.sbert.net/docs/quickstart.html

My final goal is to check sentence similarity on reduced vector size model. (for 'all-mpnet-base-v2' model, 768 -> 384 or lower)
So I following to set a new network model examples to this.

![image](https://user-images.githubusercontent.com/77488439/149667032-a83d6ea6-53b6-4b04-af97-ecf8bdd9bbd4.png)

after setting model, I just tried to check text similarities in simple sentences.
but when I checked similarities with sentence similarity quick start codes, Each time, the similarity is different.

![image](https://user-images.githubusercontent.com/77488439/149667358-b45a8ca6-fe18-483c-aa7f-cb5b20cb3438.png)

below is my full-code.

![image](https://user-images.githubusercontent.com/77488439/149667671-1c7a6b35-bf2b-4950-b406-bb6950c916f7.png)

Is there any randomness or irregularity on my model or SentenceBert code?
I cannot understand why my model always outputs different similarities in the same sentences.

Can I get some advice for this situation? Thanks!

**Comment by nreimers** [comment]
When you initialize a new Dense layer, the weights are assigned randomly. Hence, you get different results each time. You would need to train the Dense layer.

You could also use PCA to train the Dense Layer. See:
https://www.sbert.net/examples/training/distillation/README.html#dimensionality-reduction
