### ISSUE TITLE
Save sentence models locally (in my case gdrive, colab)

### ISSUE THREAD

**Issue by RohanYedagiri** [UKPLab/sentence-transformers#138]
How do we save the sentence models (e.g. roberta-large-nli-stsb-mean-tokens) locally as a compressed file? so we could load it as a zip file by giving model path instead of downloading from server.

```
embedder = SentenceTransformer('roberta-large-nli-stsb-mean-tokens')
```

since I'll have to run this on colab, every morning runtime recycles and when i run the above code it downloads 1.3G from server.

If could save it as a zip file in gdrive, it'll be much easier.

I couldn't find it here
https://public.ukp.informatik.tu-darmstadt.de/reimers/embeddings/

Thanks in advance.

**Comment by nreimers** [comment]
Hi,
you can find the models here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

In your code:
```
embedder = SentenceTransformer('path/on/your/disc/to/unzipped/model/roberta-large-nli-stsb-mean-tokens')
```
