### ISSUE TITLE
Support for Audio Data

### ISSUE THREAD

**Issue by mabu-dev** [UKPLab/sentence-transformers#1383]
Is there a way to use speech models like Wav2Vec for audio encoding? More like how we can use CLIP for image encoding.

**Comment by nreimers** [comment]
Currently it is not implemented, but could be added. One would just need to create a class similar to model.Transformer.

Sadly I'm not too familiar with audio / Wav2Vec

**Comment by mabu-dev** [comment]
Thanks @nreimers
