### ISSUE TITLE
Latency while using basic code example

### ISSUE THREAD

**Issue by Liranbz** [UKPLab/sentence-transformers#1405]
Hi,
I try to run this simple code example:

```
from sentence_transformers import SentenceTransformer
import time

if __name__ == '__main__':
    start_time = time.time()
    model = SentenceTransformer('all-MiniLM-L6-v2')
    sentences = ['This framework generates embeddings for each input sentence',
                 'Sentences are passed as a list of string.',
                 'The quick brown fox jumps over the lazy dog.']

    sentence_embeddings = model.encode(sentences)

    for sentence, embedding in zip(sentences, sentence_embeddings):
        print("Sentence:", sentence)
        print("Embedding:", embedding)

        print("")
    print("--- %s seconds ---" % (time.time() - start_time))
```
and I get 872 seconds runtime (see print screen below)
what I'm doing wrong?
thanks
![image](https://user-images.githubusercontent.com/51919286/152005143-58a106cb-5ceb-4d60-9371-6a16674c6324.png)

**Comment by nreimers** [comment]
On the first run, the model must be downloaded. Depending on the connection, this can be slow.

Also the model must be loaded from disc. This can also be slow.

Maybe if you have a GPU, it must also be moved to GPU. Which is also not the fastest.

But 900 secs is really uncommon. I think the download was really slow for you?

**Comment by Liranbz** [comment]
@nreimers may I run it again and share the results?

**Comment by Liranbz** [comment]
@nreimers I guess something was bad in my side, currently its 9 sec.
Thanks!
