### ISSUE TITLE
Passing additional parameters to forward like in Transformers library

### ISSUE THREAD

**Issue by DT6A** [UKPLab/sentence-transformers#1407]
Hello! Is it possible to pass additional arguments to the forward function of SentenceTransformers so they will be applied as in Transformers library? For example in Transformers `forward` function has argument `past_key_values`. Can I pass values that will be fed to the model as `past_key_values` variable?

It seem like I have to change the code here https://github.com/UKPLab/sentence-transformers/blob/a94030226da1f4b03f9d703596b0ebd360c9ef43/sentence_transformers/models/Transformer.py#L60
Is that right?

**Comment by nreimers** [comment]
I'm not familiar with past_key_values, what is the purpose of it? I just know that generation models like GPT2 have it.

Otherwise you can load the models also directly with HF transformers `AutoModel` class an pass any parameters you need

**Comment by DT6A** [comment]
So I can just load `all-mpnet-base-v2` with `AutoModel` and this model will share weights that SentenceTransformer(`all-mpnet-base-v2`) has. Am I right?

**Comment by nreimers** [comment]
Yes
https://huggingface.co/sentence-transformers/all-mpnet-base-v2#usage-huggingface-transformers

**Comment by DT6A** [comment]
Ok, I'll try it. Thanks a lot!
