### ISSUE TITLE
How to suppress warning "Ignored unknown kwarg option direction"

### ISSUE THREAD

**Issue by apoorvumang** [UKPLab/sentence-transformers#1410]
Hi

I am using the default example code with sentence-transformer version `2.1.0` and I get the following warning each time I use `model.encode`

```
>>> embeddings = model.encode(sentences)
Ignored unknown kwarg option direction
```

This is very annoying when I'm trying to use this in a loop with tqdm. Is there a way to remove this warning?

Thanks

**Comment by apoorvumang** [comment]
PS: using `python -W ignore` doesn't help either

**Comment by apoorvumang** [comment]
This seems to be related to tokenization https://github.com/huggingface/transformers/issues/15358 

Any help would be greatly appreciated.

**Comment by nreimers** [comment]
I had the same issue. It is an issue in tokenizers. Updating to the newest version helped:
```
pip install -U transformers tokenizers
```

**Comment by apoorvumang** [comment]
Thank you!

**Comment by jayeshchoudhari** [comment]
> I had the same issue. It is an issue in tokenizers. Updating to the newest version helped:
> 
> ```
> pip install -U transformers tokenizers
> ```

Have tried with the updated version of tokenizers (0.11.6), but still see this warning multiple times while using [keyBERT](https://maartengr.github.io/KeyBERT/guides/quickstart.html)
