### ISSUE TITLE
how to load model as SentenceTransformer after MLM finetuning

### ISSUE THREAD

**Issue by negar-mokhberian** [UKPLab/sentence-transformers#1414]
Hi,

Based on the [MLM fine-tuning code](https://github.com/UKPLab/sentence-transformers/blob/master/examples/unsupervised_learning/MLM/train_mlm.py) the type of model used for fine-tuning is AutoModelForMaskedLM and then it will be saved with this type. 
I was wondering if there is a way to load the fine-tuned model as SentenceTransformer? I am already using functions specific to SentenceTransformer such as encode() in my code and want to avoid changing them to general form of huggingface models. 

Thanks!

**Comment by nreimers** [comment]
You can load them with the normal functions, no changes needed

**Comment by negar-mokhberian** [comment]
Got it, thanks a lot!
