### ISSUE TITLE
Confusing problems of batch_size in Multi-task learning

### ISSUE THREAD

**Issue by HenryYuen128** [UKPLab/sentence-transformers#1415]
I am now using multi-task learning, there are some confusing problems:

1. batch size

```
train_batch_size=64

onli_train_examples = read_train_data('ONLI')

onli_train_dataset = SentencesDataset(onli_train_examples, model)

onli_train_dataloader = DataLoader(onli_train_dataset, shuffle=True, batch_size=train_batch_size)

train_onli_loss = losses.SoftmaxLoss(model=model,sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=3)
```

however, something strange happens in fit() in SentenceTransformer.py :

        
```
     for epoch in trange(epochs, desc="Epoch", disable=not show_progress_bar):
            training_steps = 0

            for loss_model in loss_models:
                loss_model.zero_grad()
                loss_model.train()

            for _ in trange(steps_per_epoch, desc="Iteration", smoothing=0.05, disable=not show_progress_bar):
                for train_idx in range(num_train_objectives):
                    loss_model = loss_models[train_idx]
                    optimizer = optimizers[train_idx]
                    scheduler = schedulers[train_idx]
                    data_iterator = data_iterators[train_idx]

                    try:
                        data = next(data_iterator)  **# Here len(data) = 2, it should be equal to batch size?**
                    except StopIteration:
                        data_iterator = iter(dataloaders[train_idx])
                        data_iterators[train_idx] = data_iterator
                        data = next(data_iterator)


                    features, labels = data
```

2. For multi-task learning, why do we get steps_per_epochs as below?
            `steps_per_epoch = min([len(dataloader) for dataloader in dataloaders])`

Given the minimum value, data in other tasks will be missed?

**Comment by nreimers** [comment]
Yes, that is right.

if you have 2 datasets:
Dataset A with 100k examples
Dataset B with 1k examples

How to select the steps_per_epoch? Either you miss data, or you repeat one dataset quite many times.

So here we use the smallest dataset to determine an epoch. Then you can control over the epoch value how often you want to repeat on this dataset. For other larger datasets, the iterator is kept. So if you run above e.g. 10 epochs, you will repeat 10 times on dataset B and use 10k examples from dataset A

**Comment by nreimers** [comment]
Features is a dict with different input features

**Comment by HenryYuen128** [comment]
> Features is a dict with different input features

Got it. Thx!
