### ISSUE TITLE
The model requires sentence-transformers version 2.2.0 or newer.

### ISSUE THREAD

**Issue by SkyeCC** [UKPLab/sentence-transformers#1416]
Hello!
    Thanks for your great work! I tried to use model _sentence-t5-base_ , it needs sentence-transformers version >=2.2.0.But the newest version is 2.1.0.

**Comment by nreimers** [comment]
I'm currently working on releasing 2.2.0. Just wait 5 minutes and it will be available ;)

**Comment by SkyeCC** [comment]
I upgraded sentence-transformers to 2.2.0.I tried to use it,but I got a problem: `json.decoder.JSONDecodeError`. python 3.6.13

**Comment by nreimers** [comment]
What is your code? What is the full error?

**Comment by SkyeCC** [comment]
When I  tried to use sentence-t5-large like this:
`model=st.SentenceTransformer(model_name_or_path='/home/BertModel/SentenceTransfomersModel/sentence-t5-large`
I got an error like this:
`    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by nreimers** [comment]
Do you have all needed files? Appears that a json file is empty
