### ISSUE TITLE
Improving `util.paraphrase_mining`

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#1431]
I tried your `util.paraphrase_mining` on the German Mozilla Commen Voice Corpus. Unfortunately such pairs came back (differences marked with *):

```text
Gouverneur des Bundesstaat**s Nebraska.
Gouverneur des Bundesstaat*e*s Nebraska.

Totes Gewebe bindet man ab, damit es den Rest de*s* Körpers nicht vergiftet.
Totes Gewebe bindet man ab, damit es den Rest de*r* Körpers nicht vergiftet.
```

Unfortunately, these pairs are not really suitable for training I think. My idea to prevent this would be to look for pairs with a high cosine similarity but a low TF-IDF similarity. What do you think @nreimers ? Have you implemented something like this?

Or should I just remove clusters with a high TF-IDF similarity and replace them with a single cluster representative? As a preprocessing step...

**Comment by nreimers** [comment]
Yes, that makes sense. You could also tokenize it and simply compute the jaccard similarity of the two texts. This will give you all pairs that have a high lexical overlap.

**Comment by PhilipMay** [comment]
Many thanks.

Closing this...
