### ISSUE TITLE
custom collate function with dataloader

### ISSUE THREAD

**Issue by iakshat** [UKPLab/sentence-transformers#1435]
Hi! I am trying to use MultipleNegativesRankingLoss with separated duplicate samples using a custom batch_sampler. But in order to correctly batch my samples, I need to pass their identifier in dataset and use a custom collate function to convert it to an InputExample as expected by the library. But the function would get overwritten [here](https://github.com/UKPLab/sentence-transformers/blob/42ab80a122ad521a4f9055f5530a954d29d232ce/sentence_transformers/SentenceTransformer.py#L636). Am I interpreting this correctly? If yes, Is there any another way to implement this?

**Comment by nreimers** [comment]
Hi,
so far I never needed to change the data collator. It always worked when I wrote my own custom Dataset / DataLoader or batch_sampler.

If you still need to change the data collator, you could:
- Create your own DataLoader that ignore the collate_fn function. Creating your own DataLoader is quite easy, you just need a __iter__ method that yields the batches
- Overwrite the smart_batching_collate function of the SentenceTransformer object externally (e.g. something like `model.smart_batching_collate = your_collate_function`

Best Nils

**Comment by iakshat** [comment]
Hello Nils,
Thank you for the reply. I'm sure a DataLoader will solve my problem!

As a possible improvement, it would be really great if we could call the original collate function automatically before the smart_batch_collate. It'll make the library even more flexible.

This could be a possible way to implement this:
```
class Collator(object):
    def __init__(self, original_colate):
        self.original_colate =original_colate
    def __call__(self, batch):
        batch=self.original_colate(batch)
        return smart_batch_colate(batch)
```
