### ISSUE TITLE
Tokenize input sentence

### ISSUE THREAD

**Issue by r1ckC139** [UKPLab/sentence-transformers#1438]
what is difference when call model.tokenize(sentence_input)["input_ids"] and model.tokenizer.convert_tokens_to_ids() ? As far as I understand both of these functions convert the input sentence to input_ids, but the result is different ?

**Comment by nreimers** [comment]
Don't know, try it out

**Comment by r1ckC139** [comment]
Hi @nreimers ,thank you for you quick response.
when fine-tuning BERT, there is always have a tokenizer loading step to tokenize input sentence into subswords. As far as i know in SBERT when call:
` model = models.Transformer('bert-base-uncased', max_seq_length=256)`
SBERT Load both bert model and it's tokenizer
My question is where and how SBERT do tokenize step. is right if i call this `model.tokenizer.convert_tokens_to_ids(model.tokenizer.tokenize("We should tell him the truth"))`

**Comment by nreimers** [comment]
You can just call `model.tokenize()` and then you get the token ids, attention ids and type ids

**Comment by r1ckC139** [comment]
yep, but when i call `model.tokenize` return me input_ids with (nx3) matrix is it's different from `model.tokenizer.convert_tokens_to_ids` just one dimensional vector
![ảnh](https://user-images.githubusercontent.com/61724310/155490668-52a46237-8d12-45bd-9901-9eec2d0aedfe.png)
![ảnh](https://user-images.githubusercontent.com/61724310/155490906-fdabedd3-6b79-4eaf-92c6-c83411f49a2b.png)

**Comment by nreimers** [comment]
You need to pass it as a list: model.tokenize(["your text"])

**Comment by r1ckC139** [comment]
@nreimers, you right
Thank you very much !!!
