### ISSUE TITLE
[Question] Batch encoding produces different embeddings

### ISSUE THREAD

**Issue by StaticRocket** [UKPLab/sentence-transformers#1453]
I've noticed that batch encoding with a batch size larger than 1 produces slightly different embeddings than a batch with batch_size=1 or encoding a single sentence. It this expected behavior?

I noticed it generates just enough of a difference in the embeddings that the cosine score changes, quite reliably, after the sixth decimal place.

This shift is the same for all embeddings produced, regardless of model being used. The only thing that changes the shift is increasing the size of the list of sentences given or adjusting the batch_size to any number less than the length of the list of sentences to be encoded. Sounds like some kind of precision issue.

This is using:
```
sentence-transformers==2.0.0
transformers==4.6.1
torch==1.9.0+cu111
```
On Python 3.6.8

**Comment by nreimers** [comment]
Yes, this is known and normal. For downstream tasks it has no effect.

**Comment by StaticRocket** [comment]
Ah, yeah I just found this thread: https://github.com/pytorch/pytorch/issues/58128

My bad
