### ISSUE TITLE
Problem About Custom activation_function in Dense

### ISSUE THREAD

**Issue by cgpeter96** [UKPLab/sentence-transformers#1470]
My code
```python
word_embedding_model = models.Transformer(model_name)
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)
dense_model = models.Dense(in_features=pooling_model.get_sentence_embedding_dimension(), out_features=output_dim,activation_function=lambda x:x)
model = SentenceTransformer(modules=[word_embedding_model,pooling_model,dense_model])
```

**Note**
I do not wanna use any activation_function. To keep my model work normally, I create a lambda function without any operation.

When I finish my model traning , I need to predict data by my model. A problem happen!!
```
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.8/site-packages/sentence_transformers/util.py", line 316, in import_from_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

I read the source  code of `SentenceTransformers` and find that most module need to function `import_from_string` to load. 

The problem happen in `dense_model = models.Dense(in_features=pooling_model.get_sentence_embedding_dimension(), out_features=output_dim,activation_function=lambda x:x)` . 

Let's read the source code of Dense,
```python
@staticmethod
    def load(input_path):
        with open(os.path.join(input_path, 'config.json')) as fIn:
            config = json.load(fIn)

        config['activation_function'] = import_from_string(config['activation_function'])()
        model = Dense(**config)
        model.load_state_dict(torch.load(os.path.join(input_path, 'pytorch_model.bin'), map_location=torch.device('cpu')))
        return model
# my config
{"in_features": 768, "out_features": 128, "bias": true, "activation_function": "function"}
```
when resume the model weight of Dense, the Dense need to use `import_from_string` to load target module.

`import_from_string("function") `  would be raise a exception, because the `"function"` cannot be found or mean not dot in "function" ( `module_path, class_name = dotted_path.rsplit('.', 1)`). 

Please provide a  `EmptyModule` in SentenceTransformers? e.g.
```python
class EmptyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self,*args):
          return args
```

**Comment by nreimers** [comment]
You can pass: torch.nn.Identity

as activation function. It does exactly what you want.

https://pytorch.org/docs/stable/generated/torch.nn.Identity.html

**Comment by cgpeter96** [comment]
> 

Thanks:D, I use a ugly way that modify the `load` method in `Dense` to keep my model normally.
