### ISSUE TITLE
train with unbalance dataset

### ISSUE THREAD

**Issue by srulik-ben-david-hs** [UKPLab/sentence-transformers#1474]
is there an option to add weights to the loss function in order to deal with unbalance data (multilingual unbalance data), or is there any other method for this issue?
The specific task is sentence semantic similarity.

thanks!!

**Comment by nreimers** [comment]
You could create your own loss class. It is not that difficult.

Currently there is no such function implemented

**Comment by srulik-ben-david-hs** [comment]
awesome, thanks!
