### ISSUE TITLE
Cross Encoders EarlyStopping?

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [UKPLab/sentence-transformers#1478]
I see a callback option in the fit() for cross encoders but how should I use it with an ```EarlyStopping callback```?

Please advise or point me in the right direction

**Comment by nreimers** [comment]
Early stopping the training process is not really possible, only way would be to exit / kill the process.

**Comment by PrithivirajDamodaran** [comment]
Ahh ok ! Thanks

so typically for cross-encoder fine-tuning (believe you are adding a sequence classification head) 2 epochs is acceptable ? Anecdotally speaking ? 

I am just worried about overfitting a cross-encoder.

**Comment by nreimers** [comment]
3-4 epochs is common, but depends on the size of training data.
