### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by matsaliu** [UKPLab/sentence-transformers#148]
The python examples/datasets/get_data.py isn't running on my google colab. Please what can I do?
![Capture 1](https://user-images.githubusercontent.com/59641070/76103629-999b1780-5f97-11ea-8a18-4ea2c0afd42d.PNG)

**Comment by cabhijith** [comment]
Hi @matsaliu , 
I believe you are using the wrong syntax. Try adding a ```!``` to run terminal commands. Try: 
```!python examples/datasets/get_data.py```
