### ISSUE TITLE
how do I speed up the load time of the SentenceTransformer()?

### ISSUE THREAD

**Issue by sagar1025** [UKPLab/sentence-transformers#149]
I'm using a pretrained model saved in the (default) path  
`~/.cache/torch/sentence_transformers`

I ran the following code about 5 times
```
        start = timeit.default_timer()
        model = SentenceTransformer('bert-base-nli-mean-tokens')

        stop = timeit.default_timer()
        print('Time: ', stop - start)
```

and it's averaging about 2.6 seconds.

It could just be the computer I'm using it on, but is there a way to speed this up?
I'm running this in a Linux environment with 32GB of RAM

**Comment by chaochaoSZ** [comment]
So have U solved this?

**Comment by sagar1025** [comment]
Yes. Once downloaded, I saved the model using `torch.save()` and whenever needed, I load the model using `torch.load()` as shown here
https://pytorch.org/tutorials/beginner/saving_loading_models.html
