### ISSUE TITLE
Bi-Encoder encode passages

### ISSUE THREAD

**Issue by r1ckC139** [UKPLab/sentence-transformers#1491]
Hi there,
I'm running the demo notebook semantic_search_wikipedia_qa.ipynb, in the encode corpus stage you encode each passage as [title, text] so What is the embed vector of the title used for ?
![ảnh](https://user-images.githubusercontent.com/61724310/160969651-16976b5c-f3d0-4bff-abc6-7821bba37584.png)
and if you encode corpus like this, the shape of corpus_embeddings should be (length_corpus, 2, 768) but it's just (length_corpus, 768)
![ảnh](https://user-images.githubusercontent.com/61724310/160969963-89993eca-4428-4d4c-97b8-85dda29ed855.png)

**Comment by nreimers** [comment]
The two texts are concatenated, i.e. title [SEP] text is encoded by the model

**Comment by r1ckC139** [comment]
Thanks for your response,
So if i want to train SBERT with input context like 'title [SEP] text', train_samples should be a list InputExample like this:
![Screenshot from 2022-04-14 09-31-19](https://user-images.githubusercontent.com/61724310/163302418-658602ae-e8a0-48c9-b233-a50cc63766f3.png)
am i right ?

**Comment by nreimers** [comment]
Yes
