### ISSUE TITLE
STS Labeling range vs CosSim range

### ISSUE THREAD

**Issue by abmitra84** [UKPLab/sentence-transformers#1493]
Hi @nreimers ,

If I understand correctly normalised STS labeling will range between 0 and 1 while the CosSim will range between -1 and 1. If we think about the validation metrics being correlational will it not cause issue with correlation value as we don't know how to map the negative CosSim similarity values to 0-1 range in ground truth on validation set ?

**Comment by nreimers** [comment]
No, it will not cause any issues.

**Comment by abmitra84** [comment]
Ok thanks
