### ISSUE TITLE
Cross encoders return strange results.. 

### ISSUE THREAD

**Issue by tempdeltavalue** [UKPLab/sentence-transformers#1499]
I assume problem in with checkpoints , but I don't understand how to fix that..

![Screenshot from 2022-04-03 14-35-55](https://user-images.githubusercontent.com/36921178/161426117-a4fc8cd6-ebe5-4cc5-bf21-33992a253146.png)

**Comment by nreimers** [comment]
The model is a bi-encoder model and must be loaded with SentenceTransformer class.
