### ISSUE TITLE
Getting Word Embedding from trained model

### ISSUE THREAD

**Issue by hrsmanian** [UKPLab/sentence-transformers#150]
Hi, first of all, great work. 
After training a model using sentence transformers, Is it possible to get individual word embeddings if needed? Kindly let me know

Thanks

**Comment by nreimers** [comment]
Hi @hrsmanian 
I just added an option to do this:
https://github.com/UKPLab/sentence-transformers/issues/163#issuecomment-601679678


Note that the word piece embeddings are returned, i.e. one word can be broken down into multiple word pieces and hence, get multiple token embeddings.


Best
Nils Reimers

**Comment by hrsmanian** [comment]
Thanks a lot for your reply and code changes. I think I can take the word piece embeddings and average to get the word embeddings.
