### ISSUE TITLE
Support untied bi-encoder training?

### ISSUE THREAD

**Issue by jordane95** [UKPLab/sentence-transformers#1510]
Hello,

I noticed that the DPR use separate encoders for query and passage encoding. But it appears that the APIs in your lib only support tied bi-encoder training. 

Do I need to rewrite loss model to support untied encoder or is there some easy way out?

**Comment by nreimers** [comment]
You can use the Asym class:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/models/Asym.py

Using tied weights usually gives better performances (in all my experiments and also in a lot of other experiments from other groups)

**Comment by jordane95** [comment]
Thanks!

I just find one paper [xMoCo](https://aclanthology.org/2021.acl-long.477/) who claims that they get better results with two independent encoders.

**Comment by nreimers** [comment]
It uses a negative cache with a slowly moving encoder. This quite a different story.
