### ISSUE TITLE
Why call bi-encoder?

### ISSUE THREAD

**Issue by ralgond** [UKPLab/sentence-transformers#1519]
Hi, 

I read the example [semantic_search_wikipedia_qa.py](https://github.com/UKPLab/sentence-transformers/blob/46a149433fe9af0851f7fa6f9bf37b5ffa2c891c/examples/applications/semantic-search/semantic_search_wikipedia_qa.py) and find there are only one encoder, whose name is 'bi_encoder'.  In the example, docs is encoded by bi_encoders, and query is also encoded by the same encoder 'bi_encoder'.

so, I am confused why the encoder is call bi-encoder?

Thanks.

**Comment by r1ckC139** [comment]
@ralgond 
yeah it's just one encoder, the reason they call is "bi encoder" because the they use encoder to embed sent a, sent b  independently
