### ISSUE TITLE
Triplet Loss

### ISSUE THREAD

**Issue by r1ckC139** [UKPLab/sentence-transformers#1521]
in [https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/other/training_wikipedia_sections.py](url) file, when you create training samples you pass label=0 for each InputExample
![Screenshot from 2022-04-15 17-23-26](https://user-images.githubusercontent.com/61724310/163560384-c32aa6fa-5650-4865-92a8-1828ce6bbc4a.png)
but don't in dev samples
![Screenshot from 2022-04-15 17-27-23](https://user-images.githubusercontent.com/61724310/163560478-25c0af12-63d6-4fa7-bb08-ea92141e458b.png)
so what is label=0 for ? as i understand it, when using triplet loss we don't need label for training, triplet loss will minimizes the distance between anchor and positive while it maximizes the distance between anchor and negative

**Comment by nreimers** [comment]
The label is ignored. In old versions of sentences transformers it was necessary to pass a value
