### ISSUE TITLE
MultipleNegativesRankingLoss with Hard Negatives

### ISSUE THREAD

**Issue by r1ckC139** [UKPLab/sentence-transformers#1525]
if i want to use many hard negatives for each pair training input, is oke if i do this ?
`train_samples.append(InputExample(a1, p1, h1))`
`train_samples.append(InputExample(a1, p1, h2))`
`....`
`train_samples.append(InputExample(a1, p1, hn))`
h1 is hard negative 1 for (a1, p1)
h2 is hard negative 2 for (a1, p1) and so on.

**Comment by nreimers** [comment]
Yes, but you must ensure that a1 and p1 does not appear twice in the same mini batch.

One solution is e.g. implemented here:
https://github.com/UKPLab/sentence-transformers/blob/8822bc4753849f816575ab95261f5c6ab7c71d01/examples/training/nli/training_nli_v2.py#L88
