### ISSUE TITLE
how can i get the text pair similarity?

### ISSUE THREAD

**Issue by boscoj2008** [UKPLab/sentence-transformers#1533]
I have dataset A of sentences and dataset B of the same, I would like to calculate the similarity between setence a and sentence b and for all sentence pairs. Could you please give me an idea?

**Comment by nreimers** [comment]
You can use `from sklearn.metrics.pairwise import paired_cosine_distances`

**Comment by boscoj2008** [comment]
Great thanks for always responding to queries. 
So I used the above method and it works just fine. But the cosine similarity between non matching text pair is very close (and sometimes higher) than matching text pairs. How can I solve this problem ? Basically, I intend to give combine numerical features with BERT for a classification task.

**Comment by nreimers** [comment]
If the out of the box models don't work you need labeled text pairs

**Comment by boscoj2008** [comment]
Thanks but could you elaborate more ? I appreciate you time on this. 🙌🏻
