### ISSUE TITLE
What does .encode() actually do to extract the embeddings ?

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [UKPLab/sentence-transformers#1536]
Looked at the code, it reads .encode() obtains the embeddings by looping through all hidden states (i.e. sequence outputs from all layers).

Question: But the shape of the output embeddings is 1D, it just has the ```(hidden dim size,)``` i.e (512, or 768,), as opposed to 2D ```(input_ids, hidden dim size)``` for text models and ```(pixel_values, hidden dim size)``` for vision models. So are the sentence embeddings obtained are got by adding an MLP head on top of the **sequence output of all layers** ? or by adding an MLP head on top of the **pooler output**  of the ```sequence output of all layers```? Please clarify.

Also the MLP head is the classic one i.e. simple linear layer within, out features + classic tanh activation, and no dropouts of any sort ?

Please advice ..

**Comment by nreimers** [comment]
In most cases mean pooling is performed: All output embeddings are averaged to give the fixed representation

**Comment by nreimers** [comment]
Just the mean of the last layer

**Comment by PrithivirajDamodaran** [comment]
> Just the mean of the last layer

Thanks, one last thing.

I see Mean is the default pooling strategy, but there is "CLS" only pooling strategy when is it recommend in the context of sentence embeddings (over the mean or max) ? 

Please advice.

**Comment by nreimers** [comment]
Mean worked better in all of my experiments
