### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Ywandung-Lyou** [UKPLab/sentence-transformers#1544]
<img width="1267" alt="无标题" src="https://user-images.githubusercontent.com/57492327/167099935-9d142e35-d82f-46bd-b733-cd9c0ce6cdea.png">
I install sentence-transformers via conda but fail to import it.

**Comment by tomaarsen** [comment]
Hello!

This should be resolved in the most recent version (2.2.2). I'll close this accordingly.

- Tom Aarsen
