### ISSUE TITLE
Using logging.warning instead of logger.warning in SentenceTransformer.py

### ISSUE THREAD

**Issue by doyled-it** [UKPLab/sentence-transformers#1552]
In [sentence_transformers/SentenceTransformer.py](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py), the built in module `logging` is being used instead of the instantiated `logger` (on [line 31](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L31)).

This incorrectly formats the log statements throughout the rest of the file:
  - [line 469](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L469)
  - [line 490](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L490)
  - [line 493](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L493)
  - [line 511](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L511)
  - [line 796](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L796)

**Comment by nreimers** [comment]
Thanks, it should be fixed now
