### ISSUE TITLE
Process exits with status 139 when trying to instantiate a SentenceTransformer

### ISSUE THREAD

**Issue by ivan-rivera** [UKPLab/sentence-transformers#1556]
### Description

Hi all, I'm running into a strange error while trying to run the following:

```python
import sentence_transformers as st
encoder = st.SentenceTransformer("all-mpnet-base-v2")  # also tried sentence-t5-base
```

I get an error: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`, and if I run it as a script, I get `zsh: segmentation fault python`. I also get a warning: `multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appears to be 1 leaked semaphore objects to clean up at shutdown`.

### Reproducibility

I'm afraid I don't know how to reproduce this problem, it was working until it stopped working. Here are my specs:

* MacBook Pro 2019, Intel Core i9, 32GB RAM
* macOS Monterey 12.0.1
* python 3.10.2
* sentence_transformers==2.2.0
* torch==1.11.0

### What I've tried so far

- Clear the cache from `~/.cache/torch/sentence_transformers`
- reinstall sentence_transformers (also tried downgrading to 2.1.0)
- reinstalling torch
- recreating my virtual environment
- Rebooting

I've also managed to trace this problem to the [following point](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L1521) in the torch codebase.

Any help would be appreciated, thanks in advance!

**Update:** I managed to fix the problem by downgrading to Python 3.9.11. I'm not actually sure whether the Python version is to be blamed here, or perhaps just having a new Python environment did the trick (perhaps the virtual environment wasn't enough). Anyway, this isn't really a solution but a workaround, so I think we should keep this ticket open.

**Comment by nreimers** [comment]
Maybe try it with small models. Might be that you system does not have enough resources.

**Comment by ivan-rivera** [comment]
@nreimers thanks for the quick response! I really doubt that my system doesn't have enough resources, it's a MacBook Pro with 32GB RAM. What kind of a small model do you think I could try though? Can you name one?

**Comment by nreimers** [comment]
You can try `all-MiniLM-L6-v2`

Segmentation fault indicates some deep error in Python / Pytorch connected to illegal memory access

**Comment by ivan-rivera** [comment]
Thanks, I'll give it a go tomorrow and will report back. Yeah, based on what I've read, it's a low level error and I'm not entirely sure how to troubleshoot it. Presumably, I'd need to reset this illegal memory access somehow.

**Comment by ivan-rivera** [comment]
Just wanted to add a note that I've tried model `all-MiniLM-L6-v2` and that fails too. I'm running out of ideas and I'm struggling to work out why I'm getting this error while it looks like most other users don't have that issue.

**Comment by ivan-rivera** [comment]
@nreimers I just updated the issue with a workaround, but just in case this issue returns, can you recommend an alternative library that I could try? It seems to me that [txtai](https://github.com/neuml/txtai) and [Top2Vec](https://github.com/ddangelov/Top2Vec) could be used to obtain sentence embeddings -- would you say that these are reasonable alternatives?

**Comment by nreimers** [comment]
These build on top of sentence Transformers. Python 3.10 is sadly still buggy with Pytorch, see
https://github.com/pytorch/pytorch/issues/66424

So we have to wait until Python 3.10 is fully supported by Pytorch.

**Comment by fssh72** [comment]
Just as an FYI, this issue still occurs with Python 3.9 (I'm on a 2019 Intel Apple MacBook Pro).

**Comment by fssh72** [comment]
Found a work around, see here: https://github.com/UKPLab/sentence-transformers/issues/1829#issuecomment-1724406749
