### ISSUE TITLE
Potential bug in pre-trained models with fully connected dense layer on top of pooling layer

### ISSUE THREAD

**Issue by mustaszewski** [UKPLab/sentence-transformers#1566]
In theory, a model instantiated directly through the `SentenceTransformer` API without the `modules` parameter should yield the same embeddings as a model instantiated from scratch by stacking individual modules through the `modules` parameter of the `SentenceTransformer` API. However, I have noted that in the case of pre-trained sentence transformer model that add a **fully connected dense layer on top of the poling layer** (e.g. the [sentence-transformers/distiluse-base-multilingual-cased-v2](https://huggingface.co/sentence-transformers/distiluse-base-multilingual-cased-v2) model) these two approaches yield different embeddings for the same input sentences. Is there a bug involved, or is there a conceptual difference between these two model instantiation approaches? In the documentation, I could not find any hint.

To make my point clear, please consider the following reproducible example:

```
from sentence_transformers import SentenceTransformer, models
from torch import nn

checkpoint_name = "sentence-transformers/distiluse-base-multilingual-cased-v2"

sentences = ['This is an example sentence', 'Each sentence is converted']

# instantiate first model
model_1 = SentenceTransformer(checkpoint_name)

# instantiate second model: stack individual modules
word_embedding_model = models.Transformer(checkpoint_name, max_seq_length=model_1.max_seq_length)
pooling_layer = models.Pooling(word_embedding_model.get_word_embedding_dimension())
dense_layer = models.Dense(in_features=pooling_layer.get_sentence_embedding_dimension(), out_features=model_1.get_sentence_embedding_dimension(), activation_function=nn.Tanh())

model_2 = SentenceTransformer(modules=[word_embedding_model, pooling_layer, dense_layer])

# encode sentences with model_1
embeddings_1 = model_1.encode(sentences)

# encode sentences with model_2
embeddings_2 = model_2.encode(sentences)
```

When we do a `print(model_1)` and `print(model_2)`, both models seem to have exactly the same architecture:

```
SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: DistilBertModel 
  (1): Pooling({'word_embedding_dimension': 768, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Dense({'in_features': 768, 'out_features': 512, 'bias': True, 'activation_function': 'torch.nn.modules.activation.Tanh'})
)
```

Nevertheless, the models yield different embeddings for the given input sentences:

```
>>> embeddings_1
array([[-0.03479306,  0.02635195, -0.04427199, ...,  0.01743882,
        -0.01952395, -0.00118101],
       [ 0.02096637, -0.00401743, -0.05093712, ...,  0.03618195,
         0.0294408 , -0.04497765]], dtype=float32)
>>> embeddings_2
array([[-0.04494104, -0.05743998, -0.04978986, ...,  0.01968714,
        -0.02164727,  0.04301075],
       [ 0.02116368, -0.07624205, -0.08274858, ..., -0.04191887,
        -0.02769089, -0.05722304]], dtype=float32)
```

Upon closer inspection, I realised that the parameters of the two models are identical in all layers **except for the last two layers**:

```
# get model parameters
params_1 = list(model_1.parameters())
params_2 = list(model_2.parameters())

# check if parameters are identical
from torch import equal
params_identical = [equal(params_1[i], params_2[i]) for i in range(len(params_1))]
```

Doing `print(params_identical)` we can see that for all layers except the last two ones, the parameters are identical:

```
>>> layers_identical
[True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, False, False]
>>> 
```

Why do these two model instantiation approaches result in different embeddings? Is there a conceptual (i.e. intended) reason, or is there any bug?

**Comment by nreimers** [comment]
When you call `dense_layer = models.Dense` a new Dense layer with random weights is created. Hence, the different output

**Comment by mustaszewski** [comment]
Ah yeah, makes perfect sense, thank you for the clarification.
