### ISSUE TITLE
cross-encoder/ms-marco-MiniLM-L-12-v2 download link

### ISSUE THREAD

**Issue by abhibisht89** [UKPLab/sentence-transformers#1575]
Hi All,
I am trying to download " cross-encoder/ms-marco-MiniLM-L-12-v2" locally , however not aware of the download link for this model. 
I look into this link:
[link](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/)
However it is not listed there.
Thanks

**Comment by abhibisht89** [comment]
when i download "ms-marco-MiniLM-L-12-v3" from the above link and tried to load the model 

cross_encoder = CrossEncoder('/abhishek/sent_transformer/cross-encoder/ms-marco-MiniLM-L-12-v3')

I got the below error:

ValueError: Unrecognized model in /mnt/efsdata/abhishek/sent_transformer/cross-encoder/ms-marco-MiniLM-L-12-v3. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: yolos, tapex, dpt, decision_transformer, glpn, maskformer, poolformer, convnext, van, resnet, regnet, yoso, swin, vilt, vit_mae, realm, nystromformer, xglm, imagegpt, qdqbert, vision-encoder-decoder, trocr, fnet, segformer, vision-text-dual-encoder, perceiver, gptj, layoutlmv2, plbart, beit, data2vec-vision, rembert, visual_bert, canine, roformer, clip, flava, bigbird_pegasus, deit, luke, detr, gpt_neo, big_bird, speech_to_text_2, speech_to_text, vit, wav2vec2, m2m_100, convbert, led, blenderbot-small, retribert, ibert, mt5, t5, mobilebert, distilbert, albert, bert-generation, camembert, xlm-roberta-xl, xlm-roberta, pegasus, marian, mbart, megatron-bert, mpnet, bart, opt, blenderbot, reformer, longformer, roberta, deberta-v2, deberta, flaubert, fsmt, squeezebert, hubert, bert, openai-gpt, gpt2, transfo-xl, xlnet, xlm-prophetnet, prophetnet, xlm, ctrl, electra, speech-encoder-decoder, encoder-decoder, funnel, lxmert, dpr, layoutlm, rag, tapas, splinter, sew-d, sew, unispeech-sat, unispeech, wavlm, data2vec-audio, data2vec-text

**Comment by aka2910** [comment]
Clearly, the file [msmarco-MiniLM-L-12-v3.zip](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/msmarco-MiniLM-L-12-v3.zip) is not saved in the correct format for a CrossEncoder. Moving the files from `msmarco-MiniLM-L-12-v3/0_Transformer/` to `msmarco-MiniLM-L-12-v3/` and replacing the old `config.json` with the new one from `msmarco-MiniLM-L-12-v3/0_Transformer/` will make the import of model successful. But I doubt whether this model has been properly trained or not.

**Comment by abhibisht89** [comment]
@aka2910 yes you are right import is successful with this workaround but model is not accurate , i am wondering where is "ms-marco-MiniLM-L-12-v2"

**Comment by aka2910** [comment]
`ms-marco-MiniLM-L-12-v2` is directly available on huggingface [here](https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-12-v2)

**Comment by abhibisht89** [comment]
Thanks @nreimers @aka2910 

ohh is is that "[msmarco-MiniLM-L-12-v3.zip](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/msmarco-MiniLM-L-12-v3.zip)" is bi encoder?  names are bit confusing though :)

Yes i thought there is direct download link for "ms-marco-MiniLM-L-12-v2" also.

I did download it now from hugging face , it is working fine now.

Thanks
