### ISSUE TITLE
Using SBERT to generate alternative text

### ISSUE THREAD

**Issue by cabhijith** [UKPLab/sentence-transformers#158]
With SBERT, can I do something like this: 
Given some text can I generate an alternative version of it? 
For example, given ```Man goes to play```, can I generate 'Boy plays football' or something similar? 

If not, what are some ways to achieve this? 

Thanks!

**Comment by nreimers** [comment]
Sadly this is not possible.

Have a look into sequence 2 sequence architectures (or encoder-decoder). There are many seq2seq codes available, which you could use.

You would need to train them so that the input is 'Man goes to play' and the output is 'Boy plays football'.

Best
Nils Reimers

**Comment by cabhijith** [comment]
Ahh, thought so. Yes, have been planning to use seq2seq. 

Another thing I noticed is that many queries are more about asking general doubts regarding BERT/attention models. Like this one!

Thanks for the patience @nreimers
