### ISSUE TITLE
Can other language be used for multi-qa-distilbert-cos-v1 and multi-qa-MiniLM-L6-cos-v1

### ISSUE THREAD

**Issue by rkoystart** [UKPLab/sentence-transformers#1583]
Currently I am using the multi-qa-MiniLM-L6-cos-v1 and multi-qa-distilbert-cos-v1 for finding similar phrases. Based on the doc I assumed the above mentioned model should only used for English
But when I try to give input from other languages like Spanish , German and French , the above mentioned models seems to be giving good results. 
so know I have a doubt whether can the model mentioned model can be used for other languages.
 If yes , would like to what are all the language . And also would like to know how it works since based on the docs I assume the models are only trained on English dataset.

**Comment by nreimers** [comment]
This model works mainly for English. For Spanish, German and French it works also kind of well as these languages have the same alphabet and you have mixed language data in the data.

**Comment by nreimers** [comment]
Correct, also mixed language, eg mixing German and English in the same text
