### ISSUE TITLE
 train_bi-encoder_mnrl.py add 'del ce_scores' to reduce memory consumption by @17gb

### ISSUE THREAD

**Issue by mscham** [UKPLab/sentence-transformers#1588]
ms_marco/train_bi-encoder_mnrl.py pushes over 25gb in memory just before the training begins.  Reducing the train_queries size to around 200-250k will allow you to train but after 2 epochs or so you eventually will surpass 25gb  (25gb is the limit for colab pro high ram) 

Adding the line 
del ce_scores

just before the line
logging.info("Train queries: {}".format(len(train_queries)))

drops RAM use to around 7gb

**Comment by nreimers** [comment]
Fixed by #1589
