### ISSUE TITLE
SGPT support

### ISSUE THREAD

**Issue by Muennighoff** [UKPLab/sentence-transformers#1590]
Hey, would you merge a PR adding support for [SGPT](https://arxiv.org/abs/2202.08904)? I think I would just need to add a pooling method to `Pooling.py`.
Currently, using SGPT via the HF Inference API fails with `__init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'`, because of the missing pooling method. I could also add it as a separate library to the HF Inf API, but I think it'd be much simpler to add the pooling method to this library.

**Comment by nreimers** [comment]
Yes, I would be happy to merge such a PR

**Comment by sinaak** [comment]
@Muennighoff @nreimers
I still have the same issue, with Pytorch 1.12.2, cuda 10.2, and sentence-transformers 2.2.2. Im trying to use: 

`from sentence_transformers import SentenceTransformer
model = SentenceTransformer("Muennighoff/SGPT-125M-weightedmean-nli-bitfit")
`

**Comment by Muennighoff** [comment]
> @Muennighoff @nreimers I still have the same issue, with Pytorch 1.12.2, cuda 10.2, and sentence-transformers 2.2.2. Im trying to use:
> 
> `from sentence_transformers import SentenceTransformer model = SentenceTransformer("Muennighoff/SGPT-125M-weightedmean-nli-bitfit") `

There has been no new version released since the merge, so you need to install from source via `pip install --upgrade git+https://github.com/UKPLab/sentence-transformers.git`. See also [here](https://github.com/Muennighoff/sgpt#use-sgpt-with-sentence-transformers) for more information :)

**Comment by ReadyPlayerEmma** [comment]
@nreimers Awesome work on this project. Would it be possible to take a release now that this is merged into the main branch now? It would be much appreciated to not have to install this from Git all the time. Perhaps there is some ongoing effort that has delayed a new release?

**Comment by redcodebluecode** [comment]
@nreimers I pip installed the newest version by using the commands shown below, and still having the same issue @Muennighoff  mentioned earlier. I was trying code `model = SentenceTransformer("Muennighoff/SGPT-125M-weightedmean-nli-bitfit")` and I have an error message `TypeError: __init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'`. The pip commands I tried are listed below: 
```
!pip install git+https://github.com/UKPLab/sentence-transformers.git
!pip install git+https://github.com/Muennighoff/sentence-transformers.git@sgpt_poolings_specb
!pip install --upgrade git+https://github.com/UKPLab/sentence-transformers.git
!pip install -U sentence-transformers
```

**Comment by Muennighoff** [comment]
> @nreimers I pip installed the newest version by using the commands shown below, and still having the same issue @Muennighoff mentioned earlier. I was trying code `model = SentenceTransformer("Muennighoff/SGPT-125M-weightedmean-nli-bitfit")` and I have an error message `TypeError: __init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'`. The pip commands I tried are listed below:
> 
> ```
> !pip install git+https://github.com/UKPLab/sentence-transformers.git
> !pip install git+https://github.com/Muennighoff/sentence-transformers.git@sgpt_poolings_specb
> !pip install --upgrade git+https://github.com/UKPLab/sentence-transformers.git
> !pip install -U sentence-transformers
> ```

Hmm can you try what's explained here: https://github.com/Muennighoff/sgpt/issues/14#issuecomment-1405205453

**Comment by maheshpec** [comment]
The code in `pooling.py` has been present in master branch since https://github.com/UKPLab/sentence-transformers/pull/1613 merged last September. Is there any help needed to release a version with the changes?

**Comment by np-n** [comment]
@Muennighoff, I got stuck on same issue. I fixed it by running your solution.
```
!pip install git+https://github.com/UKPLab/sentence-transformers.git
!pip install git+https://github.com/Muennighoff/sentence-transformers.git@sgpt_poolings_specb
!pip install --upgrade git+https://github.com/UKPLab/sentence-transformers.git
!pip install -U sentence-transformers
```
Thank you!

**Comment by tomaarsen** [comment]
Hello!

I intend to publish a new release soon, then this should be fully resolved without the workaround. Until then, feel free to use the workaround! I'll close this, as SGPT support has been added.

- Tom Aarsen

**Comment by zubairahmed-ai** [comment]
@tomaarsen  still getting the error even after the latest update, any fix?

**Comment by zubairahmed-ai** [comment]
@tomaarsen 
> A possibility is that your updated sentence transformers is installed in a different Python installation than what you use to run your LanceDB code.

This was indeed the case, sorry for not updating, thanks for looking into it

**Comment by tomaarsen** [comment]
No worries! I'm glad you got it resolved :)
