### ISSUE TITLE
How `smart_batching_collate` works?

### ISSUE THREAD

**Issue by InhyeokYoo** [UKPLab/sentence-transformers#1592]
Hi.

I've read SBERT paper but there's one thing I can not understand.
In section *7 Computational Efficiency* in the paper, SBERT uses 'smart batching' for computation efficiency by reducing computational overhead from padding.

> For improved computation of sentence embeddings, we implemented a smart batching strategy: Sentences with similar lengths are grouped together and are only padded to the longest element in a mini-batch. This drastically reduces computational overhead from padding tokens.

However, [the code](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L517) doesn't use this *sentences with similar lengths* information.
It seems to me that the collate function just extract text and label from `example`, and then tokenize the texts and return.

Could please somebody let me know what am I missing?

**Comment by nreimers** [comment]
Sentences are sorted by length in the encode method

**Comment by InhyeokYoo** [comment]
> Sentences are sorted by length in the encode method

Does it mean `smart_batching_collate` actually not the smart batching of the paper?

And one more question: why did you use it in encode method not also fit method?

**Comment by nreimers** [comment]
Only in the encode. In the fit we what random shuffle

**Comment by InhyeokYoo** [comment]
Thank you. Totally understood.
