### ISSUE TITLE
Pooling after TSDAE - always use CLS?

### ISSUE THREAD

**Issue by mscham** [UKPLab/sentence-transformers#1593]
I'm following the TSDAE domain adaptation steps.

I was wondering, for taking that TSDAE trained model and training against msmarco and any other training downstream, should I always be using CLS pooling since that is what TSDAE uses?  Should further training switch to mean token pooling?  Or does it not matter?

**Comment by nreimers** [comment]
You should use the same for both. If CLS or mean does not play a big role

**Comment by mscham** [comment]
Thanks!
