### ISSUE TITLE
Citation/Source for CrossEncoder?

### ISSUE THREAD

**Issue by ekoenitz** [UKPLab/sentence-transformers#1595]
Hello, a few months ago I created [issue #1458](https://github.com/UKPLab/sentence-transformers/issues/1458), asking about how best to use this library for multilingual classification.  I was told that combining the CrossEncoder with a multilingual HuggingFace model, such as XLM-RoBERTa, would be best, and I got good results when doing so.

I'm starting to write a potential paper about the experiment I used this setup in, and so I'd like to include the proper references and confirm my understanding of how everything works.  However, I can't find where the CrossEncoder was introduced.  [This paper](https://arxiv.org/pdf/1908.10084.pdf) is referenced on the CrossEncoder page on the website, but it appears to be introducing the Bi-Encoder seen [here](https://www.sbert.net/examples/applications/cross-encoder/README.html), with the cross-encoder as a baseline.  Am I misunderstanding the paper, or is there a different citation that would be more appropriate?

Further, the [website](https://www.sbert.net/examples/applications/cross-encoder/README.html) explicitly states that the CrossEncoder _cannot_ be used for individual sentences, only pairs, but I've been using it for single sentences based on the [response to this issue](https://github.com/UKPLab/sentence-transformers/issues/1272) just fine.  Where is this behavior described?

**Comment by nreimers** [comment]
You can use it for single text classification. CrossEncoder just don't work for deriving an embedding for a single sentence.

There is no dedicated paper for CrossEncoders, so you could reference the Sentence-BERT paper.

**Comment by ekoenitz** [comment]
Thank you for the fast response, and sorry for the delay on my end, life happened.

Follow-up question: what makes CrossEncoder for single text classification distinct from, say, using HuggingFace's AutoModelForSequenceClassification then?  I was initially under the impression that CrossEncoder did something special even in the single text classification context, but from the [site](https://www.sbert.net/examples/training/cross-encoder/README.html?highlight=cross%20encoder) and what I understand of the code it seems like it just serves as a wrapper class in this context?  Is that correct, or am I missing something?

**Comment by nreimers** [comment]
It is the same

**Comment by ekoenitz** [comment]
Okay gotcha, thanks!
