### ISSUE TITLE
Custom Embeddings and Tokenizer

### ISSUE THREAD

**Issue by alejandrojcastaneira** [UKPLab/sentence-transformers#16]
Hello, some times you just start digging around github and you find a library that's just awesome, I think this one it's one of theses cases, before anything  I would like to thank you for the great work!

On the technical side, will be possible to use custom word embeddings in the WordEmbeddings class together with a custom tokenizer? I'm thinking on using [BPEmb embeedings](https://github.com/bheinzerling/bpemb) as base word embeddings which perform very good for similarity tasks.

**Comment by nreimers** [comment]
Hi @alejandrojcastaneira ,
happy to hear that you like the project :)

Yes, you can use the WordEmbeddings class with your own tokenizer and with your own embeddings.

You need to initialize the layer like this:
```
word_embeddings = WordEmbeddings.WordWeights(my_bpe_tokenizer_obj, my_pytorch_weights_object)
```

Your BPEmb tokenizer must implement the abstract methods from models.tokenizer.WordTokenizer. The `my_pytorch_weights_object` variable must be a Pytorch tensor containing the embeddings you want to use.

Let me know if you need more help.

Best
-Nils Reimers
