### ISSUE TITLE
Best way to host SBERT?

### ISSUE THREAD

**Issue by cabhijith** [UKPLab/sentence-transformers#161]
Hi, 
I was thinking of exposing this as a REST API. Any recommendations on the best way to do that? 
What I want is an endpoint where I send the text and get the embeddings back. 

Regards,
Abhijith Chandran

**Comment by nreimers** [comment]
A REST API should be straight forward, you can use flask, accept the input, pass it to SBERT and return the embeddings.

If you need this API for a larger setup with a lot of different callers + the possibility to easily scale it, a more complex setup might make sense. For this complex setup, I can recommend  this blogpost:
https://hanxiao.io/2019/01/02/Serving-Google-BERT-in-Production-using-Tensorflow-and-ZeroMQ/
