### ISSUE TITLE
A question about the 14 semantic text similarity tasks

### ISSUE THREAD

**Issue by 14H034160212** [UKPLab/sentence-transformers#1618]
Hi, 

I wonder whether there is an introduction to the 14 semantic text similarity tasks here.
https://www.sbert.net/docs/training/overview.html#best-transformer-model

Kind regards,
Qiming

**Comment by nreimers** [comment]
We currently open-source them here:
https://github.com/embeddings-benchmark/mteb

**Comment by nreimers** [comment]
The scores are from an older, not really nice version of that benchmark:
https://github.com/nreimers/se-benchmark

**Comment by 14H034160212** [comment]
Thanks for that!

**Comment by 14H034160212** [comment]
Do you have the official evaluation result for STS and NLI tasks using the Sentence Transformer framework? Cause I can see STS and NLI are part of the 14 tasks, but I can only see an average score for that.
