### ISSUE TITLE
Sentence Embedding from Pretrained BERT Model with SBERT

### ISSUE THREAD

**Issue by bbardakk** [UKPLab/sentence-transformers#1621]
I am currently working on clinical notes and trying to convert them into embeddings. There is a pre-trained BERT model named ClinicalBERT which is suitable for my task.

I can load this pre-trained model into the Sentence-BERT library and take the embeddings like below.

```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("emilyasentzer/Bio_ClinicalBERT)

clinical_note_embeddings = model.encode(clinical_notes[0])
```

My question is, converting clinical notes into embeddings like the above is equal to using Bio_ClinicalBERT output + Mean Pooling operation? Also, I think that SBERT is converting the clinical notes to embeddings faster than the BERT. How is it possible?

Any help is appreciated.

**Comment by subho22** [comment]
Did you got the answer. If so post in here
