### ISSUE TITLE
Pooling Strategy Question

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [UKPLab/sentence-transformers#1631]
In the Original S-BERT paper, you mentioned 

>"Researchers have started to input individual sentences into BERT and to derive fixed size sentence embeddings. The most commonly used approach is to average the BERT output layer (known as BERT embeddings) or by using the output of the first token (the [CLS] token). As we will show, this common practice yields rather bad sentence embeddings, often worse than averaging GloVe embeddings (Pennington et al., 2014)."

When you say the ```average the BERT output layer``` do you mean the ```average pooling of the last layer's hidden state```?  if so how is it different from what Sentence Transformer does? Doesn't Sentence Transformers by default use average (mean) pooling on tokens of the last layer's hidden state (and optionally supports max pooling and CLS pooling if I am not wrong. )

So I am confused when you say before sentence transformers,  
> researchers used to get fixed dimensions by commonly used approach is to average the BERT output layer (known as BERT embeddings) 

Also, the BERT author hints (below) at the average pooling of word (or token) embeddings may not yield a good sentence embedding. All along I was under the impression this is what sentence transformed mean pooling does to get sentence embeddings. 

![68367897-b7837780-0171-11ea-8047-89cfc89184d8](https://user-images.githubusercontent.com/7071019/178228454-44676780-3251-48e2-a762-f9b2550d4345.png)

Could you please clarify?

**Comment by nreimers** [comment]
Not sure if I get the question. The output of BERT is averaged. But BERT needs fine-tuning on suitable data to produce meaningful text embeddings.

**Comment by PrithivirajDamodaran** [comment]
Sorry, Maybe this can help.

<img width="1326" alt="Screenshot 2022-07-12 at 5 47 33 PM" src="https://user-images.githubusercontent.com/7071019/178473563-67df91bf-68ef-498b-976b-9e72d4688e7b.png">

Please help me communicate the results to Juniors because we argue **sentence transformers models produce higher quality sentence embeddings than vanilla BERT model without fine-tuning. So in this case the embeddings generated in this case by the mpnet model fine-tuned with sentence transformers are of higher quality hence the similarity is lesser than the similarity of vanilla embeddings?** It is counter-intuitive for juniors.

[Question] I would like to prove that sentence-transformers are indeed the best way to create high-quality sentence embeddings compared to ```non-finetuned vanilla LMs```. How should I go about demonstrating it?

**Comment by nreimers** [comment]
You can find results on BERT without fine-tuning for text embeddings here:
https://arxiv.org/abs/1908.10084
https://arxiv.org/abs/2004.09813

BERT performs worse than average Glove embeddings if not fine-tuned for text embeddings

**Comment by PrithivirajDamodaran** [comment]
But the screenshot I shared above shows otherwise. Non-fine tuned Vanilla BERT seems to produce good embeddings. Can you let me know what I am doing wrong or missing ?

**Comment by nreimers** [comment]
You cannot infer from a single cosine score if the model does well or not. You need to test it on some task (or better: on many tasks), and see if it works.

BERT embeddings without fine-tuning have all really high similarities, even for sentences that are very different. This make them rather useless
