### ISSUE TITLE
ImportError: cannot import name 'AutoModel' from 'transformers'

### ISSUE THREAD

**Issue by SaiSandeepKantareddy** [UKPLab/sentence-transformers#1637]
ImportError: cannot import name 'AutoModel' from 'transformers'

after installing:

'torch -- 1.12.0'

pip install -U sentence-transformers  //   conda install -c conda-forge sentence-transformers 

conda install -c huggingface transformers

import transformers working.

**Comment by tomaarsen** [comment]
Hello!

It seems like your `transformers` is either: 1) not installed in the right virtual environment or 2) not up to date. `AutoModel` should be importable from `transformers`. 

- Tom Aarsen
