### ISSUE TITLE
Loss and Accuracy during train/dev

### ISSUE THREAD

**Issue by robinsongh381** [UKPLab/sentence-transformers#164]
Hello !

Thank you for your work, first of all

Im training SBERT with Korean NLI data at the moment
I was wondering what would be reasonable loss value during train and evaluation ?
Mine was around 0.890 for train loss and 0.840 for dev loss (cross entropy average loss)

Also, as for classification accuracy, (among three labels : entailment, contradiction, neutral) what are the best values for train and loss ?

The train loss starts to decrease after a quarter of the first epoch

Mine as around 60~70% for both train and loss, which i think is not good enough.

Any reply would be aprreciate
Thanks

**Comment by nreimers** [comment]
Hi @robinsongh381 
Sadly haven't worked on Korean NLI (also didn't print accuracy scores for NLI).

But what you describe sounds sensible.

Best
Nils Reimers

**Comment by robinsongh381** [comment]
Hi @nreimers 

Thank you for reply !

I would like to know loss/acc values for English NLI data, if you have printed out in previous.
Of course, I wouldn't use your values for absolute target but i want to know what sort of values for loss/acc would be reasonable

Thanks

**Comment by nreimers** [comment]
Hi  @robinsongh381 
I sadly don't have these values. But you could update the training_nli example and add the accuracy evaluator to it. Then, it would print these values.

Best
Nils

**Comment by robinsongh381** [comment]
Ok thanks !
