### ISSUE TITLE
Infinite loop during community detection algorithm

### ISSUE THREAD

**Issue by sharpsy** [UKPLab/sentence-transformers#1640]
I have encountered an edge case that causes an infinite loop when running the `util.community_detection` algorithm.

The problem can be observed when running the algorithm on a batch of sentences that all belong to the same cluster. The following snippet is the culprit:
```
                while top_val_large[-1] > threshold:
                    sort_max_size = min(2 * sort_max_size, len(embeddings))
                    top_val_large, top_idx_large = cos_scores[i].topk(k=sort_max_size, largest=True)
```
You can see that the variable `sort_max_size` increases until the cluster contains all elements. Once that happens, it is stuck in the infinite loop without progress.

It should be enough to break out of the for loop if `sort_max_size` equals `len(embeddings)`. For example, rewriting the while condition to:
`while top_val_large[-1] > threshold and sort_max_size < len(embeddings):`

Test case:
```
import torch
from sentence_transformers import util

embeddings = torch.rand(10, 300) + 1
util.community_detection(embeddings, min_community_size=5)
```

**Comment by xiang-dev** [comment]
I ran into the exact same issue.

**Comment by sharpsy** [comment]
@nreimers, the fix suggested above was applied in the https://github.com/UKPLab/sentence-transformers/commit/d8982c9f0d44f8a3c41579fa64c603eca029649b and there is no need to keep this issue open.
Closing.

**Comment by AmirPupko** [comment]
Hi, any chance you can release a new version with this fix?

**Comment by JosephThePatrician** [comment]
If anyone wonders how to fix this, the code for this issue has been updated on github, but was not uploaded to pip. All you need to do is download version from git, rather than pip
`pip install git+https://github.com/UKPLab/sentence-transformers`
