### ISSUE TITLE
Necessity of torchvision dependency

### ISSUE THREAD

**Issue by niazarak** [UKPLab/sentence-transformers#1644]
Hi, thanks for your work, we've been using sbert for quite some time.

We noticed that `sentence-transformers` depend on `torchvision`, and while it was necessary for CLIP implementation in previous versions, now `sentence-transformers` use CLIP from HF ([commit](https://github.com/UKPLab/sentence-transformers/commit/5ab198556c6122dc9e943fcb54af4d5f645a6365)).

Is there any reason to keep this dependency now?

**Comment by nreimers** [comment]
I think the HF clip model also requires torchvision

**Comment by iamhatesz** [comment]
How about moving torchvision to extras dependencies? I have a completely non-CV setup and this only complicates things for me. See e.g.: https://github.com/pytorch/vision/issues/5393

**Comment by ecly** [comment]
Agreed with @iamhatesz that having it as optional would be ideal, as `torchvision` sometimes can be a headache.

**Comment by glemaitre** [comment]
@tomaarsen I think this issue can be closed after the merge of https://github.com/UKPLab/sentence-transformers/pull/1881
