### ISSUE TITLE
Problem downloading the pretrained models

### ISSUE THREAD

**Issue by davidrotor** [UKPLab/sentence-transformers#165]
Hi, 
Due to regultations and permissions on the company that I work in I cant seem to be able to download the models in my programs is there a way to download the pretrained models manually?
I read you can just provide a path to them if you have custom models so I suppose that works also with the ones it comes with.
Update: 
was able to download distilbert nli model from your site
Error
Traceback (most recent call last):
  File "a.py", line 22, in <module>
    model = SentenceTransformer(r"C:\Users\765004502\Desktop\Bertexample\distilbert-base-nli-mean-tokens.zip")
  File "C:\Users\765004502\AppData\Local\conda\conda\envs\pricing\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 76, in __init__
    with open(os.path.join(model_path, 'modules.json')) as fIn:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\**********\\Desktop\\Bertexample\\distilbert-base-nli-mean-tokens.zip\\modules.json'
My code is the following:

"""
This basic example loads a pre-trained model from the web and uses it to
generate sentence embeddings for a given list of sentences.
"""

from sentence_transformers import SentenceTransformer, LoggingHandler
import numpy as np
import logging

#### Just some code to print debug information to stdout
np.set_printoptions(threshold=100)

logging.basicConfig(format='%(asctime)s - %(message)s',
                    datefmt='%Y-%m-%d %H:%M:%S',
                    level=logging.INFO,
                    handlers=[LoggingHandler()])
#### /print debug information to stdout

# Load Sentence model (based on BERT) from URL
model = SentenceTransformer(r"\Desktop\Bertexample\distilbert-base-nli-mean-tokens.zip")

# Embed a list of sentences
sentences = ['This framework generates embeddings for each input sentence',
             'Sentences are passed as a list of string.',
             'The quick brown fox jumps over the lazy dog.']
sentence_embeddings = model.encode(sentences)

# The result is a list of sentence embeddings as numpy arrays
for sentence, embedding in zip(sentences, sentence_embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")

System info:
Windows 10
Tensorflow 2.1
transformers 2.3
pytorch 1.4

Regards,
David.

**Comment by chen3082** [comment]
Hey men, where did you find the zip file in the site? Is it possible for you to post the link?

**Comment by nreimers** [comment]
@chen3082 
You can find them here:
https://sbert.net/models/
