### ISSUE TITLE
Explainability for Cross Encoder

### ISSUE THREAD

**Issue by FranzBuehl** [UKPLab/sentence-transformers#1650]
Hi, I'm using the Cross Encoder for a classification task. I'm looking for a way to explain my results. As is possible with Transformer models and Shap, for example. Is there a solution for this?
Thank you for your great work.

**Comment by cdpierse** [comment]
Hi @FranzBuehl I came across your issue while looking through the issues page, a package I maintain [Transformers Interpret](https://github.com/cdpierse/transformers-interpret) recently added an explainer for CrossEncoder models, it provides word attributions and visualisations for pairwise classification which is what the cross encoder is behind the scenes. 

Below is minimal example, do check out the package if you are interested in knowing more about it:
```python
from transformers import AutoModelForSequenceClassification, AutoTokenizer

from transformers_interpret.explainers.sequence_classification import PairwiseSequenceClassificationExplainer

model = AutoModelForSequenceClassification.from_pretrained("cross-encoder/ms-marco-MiniLM-L-6-v2")
tokenizer = AutoTokenizer.from_pretrained("cross-encoder/ms-marco-MiniLM-L-6-v2")

pairwise_explainer = PairwiseSequenceClassificationExplainer(model, tokenizer)

# the pairwise explainer requires two string inputs to be passed, in this case given the nature of the model
# we pass a query string and a context string. The question we are asking of our model is "does this context contain a valid answer to our question"
# the higher the score the better the fit.

query = "How many people live in Berlin?"
context = "Berlin has a population of 3,520,031 registered inhabitants in an area of 891.82 square kilometers."
pairwise_attr = pairwise_explainer(query, context)
```
Which creates the attributions
```python
>>> pairwise_attr
[('[CLS]', 0.0),
 ('how', -0.037558652124213034),
 ('many', -0.40348581975409786),
 ('people', -0.29756140282349425),
 ('live', -0.48979015417391764),
 ('in', -0.17844527885888117),
 ('berlin', 0.3737346097442739),
 ('?', -0.2281428913480142),
 ('[SEP]', 0.0),
 ('berlin', 0.18282430604641564),
 ('has', 0.039114659489254834),
 ('a', 0.0820056652212297),
 ('population', 0.35712150914643026),
 ('of', 0.09680870840224687),
 ('3', 0.04791760029513795),
 (',', 0.040330986539774266),
 ('520', 0.16307677913176166),
 (',', -0.005919693904602767),
 ('03', 0.019431649515841844),
 ('##1', -0.0243808667024702),
 ('registered', 0.07748341753369632),
 ('inhabitants', 0.23904087299731255),
 ('in', 0.07553221327346359),
 ('an', 0.033112821611999875),
 ('area', -0.025378852244447532),
 ('of', 0.026526373859562906),
 ('89', 0.0030700151809002147),
 ('##1', -0.000410387092186983),
 ('.', -0.0193147139126114),
 ('82', 0.0073800833347678774),
 ('square', 0.028988305990861576),
 ('kilometers', 0.02071182933829008),
 ('.', -0.025901070914318036),
 ('[SEP]', 0.0)]
```

**Comment by FranzBuehl** [comment]
Hi @cdpierse,

thanks for your response. Just what I was looking for.

**Comment by simeonwetzel** [comment]
Hi @cdpierse could a [PairwiseSequenceClassificationExplainer ](https://github.com/cdpierse/transformers-interpret/tree/master#pairwise-sequence-classification) also work in a setting where one calculates the similarity of two embeddings generated by a SBERT bi-encoder? I would like to explain the contribution of the two input passages to the final similarity. In contrast to a cross-encoder score I get two outputs from a bi-encoder that I have to calculate a similiarity score from (see image [here](https://raw.githubusercontent.com/UKPLab/sentence-transformers/master/docs/img/SBERT_Siamese_Network.png))

**Comment by Ahmedn1** [comment]
> Hi @cdpierse could a [PairwiseSequenceClassificationExplainer ](https://github.com/cdpierse/transformers-interpret/tree/master#pairwise-sequence-classification) also work in a setting where one calculates the similarity of two embeddings generated by a SBERT bi-encoder? I would like to explain the contribution of the two input passages to the final similarity. In contrast to a cross-encoder score I get two outputs from a bi-encoder that I have to calculate a similiarity score from (see image [here](https://raw.githubusercontent.com/UKPLab/sentence-transformers/master/docs/img/SBERT_Siamese_Network.png))

Yeah I cannot find a good interpretability approach for bi-encoders.
