### ISSUE TITLE
Feature request: Show progress when encoding with multiprocessing (encode_multi_process)

### ISSUE THREAD

**Issue by MikulasZelinka** [UKPLab/sentence-transformers#1651]
Hi,

when encoding sentences without multiprocessing, it's easy enough to just monitor the progress with `tqdm` by wrapping the loop (when encoding individual sentences) or just using the built-in progress bar of `encode`: https://github.com/UKPLab/sentence-transformers/blob/46a149433fe9af0851f7fa6f9bf37b5ffa2c891c/sentence_transformers/SentenceTransformer.py#L140-L142

However, when using `encode_multi_process`, that isn't easily possible because everything is hidden inside those methods: https://github.com/UKPLab/sentence-transformers/blob/46a149433fe9af0851f7fa6f9bf37b5ffa2c891c/sentence_transformers/SentenceTransformer.py#L230 https://github.com/UKPLab/sentence-transformers/blob/46a149433fe9af0851f7fa6f9bf37b5ffa2c891c/sentence_transformers/SentenceTransformer.py#L277

Would it please be possible to add progress bar(s) for multiprocess encoding?

Either one progress bar for the whole bunch of sequences, or a progress bar per process. Thank you!

**Comment by sam-hieken** [comment]
Hi,

It's definitely not sexy, but for a quick fix you can just replace the following line at 159 in SentenceTransformer.py:

`for start_index in trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar):`

to

`for start_index in tqdm(trange(0, len(sentences), batch_size, desc="Batches", disable=not show_progress_bar)):`

*Don't forget to `from tqdm.auto import tqdm`.

I'm going to open a PR, hopefully this won't be necessary in the future.

**Comment by abhishekmamdapure** [comment]
Any update on this ?

**Comment by WanBenLe** [comment]
@tomaarsen maybe
`from tqdm.auto import tqdm
def encode_multi_process(...,show_progress_bar:bool,...):
...
if show_progress_bar:
    results_list = sorted([output_queue.get() for _ in tqdm(range(last_chunk_id))], key=lambda x: x[0])
else:
    results_list = sorted([output_queue.get() for _ in range(last_chunk_id)], key=lambda x: x[0])
...
`
Is OK?

**Comment by tomaarsen** [comment]
Great suggestion, I'll get on this.

- Tom Aarsen
