### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by joeyoneill** [UKPLab/sentence-transformers#1652]
I am trying to pip install sentence transformers on my Macbook Pro with M1 chip. I am using:

    pip install -U sentence-transformers

When I run this, I get this error saying: 

	ModuleNotFoundError: No module named 'setuptools.command.build'

Full output:

	Defaulting to user installation because normal site-packages is not writeable
	Collecting sentence-transformers
	  Using cached sentence-transformers-2.2.2.tar.gz (85 kB)
	  Preparing metadata (setup.py) ... done
	Collecting transformers<5.0.0,>=4.6.0
	  Using cached transformers-4.21.0-py3-none-any.whl (4.7 MB)
	Collecting tqdm
	  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
	Requirement already satisfied: torch>=1.6.0 in ./Library/Python/3.8/lib/python/site-packages (from sentence-transformers) (1.12.0)
	Collecting torchvision
	  Using cached torchvision-0.13.0-cp38-cp38-macosx_11_0_arm64.whl (1.2 MB)
	Requirement already satisfied: numpy in ./Library/Python/3.8/lib/python/site-packages (from sentence-transformers) (1.23.1)
	Collecting scikit-learn
	  Using cached scikit_learn-1.1.1-cp38-cp38-macosx_12_0_arm64.whl (7.6 MB)
	Collecting scipy
	  Using cached scipy-1.8.1-cp38-cp38-macosx_12_0_arm64.whl (28.6 MB)
	Collecting nltk
	  Using cached nltk-3.7-py3-none-any.whl (1.5 MB)
	Collecting sentencepiece
	  Using cached sentencepiece-0.1.96.tar.gz (508 kB)
	  Preparing metadata (setup.py) ... done
	Collecting huggingface-hub>=0.4.0
	  Using cached huggingface_hub-0.8.1-py3-none-any.whl (101 kB)
	Collecting requests
	  Using cached requests-2.28.1-py3-none-any.whl (62 kB)
	Collecting pyyaml>=5.1
	  Using cached PyYAML-6.0.tar.gz (124 kB)
	  Installing build dependencies ... done
	  Getting requirements to build wheel ... done
	  Preparing metadata (pyproject.toml) ... done
	Requirement already satisfied: typing-extensions>=3.7.4.3 in ./Library/Python/3.8/lib/python/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (4.3.0)
	Requirement already satisfied: filelock in ./Library/Python/3.8/lib/python/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (3.7.1)
	Requirement already satisfied: packaging>=20.9 in ./Library/Python/3.8/lib/python/site-packages (from huggingface-hub>=0.4.0->sentence-transformers) (21.3)
	Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
	  Using cached tokenizers-0.12.1.tar.gz (220 kB)
	  Installing build dependencies ... done
	  Getting requirements to build wheel ... error
	  error: subprocess-exited-with-error
	  
	  × Getting requirements to build wheel did not run successfully.
	  │ exit code: 1
	  ╰─> [20 lines of output]
	      Traceback (most recent call last):
	        File "/Users/joeyoneill/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
	          main()
	        File "/Users/joeyoneill/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
	          json_out['return_val'] = hook(**hook_input['kwargs'])
	        File "/Users/joeyoneill/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
	          return hook(config_settings)
	        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
	          return self._get_build_requires(
	        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
	          self.run_setup()
	        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
	          exec(compile(code, __file__, 'exec'), locals())
	        File "setup.py", line 2, in <module>
	          from setuptools_rust import Binding, RustExtension
	        File "/private/var/folders/bg/ncfh283n4t39vqhvbd5n9ckh0000gn/T/pip-build-env-vjj6eow8/overlay/lib/python3.8/site-packages/setuptools_rust/__init__.py", line 1, in <module>
	          from .build import build_rust
	        File "/private/var/folders/bg/ncfh283n4t39vqhvbd5n9ckh0000gn/T/pip-build-env-vjj6eow8/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 20, in <module>
	          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
	      ModuleNotFoundError: No module named 'setuptools.command.build'
	      [end of output]
	  
	  note: This error originates from a subprocess, and is likely not a problem with pip.
	error: subprocess-exited-with-error

	× Getting requirements to build wheel did not run successfully.
	│ exit code: 1
	╰─> See above for output.

		note: This error originates from a subprocess, and is likely not a problem with pip.

Can anybody tell me what I should do or what is wrong with what I am currently doing? I factory reset my Mac and re-downloaded everything but I still get this same error. I am stumped.

**Comment by djh2717** [comment]
I also encounter this problem with M1 pro chip......

**Comment by HenryObj** [comment]
Same here (M1 pro). Using Python3.

Tried un-installing / re-installing / updating the various modules to no avail.
Managed to get Transformers installed by doing a virtual environment (`python3 -m venv env`) then installing the various packages in the venv. 
Didn't find how to do it outside of venv - still haven't used it :)

**Comment by nreimers** [comment]
Which Python versions are you using?

**Comment by HenryObj** [comment]
I use: Python 3.8.9

**Comment by joeyoneill** [comment]
I use 3.8.9 as well.

**Comment by nreimers** [comment]
It is connected to tokenizers, that is used by HF transformers. It is not able to run the installation for Rust, on which HF tokenizers is build up-on.

Maybe you could create an issue here:
https://github.com/huggingface/tokenizers

I'm sadly not really familiar with Rust

**Comment by micseydel** [comment]
This blocked me on installing https://github.com/openai/whisper but this [reddit comment](https://www.reddit.com/r/Python/comments/xkwt34/comment/iph6bsn/?utm_source=share&utm_medium=web2x&context=3) implies it's possible, I'm hoping without the venv. I'm going to link them to this thread...

**Comment by viticci** [comment]
FWIW, I was having the exact issue (re: Whisper) and installing directly from source (`pip install git+https://github.com/huggingface/transformers`) fixed it on my M1 Max MacBook Pro.

**Comment by micseydel** [comment]
@viticci thank you so much for replying! I tried that (based on your recommendation) and tried installing Rust with brew and via Rust's installer, as well as updating various installed modules, no luck so far. I'm probably gonna try it on my Raspberry Pi but I'm afraid it's going to be sloooow.

**Comment by andeecollard** [comment]
@viticci thank you so much that worked for me after reinstalling Homebrew Python3 and pip3

**Comment by DSLituiev** [comment]
same here on jetson nano

**Comment by joeyoneill** [comment]
This also worked for me. Thanks @viticci

**Comment by ovid1us** [comment]
I still have the same error.  When

> FWIW, I was having the exact issue (re: Whisper) and installing directly from source (`pip install git+https://github.com/huggingface/transformers`) fixed it on my M1 Max MacBook Pro.

I tried this and still go the same error.  Mac Studio M1 Ultra

error from "pip install git+https://github.com/huggingface/transformers":

Collecting regex!=2019.12.17
  Using cached regex-2022.9.13-cp38-cp38-macosx_11_0_arm64.whl (287 kB)
Requirement already satisfied: numpy>=1.17 in ./Library/Python/3.8/lib/python/site-packages (from transformers==4.23.0.dev0) (1.23.3)
Requirement already satisfied: requests in ./Library/Python/3.8/lib/python/site-packages (from transformers==4.23.0.dev0) (2.28.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1
 Downloading tokenizers-0.13.0.tar.gz (358 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 358.7/358.7 kB 8.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
   Traceback (most recent call last):
        File "/Users/ovid/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/ovid/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/ovid/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
          self.run_setup()
        File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 2, in <module>
          from setuptools_rust import Binding, RustExtension
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-build-env-u39e7z4a/overlay/lib/python3.8/site-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/private/var/folders/s0/j8wf6b05697_54202d1tr5800000gn/T/pip-build-env-u39e7z4a/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by odieXin** [comment]
I am using M1 Pro and got the same error. It is solved by: 

1. Clone the source from https://github.com/huggingface/transformers by:
 `git clone https://github.com/huggingface/transformers`
2. Install the rust steppe tools by `pip install setuptools_rust`
3. Go to the transformer folder and install by `python setup.py install`

This solves my problem.

**Comment by mrunfeldt** [comment]
I had the same issue (2021 M1 Mac) and resolved with updating python3: `brew install python3`

**Comment by TylerTheHumanCompiler** [comment]
Same issue on AMD Threadripper 2950x / Arch Linux. Package is from the AUR repo.

**Comment by BoxMars** [comment]
> same here on jetson nano

follow `Installation from sources` in the [doc](https://huggingface.co/docs/tokenizers/python/v0.9.4/installation/main.html), it works for me

**Comment by oonexdl** [comment]
same on my m1 chip，upgrade python3.8 to 3.9 solves the problem
