### ISSUE TITLE
using cuda to accelerate training?

### ISSUE THREAD

**Issue by tyker1** [UKPLab/sentence-transformers#166]
hi,

since theres no pre-trained model for XLNet (i mean those trained for sts and nli) i want to train it my self (you also gives the code in example). But i realize that, even i have cuda installed and pytorch with cuda, during the training, observe that my cpu get highly belastet (about 60% on i7-6700k) but GPU usage is only about 10%.

are there any way to use more gpu resource but lesser cpu? (also tried to use it on Jetson Nano and there gpu was just used at begining for a very shot time, and the rest always in cpu, which cause the program to crash at Nano)

As i checked the code, it seems that the training data are still in CPU?

thanks

**Comment by nreimers** [comment]
Hi @tyker1 
I was not really able to achieve any good results with XLNet.

With good utilization, you have a CPU usage of 100% and a GPU usage of 100%. Your low GPU usage indicates that maybe the batch size is too small? You can try to increase it.

Best
Nils Reimers

**Comment by tyker1** [comment]
Hi @nreimers 
the training result gives the same conclusion. it's kinda strange since many papers reported that XLNet outperforms BERT.

I also tried to increase the batch size, it seems loading the model into GPU already used up almost all my GPU-Memory (preserved about 1.1G for system usage, and the model ate up about 6.5G, not much left) and i'm only able to scale the batch size up to 32 which resaults in 5% GPU usage and 25% cpu usage. seems kinda strange

thanks

**Comment by nreimers** [comment]
Hi @tyker1 
For sentence embeddings and unsupervised tasks the scenario is a bit different, there, every dimension contributes equally (with the same weight). If the model produces useless dimensions or dimension with vastly different scales, then, this model is sadly not useful for unsupervised tasks. For supervised tasks, this model might still work great, as we learn with data which dimensions are important and what the scale is. So sadly we cannot make the conclusion better supervised results => better suited for unsupervised tasks / better sentence embeddings.


Sadly I don't know why XLNet works quite badly in generating sentence embeddings. If some one knows, of finds a ways to fix it, please let me know.

Best
Nils Reimers
