### ISSUE TITLE
The `community_detection` method run forever

### ISSUE THREAD

**Issue by phuclh** [UKPLab/sentence-transformers#1670]
This is my code:

```
model = SentenceTransformer('all-MiniLM-L6-v2')

corpus_sentences = ['how to cook bun bo hue', 'how to cook my quang']

corpus_embeddings = model.encode(corpus_sentences, batch_size=1024, show_progress_bar=False, convert_to_tensor=True)

clusters = util.community_detection(corpus_embeddings, min_community_size=2, threshold=0.4)
```

If I set the `threshold` is 0.8, the `community_detection` method works fine but If I set `the threshold` to 0.4. It will load forever. I guess the `threshold` is too small for my `corpus_sentences`. However, is there any way to throw an exception instead of keeping running like that?

Thank you!

**Comment by nreimers** [comment]
Just merged a bugfix. Issue was, when there is only one cluster, which is the case if the threshold is too small

**Comment by phuclh** [comment]
> Just merged a bugfix. Issue was, when there is only one cluster, which is the case if the threshold is too small

Nice. Are you going to tag a new version soon?

**Comment by phuclh** [comment]
@nreimers Are you going to tag a new version for this update soon? Thank you!

**Comment by 2019011821** [comment]
This issue is still there :(

**Comment by AmirPupko** [comment]
Issue still there :( looks like its fixed but not published yet

**Comment by javaccar** [comment]
Hi. The fix for this issue has not been released. This is a critical bug since it causes applications to hang. Is there any plan to release soon? Thanks

**Comment by NishqR** [comment]
This is still a persistent issue even with the latest version of the library. Function is unusable without the fix @nreimers could you please advise a solution?

**Comment by PrakharPatidar** [comment]
Hi [nreimers](https://github.com/nreimers)
I'm also facing the same issue. It's fixed and merged in main but still not released.
Can you please tell if there is one planned soon?

**Comment by v-colella** [comment]
Hi, i have this problem when i make the embeddings with specific models. For example I use "sentence-transformers/paraphrase-MiniLM-L6-v2" and community_detection runs well, but when I use "intfloat/multilingual-e5-small" it never stop. I tried to storage the embeddings and run in another notebook but is the same. 
I'm new with sentence transformers, but can a model influence in this? The embeddings have the same dimension for both models
