### ISSUE TITLE
Dataset format for NLI reader

### ISSUE THREAD

**Issue by isaacmg** [UKPLab/sentence-transformers#168]
Hello, I'm trying to train sentence transformers on the MedNLI and SciTail datasets. They have basically the same format as the MultiNLI dataset and SNLI. However, I was a bit confused on how your NLIDataReader works as it seems to assume having three separate .gz files which are then zipped together in a for loop? I only have a single train.jsonl file which contains all the training data, how do I make the NLIDataset reader work with that format? Or do you have the conversion scripts you used?

Thanks

**Comment by nreimers** [comment]
Have a look here:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/readers/NLIDataReader.py

You need 3 files: s1.train.gz, s2.train.gz, labels.train.gz

Each line contains an example (s1 and s2 the two sentences, labels the labels)

Best
Nils Reimers

**Comment by isaacmg** [comment]
Thanks I was able to write a suitable conversion script that I will post in the coming days.
