### ISSUE TITLE
Fast clustering algorithm- is the community_detection method deterministic?

### ISSUE THREAD

**Issue by theephilocalist** [UKPLab/sentence-transformers#1696]
We have a use case wherein it's good to have a deterministic clustering algorithm. For a large dataset can I expect community_detection to provide same clusters for the same input on different runs?

Thanks, 
Eve

**Comment by nreimers** [comment]
There are some edge cases where it is not deterministic when you shuffle the input data, but in most cases it should yield the same results.

If the input data is identical, the output should be identical.

**Comment by theephilocalist** [comment]
Thank you
