### ISSUE TITLE
Error import : SyntaxError: invalid syntax ,,from sentence_transformers import SentenceTransformer

### ISSUE THREAD

**Issue by Williamlizl** [UKPLab/sentence-transformers#170]
Traceback (most recent call last):

  File "/home/lbc/.local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-ec7caaddc3b7>", line 7, in <module>
    from sentence_transformers import SentenceTransformer

  File "/home/lbc/.local/lib/python3.5/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, SentenceLabelDataset

  File "/home/lbc/.local/lib/python3.5/site-packages/sentence_transformers/datasets.py", line 12, in <module>
    from . import SentenceTransformer

  File "/home/lbc/.local/lib/python3.5/site-packages/sentence_transformers/SentenceTransformer.py", line 19, in <module>
    from .evaluation import SentenceEvaluator

  File "/home/lbc/.local/lib/python3.5/site-packages/sentence_transformers/evaluation/__init__.py", line 4, in <module>
    from .BinaryEmbeddingSimilarityEvaluator import BinaryEmbeddingSimilarityEvaluator

  File "/home/lbc/.local/lib/python3.5/site-packages/sentence_transformers/evaluation/BinaryEmbeddingSimilarityEvaluator.py", line 45
    self.csv_file: str = "binary_similarity_evaluation"+name+"_results.csv"
                 ^
SyntaxError: invalid syntax

**Comment by nreimers** [comment]
The issue is connected to Python 3.5, it does not support type hint for class variables.

In general it would be good to update Python to a newer version, as 3.5 is quite out-dated.

But I updated the BinaryEmbeddingSimilarityEvaluator.py and removed the type-hint there. If you update the repository and install it from source, you should be able to use it with Python 3.5

Best
Nils Reimers

**Comment by Williamlizl** [comment]
> The issue is connected to Python 3.5, it does not support type hint for class variables.
> 
> In general it would be good to update Python to a newer version, as 3.5 is quite out-dated.
> 
> But I updated the BinaryEmbeddingSimilarityEvaluator.py and removed the type-hint there. If you update the repository and install it from source, you should be able to use it with Python 3.5
> 
> Best
> Nils Reimers

oops,
File "/home/lbc/GitHub/src/sbert/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py", line 58
    out_txt = f" after epoch {epoch}:"
                                     ^
SyntaxError: invalid syntax

and I correct the error : 
if steps == -1:
                out_txt = ' after epoch:'+ epoch
            else:
                out_txt = ' in epoch'+ epoch+' after '+steps+' steps:'

but when I install it from source again, it still shows the error.

**Comment by Williamlizl** [comment]
> > The issue is connected to Python 3.5, it does not support type hint for class variables.
> > In general it would be good to update Python to a newer version, as 3.5 is quite out-dated.
> > But I updated the BinaryEmbeddingSimilarityEvaluator.py and removed the type-hint there. If you update the repository and install it from source, you should be able to use it with Python 3.5
> > Best
> > Nils Reimers
> 
> oops,
> File "/home/lbc/GitHub/src/sbert/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py", line 58
> out_txt = f" after epoch {epoch}:"
> ^
> SyntaxError: invalid syntax
> 
> and I correct the error :
> if steps == -1:
> out_txt = ' after epoch:'+ epoch
> else:
> out_txt = ' in epoch'+ epoch+' after '+steps+' steps:'
> 
> but when I install it from source again, it still shows the error.
