### ISSUE TITLE
community detection: why is the cos_score variable explicitly deleted

### ISSUE THREAD

**Issue by theephilocalist** [UKPLab/sentence-transformers#1703]
https://github.com/UKPLab/sentence-transformers/blob/0dac5732fff3bb01986be5074bae667925a7c123/sentence_transformers/util.py#L386
Hi,
This seems like a trivial question but why is the cos_scores variable being explicitly deleted? If I'm not wrong, the garbage collector will clear that memory since it's a local variable in a loop that goes out of scope?

**Comment by nreimers** [comment]
Not sure if it is needed. But sometimes there are be issues with out-of-memory

**Comment by tomaarsen** [comment]
Hello!

#2381 has removed this `del`, which should indeed not be necessary. 

- Tom Aarsen
