### ISSUE TITLE
cuda out of memory?

### ISSUE THREAD

**Issue by tyker1** [UKPLab/sentence-transformers#171]
So i'm here again. I'm currently trying to train/fine-tune my s-bert, but even with a batch size of 16, i get the error: 

`CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.06 GiB already allocated; 0 bytes free; 6.38 GiB reserved in total by PyTorch)`

with the STS-continue-training example you give, i was able to set batch size up to 32, and when it comes as 64, same error raised.

If i check the GPU Memory allocation, it says about 6GiB is already used as long as i load the pre-trained model into memory

i know reduce batch size can temporary make the warning away, but if i can't train even with a batch size of 16, how can i use those like BatchHardTripleLoss?

**Comment by nreimers** [comment]
8 GB is sadly quite small for GPU memory. BERT, depending which version you take, can already occupy multiple GBs just for the model.

If you cannot work on a larger GPU, you could try to reduce the max input sequence length. Currently it is set to 128 word pieces. If you reduce it, you can save a lot of memory. Memory requirements scales quadratic with the input length.

Best
Nils Reimers

**Comment by tyker1** [comment]
hi,
thx for fast responce,
how can i set the max input sequence length?

**Comment by nreimers** [comment]
When you create a new sentence transformers model:
```
word_embedding_model = models.BERT(model_name, max_seq_length=64)
```

**Comment by tyker1** [comment]
ty for the responce, i also got the model runing with max_seq_length=128 by using fp16

do you think that it is a good way to always use fp16 training if my GPU has small memory?

**Comment by nreimers** [comment]
If your GPU supports FP16, it makes a lot of sense. It is faster and saves memory.

However, with FP16 it can happen that there is a loss overflow. I don't know if this happens with SBERT, never tested it

**Comment by njsdias** [comment]
Hello. I have the same issue related with CUDA out of memory that was already reported here. My question is, when I'm using 

`embedder = SentenceTransformer('bert-base-nli-mean-tokens')
`

How I can change the max_seq_length ? I need to change this parameter in config.json (which has the bellow content) ? 
{
  "max_seq_length": 128
}

**Comment by nreimers** [comment]
Hi  @njsdias 
Yes, that is an option.

**Comment by njsdias** [comment]
Thank you @nreimers.
What other options I have? I still make this question because after decrease max_seq_length value (from 128 to 64) the error persists. My GPU has 16GiB. If I need to decrease more this value maybe is not make sense continue to try to use GPU once my machine has 64GiBRAM 
Another question: Can SBERT run in MultiGPU?  
Thank you.

**Comment by nreimers** [comment]
Hi @njsdias 
Another option is to set the batch size (if you process multiple sentences at once).

Otherwise it sounds strange, is some other process blocking your GPU? It appears that the GPU has only about 100 MB RAM left.

**Comment by njsdias** [comment]
Hi @nreimers,

I really agree with you when you say its sound strange. 

**How I can redefine the bach_size?**
 I'm not building my model. I'm only use what you already did to extract the similarity between sentences. Sadly, I'm not a Pro. I'm only apply the basics.My code is inspired in this notebook. 
[https://github.com/aneesha/SiameseBERT-Notebook/blob/master/SiameseBERT_SemanticSearch.ipynb]

In resume **I'm only instantiate the model.**
`sentence_embeddings = model.encode(sentences)`

Starting in this point how I can redefine batch_size and how I can do **model fine-tune**?  
Have we any config file to setup this kind of things?

I saw when the model was loaded it generates **new folders and files**: 
added_tockens.json
config..json
sentence_bert_config.json
special_tokens_map.json
vocab.txt

Thanks a lot for your help.

**Comment by nreimers** [comment]
You can pass a parameter to model.encode
```
model.encode(sentences, batch_size=1)
```

**Comment by njsdias** [comment]
Thank you @nreimers
