### ISSUE TITLE
Incremental Sentence Transforming?

### ISSUE THREAD

**Issue by jcguu95** [UKPLab/sentence-transformers#1729]
I have a large corpus that grows over time. I wonder if we can transform sentences incrementally. Concretely, consider the following code.

```
from sentence_transformers import SentenceTransformer, util
import torch
embedder = SentenceTransformer('all-MiniLM-L6-v2')

corpus1 = ['I drank an apple.',
           'A man is eating food.',
           'A man is eating a piece of bread.']
corpus2 = ['I ate an apple.', 'A man is drinking food.']

corpus_embeddings = embedder.encode(corpus1, convert_to_tensor=True)
```

Can we do something like `corpus_embeddings.encode_more(corpus2)`?

**Comment by triandco** [comment]
@jcguu95, have you find out more information about this? I noticed if my corpus grows over time, the embeddings are not equals each subsequent time model.encode is run. E.g.:

```
from sentence_transformers import SentenceTransformer, util
import torch
model = SentenceTransformer('all-MiniLM-L6-v2')
value = 'Hello world'
corpus = [value]

embedding1 = model.encode(corpus)

corpus.append(value)
embedding2 = model.encode(corpus)

print(numpy.array_equal(embedding1[0],embedding[1]) # False
```

**Comment by jcguu95** [comment]
@triandco There seems to be a typo in your code.. `embedding` or `embedding2`?

Anyway, I read the source and found out that it is actually easy to hack the `encode` method to achieve what I want.. so I didn't follow up this issue. I should probably close it.

**Comment by jcguu95** [comment]
I didn't save the code.. but all I did was to hack this method, and in particular this [line](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/SentenceTransformer.py#L192).

```
        all_embeddings = [all_embeddings[idx] for idx in np.argsort(length_sorted_idx)]
```

Notice that this method returns `all_embeddings`, and all you had to do is to expose an option so that before transforming into tensors or what not, you add the thing you want into the list. Let me know if you need further hints. If you happen to succeed, please also paste the code here as more people may come to it in the future.

**Comment by triandco** [comment]
I'm guessing your solution is about being able to extend an existing corpus of embeddings, in which case I think I understand the hack.

For my case, I'm thinking about making sure embeddings in each subsequent runs are the same so I can perform more operations on each embeddings. I can create a different issue for this. However, if this is something you dealt with before, I would be delighted to hear more.

Anyhow, thank you @jcguu95 , very much appreciated.

**Comment by jcguu95** [comment]
That is interesting. Is there any line of code in that method that calls an undeterministic function? The code is not long, so one can go through it line by line and see if they can hack further. If you find out why, please share. Thanks :)

**Comment by triandco** [comment]
I found a related issue that might be related to this undeterministic behavior [https://github.com/UKPLab/sentence-transformers/issues/1453]

As nreimers pointed out, this has no effect on the downstream tasks. However, I since I want to work with the value of embeddings themselves, I want to avoid this behavior.

I noticed that if I was to set the ```batch_size=1``` when running ```model.encode```, then I could reliably get back the embedding that can are equal when compared using [numpy.array_equal](https://numpy.org/doc/stable/reference/generated/numpy.array_equal.html). 

Is the ```batch_size`` only an optimization for speed or does it have an impact on the value of the embeddings themselves?

**Comment by jcguu95** [comment]
Seems that the best way to ensure deterministic result is to set it to `1`.. otherwise you may want to hack pytorch. The reason for undeterministic beharior is given [here](https://github.com/pytorch/pytorch/issues/58128). Basically, when it is larger than `1`, it uses another algorithm which is not precise.

**Comment by jcguu95** [comment]
@triandco if possible, could you contact me at jcguu95@gmail.com? Thank you.
