### ISSUE TITLE
oops, File "/home/lbc/GitHub/src/sbert/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py", line 58 out_txt = f" after epoch {epoch}:" ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Williamlizl** [UKPLab/sentence-transformers#175]
oops,
File "/home/lbc/GitHub/src/sbert/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py", line 58
out_txt = f" after epoch {epoch}:"
^
SyntaxError: invalid syntax

and I correct the error :
if steps == -1:
out_txt = ' after epoch:'+ epoch
else:
out_txt = ' in epoch'+ epoch+' after '+steps+' steps:'

but when I install it from source again, it still shows the error.

**Comment by nreimers** [comment]
Have you updated the github repository and tried to install it from source:
```
pip install -e .
```
?

**Comment by Williamlizl** [comment]
> Have you updated the github repository and tried to install it from source:
> 
> ```
> pip install -e .
> ```
> 
> ?

Yes. I download it and start the process. It shows the error and I correct the error. But after I save it,
the code did not update,  so there still is the original error. 

install code:
lbc@prust-System-2:~/GitHub/src/sbert$ pip install -e /home/lbc/GitHub/src/sbert
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/lbc/GitHub/src/sber
###
from sentence_transformers import SentenceTransformer
###
File "/home/lbc/GitHub/src/sbert/sentence_transformers/evaluation/EmbeddingSimilarityEvaluator.py", line 58
    out_txt = f" after epoch {epoch}:"
                                     ^
SyntaxError: invalid syntax

![image](https://user-images.githubusercontent.com/24259779/77868930-6b93b500-726f-11ea-9d23-cbb9f0165585.png)

**Comment by Williamlizl** [comment]
thx, the problem has been sovlved
