### ISSUE TITLE
Failed to import

### ISSUE THREAD

**Issue by ravi160822** [UKPLab/sentence-transformers#1750]
```
from sentence_transformers import SentenceTransformer
```
->
```
libcublas.so.11: cannot open shared object file: No such file or directory
```

**Comment by NouiliKh** [comment]
specifying which torch version worked for me to solve this issue. 
The one I had was v1.13.0 and I switched back to v1.12.1

**Comment by NouiliKh** [comment]
This issue should be closed since it is unrelated to sentence transformers but to torch.
