### ISSUE TITLE
Push to HF Hub fails with `create_repo()` got an unexpected keyword argument 'organization'

### ISSUE THREAD

**Issue by lewtun** [UKPLab/sentence-transformers#1760]
With the merge of #1756 it seems one cannot push models to the HF Hub with `sentence-transformers` v2.2.2 because the `huggingface_hub` version isn't pinned in `requirements.txt`

Here's a [Colab](https://colab.research.google.com/drive/1U93w9ISars4O-5hZk1y2cWqeZJ9_Lxqm?usp=sharing) which basically does the following:

```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('sentence-transformers/paraphrase-mpnet-base-v2')
model.save_to_hub("st-demo")
```

and gives the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-4-83566a1fabd1>](https://localhost:8080/#) in <module>
----> 1 model.save_to_hub("st-demo")

2 frames
[/usr/local/lib/python3.7/dist-packages/sentence_transformers/SentenceTransformer.py](https://localhost:8080/#) in save_to_hub(self, repo_name, organization, private, commit_message, local_model_path, exist_ok, replace_model_card, train_datasets)
    471                 private=private,
    472                 repo_type=None,
--> 473                 exist_ok=exist_ok,
    474             )
    475         full_model_name = repo_url[len(endpoint)+1:].strip("/")

[/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py](https://localhost:8080/#) in _inner_fn(*args, **kwargs)
    122             )
    123 
--> 124         return fn(*args, **kwargs)
    125 
    126     return _inner_fn  # type: ignore

[/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_deprecation.py](https://localhost:8080/#) in inner_f(*args, **kwargs)
     43             )
     44             kwargs.update(zip(sig.parameters, args))
---> 45             return f(**kwargs)
     46 
     47         return inner_f

TypeError: create_repo() got an unexpected keyword argument 'organization'
```

Would it be possible to pin the version or make a new release of `sentence-transformers`?

cc @osanseviero

**Comment by nreimers** [comment]
Do you know which huggingface_hub would be compatible with the old sentence-transformers 2.2.x? Then I could push a new release?

2.3 will then work with the latest huggingface_hub version

**Comment by Muennighoff** [comment]
> Do you know which huggingface_hub would be compatible with the old sentence-transformers 2.2.x? Then I could push a new release?
> 
> 2.3 will then work with the latest huggingface_hub version

From this issue: https://github.com/UKPLab/sentence-transformers/issues/1762, I think `huggingface-hub==0.10.1`

**Comment by vitthal-bhandari** [comment]
@lewtun did you find a fix? facing the same issue.

**Comment by samtn4** [comment]
Hi ! I'm facing the same issue. I realized that the create_repo() method had changed the arguments that it receives. I think the save_to_hub() is sending by default organization=None, causing the issue. I'm trying to change the package code on my ubuntu, but I'm facing some other problems. Hope SentenceTransformers could realese a new version.

**Comment by amitkml** [comment]
I am facing this issue still and do we have any workaround for this please?

**Comment by vitthal-bhandari** [comment]
> I am facing this issue still and do we have any workaround for this please?

Hi @amitkml 
You can do something like this

```
files_to_push_to_hub = [
    'README.md',
    'config.json',
    'config_sentence_transformers.json',
    'merges.txt',
    'modules.json',
    'pytorch_model.bin',
    'sentence_bert_config.json',
    'special_tokens_map.json',
    'tokenizer.json',
    'tokenizer_config.json',
    'vocab.json'
]

for filename in files_to_push_to_hub:
  api.upload_file(
      path_or_fileobj="/content/output/training_simcse_edos_100k/"+filename,
      repo_id="bitsanlp/simcse_retrain_edos_100k_128batch",
      path_in_repo=filename,
      repo_type="model",
      commit_message="Pushing simcse 500k model",
      commit_description="Model trained on 500k tweets using simcse unsup"
  )

api.upload_folder(
    folder_path="/content/output/training_simcse_edos_100k/1_Pooling",
    path_in_repo="1_Pooling",
    repo_id="bitsanlp/simcse_retrain_edos_100k_128batch",
    repo_type="model",
)

```
