### ISSUE TITLE
huggingface_hub.snapshot_download is not exposed as a public module anymore

### ISSUE THREAD

**Issue by shankha06** [UKPLab/sentence-transformers#1762]
As per release documents of huggingface_hub, https://github.com/huggingface/huggingface_hub/releases/tag/v0.11.0, the snapshot_download is no longer public anymore.
Please update the requirements file for huggingface_hub <=0.10.1

**Comment by prakharlovesdata** [comment]
fixed this by changing huggingface-hub==0.10.1

**Comment by tomaarsen** [comment]
Hello!

The new 2.3.0 release no longer depends on `snapshot_download`, but has been updated to work with `huggingface_hub` its newer features. In short, this should no longer be an issue.

- Tom Aarsen
