### ISSUE TITLE
The params of normalize_embeddings=True doesn't work

### ISSUE THREAD

**Issue by PF-Chen** [UKPLab/sentence-transformers#1776]
I want to normalize the output vectors. But normalize_embeddings=True may not work. I add the params of normalize_embeddings, but the output doesn't normalized!

Can you help me, thanks.

This is my demo code
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('/mlx/data00/all-MiniLM-L6-v2')

#Our sentences we like to encode
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown fox jumps over the lazy dog.']

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences, normalize_embeddings=True)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
    print("Sentence:", sentence)
    print("Embedding:", embedding)
    print("")
```

<img width="651" alt="image" src="https://user-images.githubusercontent.com/69154067/205336517-f4be210a-91ae-4e2b-81f2-edb62304ad87.png">

**Comment by nreimers** [comment]
These are normalized.

Normalized means vector length is 1.

**Comment by PF-Chen** [comment]
> These are normalized.
> 
> Normalized means vector length is 1.

thanks for you explain.
you are right. i mixed the concept.
thanks
