### ISSUE TITLE
save_to_hub not working with any version of hub

### ISSUE THREAD

**Issue by vitthal-bhandari** [UKPLab/sentence-transformers#1777]
Environment : Colab
Steps to reproduce : 
```
!pip install sentence-transformers
!pip3 install huggingface_hub==0.10.0
```

```
HF_TOKEN = 'XYZ'
from huggingface_hub import notebook_login
notebook_login()
```

`model.save_to_hub("simcse_edos_10k")`

tried with versions 10.0, 10.1, 11.1, 9.1

Getting  RepositoryNotFoundError  error or Organization parameter as extra error.

Just trained SimCSE on 100k sentences, don't know how to save model now.

**Comment by sidraina89** [comment]
I am facing the same issue as mentioned by vitthal-bhandari above:
Environment: JupyterLab
<img width="330" alt="image" src="https://user-images.githubusercontent.com/8019721/207292192-7db47498-5dce-41bf-84af-0baad8e8266c.png">

Error Response: TypeError: create_repo() got an unexpected keyword argument 'organization'

**Comment by Jerado10** [comment]
I'm facing exactly the same issue

**Comment by sidraina89** [comment]
I was able to upload the model to hub using a workaround. Specifically by using the `upload_folder()` functionality from HFApi. 

Example below:

``` 
from huggingface_hub import HfApi
api = HfApi()
api.upload_folder(
    repo_id="<Your repo at hf hub>",
    folder_path="<local model folder>",
    repo_type="model",
)
```

Hope this helps! 😄
