### ISSUE TITLE
How to load a hf model with cls pooling?

### ISSUE THREAD

**Issue by jordane95** [UKPLab/sentence-transformers#1790]
Hi, I want to load a model weights from hugging face, but with [CLS] pooling. I'm wondering if there is some convenient way to specify the pooling method, since the default pooling method in your code is mean pooling.

**Comment by nreimers** [comment]
See:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

In pooling, you can pass as argument "cls"
