### ISSUE TITLE
`community_detection` algorithm returns results sorted by indexes

### ISSUE THREAD

**Issue by maiiabocharova** [UKPLab/sentence-transformers#1791]
Hello, community detection algorithm started always returning the results in the sorted by index way. Previously it returned the results sorted from center, but not anymore, now for all `embeddings` it sorts all the clusters by indexes (tried on several cases, always results are sorted by indexes)

```
torch 1.12.1
sentence_transformers 2.2.2
```

**Comment by psardin** [comment]
You need to comment this line to have the centers first
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/util.py#L402

**Comment by Ellyuca** [comment]
Thanks @psardin for the tip.
The documentation is a bit misleading... 
```The first element in each list is the central point in the community```

**Comment by dyaaalbakour** [comment]
created a pull request here https://github.com/UKPLab/sentence-transformers/pull/2277

**Comment by tomaarsen** [comment]
Resolved via #2277
