### ISSUE TITLE
Open Model from S3?

### ISSUE THREAD

**Issue by fabioselau077** [UKPLab/sentence-transformers#1798]
Hello, I'm using it to detect similarity between two images, the function has about 15 lines, but because of the model it gets very heavy and ends up crashing.
I tried to host it on Heroku but as it gave almost 2GB it gave the limit, I managed to deploy it on DigitalOcean Apps but when I try to download the model it ends up crashing too.
Is there any recommended way to cache the model or upload the model to AWS S3 and then retrieve it somehow?
On localhost everything works fine

`
    
    print('Loading CLIP Model...')
    
    model = SentenceTransformer('clip-ViT-B-32')
`
Print of DigitalOcean Apps
![image](https://user-images.githubusercontent.com/57275833/209507461-84f9f359-e65b-4bdd-8c20-f32b206b4ba3.png)

How to use model from S3?

**Comment by bm777** [comment]
@fabioselau077, this issue has already been solved here -> https://github.com/UKPLab/sentence-transformers/issues/1107
