### ISSUE TITLE
can we train albert model with same package ? 

### ISSUE THREAD

**Issue by tuner007** [UKPLab/sentence-transformers#180]
Unable to train alberta model using ALBERT script provided in models.
Can you please guide me here.. 
thanks !!

**Comment by nreimers** [comment]
The ALBERT model in  the transformers version that is used here has a bug when trained on a GPU. Update to the newest transformers package, than you should be able to train it.

Hint: I did not achieve good results with ALBERT, about 10 points worse than the other models.

**Comment by tuner007** [comment]
> The ALBERT model in the transformers version that is used here has a bug when trained on a GPU. Update to the newest transformers package, than you should be able to train it.
> 
> Hint: I did not achieve good results with ALBERT, about 10 points worse than the other models.

Sure let me try with latest transformer package.

Thanks !

**Comment by tuner007** [comment]
@nreimers just to update.. i got 0.81 on STS test with albert-large-nli-mean-tokens 
- Next will train on STS dataset

**Comment by tuner007** [comment]
@nreimers  i wanted to use [bert-as-service](https://github.com/hanxiao/bert-as-service) for generating sentence embedding, can i convert SBERT model to tensorflow model and use this tensorflow model in bert-as-service ?

Also, can you help me with the parameters: 
bert-serving-start -num_worker=1 **-pooling_strategy** REDUCE_MEAN **-pooling_layer** -6 -model_dir=model_path

Thanks !

**Comment by nreimers** [comment]
Hi @tuner007 
It should be possible, but I never tried to convert it to TF. Maybe there is more information in the huggingface repository how to convert models to TF.

Best
Nils Reimers

**Comment by tuner007** [comment]
> Hi @tuner007
> It should be possible, but I never tried to convert it to TF. Maybe there is more information in the huggingface repository how to convert models to TF.
> 
> Best
> Nils Reimers

Hi @nreimers ,

Thanks a lot for you quick support. :)

I tried bert-base with bert-as-a-service and i think it works well.
But when i tried converting distiluse-base-multilingual-cased to tf model i only considered 0_DistilBERT folder which did not gave good results later i checked you have also added a dense layer for 768->512 emb.
How can i convert this distiluse-base-multilingual-cased to tf model?

FYI below is the script i used to convert it into tf model:
`
from transformers import DistilBertModel
import torch
model = DistilBertModel.from_pretrained(
        pretrained_model_name_or_path=model_path,
        state_dict=torch.load(pytorch_model.bin_path),
        cache_dir=model_path,)

[convert_pytorch_checkpoint_to_tf](https://github.com/nlpyang/pytorch-transformers/blob/master/pytorch_transformers/convert_pytorch_checkpoint_to_tf.py) (model=model, ckpt_dir=xx, model_name='distilbert_model')
`

Thanks & Regards,
Arpit

**Comment by nreimers** [comment]
Hi Arpit,
you would also need to convert the dense layer to TF and then add it when it is loaded with bert-as-a-service. I am afraid this is not straight forward.

Maybe is is easier to just create a simple Flask / FastAPI service based on SBERT for your use-case?

Best
Nils
