### ISSUE TITLE
Community detection algorithm can loop forever

### ISSUE THREAD

**Issue by maiiabocharova** [UKPLab/sentence-transformers#1800]
If only one vector is passed community detection algorithm will loop forever.

I suggest adding
```
assert embeddings.shape[0] >= 2, "Embeddings should contain at least two vectors"
assert embeddings.shape[0] >= min_community_size, "Number of vectors is less than specified min_community_size"
```
checks.
(Can open a pull request for this)

**Comment by AmirPupko** [comment]
Hi, any updates on this? Is this fix gonna be released soon?

**Comment by stefansturlu** [comment]
This i still an issue. Seems to happen when all the embeddings are more similar to each other than the threshold.

Here's an example that causes an infinite loop:
```python
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer("all-mpnet-base-v2")
texts = ["Example string", "Example string", "Example string"]
embeddings = model.encode(texts, convert_to_tensor=True)
clusters = util.community_detection(embeddings)  # This results in an infinite loop
```

Looks like it was already fixed on the master branch a while ago, but it isn't fixed the latest version (i.e. `sentence-transformers=2.2.2`)

**Comment by gab-palmeri** [comment]
Hi, any news about this issue? Do we have to manually download the repository for the moment?

**Comment by gab-palmeri** [comment]
Hi, any news about this issue? Do we have to manually download the repository at the moment?

**Comment by mtalcott** [comment]
I'm running into this issue as well. Would appreciate a new release!

**Comment by mou23** [comment]
I'm also having this issue!

**Comment by tomaarsen** [comment]
I intend for a new release to be out within the next few days/weeks.

**Comment by GowthamSagar310** [comment]
hi, any updates on this ?

**Comment by tomaarsen** [comment]
There have been some delays. However, I intend to release v2.3.0 within the next two weeks.

**Comment by vineetsajuTR** [comment]
Any updates yet? Its been a month since your last comment @tomaarsen

**Comment by AronsonDan** [comment]
Any ETA for a new release?

**Comment by tomaarsen** [comment]
I'm afraid the ETA is still "as soon as possible". I am awaiting the permissions to update the sbert.net website, and I can publish the release the same day that I gain access. I've once again requested access, so hopefully the release can be carried out soon.

- Tom Aarsen

**Comment by vineetsajuTR** [comment]
> I'm afraid the ETA is still "as soon as possible". I am awaiting the permissions to update the sbert.net website, and I can publish the release the same day that I gain access. I've once again requested access, so hopefully the release can be carried out soon.
> 
> * Tom Aarsen

Who needs to provide these permissions just out of curiosity. Is it another maintainer of the repo? Wondering if there are any workarounds?

**Comment by tomaarsen** [comment]
From the original maintainer from who I am taking over. He was out of office a lot over Christmas & up to last week. It shouldn't take long now :)

**Comment by tomaarsen** [comment]
Hello!

The release has been published! You can now use 
```
pip install -U sentence-transformers
```
to install v2.3.0.

- Tom Aarsen

**Comment by vineetsajuTR** [comment]
Assuming this release contains everything in the main branch? Thank you!

**Comment by tomaarsen** [comment]
That is exactly right!
