### ISSUE TITLE
SentenceTransformer.encode() moves self (Module) to device

### ISSUE THREAD

**Issue by piteren** [UKPLab/sentence-transformers#1806]
When you call SentenceTransformer.encode() it moves self (Module) to device which by default is None (Line #153 of SentenceTransformer.py). I don't know if it is desired behavior, but I was a bit confused. Imagine such scenario:

model = SentenceTransformer() # I know that I can give device here, while init, but I do not want to
model.to('cuda:1')
model.encode('some text') # it will be encoded on cuda:0 if you have 2 GPUs

**Comment by tomaarsen** [comment]
I ran into similar issues with moving models to other devices. My solution was to also update `model._target_device` when moving the model with `to`.

See the following example:
https://github.com/tomaarsen/setfit/blob/14602ea2773f77b82243624ed1bca5e0772519e7/src/setfit/modeling.py#L442-L445

**Comment by tomaarsen** [comment]
This confusing behaviour has been updated in #2351, and will be included in the upcoming release.
