### ISSUE TITLE
Model caching on SentenceTransformer and models.Transformer

### ISSUE THREAD

**Issue by sadaqabdo** [UKPLab/sentence-transformers#1828]
When initiating the `SentenceTransformer`, the model downloads from hf, and when initiating models.Transformer with the same model, it downloads again instead of using cache.  This is causing longer load times and potentially unnecessary data usage. 

Is this an expected behaviour?
Example to reproduce:
```Python
from sentence_transformers import SentenceTransformer, models

SentenceTransformer("distilroberta-base")
```

```Python
models.Transformer("distilroberta-base", max_seq_length=75)
```

**Comment by bm777** [comment]
Hi @sadaqabdo,

yes, you have to specify the `cache_dir` when you are using `sentence_tranformers.models.Transformer` class.

Parameters:

- **cache_dir** – Cache dir for Huggingface Transformers to store/load models

See the documentation about -> [sentence_transformer.models.Transformer](https://www.sbert.net/docs/package_reference/models.html#sentence_transformers.models.Transformer)

**Comment by sadaqabdo** [comment]
Thanks @bm777

**Comment by NouiliKh** [comment]
@bm777 As far as I understand the default caching folder is `~/.cache/torch/sentence_transformers`
You don't need to specify `cache_dir`if you want to cache. 
https://github.com/UKPLab/sentence-transformers/blob/3e1929fddef16df94f8bc6e3b10598a98f46e62d/sentence_transformers/SentenceTransformer.py#L55

**Comment by gennaro-tedesco** [comment]
Would it be possible to clarify what options specifically need to be provided to the estimator? The documentation is a little unclear: for instance the [docs](https://www.sbert.net/docs/package_reference/models.html#sentence_transformers.models.Transformer) indicate `cache_dir` as parameter, however the [code](https://github.com/UKPLab/sentence-transformers/blob/3e1929fddef16df94f8bc6e3b10598a98f46e62d/sentence_transformers/SentenceTransformer.py#L40) refers to `cache_folder`; moreover [model_name](https://github.com/UKPLab/sentence-transformers/blob/3e1929fddef16df94f8bc6e3b10598a98f46e62d/sentence_transformers/SentenceTransformer.py#L37) seems to circumvent all of this.

What is the difference between specifying `model_name` and/or `cache_folder`? Would the estimator look into the cache folder to retrieve the same model once cached (it does not seem to be the case from the code _unless_ `model_name` is explicitly stated, which makes the option `cache_dir` redundant then)?

**Comment by gabrimarconi** [comment]
Hello, can you give an example of how to use cache_dir? I don't find one in the documentation. In the specific, I would like to indicate the caching directory from which to source the model when I load it.

**Comment by tomaarsen** [comment]
@gabrimarconi If you want to load a local model saved in a specific directory, you can load the model like this instead:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("my/path/to/directory")
```

Otherwise, the `cache_folder` is just where the model is cached after downloading from Hugging Face. If not specified, `~/.cache/huggingface` is used.

- Tom Aarsen
