### ISSUE TITLE
Installation recommends transformer library beyond latest

### ISSUE THREAD

**Issue by cm-ndx** [UKPLab/sentence-transformers#1832]
https://www.sbert.net/docs/installation.html

We recommend Python 3.6 or higher, [PyTorch 1.6.0](https://pytorch.org/get-started/locally/) or higher and [transformers v4.6.0](https://github.com/huggingface/transformers) or higher. The code does not work with Python 2.7.

The latest transformers library as of this writing is 4.26.1 
https://github.com/huggingface/transformers/releases

**Comment by tomaarsen** [comment]
Hello!

`4.6.0` is much lower than `4.26.1`: it's the 6th minor release of major version 4 versus the 26th minor release of major version 4.

As of Sentence Transformers v2.3.0 (released today), you need:
> We recommend Python 3.8 or higher, [PyTorch 1.11.0](https://pytorch.org/get-started/locally/) or higher and [transformers v4.32.0](https://github.com/huggingface/transformers) or higher.

- Tom Aarsen
