### ISSUE TITLE
__version__ attribute missing in mode config.

### ISSUE THREAD

**Issue by yakazimir** [UKPLab/sentence-transformers#184]
https://github.com/UKPLab/sentence-transformers/blob/43e89d9d974478b85b8ef3c73006f177df64dd9c/sentence_transformers/SentenceTransformer.py#L73

I'm trying to load a model that I trained from scratch, and it appears that the `SentenceTransformer.py` code above is requesting a field `__version__` in the model config that doesn't appear to be there. 

I haven't looked too deeply, but in case it matters, this is a RoBERTa large NLI model (I notice in the Bert-base model I trained it's also missing).

Also, thanks for such a great toolkit!

**Comment by nreimers** [comment]
Hi @yakazimir 
if you want to use your own, custom BERT model, you must load it via:

```
# Use BERT for mapping tokens to embeddings
word_embedding_model = models.BERT('path/to/your/bert/model')

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

Best
Nils Reimers

**Comment by yakazimir** [comment]
ah, I see. Thanks for the details, that is much simpler! (I did get it loaded in the normal fashion by just adding the __version__ field manually to the config. Is there any unexpected issues with doing this?)

**Comment by nreimers** [comment]
Just adding the version to the config file shouldn't give you a working model.

**Comment by yakazimir** [comment]
should or shouldn't? hm.. it seems to work fine after that. But in any case I will follow your more sensible instructions. Thanks again.

**Comment by nreimers** [comment]
The mean Pooling layer should be missing if you load a Bert model with SentenceTransformer('bertmodel'), so it should not produce any sentence embeddings. I am surprised that you didn't get any further warnings.

**Comment by yakazimir** [comment]
got it. I will close, since this seems to have been sorted out. Thanks again!

**Comment by yakazimir** [comment]
Hi sorry. I took a closer look at the code, and perhaps there was a misunderstanding. The model that I `trained from scratch` was a model trained with your sentence transformer code, via `examples/training_nli_bert.py` (not a custom model trained in some other way). 

What I was trying to do was load it again via the `SentenceTransformer` class, as you do when you evaluate the trained model at this line: https://github.com/UKPLab/sentence-transformers/blob/7fa3f0df28b3ae2a1d7353602de4e020e5f9e8d0/examples/training_nli_bert.py#L82.  So after training the resulting models like look:

```
$ ls /path/to/SIMILARITY_MODEL/models/roberta_larger_nli/roberta-large-2020-03-24_19-14-48/
0_RoBERTa/                         config.json                        similarity_evaluation_results.csv
1_Pooling/                         modules.json 
```

The problem is that I was trying to load it by looking inside the `config` in `0_RoBERTa/`, which clearly doesn't have the `__version__` field.

**Comment by dcnkmitte** [comment]
> Hi @yakazimir if you want to use your own, custom BERT model, you must load it via:
> 
> ```
> # Use BERT for mapping tokens to embeddings
> word_embedding_model = models.BERT('path/to/your/bert/model')
> 
> # Apply mean pooling to get one fixed sized sentence vector
> pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
>                                pooling_mode_mean_tokens=True,
>                                pooling_mode_cls_token=False,
>                                pooling_mode_max_tokens=False)
> 
> model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
> ```
> 
> Best Nils Reimers

Hi Nils,
can you tell me what should I import to get the model.
I mean "import model from XYZ"

thanks in advance

**Comment by hwaking** [comment]
邮件已收到！
