### ISSUE TITLE
Model download link giving 500 error

### ISSUE THREAD

**Issue by paullovachy** [UKPLab/sentence-transformers#1861]
Using version 0.3.7.2. 

Code:
model_choice = 'bert-base-nli-mean-tokens'
model = SentenceTransformer(model_choice) # error coming from this piece

Error:
HTTPError: 500 Server Error: Internal Server Error for url: https://sbert.net/models/bert-base-nli-mean-tokens.zip

Seems that the page https://sbert.net/models no longer exists? Using this for a major workflow - is that link permanently invalid, and if so, where can I download bert-base-nli-mean-tokens? Not seeing it here: https://www.sbert.net/docs/pretrained_models.html

**Comment by nreimers** [comment]
I strongly advise to update to sentence-transformers v2, which is based on the huggingface model hub.

Also that model is terribly bad, highly recommend to use one of the newer models.

**Comment by nreimers** [comment]
Issue should be fixed
