### ISSUE TITLE
Where to find tasks used to evaluate models?

### ISSUE THREAD

**Issue by zhaowei-wang-nlp** [UKPLab/sentence-transformers#1863]
On the page of pre-trained models, there are two metrics: Performance Sentence Embeddings and Performance Semantic Search. Their explanations say that those two metrics are computed on 14 and 6 datasets separately. What are they specifically? Could you provide more details about the evaluation?
https://www.sbert.net/docs/pretrained_models.html

**Comment by Kn0rk** [comment]
I also could not find the datasets. Did you find them? If so it might be useful to add them to the website.
