### ISSUE TITLE
make sentencepiece optional

### ISSUE THREAD

**Issue by psifertex** [UKPLab/sentence-transformers#1872]
Because sentencepiece [still doesn't have 3.11 support](https://github.com/google/sentencepiece/issues/810) and building it without an existing wheel has a relatively large number of dependencies, it would be nice if it were an optional requirement. This is, in fact how transformer [already handles it](https://huggingface.co/transformers/v4.4.2/migration.html#id1).

**Comment by fkdosilovic** [comment]
Resolved in https://github.com/UKPLab/sentence-transformers/pull/2476

cc @tomaarsen
