### ISSUE TITLE
TED Dataset no longer available

### ISSUE THREAD

**Issue by ArjunBhalla98** [UKPLab/sentence-transformers#1874]
Hi, in trying to run the multilingual example we get the error:

```requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/ted2020.tsv.gz```

Upon looking at the directory (```https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/```), it seems that ted2020.tsv.gz does not exist there.

**Comment by nemphys** [comment]
Same here, is the file still available somewhere else?

**Comment by jiayaopeng** [comment]
same here @nreimers, may I ask is there any other multi lingual datasets I could use from this https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/? thank u

**Comment by ecoli-hit** [comment]
Maybe here is the dataset https://opus.nlpl.eu/TED2020.php

**Comment by tomaarsen** [comment]
Hello!

I'm afraid this dataset has been removed. However, we do support a parallel sentences dataset that can be used to make a model multilingual. See #2243 for example.

- Tom Aarsen
