### ISSUE TITLE
encode() single sentence vs. list of sentences not same embeddings

### ISSUE THREAD

**Issue by leonardlin** [UKPLab/sentence-transformers#1883]
I encountered something odd I don't understand

I get different embedding vector for the same string, depending if it was encoded alone or as part of a list of multiple sentences.

Given following snippet
```
model = SentenceTransformer('./nlp_model/')

sentence1 = 'this is sentence 1'
sentence2 = 'the house is red'

tensor1 = model.encode([sentence1], convert_to_tensor=True)
tensor2 = model.encode([sentence1, sentence2], convert_to_tensor=True)

## expected
tensor1.tolist()[0] same as tensor2.tolist()[0]

## actual
tensor1.tolist()[0] NOT same as tensor2.tolist()[0]
```

I tried tensor=False, batch_size = 1 but all with the same result.

What am I missing?

Thanks for any hints.

I'm using sentence-transformer == 2.2.2

**Comment by Ravi2712** [comment]
I think making this explicit in a document might be a good idea. What do you think? From a research perspective, I think there should be an option(argument) to truncate the sentence instead implicit based on the maximum length of sentence from the list.  @leonardlin

**Comment by leonardlin** [comment]
@Ravi2712 thanks for asking, but I'm not sure if I'm qualified to give proper feedback.
the optional truncate argument sounds ok for me, this way people can discover the option and use it explicitly

The original confusion I think can be fixed by adding something to the documentation.
Not automatically extend the padding would create truncation which would be super confusing for newbies..
