### ISSUE TITLE
Roberta Tokenizer too many SEP?

### ISSUE THREAD

**Issue by Aaronsom** [UKPLab/sentence-transformers#19]
In https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/models/RoBERTa.py at get_sentence_features() two SEP tokens are added to the input.

According to the HuggingFace RobertaTokenizer (https://huggingface.co/pytorch-transformers/_modules/pytorch_transformers/tokenization_roberta.html#RobertaTokenizer) only one SEP token is added if you encode one sentence with add_special_tokens_single_sentence().
However, add_special_tokens_sentences_pair has two SEP tokens between the sentences.

Which format is correct? Does it even matter what format you use?

**Comment by nreimers** [comment]
Good question. I used the implementation from utils_glue.py from the examples folder. There, if I am not wrong, is always a second sep token added to the sentence. Not sure if this is required.

I think the difference will not be so great between one and two sep tokens. Will need to check the official RoBERTa code.

**Comment by nreimers** [comment]
Fixed in the latest version
