### ISSUE TITLE
trl and sentence-transformers? (RLHF)

### ISSUE THREAD

**Issue by leoplusx** [UKPLab/sentence-transformers#1908]
Can I use trl to improve sentence-transformers on semantic search tasks?

I hear that trl is more sample efficient than normal training or fine tuning. So in theory, it should be possible to use this technique to domain adapt a sentence-transformer with far fewer annotation triplets.

I am thinking

a) using it on a pre-trained sentence-transformer directly or

b) using it on a pre-trained transformer model, and then combining that model into a sentence-transformer by adding a pooling layer.

I haven't found any documentation on this. Is there any reason why this shouldn't work? What would be the best way to go about it?

Thanks!

**Comment by seganrasan** [comment]
Hi, any info on the above query?

**Comment by tomaarsen** [comment]
Hello!

Yes! Thanks @seganrasan for pointing me to this issue.
In essence, TRL uses reinforcement learning to finetune models, but in particular, it finetunes *generative* models. The primary use case is to finetune LLMs to follow instructions well, for example through RLHF or SFT + DPO. 

On the other hand, Sentence Transformers can also be used for finetuning models, but in particular, it allows for finetuning *embedding* models. 

In short, the two projects have different goals, and work on different kinds of models. TRL would not work together with Sentence Transformers.

P.s. to my knowledge, TRL is not more sample efficient than normal finetuning. Most TRL Trainers are just regular `transformer` Trainer subclasses with a bit of extra quality-of-life stuff. Perhaps you are thinking of PEFT (although I'm not sure that PEFT is more sample efficient either, but it's a surprisingly common mixup).

I'll close this for now, but feel free to respond if you still have more questions.

- Tom Aarsen
