### ISSUE TITLE
Sentence Transformers pre-trained models no longer on Hugging Face.

### ISSUE THREAD

**Issue by JLPiper** [UKPLab/sentence-transformers#1915]
The pre-trained models are no longer on Hugging Face. Any current understanding of why?
It looks like not even the account is active anymore. Just coming up with a 404 message.

**Comment by nirahs** [comment]
Yes, I'm also encountering this problem, but the models are still accessible through the SentenceTransformers library.

**Comment by Barry-Menglong-Yao** [comment]
Same here.

**Comment by yudhiesh** [comment]
I am using KeyBERT for a pipeline(uses sentence-transformers within it) and it throws an error as well:
```
RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64599ec7-55ee4d860d9461c170c5b5d6)

Repository Not Found for url: https://huggingface.co/multi-qa-MiniLM-L6-cos-v1/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.
```
The URL to the model is indeed throwing a 404 Error.

**Comment by JLPiper** [comment]
> I am using KeyBERT for a pipeline(uses sentence-transformers within it) and it throws an error as well:
> 
> ```
> RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-64599ec7-55ee4d860d9461c170c5b5d6)
> 
> Repository Not Found for url: https://huggingface.co/multi-qa-MiniLM-L6-cos-v1/resolve/main/config.json.
> Please make sure you specified the correct `repo_id` and `repo_type`.
> If you are trying to access a private or gated repo, make sure you are authenticated.
> Invalid username or password.
> ```
> 
> The URL to the model is indeed throwing a 404 Error.

I use the "txtai" library, and noticed because I was being thrown a similar error!

**Comment by complexitysoftware** [comment]
Yes me too. But as @nirahs said, for me the sentence_transformers library still works:
```
modelNameFull = "sentence-transformers/distiluse-base-multilingual-cased-v1"
model = SentenceTransformer(modelNameFull)
tokenizer = model.tokenizer
```
but avoid the transformer library:
`tokenizer = AutoTokenizer.from_pretrained(modelNameFull, use_fast=True)`

**Comment by DimBer** [comment]
Same problem with `sentence_transformers` library:

```
Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/msmarco-distilbert-base-tas-b.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.
Invalid username or password.
```

**Comment by thatjuan** [comment]
There are all manner of dependencies on huggingface/sentence-transformers on LangChain... Is this permanent?

**Comment by DimBer** [comment]
It seems like https://huggingface.co/sentence-transformers throws 404 as well (i.e., sentence-transformers are completely missing from hugging face)

**Comment by carlesoctav** [comment]
any update ...

**Comment by ali-sheikh** [comment]
Anyone came up with any solutions for this?

**Comment by NathanPages** [comment]
As a temporary workaround you can check if the model you want to use has been previously cached. By default the models get cached in `torch.hub._get_torch_home()`. Then you can call directly the model using the path, for example, for `MiniLM-L6-v2`:
```python
from pathlib import Path
import torch
from sentence_transformers import SentenceTransformer
cache_folder = Path(torch.hub._get_torch_home()).resolve()
model = SentenceTransformer(cache_folder / 'sentence_transformers' / 'sentence-transformers_all-MiniLM-L6-v2')
```

**Comment by pruthvi-itribe** [comment]
facing similar issue

**Comment by ali-sheikh** [comment]
> As a temporary workaround you can check if the model you want to use has been previously cached. By default the models get cached in `torch.hub._get_torch_home()`. Then you can call directly the model using the path, for example, for `MiniLM-L6-v2`:
> ```python
> from pathlib import Path
> import torch
> from sentence_transformers import SentenceTransformer
> cache_folder = Path(torch.hub._get_torch_home()).resolve()
> model = SentenceTransformer(cache_folder / 'sentence_transformers' / 'sentence-transformers_all-MiniLM-L6-v2')
> ```

Thanks @NathanPages ! I'm running the whole thing on a docker container. I'll see if it's cached somewhere, but not sure.

**Comment by davidmezzetti** [comment]
https://twitter.com/huggingface/status/1655760648926642178

Seems like an issue with the Hugging Face Hub. I wouldn't go changing code, wait for the fix from Hugging Face.

**Comment by nithinkanil1** [comment]
I am also facing an invalid username and password error. How to fix this error?

**Comment by ToolmanP** [comment]
Same situation here. Waiting for Hugging Face to fix that bug.

**Comment by czx20010217** [comment]
same error for invalid username and password, maybe they need to reconfig the repo?

**Comment by cross-hello** [comment]
🙃 same problem here...

**Comment by cross-hello** [comment]
Temporarily workaround, download from here: https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

**Comment by ArrichM** [comment]
+1

**Comment by regCode** [comment]
Same here

**Comment by nreimers** [comment]
Not sure why this happens, appears to be an issue by HuggingFace. Somehow account appears to be removed, not sure why.

Will investigate

**Comment by nreimers** [comment]
HuggingFace commented on this on Twitter
It is a bug, they work on a fix
https://twitter.com/huggingface/status/1655760648926642178

**Comment by davidmezzetti** [comment]
They have updated that they are still working on the issue: https://twitter.com/huggingface/status/1655885897961811971

**Comment by mzh1996** [comment]
It seems that the page of the sentence-transformers account is unaccessible...

**Comment by akashe** [comment]
I am still facing the above issue.

Repository Not Found for url: https://huggingface.co/api/models/sentence-transformers/bge-large-en.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

**Comment by VIKI623** [comment]
已收到您的来件，我会尽快阅读并处理。祝好！I have received your email. I will read and deal it as soon as possible.Best regards.

**Comment by davidmezzetti** [comment]
I believe you want to use this model: https://huggingface.co/BAAI/bge-large-en

**Comment by akashe** [comment]
Yes, I am trying to use the model via langchain which uses sentence transformer to generate embeddings

**Comment by akashe** [comment]
Any updates or help on this

https://github.com/UKPLab/sentence-transformers/issues/1915#issuecomment-1689748007
