### ISSUE TITLE
max_seq_length of pre-trained models

### ISSUE THREAD

**Issue by IliasAarab** [UKPLab/sentence-transformers#1918]
The [model overview](sbert.net/docs/pretrained_models.html#sentence-embedding-models) section of the documentation mentions that the `all-MiniLM-L6-v2`  pre-trained model has a maximum sequence length of `256`. However I am able to successfully set the `max_seq_length` property to `510` and the model is able to encode sentences with this many word pieces.

I'm wondering whether the documentation is off, or whether setting the max length to `510` would cause any issues down the road?

**Comment by Ravi2712** [comment]
@IliasAarab Are you able to encode sentence with newly set `max_seq_length`? Can you confirm if you are talking about `encode()` method or something else. I don't see `encode()` method using newly set `max_seq_length`. Just making sure, thanks.

**Comment by IliasAarab** [comment]
@Ravi2712 Apologies for the late response.

Yes, I'm talking about the `encode()` method indeed. I can use it with a newly set `max_seq_length` as long the max length is less than or equal to the max length of the underlying model used for the sentence transformer. However, in my above example the `all-MiniLM-L6-v2 ` model has been trained with truncated instances of max length `256`, so, although increasing the length to the max of the base model works, it is not advisable to do so.

**Comment by langchain4j** [comment]
Hi @IliasAarab, did you test the performance of semantic search with lengths more than 256?
Thanks!

**Comment by IliasAarab** [comment]
@langchain4j no, I haven't really. I used models that were trained with a larger seq length and used models with a smaller seq length but further trained them using TSDAE.
