### ISSUE TITLE
models not recognized

### ISSUE THREAD

**Issue by sravs1234** [UKPLab/sentence-transformers#192]
# Use BERT for mapping tokens to embeddings
word_embedding_model = models.BERT('bert-base-uncased')

----> 1 word_embedding_model = models.BERT('bert-base-uncased')
      2 
      3 # Apply mean pooling to get one fixed sized sentence vector
      4 pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
      5                                pooling_mode_mean_tokens=True,

NameError: name 'models' is not defined

**Comment by nreimers** [comment]
How does your import look like and do you import the models package from sentencetransformers?

**Comment by sravs1234** [comment]
from sentence_transformers import models, losses

Got this after searching the imports, it worked. Thanks.
