### ISSUE TITLE
Error in encode method documentation of SentenceTransformer 

### ISSUE THREAD

**Issue by albertovilla** [UKPLab/sentence-transformers#1922]
In the `encode` method of `SentenceTransformer` class the signature of the method states that:

> By default, a list of tensors is returned. If convert_to_tensor, a stacked tensor is returned. If convert_to_numpy, a numpy matrix is returned.

However, I think this is not correct because the default value of `convert_to_numpy` is `True` and the default value of `convert_to_tensor` is `False`, therefore, the part of the code where the output type is defined will select the branch where a `ndarray` is returned.

```python
if convert_to_tensor:
    all_embeddings = torch.stack(all_embeddings)
elif convert_to_numpy:
    all_embeddings = np.asarray([emb.numpy() for emb in all_embeddings])
```

This behaviour can be verified by loading any model (e.g. all-mpnet-base-v2) and call the `encode` method on a sentence. The return type of the method is `numpy.ndarray`.

**Comment by Ravi2712** [comment]
Yes, I came across this today while investigating `encode()` method and documentation. Maybe we can make a documentation change PR. @albertovilla
