### ISSUE TITLE
Electra model

### ISSUE THREAD

**Issue by e-ndrus** [UKPLab/sentence-transformers#193]
@nreimers, would be great to have Electra among the available models. Are there plans to include it, as well? It's already available in HuggingFace Transformers.

**Comment by nreimers** [comment]
It will be available soon. The next version is nearly done, I currently do the last tests.

Best regards 
Nils Reimers

**Comment by nreimers** [comment]
Hi @e-ndrus 
A new version was released, with huggingface transformers version 2.8.0. You can use models.Transformer to load the google/electra models.

I trained them with NLI data but sadly didn't get great results so far (not better than the BERT models).

Best
Nils Reimers

**Comment by omerarshad** [comment]
@nreimers Did you tried the same pipeline? i.e. first trained on snli/Mnli and then trained on STS

**Comment by nreimers** [comment]
@omerarshad Run it on NLI, but sadly did not yield convincing results (about 5-10 points worse than BERT if I remember correctly).

**Comment by omerarshad** [comment]
ah.. i have a question, if a model is trained on nli+STS and i want to transfer it to another domain. Is their any technique which preserves semantic capturing of model and just pre-train model on new corpus. Which means that i dont have to retrain new model again on nli+STS.

**Comment by omerarshad** [comment]
ok. can you please share electra trained on NLI model?

**Comment by nreimers** [comment]
Haven't saved that model. But you can train it yourself by running:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training_transformers/training_nli.py

And passing the right google/electra model to it.

**Comment by PhilipMay** [comment]
> 
> 
> @omerarshad Run it on NLI, but sadly did not yield convincing results (about 5-10 points worse than BERT if I remember correctly).

Hey @nreimers - I also trained it on our brand new german electra model `german-nlp-group/electra-base-german-uncased` (1) but have relativly bad results compared to other german models. But we showed that our new electra model is better on downstream tasks (germeval18 and 17).

What might be the reason? Do you have a theory?

(1) through a bug it does not show up on HF yet - see here https://github.com/huggingface/transformers/issues/6495

**Comment by PhilipMay** [comment]
> 
> 
> @omerarshad Run it on NLI, but sadly did not yield convincing results (about 5-10 points worse than BERT if I remember correctly).

Concerning this I opened a new issue: #362
