### ISSUE TITLE
sentence similarity question

### ISSUE THREAD

**Issue by sersoage** [UKPLab/sentence-transformers#194]
Hi, thanks again for the time, I was wondering if you could help me with something, can you think of a way of getting evidence based similarity. That is imagine you have a query that you want to match against a corpus, and in that corpus (for the sake of simplicity) lets assume only two entries score higher. Can you think of a way of matching which part of the query had higher similarity with one entry of the corpus and which other part of the query had higher similarity with the other? Like I said before as a way of providing evidence for the similarity...
Any thoughts would we appreciated 
Best

**Comment by nreimers** [comment]
Hi @sersoage 
Sounds like semantic search:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/application_semantic_search.py

You compute the cosine similarity between the query and all entries in the corpus. Than you take the samples with the highest score.

If your corpus is large (>100k entries), you would need an index server like faiss, which can index your vectors and where you can perform an efficient search.

Best
Nils Reimers

**Comment by sersoage** [comment]
Yes that is correct that is what I am doing, what I meant is doing that similarity search but being able to match which parts of the query have more similarity with different entries in the corpus.
for example if the query is: "Hi how are you I would like to ask you a question regarding Covid"
and imagine that the following are the highest scoring entries in the corpus:
- "Hello how are you"
- "I have a question about covid19"
What I am asking is if you think there is a way to be able to match that the first part of the query matches with the first entry in the corpus and the last with the second. 
Hope it makes sense now.

**Comment by nreimers** [comment]
Hi @sersoage 
This is not trivial, as a sentence can be composed of an arbitrary number of subordinate clauses. I would first try to decompose the input sentence to sub clauses. Sadly I don't know what works best there, but maybe there is already some work on that.

If you have the two subclauses ("Hi how are you" and "I would like to ask you a question regarding Covid") you could run the semantic search for each subclause and find the most matching entries for them.

Best
Nils Reimers

**Comment by sersoage** [comment]
Correct that is how i was attempting to do it, but since this is a transformer architecture perhaps you had thought of a way of using somehow the attention heads..... thanks!!

**Comment by sersoage** [comment]
Great insights as always
