### ISSUE TITLE
Two berts in siamese

### ISSUE THREAD

**Issue by amobash2** [UKPLab/sentence-transformers#199]
Hi,
Thanks for the great work, I am trying to understand the code, and while in paper is refered to two bert networks that have tied weights, but the code has only a call to a single bert model and then a pooling model in e.g. training_nli_bert.py. So by tied weights does this mean we only train a single bert in the architecture and both sentence a and sentence b go through same, or am I understanding incorrectly?
Thanks for your help.

**Comment by nreimers** [comment]
Only one Bert is used. This is the usual way how models with tight weights are implemented, that you only have one instance of that part in your system.

**Comment by amobash2** [comment]
@nreimers thank you very much for prompt response and confirming :)
