### ISSUE TITLE
Batch embedding

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [UKPLab/sentence-transformers#201]
Dear all,

first of all, thank you for the amazing library! Is there a way to call `.encode` with a batch of sentences?

Best Regards,

Francesco Saverio Zuppichini

**Comment by nreimers** [comment]
Hi,
You can pass a list of sentences to encode. The function then performs batching. The size of the batch can be controlled via the parameter passed to that method.

**Comment by FrancescoSaverioZuppichini** [comment]
Thank you. I feel so stupid :)

**Comment by nathan-chappell** [comment]
Excited to be using your guys' library.  Please close issues that you successfuly resolve :)
