### ISSUE TITLE
The maximum length of XLMRoBERTa

### ISSUE THREAD

**Issue by andyweizhao** [UKPLab/sentence-transformers#207]
Hi Nils,

I got an error when the input texts are larger than 512. The problem is solved after I modified L.65 in XLMRoBERTa.py to "pad_seq_length = min(pad_seq_length, self.max_seq_length) + 2".

**Comment by nreimers** [comment]
Hi @andyweizhao 
Thanks for pointing this out. I updated the code and it will be in the next release.
