### ISSUE TITLE
If it's true in your application

### ISSUE THREAD

**Issue by chaochaoSZ** [UKPLab/sentence-transformers#219]
Hi, I just found an interesting thing in your Application code.

distances = scipy.spatial.distance.cdist([query_embedding], corpus_embeddings, "cosine")[0]
results = zip(range(len(distances)), distances)
results = sorted(results, key=lambda x: x[1])

you can see the cosine score is ascending order, but cosine score the bigger the better. Don't know if I am right.

Thank you.

**Comment by nreimers** [comment]
Hi,
The cdist method computes cosine distance, which is cosine-distance=1 - cosine-similarity.

Examples with a low cosine distance have therefore a high cosine similarity. 

Best 
Nils Reimers

**Comment by chaochaoSZ** [comment]
get it. Thanks, sir.
