### ISSUE TITLE
Model `device` differs from `_target_device`

### ISSUE THREAD

**Issue by samuliasmala** [UKPLab/sentence-transformers#2220]
According to [the documentation](https://www.sbert.net/docs/package_reference/SentenceTransformer.html#sentence_transformers.SentenceTransformer.device) the `model.device` should 

> Get torch.device from module, assuming that the whole module has one device.

I have one cuda device which is working fine, but the `model.device` is still always indicating I'm using `cpu`. However, the `model._target_device` is correctly showing `cuda`.

What is the difference between `model.device` and `model._target_device` and why `model.device` is showing `cpu` even though GPU is used?

Here is a short script showing the difference:

```python
from sentence_transformers import SentenceTransformer
from torch import cuda

model = SentenceTransformer("all-MiniLM-L6-v2", device="cuda")
print("model.device:", model.device)
print("model._target_device:", model._target_device)
print("cuda.is_available():", cuda.is_available())
print("torch.cuda.device_count():", cuda.device_count())

# Output
# model.device: cpu
# model._target_device: cuda
# cuda.is_available(): True
# torch.cuda.device_count(): 1
```

Version information:
WSL2 / Windows 10
Ubuntu 22.04.2 LTS
Python 3.10.6
sentence-transformers    2.2.2

**Comment by nreimers** [comment]
Model is moved to device only when you call encode for the first time
