### ISSUE TITLE
Possible token limit inconsistencies?

### ISSUE THREAD

**Issue by JensMadsen** [UKPLab/sentence-transformers#2227]
I want to use sentence transformers for vector-based search (like everyone else :-)). If I have an input text I would like to split the text into chunks that fit the token limit of the model that I want to use. Therefore I: 1) encode the input text, 2) split tokens into chunks that correspond to the model token limit, e.g. if the model token limit is 100 and the input text has 150 tokens I split into two chunks of size 100 and 50 tokens, respectively. 

As an example lets consider the paraphrase-albert-small-v2 model. According to the [documentation](https://www.sbert.net/docs/pretrained_models.html#model-overview) the token limit is 256. But the code below returns different results

``` python
from sentence_transformers import SentenceTransformer  # type: ignore
from transformers import AutoTokenizer


model = SentenceTransformer('sentence-transformers/paraphrase-albert-small-v2')
print(model.get_max_seq_length)  # prints 100 but documentation https://www.sbert.net/docs/pretrained_models.html#model-overview says 256
print(model.tokenizer.model_max_length) # prints 512
breakpoint()
tokenizer = AutoTokenizer.from_pretrained('sentence-transformers/paraphrase-albert-small-v2')

print(tokenizer.model_max_length)  # This one returns 512 as well
```

The reason why this is important is that  we must know the correct chunk size for a given model in order to calculate sentence embedding correctly and efficiently.

**Comment by carlesoctav** [comment]
While in theory, the model can use 512 tokens as an input (as specified by tokenizer.model_max_length), the model you are using has been trained with a maximum of 100 tokens. With this information, we can assume that the model does its best to encode sentences within the 100-token limit, as that is how it was trained. Consequently, it may not perform as effectively with longer texts or more tokens.

**Comment by tomaarsen** [comment]
That's indeed a very good description of what's happening here, @carlesoctav 

It is recommended to follow the `max_seq_length` as set in the model configurations (e.g. in [`sentence_bert_config.json`](https://huggingface.co/intfloat/multilingual-e5-large/blob/main/sentence_bert_config.json#L2)), as this is the maximum sequence length adopted during training, i.e. the one that the model will work best for.

Hope this helps. I'll close this for now.

- Tom Aarsen

**Comment by JensMadsen** [comment]
Thank you @carlesoctav. Still there is a discrepancy between `m̀ax_seq_length` and the documentation (100 and 256, respectively for paraphrase-albert-small-v2).

**Comment by tomaarsen** [comment]
You're very right. Now I'm not quite sure which is the correct value. Hmm.
