### ISSUE TITLE
Issue : Load model from local path in Senetnce Transformers

### ISSUE THREAD

**Issue by eshaanagarwal** [UKPLab/sentence-transformers#2239]
I wish to know where the model gets saved when it is loaded for the first time. My main intention is that i want to download the model before hand so that we dont have to go through the process of downloading it the first time the first time i run it. This would help me from users perpspective.

**Comment by liguoqinjim** [comment]
default download path:`/Users/xxx/.cache/torch/`.
I'm on a MAC.

**Comment by firasm** [comment]
For anyone reading this, the default path has changed. [See this comment](https://github.com/UKPLab/sentence-transformers/issues/2523#issuecomment-1976094534)

**Comment by tomaarsen** [comment]
@firasm is right, thanks for sharing. You should only have to fully download the model once and it'll be cached in that location.
I'll close this issue now.

- Tom Aarsen
