### ISSUE TITLE
Selecting layer with BERT model

### ISSUE THREAD

**Issue by Thomzoy** [UKPLab/sentence-transformers#225]
Hello !

First of all thank you for all the effort put into this package, it's truly great !
I'm currently using the pretrained SBERT model with mean-pooling. I was wondering if it was possible to choose which layer in the BERT model is used as the embedding ?

Thanks a lot !

**Comment by Thomzoy** [comment]
I just found that you recently added a WeightedLayerPooling method which will do the trick, perfect !

**Comment by nreimers** [comment]
Yes, you can pass a weight parameter if you want to select specific layers. You can also choose a combination of them.

If weight=None, then an average of the layers 4-12 will be used. This average will be learned while training.

**Comment by thak123** [comment]
How do we specify the weight ? Is it a list ?
