### ISSUE TITLE
The need to trust_remote_code attribute in SentenceTransformer model loading.

### ISSUE THREAD

**Issue by Alkahwaji** [UKPLab/sentence-transformers#2272]
I want to load the model from Huggingface models but I received a problem with remote code trust and I received this error. Is there a method to add trust_remote_code in SentenceTransformer?? 

![image](https://github.com/UKPLab/sentence-transformers/assets/23569519/1f9fb763-f47f-4329-bbf1-d151d458fedb)

**Comment by toniopelo** [comment]
This seems to be implemented in a later release, I think this issue could be closed.
See [this PR](https://github.com/UKPLab/sentence-transformers/pull/2398), that was [released in v2.3.0](https://github.com/UKPLab/sentence-transformers/releases/tag/v2.3.0)
You might want to test it before closing the issue though, I didn't

**Comment by tomaarsen** [comment]
@toniopelo you're very right!  `trust_remote_code` can now be used with Sentence Transformers. I think this can indeed be closed - thanks for the help.

- Tom Aarsen
