### ISSUE TITLE
`tqdm` dependency breaks certain applications

### ISSUE THREAD

**Issue by freckletonj** [UKPLab/sentence-transformers#2275]
`tqdm` is a nice progress bar to have for toy applications, but should not be a default feature.

I recently built an LSP integration for VSCode and had a heck of  time debugging that the issue was ultimately this:

In one thread, SentenceTransformers encodes a str. This causes `tqdm` to output a message to `stderr`. VSCode interprets an output to `stderr` as an error, and blows up the whole application (and then gobbles up the logs to make sure you can't debug).

If `tqdm` must remain, I recommend an argument `verbose=False` that defaults to False, and if `True` will then use `tqdm` as it does now.

Thanks for this lib by the way, love it!

**Comment by nreimers** [comment]
You can set show_progess_bar=False when calling encode

**Comment by freckletonj** [comment]
Ah nice, thank you!
