### ISSUE TITLE
Pooling-layer in pre-trained SentenceTransformer has no parameters

### ISSUE THREAD

**Issue by Jakobhenningjensen** [UKPLab/sentence-transformers#2292]
When I use the following model
https://huggingface.co/sentence-transformers/paraphrase-multilingual-mpnet-base-v2/tree/main, the `SentenceTransformer` creates the same output as the internal RoBERTa model

```python
model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')
model.to("cpu")
transformer_model = model._modules["0"]

a = ["hello world"]
tokens = model.tokenize(a)

transformer_output = transformer_model(tokens)
sentence_embedder_ouput= model.forward(tokens)
print(np.allclose(transformer_output .detatch(), sentence_embedder_ouput.detatch()) # True

pool = model._modules["1"]
list(pool.parameters())# []
```
Is that expected behaviour? I've understood SBERT as BERT+pooling thus I find it strange that the pooling is empty.

**Comment by tomaarsen** [comment]
Hello!

This is indeed correct - Pooling is not _learned_, it's always the same procedure depending on the pooling strategy, e.g. only grabbing the first token. With other words, pooling has no learnable parameters, and so the list of parameters is empty. I hope that clarifies it somewhat.

I'll close this for now, as I think this should be resolved now, but you're free to ask follow-up questions.

- Tom Aarsen
