### ISSUE TITLE
Does `sentence-transformers` prefer `safetensors` when available?

### ISSUE THREAD

**Issue by steve-marmalade** [UKPLab/sentence-transformers#2293]
I have recently started seeing pretrained models on the huggingface hub in [model.safetensors](https://huggingface.co/docs/safetensors/index) files in addition to the (less secure) pickled `pytorch_model.bin`. The transformers [PreTrainedModel.from_pretrained](https://huggingface.co/docs/transformers/v4.32.1/en/main_classes/model#transformers.PreTrainedModel.from_pretrained) has a `use_safetensors` argument that controls whether these files should be used.

Does `sentence-transformers` have something equivalent and/or default to using them where available?

**Comment by tomaarsen** [comment]
Hello!

Yes, `model.safetensors` files are automatically prioritized over `pytorch_model.bin`. However, currently the full HF Hub repository is downloaded, often resulting in a download for both `model.safetensors` *and* `pytorch_model.bin`, but #2345 will resolve this inefficiency.

- Tom Aarsen

**Comment by steve-marmalade** [comment]
Thanks, @tomaarsen !
