### ISSUE TITLE
Model args not passed through when loading weights

### ISSUE THREAD

**Issue by riklopfer** [UKPLab/sentence-transformers#2299]
Fixed and merged last year: https://github.com/UKPLab/sentence-transformers/commit/8fb8e1510f433d084e9cbddd065a91889d083f4f

All good on main: https://github.com/UKPLab/sentence-transformers/blob/a458ce79c40fef93d5ecc66931b446ea65fdd017/sentence_transformers/models/Transformer.py#L44

Change does not appear on latest tag (v2.2.2): https://github.com/UKPLab/sentence-transformers/blob/f38e91e1e505fb338f03ad80a2f2b473569c7591/sentence_transformers/models/Transformer.py#L44

**Comment by tomaarsen** [comment]
Hello!

This will be included in the upcoming v2.3.0 release. I'd like to get this release out as soon as possible, I'm just waiting for a small blocker to get resolved.

- Tom Aarsen
