### ISSUE TITLE
[Question] are multi-qa models suitable for Asymmetric Semantic Search ?

### ISSUE THREAD

**Issue by yoch** [UKPLab/sentence-transformers#2304]
This section suggests that best models for Asymmetric Semantic Search are MS MARCO Models.

https://github.com/UKPLab/sentence-transformers/blob/a458ce79c40fef93d5ecc66931b446ea65fdd017/examples/applications/semantic-search/README.md?plain=1#L24

But this refers to an [old page](https://www.sbert.net/docs/pretrained-models/msmarco-v3.html) for these models, the [latest one](https://www.sbert.net/docs/pretrained-models/msmarco-v5.html) compares **msmarco**  models to **multi-qa**, so I'm not sure if they can be used interchangeably for Asymmetric Semantic Search.

**Comment by tomaarsen** [comment]
Hello!

Based on the MS MARCO and Multi-QA datasets, both types of models should work well for asymmetric semantic search.

- Tom Aarsen
