### ISSUE TITLE
Availability of models on the Hugging Face Hub

### ISSUE THREAD

**Issue by tea-de-kay** [UKPLab/sentence-transformers#2306]
Hello,

I noticed, that the only multilingual cross encoder (https://huggingface.co/cross-encoder/mmarco-mMiniLMv2-L12-H384-v1) was recently removed from the hub. Any idea, why this happened?
I found a substitute on Nils Reimers space (https://huggingface.co/nreimers/mmarco-mMiniLMv2-L12-H384-v1), but I wonder how much I can rely on your models being available.

Best regards!

**Comment by tomaarsen** [comment]
Hello!

I'm not sure why that model was removed; perhaps Nils thought the performance was not sufficiently good. However, going forward I don't intend for any existing model to be removed/stop working. You can rely on that.

- Tom Aarsen
