### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by jiguangxi** [UKPLab/sentence-transformers#231]
Hi, I want to know. 
If we have trained the model and used it to load n sentences (Corpus). Given a new sentence, what is the complexity of using the pattern to find the most similar one in the corpus?
Note, this is a new sentence.

**Comment by nreimers** [comment]
You have a fixed runtime to compute the Embedding for the new sentence.

Finding the most similar sentence can also be efficiently implemented. If you use faiss, than you retrieve it in a few ms even for really large corpora

**Comment by jiguangxi** [comment]
Okay, thank you very much.
Best wishes to you.
