### ISSUE TITLE
embedding mismatch

### ISSUE THREAD

**Issue by riyajatar93** [UKPLab/sentence-transformers#2311]
https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/computing-embeddings/README.md

I am trying to use hugging face sentence transformer to generate sentence-embedding instead of sentence-transformers.

but i am not getting same output with these methods.

am i making any mistake.

**Comment by carlesoctav** [comment]
If you're exclusively using transformers, there are certain post-processing steps, such as mean pooling or cls pooling, and possibly normalization, that you need to include. I suggest checking the repository for details on the required post-processing steps:
https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

**Comment by riyajatar93** [comment]
thanks .
its working as expected now.

**Comment by tomaarsen** [comment]
Thanks for the help. I think this has been answered now.
