### ISSUE TITLE
CrossEncoder Module cannot load a local model based on the model path it needs huggingface repo model string

### ISSUE THREAD

**Issue by bhavishpahwa** [UKPLab/sentence-transformers#2325]
By default the CrossEncoder class's designed to load a model using HuggingFace repo model string but the underlying helpers that it uses like AutoConfig.from_pretrained(), AutoModelForSequenceClassification.from_pretrained() and AutoTokenizer.from_pretrained() all have the functionality to pass both model string as well as os.PathLike object. Can raise a PR to change the typing and the control for loading local model.

**Comment by tomaarsen** [comment]
Hello!

Is the only problem here the typing of the CrossEncoder `model_name` parameter? Because you should just be able to pass a path to a local model as well as a Hugging Face Hub model identifier.

- Tom Aarsen

**Comment by bhavishpahwa** [comment]
Yup the only problem is typing as the linter won't allow that.

**Comment by tomaarsen** [comment]
I think `str` should be fine, as the expectation is to either pass a string model ID (e.g. `"sentence-transformers/all-MiniLM-L6-v2"`) or a string path (e.g. "models/checkpoints/my_model"). That said, I'll mention that the model_name can also be a string path in the docstring in #2347.

- Tom Aarsen
