### ISSUE TITLE
About TED2020

### ISSUE THREAD

**Issue by SantiDianaClibrain** [UKPLab/sentence-transformers#2327]
Hi. Is TED2020 no longer publicly available? I cannot find the neither the corresponding README.md file nor the data itself. 

Thanks in advance!

**Comment by SantiDianaClibrain** [comment]
Lots of parts of `/sentence-transformers/examples/training/multilingual` are deprecated and do not work. TED2020 is no longer available, `get_parallel_data.py` does not work for any dataset. Could you please explain if there is any problem with the methodology? I was trying to distill a multilingual model but I cannot reproduce the original paper's experiments.

**Comment by tomaarsen** [comment]
Hello!

Indeed, it looks like the TED2020 dataset was removed from this repository in a prior commit, I'm afraid. I'm not quite sure about the reasoning.

- Tom Aarsen

**Comment by tomaarsen** [comment]
Hello!

I'm afraid this dataset has been removed. However, we do support a parallel sentences dataset that can be used to make a model multilingual. See #2243 for example.

- Tom Aarsen
