### ISSUE TITLE
How to make prediction in NLI

### ISSUE THREAD

**Issue by trthminh** [UKPLab/sentence-transformers#2330]
I can't make prediction in NLI task when run based file training_NLI. Can you help me?

**Comment by aflip** [comment]
Please give more details.  here's a guide for better bug reports https://gist.github.com/automationhacks/87b62440faf36d98ebbb732c372dd7c3

**Comment by tomaarsen** [comment]
Hello!

Are you using this [training_nli.py](https://github.com/UKPLab/sentence-transformers/blob/c006921e9e9977bc107b05676266b581091688a2/examples/training/cross-encoder/training_nli.py)?

If so, you can make predictions on the trained model by adding:
```py
outputs = model.predict([["Dave wasn't paying attention", "Dave tripped"], ["John spoke poorly of the test", "John loved the exam"]])
```
Then, outputs may look something like:
```python
array([[-0.11257678, -0.76858264,  0.8534712 ],
       [ 1.2303571 , -1.8494376 ,  1.0168376 ]], dtype=float32)
```
In the example, index 0 means contradiction, index 1 is entailment and 2 is neutral. So, the first sample (`["Dave wasn't paying attention", "Dave tripped"]`) is most likely neutral. The second sample (`["John spoke poorly of the test", "John loved the exam"]`) is most likely a contradiction.

(Note: I did only train this test model for 5 minutes)

- Tom Aarsen
