### ISSUE TITLE
How sentence transformers calculating the embeddings of the domain specific words?

### ISSUE THREAD

**Issue by pradeepdev-1995** [UKPLab/sentence-transformers#2334]
How sentence transformers calculating the embeddings of the domain specific words?

**Comment by akshaydevml** [comment]
Like any transformer based embedding models, Sentence Transformers uses the data it was trained on to generate embeddings, since they are mostly trained on public datasets, you might see a dip in the encoding quality for domain specific jargon.

**Comment by tomaarsen** [comment]
Indeed. There is some work done on domain adaptation for embedding models: https://sbert.net/examples/domain_adaptation/README.html
However, I theorize that most users simply stick with the pretrained "general" embedding models.

I'll close this for now, as I think the main question has been answered by @akshaydevml. 

- Tom Aarsen
