### ISSUE TITLE
How to get individual token embeddings of a sentence from sentence transformers

### ISSUE THREAD

**Issue by pradeepdev-1995** [UKPLab/sentence-transformers#2335]
How to get individual token embeddings of a sentence from sentence transformers

**Comment by tomaarsen** [comment]
Hello!

You can use the [`output_value`](https://www.sbert.net/docs/package_reference/SentenceTransformer.html#sentence_transformers.SentenceTransformer.encode) argument, e.g.:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-mpnet-base-v2")
token_embeddings = model.encode("This is a test sentence", output_value="token_embeddings")
print(token_embeddings.shape)
# -> torch.Size([7, 768])
```

- Tom Aarsen

**Comment by pradeepdev-1995** [comment]
@tomaarsen  Thank you
