### ISSUE TITLE
Official procedure for adding new trained models

### ISSUE THREAD

**Issue by saskiabosma** [UKPLab/sentence-transformers#2336]
I use a pretrained CLIP [model](https://huggingface.co/patrickjohncyh/fashion-clip/tree/main) (base architecture is [CLIP-ViT-B-32 model](https://huggingface.co/laion/CLIP-ViT-B-32-laion2B-s34B-b79K)) that wasn't fine-tuned using the sentence-transformers library. It looks like it is possible to integrate it by adding files `modules.json` and `config_sentence_transformers.json` copied from `sentence-transformers/clip-ViT-B-32` in my model artifacts directory, and setting the correct `path`  in `module.json`.

Could you please confirm that this procedure is correct ? If so, it might be worth to add it to the docs, as other users may have similar needs !

**Comment by saskiabosma** [comment]
Thanks a lot ! (cc @vinid)

**Comment by saskiabosma** [comment]
@tomaarsen, what do you think of adding a few lines to the docs (specifically [hugging_face.md](https://github.com/UKPLab/sentence-transformers/blob/master/docs/hugging_face.md)) to guide users who want to use private local models ? Can I do a MR ?

**Comment by tomaarsen** [comment]
Feel free! I'll be glad to review it.

- Tom Aarsen
