### ISSUE TITLE
InformationRetrievalEvaluator with non-sentence transformer modell

### ISSUE THREAD

**Issue by samothk** [UKPLab/sentence-transformers#2346]
Hello, 
is it possible to use an Evaluator , e.g. InformationRetrievalEvaluator with a pretrained huggingface model that is no sentence transformer model? 
I tried it with microsoft/mdeberta-v3-base:

instead of:
model = SentenceTransformer("microsoft/mdeberta-v3-base")
I used:
model= AutoModel.from_pretrained("microsoft/mdeberta-v3-base")
test_evaluator = evaluation.InformationRetrievalEvaluator(queries_test, corpus_test, relevant_docs_test)
 test_evaluator(model, output_path="..."])

but  get the error (in test_evaluator(model, output_path="..."])):
AttributeError: 'DebertaV2Model' object has no attribute 'encode'

**Comment by tomaarsen** [comment]
Hello!

No, it is not possible to use the SentenceTransformer evaluators on anything other than a `SentenceTransformer` instance. This is because they all use `model.encode`, which only exists on `SentenceTransformer` instances, and not on pure `transformer` models. 

That said, you can convert `microsoft/mdeberta-v3-base` into a SentenceTransformer with `model = SentenceTransformer("microsoft/mdeberta-v3-base")` and use that with the evaluator, if you wish.

- Tom Aarsen

**Comment by tomaarsen** [comment]
That seems very plausible. I'm not very sure how mdeberta-v3 is normally used for information retrieval, but indeed - if the model was not trained with a mean pooling, then mean pooling to convert from token embeddings to sentence embeddings might not result in very useful embeddings.

**Comment by samothk** [comment]
Hello Tom, 
actually I wanted to evaluate anD compare the Jina Embeddings 2 models with SBERT-models. Is there something similar than InformationRetrievalEvaluator to compare them on the sentence pairs of my corpus or is it better to write my own custom InformationRetrievalEvaluator that can handle also non-SBERT sentence models?

**Comment by tomaarsen** [comment]
To my knowledge, the Jina Embedding 2 models are fully compatible with SentenceTransformers:
```py

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("jinaai/jina-embeddings-v2-base-en")
print(model)
# SentenceTransformer(
#   (0): Transformer({'max_seq_length': 8192, 'do_lower_case': False}) with Transformer model: JinaBertModel 
#   (1): Pooling({'word_embedding_dimension': 512, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False})
# )

embeddings = model.encode(["How are you doing?", "I'm quite well, thank you."])
print(embeddings.shape)
# (2, 768)
```

So you should just be able to use the default evaluator options!

- Tom Aarsen

**Comment by samothk** [comment]
Hello Tom, thanks quick reply. 
when I try, I get this:
E     model = SentenceTransformer(language_model["path"])
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
E     modules = self._load_sbert_model(model_path)
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
E     module = module_class.load(os.path.join(model_path, module_config['path']))
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 137, in load
E     return Transformer(model_name_or_path=input_path, **config)
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 29, in __init__
E     self._load_model(model_name_or_path, config, cache_dir)
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py", line 49, in _load_model
E     self.auto_model = AutoModel.from_pretrained(model_name_or_path, config=config, cache_dir=cache_dir)
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 544, in from_pretrained
E     trust_remote_code = resolve_trust_remote_code(
E   File "/home/thomasku/venv_NLP/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 610, in resolve_trust_remote_code
E     raise ValueError(
E ValueError: The repository for /home/thomasku/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/ contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/thomasku/.cache/torch/sentence_transformers/jinaai_jina-embeddings-v2-base-en/.
E Please pass the argument `trust_remote_code=True` to allow custom code to be run.

**Comment by tomaarsen** [comment]
Oh, you are very correct. The fix has been applied on the main branch of `sentence-transformers`, but it hasn't been released yet. I'd like to get a release out as soon as I can.

Until then, you can download `sentence-transformers` from the repository directly to counteract this problem:
```
pip install git+https://github.com/UKPLab/sentence-transformers
```

- Tom Aarsen

**Comment by tomaarsen** [comment]
That one is indeed not compatible. However, someone has done some experiments with `text-embedding-ada-002` on MTEB. See the Retrieval tab there: https://huggingface.co/spaces/mteb/leaderboard

`text-embedding-ada-002` places 21st, `jina-embeddings-v2-base-en` 29th. The strong BGE models claim 3rd, 5th and 8th, they might be worthwhile.
