### ISSUE TITLE
How to Finetune a Clip Model with Custom Data 

### ISSUE THREAD

**Issue by unmo** [UKPLab/sentence-transformers#2355]
I want to do my custom data training to get high accuracy embeddings of my image data.

Are there any scripts or documentation that would be helpful?

thank you.

**Comment by tomaarsen** [comment]
Hello! 

To my knowledge, no tutorials, scripts or documentation exist for it right now, though Nils Reimers who authored the CLIP model  class in Sentence Transformers said that it worked similarly to finetuning any other Sentence Transformer model. Perhaps the snippet from #1573 will be useful for you to get started.

- Tom Aarsen

**Comment by unmo** [comment]
Thank you!
Tried it and it appears to have worked.

**Comment by tomaarsen** [comment]
If you're interested, I would happily welcome a PR with a simple example of how to finetune a CLIP model in the `examples` folder.

Don't feel pressured though, you don't have to :)

- Tom Aarsen

**Comment by unmo** [comment]
My scritp is .ipynb not .py. Is it OK?

**Comment by tomaarsen** [comment]
That's okay! I can convert the file to a .py and modify it to make for a good example :)

**Comment by unmo** [comment]
I made pull req (https://github.com/UKPLab/sentence-transformers/pull/2390).
Thank you.
