### ISSUE TITLE
Degrading retrieval performance with fine-tuning embedding model

### ISSUE THREAD

**Issue by mapa17** [UKPLab/sentence-transformers#2358]
Hi,

I am trying to improve my retrieval system by performing a fine-tuning of the `thenlper/gte-base` with a retrieval training dataset of 25k examples and `MultipleNegativeRanking` (MNR) Loss.

Unfortunately, doing so seems to degrade the performance of the embedding model.
I evaluate the model using an `InformationRetrievalEvaluator` based evaluator and the end-to-end performance of the retrieval.
Borth evaluations show a strong decline in accuracy/retrieval.

Following instructions like [pincone docs](https://www.pinecone.io/learn/series/nlp/fine-tune-sentence-transformers-mnr/) using the "standard" `SentenceTransformer.fit()` method.

```python
  
    # Load basemodel
    model = SentenceTransformer("thenlper/gte-base")

   # Load training data
    train_dataloader = DataLoader(training_data, batch_size=batch_size)

    # Load InformationRetrievalEvaluator
    evaluator = DataLoader.create_evaluator(evaluation_data)

    # MNR loss
    train_loss = losses.MultipleNegativesRankingLoss(model)

    model.evaluate(evaluator, output_path=model_save_path+"/before-training-eval/")

    # Train the model
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        evaluator=evaluator,
        epochs=epochs,
        warmup_steps=1000,
        optimizer_class=torch.optim.AdamW,
        optimizer_params={ 'lr': 0.00002 },
        output_path=model_save_path,
        save_best_model=True,        
        use_amp=True,  # Set to True, if your GPU supports FP16 operations
        callback=lambda score, epoch, steps: print(f"eval score: {score}, epoch: {epoch}"),
    )
```

I have checked the data loading to be creating pairs of (anchor, positive-example) sets, but I am unsure on what to do next.

I am thinking about looking into the following points:
- The training data is bad → Train on a subset that is manually inspected
- The data loading fails → Load a hand crafted mini test dataset
- The hyper parameters are wrong → Vary LR, Warmup steps
- The base embedding model is not compatible → Try with another embedding model

Anyone has suggestions on what else to look for or how to debug the problem?

**Comment by mapa17** [comment]
Hi @tomaarsen thx for the critical remark. I checked and found that my batch aggregation "implementation" is fundamentally wrong. I am going to try to fix it, repeat the tests and get back with results.

**Comment by tomaarsen** [comment]
Glad I could help! I'll be curious to hear your results.

**Comment by mapa17** [comment]
So, many hours of testing later, I unfortunately have little positive things to share.
I performed hyper parameter search varying LR and the number of batches over which gradients are aggregated.

In my case with a RTX 3060 12GB fine-tuning `thenlper/gte-base` my top improvement is +2.5% MAPS@10 with `LR=3e-7` and 80 aggregated batches of size 16.

My recommendation for anyone having similar fine-tuning issues is exploring LR and BS. Probably increasing BS either directly (if VRAM permits) or perform batch aggregation

**Comment by shrijayan** [comment]
> Hi,
> 
> I am trying to improve my retrieval system by performing a fine-tuning of the `thenlper/gte-base` with a retrieval training dataset of 25k examples and `MultipleNegativeRanking` (MNR) Loss.
> 
> Unfortunately, doing so seems to degrade the performance of the embedding model. I evaluate the model using an `InformationRetrievalEvaluator` based evaluator and the end-to-end performance of the retrieval. Borth evaluations show a strong decline in accuracy/retrieval.
> 
> Following instructions like [pincone docs](https://www.pinecone.io/learn/series/nlp/fine-tune-sentence-transformers-mnr/) using the "standard" `SentenceTransformer.fit()` method.
> 
> ```python
>   
>     # Load basemodel
>     model = SentenceTransformer("thenlper/gte-base")
> 
>    # Load training data
>     train_dataloader = DataLoader(training_data, batch_size=batch_size)
> 
>     # Load InformationRetrievalEvaluator
>     evaluator = DataLoader.create_evaluator(evaluation_data)
> 
>     # MNR loss
>     train_loss = losses.MultipleNegativesRankingLoss(model)
> 
>     model.evaluate(evaluator, output_path=model_save_path+"/before-training-eval/")
> 
>     # Train the model
>     model.fit(
>         train_objectives=[(train_dataloader, train_loss)],
>         evaluator=evaluator,
>         epochs=epochs,
>         warmup_steps=1000,
>         optimizer_class=torch.optim.AdamW,
>         optimizer_params={ 'lr': 0.00002 },
>         output_path=model_save_path,
>         save_best_model=True,        
>         use_amp=True,  # Set to True, if your GPU supports FP16 operations
>         callback=lambda score, epoch, steps: print(f"eval score: {score}, epoch: {epoch}"),
>     )
> ```
> 
> I have checked the data loading to be creating pairs of (anchor, positive-example) sets, but I am unsure on what to do next.
> 
> I am thinking about looking into the following points:
> 
> * The training data is bad → Train on a subset that is manually inspected
> * The data loading fails → Load a hand crafted mini test dataset
> * The hyper parameters are wrong → Vary LR, Warmup steps
> * The base embedding model is not compatible → Try with another embedding model
> 
> Anyone has suggestions on what else to look for or how to debug the problem?

Same issue for me after fine-tuning the performance degrades, meanwhile trying to implement the code.
```
    evaluator = DataLoader.create_evaluator(evaluation_data)
AttributeError: type object 'DataLoader' has no attribute 'create_evaluator'
```
I need to solve this issue.
