### ISSUE TITLE
some advices

### ISSUE THREAD

**Issue by SaintLogos1234** [UKPLab/sentence-transformers#236]
I use training_stsbenchmark.py script to perform the STS task，There were no problems during the training， but during dev it was always an error to report out of memory, After careful debugging, I found that the problem appeared in EmbeddingSimilarityEvaluator, EmbeddingSimilarityEvaluator uses GPU:0 by default, but my number GPU:0 is already full. So I suggest you add a device attribute to the EmbeddingSimilarityEvaluator to adjust the GPU it uses

**Comment by nreimers** [comment]
Thanks for the hint.

What you can do is to run the code like this:
```
CUDA_VISIBLE_DEVICES=5 python run_code.py
```

CUDA_VISIBLE_DEVICES is an env. variable that controls which GPUs a script can see and use. In the above example, only GPU with ID 5 is available and can be used. All other GPUs are hidden.

Best
Nils Reimers
