### ISSUE TITLE
ST not using CUDA when provided as parameter, but only when the device is explicitly set to it

### ISSUE THREAD

**Issue by TijanaTL** [UKPLab/sentence-transformers#2391]
Env:  <br>
Win11, Pytorch 1.12.1, cuda 11.6, SentenceTransformers 2.2.2 <br>

Problem: I tried to set the model running on cuda with providing parameter:       
 model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2', device='cuda')
 <br>
 Then when printing the model, it prints 'cpu'. But when I set the cuda with model.to_device(torch.device('cuda')) it works fine, printing 'cuda'. 

 Is this some issue or just lazy initialization?

**Comment by tomaarsen** [comment]
Hello!

This is indeed lazy initialization, the model is moved to whatever device you have specified at the start of e.g. `fit` or `encode`. However, this will change in v2.3.0 (expected release is early January): the model will immediately be moved to the specified device at initialization. This matches the expected behavior more closely.

- Tom Aarsen

**Comment by bwanglzu** [comment]
@tomaarsen shall you create a lit of features/tickets/milestone for v2.3.0 release? i could contribute in my spare time :)

**Comment by dhdaines** [comment]
> Hello!
> 
> This is indeed lazy initialization, the model is moved to whatever device you have specified at the start of e.g. `fit` or `encode`. However, this will change in v2.3.0 (expected release is early January): the model will immediately be moved to the specified device at initialization. This matches the expected behavior more closely.
> 
> * Tom Aarsen

Thanks, this will also solve the problem where, if you want to load some pre-compted embeddings to the same device as the model, you have to first encode something (anything) so that `model.device` will return the correct value.

**Comment by tomaarsen** [comment]
> @tomaarsen shall you create a lit of features/tickets/milestone for v2.3.0 release? i could contribute in my spare time :)

Apologies, I already wrote the v2.3.0 release notes before my vacation! I had actually hoped to release before the new year, but I wouldn't have been able to update http://sbert.net.

**Comment by tomaarsen** [comment]
Hello!

The release has been published! You can now use 
```
pip install -U sentence-transformers
```
to install v2.3.0.

- Tom Aarsen
