### ISSUE TITLE
community_detection is taking infinite time.

### ISSUE THREAD

**Issue by AniketModi** [UKPLab/sentence-transformers#2393]
`while top_val_large[-1] > threshold:
            sort_max_size = min(2 * sort_max_size, len(embeddings))
            top_val_large, top_idx_large = cos_scores[i].topk(k=sort_max_size, largest=True)
`

Above loop is going infinite if all the values are greater than threshold. Can you pls include the maximum number of iterations in the loop ?

**Comment by tomaarsen** [comment]
Hello!

The efficiency of this has been heavily improved if you're using `cuda` and you're installing the bleeding edge version of `sentence-transformers`:
https://github.com/UKPLab/sentence-transformers/blob/5c838a705c24c2dfd151a71674c99d09d014c1a9/sentence_transformers/util.py#L376-L395

Install it with:
```
pip install -U git+https://github.com/UKPLab/sentence-transformers.git
```

Hope that helps the situation!

- Tom Aarsen

**Comment by tomaarsen** [comment]
This has now been integrated in Sentence Transformers v2.3:
![image](https://github.com/UKPLab/sentence-transformers/assets/37621491/2714a10c-52ee-4afa-8277-5a14914c790f)

- Tom Aarsen
