### ISSUE TITLE
is contextual semantic meaning not taken into account in the all-MiniLM-L6-v2 model?

### ISSUE THREAD

**Issue by fn-hide** [UKPLab/sentence-transformers#2408]
I tried the example of using the `all-MiniLM-L6-v2` model to find the similarity value. I modified the example code on `https://www.sbert.net/docs/usage/semantic_textual_similarity.html` to :
```
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('all-MiniLM-L6-v2')

# Two lists of sentences
sentences1 = [
    'The cat sits outside.',
    'The new movie is so bad.',
    'The latest film is fantastic.',
]

sentences2 = [
    'The dog plays in the garden.',
    'The new movie is so great.',
    'The new movie is so great.',
]

#Compute embedding for both lists
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
embeddings2 = model.encode(sentences2, convert_to_tensor=True)

#Compute cosine-similarities
cosine_scores = util.cos_sim(embeddings1, embeddings2)

#Output the pairs with their score
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[i], cosine_scores[i][i]))
```

I just modified the sentence so I could see the similarities between "The new movie is so bad." and "The new movie is so great."
But why is the result of similarity higher than "The new movie is so great." and "The latest film is fantastic."?
I thought this could be used to search for similar semantic meanings, but why are the results like this? Is there anything wrong with what I did?

**Comment by tomaarsen** [comment]
Hello!

Your code looks totally fine. I think your findings could be explained in a few ways:
1. The [`all-MiniLM-L6-v2`](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) model is small.
2. The two sentences ("... so bad", "... so great") can be argued to be semantically similar as they both describe ratings for movies, albeit with different sentiments.

It would be reasonable that the third pair ("The latest film is fantastic.", "The new movie is so great.") should be more semantically similar. Larger models agree that they are:

* [all-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2)
```py
The cat sits outside.            The dog plays in the garden.            Score: 0.1859
The new movie is so bad.                 The new movie is so great.              Score: 0.6920
The latest film is fantastic.            The new movie is so great.              Score: 0.7916
```

* [BAAI/bge-large-en-v1.5](https://huggingface.co/BAAI/bge-large-en-v1.5)
```python
The cat sits outside.            The dog plays in the garden.            Score: 0.5609
The new movie is so bad.                 The new movie is so great.              Score: 0.6988
The latest film is fantastic.            The new movie is so great.              Score: 0.8769
```

* [WhereIsAI/UAE-Large-V1](https://huggingface.co/WhereIsAI/UAE-Large-V1)
```py
The cat sits outside.            The dog plays in the garden.            Score: 0.4891
The new movie is so bad.                 The new movie is so great.              Score: 0.7396
The latest film is fantastic.            The new movie is so great.              Score: 0.8848
```

- Tom Aarsen

**Comment by fn-hide** [comment]
@tomaarsen  Wow, thank you for providing a detailed and reasonable explanation. I've only tried a small model, so I don't know the difference.
