### ISSUE TITLE
I can't use model_name_or_path as a filepath on disc, which loads the model from that path.

### ISSUE THREAD

**Issue by Sun0308** [UKPLab/sentence-transformers#2422]
my code:
from sentence_transformers import SentenceTransformer
model_name_or_path = '/mnt/data/Bert_Embedding/model/all-MiniLM-L6-v2'
model = SentenceTransformer(model_name_or_path)
error:
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/mnt/data/Bert_Embedding/model/all-MiniLM-L6-v2'. Use `repo_type` argument if needed.
I have download the all-MiniLM-L6-v2 from huggingface and set it on /mnt/data/Bert_Embedding/model/all-MiniLM-L6-v2.Can you help me?

**Comment by Sun0308** [comment]
my filepath is really true, but the error is still keep.l need your help.

**Comment by Sun0308** [comment]
I can use this way in local computer, but can't use it on ubuntu server.

**Comment by tomaarsen** [comment]
Hello!

I'll try to reproduce this in a minute. What version of `sentence-transformers` are you using?

- Tom Aarsen

**Comment by Sun0308** [comment]
> Hello!
> 
> I'll try to reproduce this in a minute. What version of `sentence-transformers` are you using?
> 
> * Tom Aarsen

Thank you for your reply. I made a small mistake and put the demo.py(put my code) file in the same path as the sentence_transformers file, so I could not import this package

**Comment by Sun0308** [comment]
I deleted the sentence_transformers folder under the projects folder and the problem was solved.

**Comment by tomaarsen** [comment]
Well done! That is indeed a tricky mistake. I'll close this :)

- Tom Aarsen
