### ISSUE TITLE
sentence-transformers-testing/stsb-bert-tiny-safetensors doesn't load

### ISSUE THREAD

**Issue by rossmessing** [UKPLab/sentence-transformers#2448]
On `sentence_transformers` 2.2.2, the following code:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers-testing/stsb-bert-tiny-safetensors")
```

Fails with
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rmessing/anaconda/envs/python39/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 95, in __init__
    modules = self._load_sbert_model(model_path)
  File "/Users/rmessing/anaconda/envs/python39/lib/python3.9/site-packages/sentence_transformers/SentenceTransformer.py", line 840, in _load_sbert_model
    module = module_class.load(os.path.join(model_path, module_config['path']))
  File "/Users/rmessing/anaconda/envs/python39/lib/python3.9/site-packages/sentence_transformers/models/Pooling.py", line 120, in load
    return Pooling(**config)
TypeError: __init__() got an unexpected keyword argument 'pooling_mode_weightedmean_tokens'
```

**Comment by tomaarsen** [comment]
Hello!

That model is only compatible with the `master` version of this repository at this time, and will be compatible with the yet-to-be released version 2.3.0. Feel free to install the `master` version and retry it!

```
pip install -U git+https://github.com/UKPLab/sentence-transformers.git
```
I hope to get the 2.3.0 release out soon.

Also, the model is not particularly good - it just exists to test whether a `safetensors` model can be loaded easily with Sentence Transformers v2.3.0.


- Tom Aarsen

**Comment by rossmessing** [comment]
@tomaarsen Thanks!  That's helpful context.  

I was hoping to use it as a super tiny model in a unit / integration test.  Any other super tiny models you'd recommend for the purpose?

**Comment by tomaarsen** [comment]
That's exactly what we use it for too 😄 
If you don't mind that the embeddings are useless, then you can just freshly initialize a Sentence Transformer model using a tiny transformers model:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("prajjwal1/bert-tiny")
```
I use this tiny model for various tests in three separate projects.

- Tom Aarsen

**Comment by tomaarsen** [comment]
Hello!

The v2.3.0 release is now out, so you should be able to pin that version and use the model as expected:
```python
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers-testing/stsb-bert-tiny-safetensors")
print(model.encode(["First do it", "then do it right", "then do it better"]).shape)
# (3, 128)
```

- Tom Aarsen
