### ISSUE TITLE
TypedStorage is deprecated

### ISSUE THREAD

**Issue by rizpras** [UKPLab/sentence-transformers#2450]
Hello,

While trying to save model to my local storage, I get this error:

`UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()`

What I get is that `TypedStorage` in torch library is deprecated. Is there any fix to address this issue?

Additional Note: The model is saved to local storage in a CI/CD stage, so I am looking for a method to fix this that does not involve opening the torch code and edit the code directly. It will be quite impractical to edit the code everytime the process is run.

Thank you

**Comment by tomaarsen** [comment]
Hello!

Could you perhaps provide a larger stack trace? And/or your `sentence_transformers` and `torch` versions?
That should help me reproduce this :)

- Tom Aarsen

**Comment by rizpras** [comment]
Here you are:

`/usr/local/lib/python3.11/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()`

That's the only stack trace I get, sorry if it's still not really detailed.

I use `sentence_transformers-2.2.2` and `torch-2.1.2`

**Comment by tomaarsen** [comment]
It looks like I can reproduce this if I set `transformers` to version 4.37.1, but I don't get this warning on 4.36.2.
Also, it seems like it is just a warning - the model still seems to get saved correctly. In fact, I get this warning when loading the model, not when saving it.

I think this might need to be raised in `transformers`. I'll make an issue there!

- Tom Aarsen

**Comment by rizpras** [comment]
Yes, it's just a warning and the model is still saved correctly. Curiously (this is rather unrelated), after the warning, the process is cut short in my CI/CD. Somehow the warning also prints the `return` statement, so I assume the warning stops everything.

Thanks for your suggestion, I'll try it!

**Comment by tomaarsen** [comment]
Feel free to let me know how it goes!

**Comment by rizpras** [comment]
After I use `transformer` 4.36.2, the warning disappear! But the process still stopped somehow... Anyway, I am sure now that it is not caused by the deprecation. Thanks for your help @tomaarsen! I will close the issue
