### ISSUE TITLE
model not downloading and downloaded model not loading

### ISSUE THREAD

**Issue by sumitmandal13** [UKPLab/sentence-transformers#2452]
OSError: Unable to load weights from pytorch checkpoint file for '/root/.cache/torch/sentence_transformers/sentence-transformers_all-mpnet-base-v2/pytorch_model.bin' at '/root/.cache/torch/sentence_transformers/sentence-transformers_all-mpnet-base-v2/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by tomaarsen** [comment]
Hello!

This sounds like the cache was perhaps a bit broken for you. I'm glad that incrementing your `transformers` version helped, but I would like to avoid the dependencies from getting too restrictive. To my knowledge, `transformers>=4.32.0` should work well, so I would like to keep it at that.

But if someone experiences the same issue as you, I'll be sure to tell them to upgrade their `transformers` like you've done.

- Tom Aarsen
