### ISSUE TITLE
Converting TFHub (Kaggle) model to Huggingface

### ISSUE THREAD

**Issue by jhyuklee** [UKPLab/sentence-transformers#2457]
Hi, I'd like to know how you converted the Tensorflow model gtr-base-1 to PyTorch as described in the README (https://huggingface.co/sentence-transformers/gtr-t5-base). We have a similar model in Kaggle and would like to know how you did it. Could you give us more detail on this? Thanks!

**Comment by jhyuklee** [comment]
FYI, I believe the original GTR is in the TF2 SavedModel format.

**Comment by tomaarsen** [comment]
Hello!

The gtr-t5-base repository contains this file: https://huggingface.co/sentence-transformers/gtr-t5-base/blob/main/convert-gtr.ipynb
Which seems to show how the model was converted. I hope this should answer your question, so I'll close this, but feel free to respond or reopen if you have extra questions.

- Tom Aarsen
