### ISSUE TITLE
Error in evaluation

### ISSUE THREAD

**Issue by unmo** [UKPLab/sentence-transformers#2461]
I am trying to use Evaluator as BinaryClassificationEvaluator when training CLIP on my own dataset.
However, I get the following error and cannot fit method.

* Error message
  * TypeError: unhashable type: 'PngImageFile'

* Train script
```
# train_dataloder
train_examples = []
for row in train_df.itertuples():    
    traindata = InputExample(
        texts=[Image.open(row.traindata1), Image.open(row.traindata2)],
        label=row.label,
    )
    train_examples.append(traindata)
train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=4)

# evaluator
imgs_1 = []
imgs_2 = []
labels = []
for row in val_df.itertuples():
    imgs_1.append(Image.open(row.traindata1))
    imgs_2.append(Image.open(row.traindata2))
    labels.append(row.label)

evaluator = evaluation.BinaryClassificationEvaluator(imgs_1, imgs_2, labels)    

# loss
train_loss = losses.ContrastiveLoss(model=model)

# train
model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=5,
    evaluator=evaluator,
    evaluation_steps=10,
    show_progress_bar=True)
```

Could you please help me what the problem is?
How should I define the evaluator when training image-to-image similarity?

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting this! This is indeed a bit of a bug in the BinaryClassificationEvaluator: it uses sets and dictionaries to avoid embedding duplicate things, but this requires hashing on the inputs. This isn't possible on the images, causing the crash that you've uncovered.

I've created a pull request to resolve this bug.

- Tom Aarsen

**Comment by unmo** [comment]
Hello Tom.

In this case, I used the BinaryClassificationEvaluator for this script, is there an Evaluator that you recommend for CLIP?

**Comment by tomaarsen** [comment]
Hello!

I personally enjoy using the `EmbeddingSimilarityEvaluator` - I see it used a lot in the examples a lot as well, although not exclusively for CLIP. 

- Tom Aarsen

**Comment by unmo** [comment]
I am using ContrastiveLoss for the loss function, but is it okay to use EmbeddingSimilarityEvaluator?
I couldn't find ContrastiveEvaluator.
