### ISSUE TITLE
Feat: Add Revision for CrossEncoder

### ISSUE THREAD

**Issue by michaelfeil** [UKPLab/sentence-transformers#2469]
I noticed that in https://github.com/UKPLab/sentence-transformers/pull/2419 there was a revision implemented! 
For CrossEncoder, there is no revision. The goal would be to implement revision in similar fashion.

Potentially could be a _starter issue_

**Comment by tomaarsen** [comment]
Indeed, revision must currently be specified via `automodel_args` & `tokenizer_args`, but I'm not a big fan of that. It seems preferable to align the signatures of the CrossEncoder and the SentenceTransformer as much as possible. I'd like to see the revision implemented in the CrossEncoder too.

- Tom Aarsen
