### ISSUE TITLE
Types for `score_functions`

### ISSUE THREAD

**Issue by kevinhu** [UKPLab/sentence-transformers#2501]
The types for `score_functions` are annotated as a `List[Callable[[Tensor, Tensor], Tensor]]`: https://github.com/UKPLab/sentence-transformers/blob/e0d93bb377eca9e0c94da436f3f35c336e9c109d/sentence_transformers/evaluation/InformationRetrievalEvaluator.py#L39-L42

However, the default value is not a list, but a dictionary:
```python
{ 
     "cos_sim": cos_sim, 
     "dot_score": dot_score, 
 }
 ```

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting - you're correct, that should be a Dict. I've merged the fix from @fkdosilovic.

- Tom Aarsen
