### ISSUE TITLE
Inconistent pooling mode options

### ISSUE THREAD

**Issue by david-waterworth** [UKPLab/sentence-transformers#2505]
The validation requires `pooling mode in ["mean", "max", "cls", "weightedmean", "lasttoken"]`

https://github.com/UKPLab/sentence-transformers/blob/e0d93bb377eca9e0c94da436f3f35c336e9c109d/sentence_transformers/models/Pooling.py#L52

This means `self.pooling_mode_weightedmean_tokens` cannot be set via `pooling_mode`

https://github.com/UKPLab/sentence-transformers/blob/e0d93bb377eca9e0c94da436f3f35c336e9c109d/sentence_transformers/models/Pooling.py#L63

**Comment by tomaarsen** [comment]
Hello!

> This means `self.pooling_mode_weightedmean_tokens` cannot be set via `pooling_mode`

I think you mean `pooling_mode_mean_sqrt_len_tokens`, and I think you're right. We need to add `mean_sqrt_len_tokens` to the pooling modes. Perhaps someone would like to pick this up in a PR, and otherwise I'll take care of it in a few days.

Thanks for reporting!

- Tom Aarsen

**Comment by kishore-s-15** [comment]
Hi @tomaarsen, Can I work on this?

**Comment by tomaarsen** [comment]
@kishore-s-15 I'm afraid that there's already an open pull request in #2507 which should solve this issue.

- Tom Aarsen

**Comment by david-waterworth** [comment]
Note also I forgot to mention the docstring also doesn’t mention all the possible values for pooling modes.

**Comment by tomaarsen** [comment]
Both should be fixed now @david-waterworth!
