### ISSUE TITLE
Redundant Vector Normalization in Agglomerative Clustering Example Despite Model Card Indicating Pre-normalized Vectors

### ISSUE THREAD

**Issue by archit15singh** [UKPLab/sentence-transformers#2519]
https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/clustering/agglomerative.py

The example normalizes the vector embeddings even though the model card says the vector is already being returned as normalized.

<img width="1092" alt="Screenshot 2024-03-01 at 4 30 49 AM" src="https://github.com/UKPLab/sentence-transformers/assets/131599737/90392982-68ca-4225-be96-fe49afde2ae0">
<img width="756" alt="Screenshot 2024-03-01 at 4 31 21 AM" src="https://github.com/UKPLab/sentence-transformers/assets/131599737/38ff964e-bd8e-4dd1-8a19-b3b7f25e8c04">

**Comment by tomaarsen** [comment]
Hello!

Well spotted. I've updated the example to remove the normalization by default (but left a comment that you might want to normalize if your model doesn't do it automatically already).

- Tom Aarsen

**Comment by archit15singh** [comment]
🚀
