### ISSUE TITLE
Huggingface inference API does not support "include_prompt" from pooling config

### ISSUE THREAD

**Issue by h4c5** [UKPLab/sentence-transformers#2527]
I uploaded a [sentence-transformer model](https://huggingface.co/h4c5/sts-camembert-base) on huggingface and the inference API was not working properly.

It seems the `"include_prompt": true` is not yet supported by huggingface so I deleted it from my `1_Pooling/config.json` configuration file and it was all fine.

Maybe there is something to do about it ?

**Comment by tomaarsen** [comment]
Hello!

Thanks for bringing this to my attention - I missed it when I updated Sentence Transformers recently. This should be resolved now (or as of the next deployment) due to https://github.com/huggingface/api-inference-community/pull/417. Thanks again!

- Tom Aarsen
