### ISSUE TITLE
Which pooling method to use?

### ISSUE THREAD

**Issue by Robert60CB** [UKPLab/sentence-transformers#253]
Firstly, this library has been a blessing. It got me started with deep learning despite being non technical - since last month I'm amazed by how much I've learned about NLP from simply playing around with it (from initialisation -> fine tuning).

As I get more ambitious... I would like to build a model with my own task specific sentence embeddings. I understand pooling is used to convert word, to sentence embeddings. 

However, to my understanding - mean/average pooling would be on the same vein of creating embeddings like Universal Sentence Encoder's DAN (Deep Averaging Network). 

I'm wondering how to do pooling similar to how USE Transformer does it? "By computing the element-wise sum of the representations at each word position.... then dividing by the square root of the length of the sentence so that the differences between short sentences are
not dominated by sentence length effects"

I'd love any high level direction for this... if the question is stupid, please don't hesitate to say so.

**Comment by Robert60CB** [comment]
I read the paper more carefully (as I do this more of  the vocabulary and paper makes sense) and realised element pair pooling led to poorer results in testing

**Comment by nreimers** [comment]
When you create a new model from scratch, you can specify the pooling layer such that it takes sentence length into account by setting: pooling_mode_mean_sqrt_len_tokens to rue
