### ISSUE TITLE
MiniLM L6 Multilingual Uncased Model

### ISSUE THREAD

**Issue by mossaab0** [UKPLab/sentence-transformers#2561]
Hi,

What can I do to get a MiniLM L6 multilingual uncased model?

1. If [make_multilingual.py](https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/multilingual/make_multilingual.py) is the way to go, what should I use as teacher and student models to make [all-MiniLM-L6-v2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) multilingual?

2. I'm aware of [paraphrase-multilingual-MiniLM-L12-v2](https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2). But, I'm interested in an uncased smaller model (L6).

3. From its name, I suspect [mMiniLMv2-L6-H384-distilled-from-XLMR-Large](https://huggingface.co/nreimers/mMiniLMv2-L6-H384-distilled-from-XLMR-Large) could work out of the box. But, I don't see much documentation around it. In particular, it isn't clear whether it's an uncased model.

**Comment by tomaarsen** [comment]
Hello!

First of all, https://huggingface.co/intfloat/multilingual-e5-small might be an interesting model for you (although it is cased!).

There are indeed a few approaches to create such a model. The most straight-forward one is to distil from a larger multilingual model into a model that matches your requirements. E.g. running [make_multilingual.py](https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/multilingual/make_multilingual.py). Some solid teacher models might be https://huggingface.co/intfloat/multilingual-e5-base, https://huggingface.co/intfloat/multilingual-e5-large, https://huggingface.co/BAAI/bge-m3. However, do note that the MiniLM tokenizer is specifically created for English, so it may not play well with multilingual text. 

This is kind of tricky, as there are not that many tokenizers that are both uncased and multilingual. The XLM-RoBERTa tokenizer seem to be cased, for example. You might have the best luck with a model that is based on the mBERT uncased tokenizer from this model: https://huggingface.co/google-bert/bert-base-multilingual-uncased
But then you want it to be 1) smaller and 2) trained for embeddings. You can make it smaller by adopting the same approach that was used for MiniLM L6, which is to only take every 2nd layer. Then you can tune it for embeddings by running `make_multilingual.py`, but it may not perform very well out of the box. 

A much simpler approach is to revisit whether you actually need the model to be uncased, as then you can use e.g. https://huggingface.co/intfloat/multilingual-e5-small or https://huggingface.co/nreimers/mMiniLMv2-L6-H384-distilled-from-XLMR-Large out of the box.

As for https://huggingface.co/nreimers/mMiniLMv2-L6-H384-distilled-from-XLMR-Large, I believe this is simply an exact copy of the model here: https://github.com/microsoft/unilm/tree/master/minilm (that page is an interesting read FYI)

- Tom Aarsen
