### ISSUE TITLE
How to improve sentence-transformers' performance on CPU?

### ISSUE THREAD

**Issue by chensuo2048** [UKPLab/sentence-transformers#2568]
On the CPU, I tried huggingface‘s optimization.onnx and sentence_transformers and I found that on the task of feature_extraction, optimization.onnx was not as good as sentence_transformers in batch encoding performance.
My question is, are sentence_transformers the current ceiling on CPU performance?

**Comment by chensuo2048** [comment]
Could anyone tell me is there any way to improve sentence-transformers' performance on CPU?

**Comment by tomaarsen** [comment]
Hello!

To my understanding, there is not yet a consensus of the best approach to speed up a model inference on CPU, but I think that the [Infinity](https://github.com/michaelfeil/infinity) project has some solid ideas. It might be worth using. There's some benchmarking resulte [here](http://michaelfeil.eu/infinity/latest/benchmarking/), showing e.g. a 2.5x speedup on CPU.

- Tom Aarsen

**Comment by chensuo2048** [comment]
> Hello!
> 
> To my understanding, there is not yet a consensus of the best approach to speed up a model inference on CPU, but I think that the [Infinity](https://github.com/michaelfeil/infinity) project has some solid ideas. It might be worth using. There's some benchmarking resulte [here](http://michaelfeil.eu/infinity/latest/benchmarking/), showing e.g. a 2.5x speedup on CPU.
> 
> * Tom Aarsen

I tried infinity and it is indeed faster than sentence_transformer, thank you very much!
