### ISSUE TITLE
Missing retrieve_rerank_simple_wikipedia.py

### ISSUE THREAD

**Issue by szetakyu** [UKPLab/sentence-transformers#2577]
This is a missing python script (Missing retrieve_rerank_simple_wikipedia.py) in
https://www.sbert.net/examples/applications/semantic-search/README.html#question-answer-retrieval while the colab version exists.

**Comment by tomaarsen** [comment]
Hello!

Thanks for reporting this. I've looked into it, and there is a jupyter notebook that was intended to be linked. I've created a PR to address it.

- Tom Aarsen
