### ISSUE TITLE
Support for CSTS?

### ISSUE THREAD

**Issue by ir2718** [UKPLab/sentence-transformers#2606]
Hi,

I know this is a very niche area, but are there any plans on supporting CSTS and related models/data utility functions in the future? 

For example, I'm interested in the tri-encoder and hypernetwork approaches taken from [here](https://arxiv.org/html/2403.09490v1).

![image](https://github.com/UKPLab/sentence-transformers/assets/94498051/12ac09a8-e87f-4e46-9449-4cfc7646f93a)

**Comment by tomaarsen** [comment]
Hello!

There's no plans for this right now. I think it might be a bit too niche, although I haven't heard about the merits of the tri-encoder & hyper-cl architectures.
For right now I want to focus on:
- Bi-Encoder: (focus of v3)
- Cross-Encoder (focus after v3 release)
- ColBERT (focus after v3 release)
- Sparse models (later)

At least, that was my plan - again, that was before I knew about these architectures.

- Tom Aarsen
