### ISSUE TITLE
Models without PyTorch parameters don't work since v2.3.0

### ISSUE THREAD

**Issue by maxfriedrich** [UKPLab/sentence-transformers#2607]
Hi, models that don't have any PyTorch parameters seem broken since sentence-transformers v2.3.0, e.g.

```python
from sentence_transformers import SentenceTransformer, models

st = SentenceTransformer(modules=[models.BoW(vocab=["a", "b", "c"])])
st.encode(["a"])
```

works as expected in v2.2.2 but crashes since v2.3.0 inside `self.device` because `next(...)` in the PyTorch 1.5 fallback branch raises `StopIteration`  (https://github.com/UKPLab/sentence-transformers/blob/v2.3-release/sentence_transformers/SentenceTransformer.py#L1122).

(More context: we sometimes use `SentenceTransformer` to wrap calls an embedding API so we can use them in the same way as local trainable models, now we have to add a dummy parameter such as `self.dummy = nn.Linear(1, 1)` to make it work)

I haven't tried the v3 branches yet, feel free to close in case this is fixed soon since it's only a small inconvenience. Thanks!

**Comment by maxfriedrich** [comment]
In case you have a hint how to fix this, I'm also happy to open a PR. Would it be ok to fall back to `torch.device("cpu")` in case there are no PyTorch parameters?

**Comment by tomaarsen** [comment]
Hello!

This issue should still persist in the v3 branch. I've noticed the same issue myself when experimenting with an ONNX model, and I know that @michaelfeil has also had issues with this with CTranslate. In both of those cases, the model does not have actual torch  parameters. I think `torch.device("cpu")` should be a good default, but I'd also like to hear Michael's opinion on that.

And yes, I would be very receptive to a PR on this.

- Tom Aarsen

**Comment by maxfriedrich** [comment]
Thanks! I opened a PR with the CPU fallback, looking forward to hearing Michael's thoughts too
