### ISSUE TITLE
Can I modify the network structure of the pre trained model?

### ISSUE THREAD

**Issue by renjd** [UKPLab/sentence-transformers#2618]
As shown in the figure, SentenceTransformer is the structure of the pre trained network model itself. **I would like to add a custom layer between (0) and (1)**. Is this feasible. I found that I can add my own layer after the pre trained model structure, and the structure (2) in the figure is what I tried to add myself. I'm not sure if it's possible to add between layers. Thank you for your reply!
![1714134425678](https://github.com/UKPLab/sentence-transformers/assets/165153801/cf1e65b2-b4c6-4bc7-9593-00a0b76a827d)

**Comment by ir2718** [comment]
Hi,

yes you can add custom layers between the transformer and the pooling layer, although keep in mind that the output of the transformer is a dictionary with the following items:
```
{
    "input_ids" torch.Tensor of shape (B, seq_len),
    "attention_mask": torch.Tensor of shape (B, seq_len),
    "token_embeddings": torch.Tensor of shape (B, seq_len, hidden_size),
}
```

Since `SentenceTransformer` inherits `nn.Sequential` you can just create a custom class that inherits `nn.Module`. Here's an example of adding a linear layer after the transformer:
```
import torch.nn as nn
from sentence_transformers import models, SentenceTransformer

model_name = "sentence-transformers/stsb-distilbert-base"

# Use Huggingface/transformers model (like BERT, RoBERTa, XLNet, XLM-R) for mapping tokens to embeddings
word_embedding_model = models.Transformer(model_name)

class CustomLinear(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(
            in_features=word_embedding_model.get_word_embedding_dimension(),
            out_features=512,
        )

    def forward(self, x):
        return {
            "input_ids": x["input_ids"],
            "attention_mask": x["attention_mask"],
            "token_embeddings": self.linear(x["token_embeddings"])
        }
custom_module = CustomLinear()

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(
    word_embedding_model.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

model = SentenceTransformer(
    modules=[word_embedding_model, custom_module, pooling_model]
)

model.encode("This is a sentence.")
```

You can also check out the `models` module for already existing layers that might come in handy.

**Comment by renjd** [comment]
> Hi,
> 
> yes you can add custom layers between the transformer and the pooling layer, although keep in mind that the output of the transformer is a dictionary with the following items:
> 
> ```
> {
>     "input_ids" torch.Tensor of shape (B, seq_len),
>     "attention_mask": torch.Tensor of shape (B, seq_len),
>     "token_embeddings": torch.Tensor of shape (B, seq_len, hidden_size),
> }
> ```
> 
> Since `SentenceTransformer` inherits `nn.Sequential` you can just create a custom class that inherits `nn.Module`. Here's an example of adding a linear layer after the transformer:
> 
> ```
> import torch.nn as nn
> from sentence_transformers import models, SentenceTransformer
> 
> model_name = "sentence-transformers/stsb-distilbert-base"
> 
> # Use Huggingface/transformers model (like BERT, RoBERTa, XLNet, XLM-R) for mapping tokens to embeddings
> word_embedding_model = models.Transformer(model_name)
> 
> class CustomLinear(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.linear = nn.Linear(
>             in_features=word_embedding_model.get_word_embedding_dimension(),
>             out_features=512,
>         )
> 
>     def forward(self, x):
>         return {
>             "input_ids": x["input_ids"],
>             "attention_mask": x["attention_mask"],
>             "token_embeddings": self.linear(x["token_embeddings"])
>         }
> custom_module = CustomLinear()
> 
> # Apply mean pooling to get one fixed sized sentence vector
> pooling_model = models.Pooling(
>     word_embedding_model.get_word_embedding_dimension(),
>     pooling_mode_mean_tokens=True,
>     pooling_mode_cls_token=False,
>     pooling_mode_max_tokens=False,
> )
> 
> model = SentenceTransformer(
>     modules=[word_embedding_model, custom_module, pooling_model]
> )
> 
> model.encode("This is a sentence.")
> ```
> 
> You can also check out the `models` module for already existing layers that might come in handy.

Thank you for your patient answer! I will give it a try.

**Comment by renjd** [comment]
> Hi,
> 
> yes you can add custom layers between the transformer and the pooling layer, although keep in mind that the output of the transformer is a dictionary with the following items:
> 
> ```
> {
>     "input_ids" torch.Tensor of shape (B, seq_len),
>     "attention_mask": torch.Tensor of shape (B, seq_len),
>     "token_embeddings": torch.Tensor of shape (B, seq_len, hidden_size),
> }
> ```
> 
> Since `SentenceTransformer` inherits `nn.Sequential` you can just create a custom class that inherits `nn.Module`. Here's an example of adding a linear layer after the transformer:
> 
> ```
> import torch.nn as nn
> from sentence_transformers import models, SentenceTransformer
> 
> model_name = "sentence-transformers/stsb-distilbert-base"
> 
> # Use Huggingface/transformers model (like BERT, RoBERTa, XLNet, XLM-R) for mapping tokens to embeddings
> word_embedding_model = models.Transformer(model_name)
> 
> class CustomLinear(nn.Module):
>     def __init__(self):
>         super().__init__()
>         self.linear = nn.Linear(
>             in_features=word_embedding_model.get_word_embedding_dimension(),
>             out_features=512,
>         )
> 
>     def forward(self, x):
>         return {
>             "input_ids": x["input_ids"],
>             "attention_mask": x["attention_mask"],
>             "token_embeddings": self.linear(x["token_embeddings"])
>         }
> custom_module = CustomLinear()
> 
> # Apply mean pooling to get one fixed sized sentence vector
> pooling_model = models.Pooling(
>     word_embedding_model.get_word_embedding_dimension(),
>     pooling_mode_mean_tokens=True,
>     pooling_mode_cls_token=False,
>     pooling_mode_max_tokens=False,
> )
> 
> model = SentenceTransformer(
>     modules=[word_embedding_model, custom_module, pooling_model]
> )
> 
> model.encode("This is a sentence.")
> ```
> 
> You can also check out the `models` module for already existing layers that might come in handy.

Hello, I'm really sorry, I have another new question. I would like to ask if the pre trained model in the SentenceTransformer library I imported was trained based on the twin network structure in the SBERT paper?

**Comment by ir2718** [comment]
@renjd 

Assuming you're using the model with the `sentence-transformers/stsb-distilbert-base` model tag, the model is fine-tuned using the STSB dataset in a bi-encoder (SBERT) setting. Keep in mind that adding randomly initialized modules without fine-tuning will mess up the embeddings. If you plan on fine-tuning your model, you can use (almost) any huggingface model. The constructor in the `SentenceTransformer` class uses the `AutoModel.from_pretrained` method under the hood.

**Comment by renjd** [comment]
> @renjd
> 
> Assuming you're using the model with the `sentence-transformers/stsb-distilbert-base` model tag, the model is fine-tuned using the STSB dataset in a bi-encoder (SBERT) setting. Keep in mind that adding randomly initialized modules without fine-tuning will mess up the embeddings. If you plan on fine-tuning your model, you can use (almost) any huggingface model. The constructor in the `SentenceTransformer` class uses the `AutoModel.from_pretrained` method under the hood.

Then I can add custom layers, such as the Dense layer, on top of the pre trained model. Compared to modifying the pre trained model structure, this operation is feasible, right. This is my understanding

**Comment by ir2718** [comment]
> Then I can add custom layers, such as the Dense layer, on top of the pre trained model. 

This is exactly what the code I added above does, although `models.Dense` is compatible only with the pooled output, while the `CustomLinear` works directly on token embeddings. 

> Compared to modifying the pre trained model structure, this operation is feasible

Keep in mind that the DistilBERT model is pretrained by distilling the BERT model. There is no extra pretraining done when a `SentenceTransformer` is created, meaning both options are viable and will need further fine-tuning.
