### ISSUE TITLE
Question: Encoding long documents

### ISSUE THREAD

**Issue by FahadEbrahim** [UKPLab/sentence-transformers#2669]
Hi all,

I have a question related to long texts. I want to perform paraphrase mining to retrieve the most similar pairs. However, the texts are long (around 4k tokens), and I'm using models with a maximum length of 512 tokens. Using larger models is not feasible for me.

Therefore, one solution is to divide the long texts into chunks and encode them. Could you please guide me with an example of how to do that and whether that is feasible?  Other suggestions are also appreciated.

Thanks,
Fahad.

**Comment by ir2718** [comment]
Hi,

if you opt for the chunking solution I would recommend directly using Huggingface's transformers as it would simplify the process. Here's a general overview of what you need to do:

1. Tokenization
    - choose a new max sequence length defined by your data eg. 4096 might be a good starting point for you
    - tokenize the data WITHOUT truncation
    - split the `input_ids` into chunks of the size you want - this size has to be smaller or equal to `tokenizer.model_max_length - 2` to accomodate for the `[CLS]` and `[SEP]` tokens
    - additionally, you can add some overlap between the subsequences although, but I will leave that out for now
    - add `[CLS]` at the beggining and `[SEP]` at the end of each subsequence
2. Modeling
    - encode each subsequence in the example - this will be a tensor of shape `(num_subseq, B, seq_length, D)`
    - now you need to aggregate the subsequences using some king of pooling, here are two examples and their output dims:
        - do mean pooling on each of the subsequences and concatenate them - `(B, num_subseq * D)`
        - stack the encoded subsequences into a single tensorof shape `(B, num_subseq * seq_length, D)` and do mean pooling - `(B, D)`

The rest of the training procedure stays the same.

Other ideas that make sense to me are:
1. Doing summarization before to make the inputs fit the 512 token window
2. [BERT-AL](https://openreview.net/pdf?id=SklnVAEFDB)
3. Just trimming the input sequence

**Comment by FahadEbrahim** [comment]
Thank you @ir2718 for the detailed answer. I'll give it a try and I'll reopen the issue if stuck.

Much appreciated,
Fahad.
