### ISSUE TITLE
Question: ColBERT integration

### ISSUE THREAD

**Issue by FahadEbrahim** [UKPLab/sentence-transformers#2670]
Hi, 

Is there a plan to integrate retrievers such as ColBERT with the library allowing fine-tuning?

Thanks,
Fahad.

**Comment by FahadEbrahim** [comment]
Got the answer. 
https://github.com/UKPLab/sentence-transformers/issues/2606#issuecomment-2074583865

**Comment by tomaarsen** [comment]
Well found! Indeed, ColBERT is on my to-do list after v3. I think they're a fascinating architecture, and I'd love to assist in making them easier to train and finetune.

- Tom Aarsen

**Comment by FahadEbrahim** [comment]
@tomaarsen Glad to hear that and I'm looking forward to having ColBERT within sentence-transformers.
