### ISSUE TITLE
What should I do to install bitext_mining_utils?

### ISSUE THREAD

**Issue by evacaptain** [UKPLab/sentence-transformers#2671]
I can't install bitext_mining_utils whatever I use command like pip install or conda install, and I have installed faiss

**Comment by tomaarsen** [comment]
Hello!

If you're trying to run [bitext_mining.py](https://github.com/UKPLab/sentence-transformers/blob/684b6b5736c4551c17c62830e975e78edcca0fa0/examples/applications/parallel-sentence-mining/bitext_mining.py) or [bucc2018.py](https://github.com/UKPLab/sentence-transformers/blob/684b6b5736c4551c17c62830e975e78edcca0fa0/examples/applications/parallel-sentence-mining/bucc2018.py) locally, then your best option is to also download/copy the [bitext_mining_utils.py](https://github.com/UKPLab/sentence-transformers/blob/684b6b5736c4551c17c62830e975e78edcca0fa0/examples/applications/parallel-sentence-mining/bitext_mining_utils.py) file.

You can place this file adjacent to your local bitext_mining.py/bucc2018.py and make sure that it's named `bitext_mining_utils.py`. Then, you should be able to run your original file like normal.

- Tom Aarsen

**Comment by evacaptain** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
