### ISSUE TITLE
Resume last training

### ISSUE THREAD

**Issue by MaxWenzel** [UKPLab/sentence-transformers#2695]
I use version 3 of the library to finetune a Sentence Transfomer Model.

I would like to resume a training. For this I use the parameter ‘resume_from_checkpoint’ of the SentenceTransformerTrainingArguments class. But which model do I have to use to initialize the SentenceTransformerTrainer? The one that I saved in the last training with ‘model.save_pretrained(output_dir_final)’ or do I have to load the base model again with which I started the training?

**Comment by tomaarsen** [comment]
Hello!

Apologies, this is rather poorly documented at the moment. You can resume training in two ways:
1. From a training checkpoint: this involves continuing a training session that was halted before it could be completed. This is done by running exactly your previous code with one change involving [train()](https://sbert.net/docs/package_reference/sentence_transformer/trainer.html#sentence_transformers.trainer.SentenceTransformerTrainer.train):
```
trainer.train(resume_from_checkpoint=True)
# or
trainer.train(resume_from_checkpoint="path/to/my/checkpoint/dir")
```
Then it will load this checkpoint, skip the number of training steps that were previously done, load the trainer state, etc. Note: you can keep the `model = SentenceTransformer(...)` the same, i.e., you can load the base model again. The weights will be overridden by the `trainer.train(resume_from_checkpoint=...)`.

2. From a previously completed trained model: this would be equivalent to just further finetuning a Sentence Transformer model. I would not consider this "resuming" per se, but just doing finetuning. You don't have to specify `resume_from_checkpoint` or anything, and you should load the model that you're training with `SentenceTransformer(path_to_saved_model)`. You can just use this model as if you've loaded `SentenceTransformer("all-mpnet-base-v2")` or `SentenceTransformer("bert-base-uncased")`.

I hope that helps.

- Tom Aarsen

**Comment by MaxWenzel** [comment]
Yes, thank you for the clarification. That helps me a lot.

**Comment by david-waterworth** [comment]
Note huggingface has a nice helper `from transformers.trainer_utils import get_last_checkpoint` which makes it easier to write a script that auto-resumes or trains from scratch, i.e.

```
    last_checkpoint = get_last_checkpoint(args.output_dir)

    args = SentenceTransformerTrainingArguments(
        output_dir=args.output_dir,
        overwrite_output_dir=True if last_checkpoint is not None else False,

<snip>

    if last_checkpoint is not None:
        logging.info("resume training from checkpoint %s", last_checkpoint)
        train_result = trainer.train(resume_from_checkpoint=last_checkpoint)
    else:
        train_result = trainer.train()
...


```

**Comment by tomaarsen** [comment]
That's very useful! Thanks for sharing, I wasn't aware of that one myself.

**Comment by tomaarsen** [comment]
Apologies for the confusion @csanadpoda.
Before Sentence Transformers v3, training was done without any Trainer and resuming wasn't possible. After v3, this became possible, but only via the `SentenceTransformerTrainer`. Not all of the training examples have been updated, especially if the training example involved a custom Dataset or DataLoader. This script still uses the old v2 approach (which still works, but it doesn't have the newer features like resuming)

My recommendation is to take a look at the new v3 training overview: https://sbert.net/docs/sentence_transformer/training_overview.html

and make the following changes:
1. After loading a `datasets.Dataset` with 1 column of texts, call `dataset = dataset.map` with a noise function to add a 2nd column with noisy text.
2. Use the `DenoisingAutoEncoderLoss`

For example:
```python
from datasets import load_dataset
from sentence_transformers import (
    SentenceTransformer,
    SentenceTransformerTrainer,
    SentenceTransformerTrainingArguments,
    SentenceTransformerModelCardData,
)
from sentence_transformers.losses import DenoisingAutoEncoderLoss
from sentence_transformers.training_args import BatchSamplers
from sentence_transformers.evaluation import TripletEvaluator
from nltk import word_tokenize
from nltk.tokenize.treebank import TreebankWordDetokenizer

# 1. Load a model to finetune with 2. (Optional) model card data
model = SentenceTransformer(
    "microsoft/mpnet-base",
    model_card_data=SentenceTransformerModelCardData(
        language="en",
        license="apache-2.0",
        model_name="MPNet base trained on AllNLI triplets",
    )
)

# 3. Load a dataset to finetune on
dataset = load_dataset("sentence-transformers/all-nli", "triplet")
train_dataset = dataset["train"].select_columns(["anchor"]).select(range(100_000))
eval_dataset = dataset["dev"].select_columns(["anchor"])
test_dataset = dataset["test"].select_columns(["anchor"])
# Now we have 3 datasets, each with one column of text (called "anchor", but the name doesn't matter)
# Now we need to convert the dataset into 2 columns: (damaged_sentence, original_sentence), see https://sbert.net/docs/sentence_transformer/loss_overview.html

def noise_fn(text, del_ratio=0.6):
	words = word_tokenize(text)
	n = len(words)
	if n == 0:
	    return text

	keep_or_not = np.random.rand(n) > del_ratio
	if sum(keep_or_not) == 0:
	    keep_or_not[np.random.choice(n)] = True  # guarantee that at least one word remains
	words_processed = TreebankWordDetokenizer().detokenize(np.array(words)[keep_or_not])
	return {
        "damaged": words_processed,
        "original": text,
    }

train_dataset = train_dataset.map(noise_fn, input_columns="anchor", remove_columns="anchor")
eval_dataset = eval_dataset.map(noise_fn, input_columns="anchor", remove_columns="anchor")
test_dataset = test_dataset.map(noise_fn, input_columns="anchor", remove_columns="anchor")
# Now we have datasets with 2 columns, damaged & original (in that order). The "anchor" column is removed

# 4. Define a loss function
loss = DenoisingAutoEncoderLoss(model, decoder_name_or_path="microsoft/mpnet-base", tie_encoder_decoder=True)

# 5. (Optional) Specify training arguments
# Feel free to fully update these:
args = SentenceTransformerTrainingArguments(
    # Required parameter:
    output_dir="models/mpnet-base-all-nli-tsdae",
    # Optional training parameters:
    num_train_epochs=1,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    learning_rate=2e-5,
    warmup_ratio=0.1,
    fp16=True,  # Set to False if you get an error that your GPU can't run on FP16
    bf16=False,  # Set to True if you have a GPU that supports BF16
    # Optional tracking/debugging parameters:
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=2,
    logging_steps=100,
    run_name="mpnet-base-all-nli-tsdae",  # Will be used in W&B if `wandb` is installed
)

# 6. (Optional) Make an evaluator to evaluate before, during, and after training

# 7. Create a trainer & train
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss=loss,
)
trainer.train()

# 8. Save the trained model
model.save_pretrained("models/mpnet-base-all-nli-tsdae/final")

# 9. (Optional) Push it to the Hugging Face Hub
model.push_to_hub("mpnet-base-all-nli-tsdae")
```

I have to warn you: I didn't actually run this, I just copied it from https://sbert.net/docs/sentence_transformer/training_overview.html#trainer and updated it in GitHub.

Updating the TSDAE example so that it uses the new Trainer is still on my TODO list.

cc @JINO-ROHIT if you're interested

- Tom Aarsen

**Comment by JINO-ROHIT** [comment]
@tomaarsen yes please, ill take this up.
