### ISSUE TITLE
CrossEncoder always looks for safetensors file

### ISSUE THREAD

**Issue by sugarforever** [UKPLab/sentence-transformers#2696]
I was trying to wrap the reranking model as a service using CrossEncoder
https://github.com/sugarforever/peanut-shell/blob/main/services/cross_encoder/cross_encoder_rerank_service.py

```
class CrossEncoderRerankService(RerankService):

    def __init__(self, modelName: str) -> None:
        super().__init__()
        self.cross_encoder = CrossEncoder(model_name=modelName)

    def rerank(self, request: RerankRequest) -> RerankResponse:
        pairs = []
        for document in request.documents:
            pairs.append([request.query, document])

        scores = self.cross_encoder.predict(pairs)

        scored_pairs = list(zip(scores, range(len(request.documents))))
        scored_pairs.sort(key=lambda x: x[0], reverse=True)

        # Generate a list of indices in descending order of their corresponding scores
        results = [RerankResult(index=index, relevance_score=score) for score, index in scored_pairs]

        return RerankResponse(results=results[:request.top_n])
```

But even when the API was first called, and model files got downloaded in the HF default cache folder, it was still trying to connect HF and download some files in following API calls.

According to my debug, I realized, the underlying components of CrossEncoder still looked for safesensors file, even `pytorch_model.bin` was already cached. 

It resulted in the fact that my service can't fully work offline. It will still require network connectivity all the time.

May I query if it's how CrossEncoder or underlying components are supposed to work? Is there any way to achieve my goal? I'm trying to help users to download the models once and use them without access to HF.

Thanks.

**Comment by tomaarsen** [comment]
Hello!

This is a very valid usecase, I understand. I can't easily influence the underlying `transformers` code which is responsible for this, but I think you might be able to resolve your problem fully by using `self.cross_encoder = CrossEncoder(model_name=modelName, local_files_only=True)`. Although then you would have to already have the files cached, I believe. I imagine this might still not be ideal - please let me know how that works for you as I'm not 100% up to date on the underlying code when `local_files_only=True`.

A potential solution might be to try and first load with `local_files_only=True`, load without it if it fails due to not having the model in the cache.

Another thing to look into is the Hugging Face Offline Mode options: https://huggingface.co/docs/transformers/main/en/installation#offline-mode

- Tom Aarsen

**Comment by sugarforever** [comment]
> Hello!
> 
> This is a very valid usecase, I understand. I can't easily influence the underlying `transformers` code which is responsible for this, but I think you might be able to resolve your problem fully by using `self.cross_encoder = CrossEncoder(model_name=modelName, local_files_only=True)`. Although then you would have to already have the files cached, I believe. I imagine this might still not be ideal - please let me know how that works for you as I'm not 100% up to date on the underlying code when `local_files_only=True`.
> 
> A potential solution might be to try and first load with `local_files_only=True`, load without it if it fails due to not having the model in the cache.
> 
> Another thing to look into is the Hugging Face Offline Mode options: https://huggingface.co/docs/transformers/main/en/installation#offline-mode
> 
> * Tom Aarsen

Hi @tomaarsen , thanks for the advice. I have tried with your proposal. Please refer to my PR for how to make it work - https://github.com/sugarforever/peanut-shell/pull/7

Changes involved:

1. Upgrade sentence-transformers to 3.0.0
2. Upgrade transformers to 4.41.2
3. Attempt to local model files firstly with local_files_only=True in CrossEncoder.

Notice that, according to my test, the versions upgrade is necessary, especially for `transformers==4.41.2`. I remember `sentence-transformers==3.0.0` brings transformers 4.40 which doesn't really support the local files first mechanism I expected.

Now with my changes, I can make API call for reranking, in which it will download the model files for the first time. Later on, I can turn off my network, and continue to make same API call for reranking.

:-)

**Comment by tomaarsen** [comment]
Excellent! Then I think we can close this issue. If anyone stumbles upon this in the future, then your post is a nice recommendation for them.

- Tom Aarsen
