### ISSUE TITLE
Add method to encode using pre-encoded tokens to facilitate GPU accelerated encoding

### ISSUE THREAD

**Issue by rjurney** [UKPLab/sentence-transformers#273]
It is not possible to put `SentenceTransformers.encode()` on a GPU to encode documents because you can't create a Tensor of strings to send to a GPU. This presents a huge scalability problem when working with a lot of text. 

Can we make `SentenceTransformers.encode()` tokenize/encode the data in integers and have another method that accepts lists of integers use `SentenceTransformers.embed()` to actually create the embedding? Maybe the names are wrong but splitting this process would be wonderful.

Or is this possible now somehow? I am reading the `SentenceTransformers.encode()` method and it is taking a lot of time to understand/hack so I wanted to ask.

**Comment by aced125** [comment]
I would hope this feature exists too.

**Comment by rjurney** [comment]
I have this working. It was a minor change in the end. I’ll try to update the PR this week.

**Comment by rjurney** [comment]
@aced125 See https://github.com/UKPLab/sentence-transformers/pull/277
