### ISSUE TITLE
ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1` when using Huggingface's TrainArguments?

### ISSUE THREAD

**Issue by harshitv804** [UKPLab/sentence-transformers#2745]
I was trying to fine tune a mbert model using SentenceTransformerTrainer and I came across this issue:
 **ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1` when using Huggingface's TrainArguments?**

before finding the problem:
`sentence-transformers` version: `3.0.1`
`transformers` version : `4.41.2`
`accelerate` version: `0.31.0`

though `accelerate` version was latest it still throwed some error. I tried to find what's the problem then I came to know that there was a problem with the `transformers`. I reverted the `transformers` version to `4.36.2` and it was working without errors.

If anyone come across this issue with the newly try with these working versions:
`sentence-transformers` version: `3.0.1`
`transformers` version : `4.38.0`
`accelerate` version: `0.31.0`

I couldn't figure out what's the issue, I kindly request the team to solve this bug.
Thank You

**Comment by tomaarsen** [comment]
Hello!

Apologies for the delay, I was on vacation last week.
I'm unable to reproduce this with your versions
* `sentence-transformers` version: `3.0.1`
* `transformers` version : `4.41.2`
* `accelerate` version: `0.31.0`

For reference, this error is thrown by `transformers` after it tries to check the `accelerate` version. My best guess is that you have multiple Python installations/environments, and you've installed `accelerate==0.31.0` in a different environment than you're using to run your training code.

- Tom Aarsen

**Comment by harshitv804** [comment]
Hi, thanks for the reply. I have only one virtual ENV running and also confirmed the package installations using `pip list` but for some reason it was throwing same error. **Anyways I fully reinstalled the python and ran from a new ENV and it works now!**

Thanks, I will close this Issue.

**Comment by tomaarsen** [comment]
`accelerate` can be tricky with that, sometimes a restart is required for that one to really catch on.
Glad to hear that you got it working.

- Tom Aarsen
