### ISSUE TITLE
API type hinting not overloaded properly

### ISSUE THREAD

**Issue by janrito** [UKPLab/sentence-transformers#2758]
Just wondering if this is a desirable thing, but there are a few methods that have type annotations that strictly correspond to an input. 

```
Returns:
    Union[List[Tensor], ndarray, Tensor]: By default, a 2d numpy array with shape [num_inputs, output_dimension] is 
returned. If only one string input is provided, then the output is a 1d array with shape [output_dimension]. If 
convert_to_tensor, a torch Tensor is returned instead. If self.truncate_dim <= output_dimension then output_dimension is 
self.truncate_dim.
```

This could be specified using [overload](https://docs.python.org/3/library/typing.html)

**Comment by tomaarsen** [comment]
Hello!

Fair enough! I did some experimentation with this locally, resulting in:
![image](https://github.com/UKPLab/sentence-transformers/assets/37621491/6510131f-2c90-483f-8f1e-5aac432f3eb5)

![image](https://github.com/UKPLab/sentence-transformers/assets/37621491/e31f8cbf-04e3-4d67-b445-b2c72de534bd)

Is that what you would expect to see?

- Tom Aarsen
