### ISSUE TITLE
Paragraph Embedding

### ISSUE THREAD

**Issue by abmitra84** [UKPLab/sentence-transformers#276]
Hi,

- If I want to do paragraph embedding just by using pre-trained models do you suggest to first extract individual sentence embeddings and then take a mean/sum ?

- If I want to fine tune on paragraph matching and create triplets of anchor, positive and negative paragraphs separated by tab delimiter will it work?

**Comment by nreimers** [comment]
1) I sadly haven't done experiment with paragraphs. So I don't know what the best approach is. 

2) Yes, that works. Be careful, the models have a max sequence length parameter which is by default 128 word pieces. You might want to increase this for your paragraphs.

**Comment by abmitra84** [comment]
Thanks for your response.
