### ISSUE TITLE
Multiple GPU support

### ISSUE THREAD

**Issue by kevinmandich** [UKPLab/sentence-transformers#28]
First, I just wanted to say that this repo is fantastic. It's very useful and powerful for training a model to detect sentence similarity.

A question I have: are there any plans to support multi-GPU training? If not, could you recommend any examples in other repos that show how to implement this? Thank you,

Kevin

**Comment by nreimers** [comment]
Hi Kevin, I think the examples in hugging face pytorch transformers support multi GPU training.

As this repo is derived from pytorch transformers, multi GPU training might already work (I haven't tested it) 

Best
Nils Reimers

**Comment by kevinmandich** [comment]
Thanks Nils, I'll give it a shot.

**Comment by rexdouglass** [comment]
I'm following the same path. If anyone gets it working multi-gpu can you please post some example code?

Fantastic repo btw.
