### ISSUE TITLE
AttributeError: 'MPNetTokenizerFast' object has no attribute 'split_special_tokens'

### ISSUE THREAD

**Issue by arshee2403** [UKPLab/sentence-transformers#2806]
getting this error post 27th june,24 update
version=2.2.2

**Comment by arshee2403** [comment]
Resolved : use transformers==4.41.2

**Comment by tomaarsen** [comment]
Hello!

Excellent, thanks for sharing your solution. I'll close this now, as it has been resolved.

- Tom Aarsen
