### ISSUE TITLE
Support for Turing NLG

### ISSUE THREAD

**Issue by shameelct** [UKPLab/sentence-transformers#281]
Hi team,
Are you planning to add support for Turing NLG any time soon: https://www.microsoft.com/en-us/research/blog/turing-nlg-a-17-billion-parameter-language-model-by-microsoft/

**Comment by nreimers** [comment]
Hi @shameelct 

It depends when (if) it is added to huggingface transformers. Also, will it fit on a single GPU or is a distribution to multiple GPUs needed? Currently, this framework only supports single GPU models. So the model might be too big and it wouldn't be able to use it until we get GPUs with more memory than 32GB.

**Comment by shameelct** [comment]
Checked it up. Not yet part of hugging face. Thanks a lot !

You ve built a fantastic framework
