### ISSUE TITLE
Question: Same base-model for finetuning Bi- and Cross-Encoder?

### ISSUE THREAD

**Issue by Max-KI** [UKPLab/sentence-transformers#2813]
For my domain-specific use case, I would like to finetune a bi- and a cross-encoder model for the 'Retrieve & Re-Rank' scenario. Does it make sense to use the same base model for both? Or can I, for example, also fine-tune the model for the bi-encoder only and then use the finetuned model for the cross-encoder as well? I am currently using '_sentence-transformers/distiluse-base-multilingual-cased-v2_' for the bi-encoder and '_cross-encoder/stsb-roberta-large_' for the cross-encoder.

In my eyes, there are (at least) the following possibilities:

1. Using the same base model for fine-tuning bi- and cross-encoders
2. Using different base models for fine tuning
3. Perform only one fine-tuning and use the finetuned model for bi- **and** cross-encoders

Which option is the best?

**Comment by tomaarsen** [comment]
Hello!

> Does it make sense to use the same base model for both?

I don't want to say that it "makes sense", but you can definitely use the same base model, but there's no necessity to do this.

> Or can I, for example, also fine-tune the model for the bi-encoder only and then use the finetuned model for the cross-encoder as well?

You cannot, I'm afraid. Well, you technically could, but the finetuned bi-encoder would not be an effective cross-encoder out of the box. Using the same underlying model for both a bi-encoder and a cross-encoder and then training both simultaneously is rather interesting actually, but primarily as a research idea. I suspect it wouldn't work too well 😄 

As for your 3 possibilities: 1 & 2 are feasible & common, 3 is rather unusual and likely would not work.

Furthermore, I want to warn you that whereas finetuning a bi-encoder (i.e. the `SentenceTransformer` class) has been refactored in the v3 update, finetuning a `CrossEncoder` still uses an older training loop that e.g. doesn't have as many parameters or integrations with Weights & Biases, etc. With other words, it might be a bit trickier to finetune the CrossEncoder. There example code [here](https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/cross-encoder).

Beyond that, my recommendation is to start with finetuning a bi-encoder. This is also the first step in your retrieval + reranking pipeline, and it will act as a good baseline for determining how much the cross-encoder helps. Perhaps the finetuned bi-encoder will also perform sufficiently satisfactory that you won't feel the need for the cross-encoder.

- Tom Aarsen

**Comment by Max-KI** [comment]
Hello,
as always, thank you very much for your quick and comprehensive reply! 
Thank you very much
Max
