### ISSUE TITLE
question about the distance in en example : semantic_search.py

### ISSUE THREAD

**Issue by AsmaZbt** [UKPLab/sentence-transformers#282]
hello ,  
this may be a verry stupide question , but i really didn't understand why did you subtract the distance from 1 in the last line of your code of the example : semantic_search.py.

for idx, distance in results[0:closest_n]:
        print(corpus[idx].strip(), "(Score: %.4f)" % (1-distance))

thank you so much for this great work (y)

**Comment by nreimers** [comment]
The cdist function computes the cosine distance , which is defined as cos_distance=1-cos_similarity

**Comment by AsmaZbt** [comment]
thank you so much
