### ISSUE TITLE
Monolingual model for other languages - Norwegian

### ISSUE THREAD

**Issue by manycoding** [UKPLab/sentence-transformers#283]
What's the right approach if I want to do some similarity search on Norwegian text only?

The constraints are google colab pro and lack of labelled data.

I tried various multilingual transformer models, but they don't perform at all. Now I am going to train a multilingual model as you described in readme, but I am not sure it will perform well on one language only

**Comment by nreimers** [comment]
Hi,
this approach:
https://arxiv.org/abs/2004.09813

Also works for monolingual models. You could extend the English NLI-STS model with English-Norwegian parallel data. This gives you a bilingual model with aligned vector spaces.

But you can use this model of course also for Norwegian only data

**Comment by manycoding** [comment]
I did fine-tuning and the performance is poor. But I think it's because the data is a bit different - it's wine reviews, even the English translation performs poorly.
I think I'd need to fine-tune on a data which is similar to mine to get good similarity results.

**Comment by nreimers** [comment]
Hi @manycoding 
This might be an issue. The models sadly do not work too well for domain specific texts. NLI (&STS) data has only rather generic sentences, but no specific language is covered by these training datasets.

Further, I think the reviews might be multiple sentences long? The current models are rather optimized for individual sentences, not for longer paragraphs / docs.

**Comment by manycoding** [comment]
Not really, they are concatenation of description and food pairings like
'Aroma with distinctive anise. Sweet with good fullness and distinctive anise. Water Ready.'

**Comment by manycoding** [comment]
@nreimers To continue fine-tuning of my multilingual model do I just use it as a teacher and keep everything same?

**Comment by nreimers** [comment]
What do you mean with continue training? 

To continue on labeled training data (like NLI): Use the regular setup

The teacher-student model is just used to make a monolingual model multilingual.

After that, you use the student model

**Comment by manycoding** [comment]
@nreimers  I mean I fine-tuned a monolingual with teacher-student setup. Now I have this model and I want to fine tune it a bit more on the same data.

**Comment by nreimers** [comment]
If I understand you correctly, you keep the teacher model  as is. As student model, you use the previously fine-tuned model and continue training on it.
