### ISSUE TITLE
Embedding the way Universal Sentence Encoding does it

### ISSUE THREAD

**Issue by shameelct** [UKPLab/sentence-transformers#291]
Is there a specific reason why Sentence Transformer follows embedding the way it is done now. From the results USE is giving, is it not a good idea to follow similar method as USE to find the Sentence Embedding (I know from paper that Sentence Transformer gives better results on some tasks, but for general cosine similarity based tasks USE seems to give good results on wider set).

I am not sure if the method used by USE to form embedding is fully open. Bouncing it off as this thought has been around for some time, and could not find an explanation myself.

**Comment by nreimers** [comment]
Hi @shameelct 
Not sure what you exactly mean.

USE is sadly not open. It is quite unclear how and on which data it was trained. Further, no training code is provided to train sentence embeddings for specific tasks. You are stuck with the pre-trained models that are provided by USE, adaptation to tasks is hardly possible.

USE-large and SentenceTransformers both are based on transformer networks, i.e., they are quite similar in the architecture. USE was trained from scratch, while SentenceTransformers was pre-trained with a language model like BERT / RoBERTa etc.

**Comment by shameelct** [comment]
Makes sense. We would ve been able to do some thing if it was open. Closing the issue.

Thanks for the quick reply.
