### ISSUE TITLE
Doubt about paragraph embedding composed by mean/sum of sentence embedding

### ISSUE THREAD

**Issue by Guillermogsjc** [UKPLab/sentence-transformers#293]
Hi @nreimers,

I have one doubt about the behaviour of performing a paragraph embedding composed  as the sum/mean of the embeddings created by `distiluse-multilingual` of the sentences in the paragraph. 

It is well behaved? Have you tested it?

Regards.

**Comment by nreimers** [comment]
Hi @Guillermogsjc 
I haven't tested it and I don't know if it will be well behaved.

Best
Nils
