### ISSUE TITLE
Range of similarity

### ISSUE THREAD

**Issue by s3afroze** [UKPLab/sentence-transformers#297]
Hi guys,
Thank you for making this awesome library!!

I am interested in knowing the range for similarity score, I was expecting the result between the range of 0 and 1 but I am getting less than 0 for sentences compared to 'none' (as string).

I am using example from [here](https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/semantic_search.py)

Thanks,

Shahzeb

**Comment by nreimers** [comment]
Hi @s3afroze 
The code uses cosine-similarity to compare embeddings, which can produce scores between -1 and 1.

Best
Nils Reimers

**Comment by s3afroze** [comment]
Thank you Nils : )!
