### ISSUE TITLE
Cannot load fine-tuned model saved with Peft and LoRa

### ISSUE THREAD

**Issue by pesuchin** [UKPLab/sentence-transformers#2979]
# Summary

When attempting to load a model fine-tuned with Peft and LoRa, the model fails to load in SentenceTransformers because it only contains adapter differences from the base model and lacks the necessary config.json and model files. As a result, an OSError is raised due to missing files.

The Pull Request to resolve this issue is as follows:

# Related Issue

https://github.com/UKPLab/sentence-transformers/issues/2465

# Steps to Reproduce:

A step-by-step guide to reproduce the issue

- Step 1: Fine-tune a model using Peft & Save the checkpoint
```python
from sentence_transformers import SentenceTransformer, SentenceTransformerTrainingArguments, SentenceTransformerTrainer, losses
from datasets import load_dataset

train_dataset = load_dataset("sentence-transformers/all-nli", "triplet", split="train").select(range(100))
eval_dataset = load_dataset("sentence-transformers/all-nli", "triplet", split="dev").select(range(100))

model_name = "sentence-transformers-testing/stsb-bert-tiny-safetensors" 
model = SentenceTransformer(model_name)

from peft import LoraConfig, TaskType, get_peft_model
peft_config = LoraConfig(
    target_modules=["dense"],
    task_type=TaskType.FEATURE_EXTRACTION,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
)

model._modules["0"].auto_model = get_peft_model(
    model._modules["0"].auto_model, peft_config
)

train_loss = losses.CachedMultipleNegativesRankingLoss(model, mini_batch_size=1)
args = SentenceTransformerTrainingArguments("working_dir")
trainer = SentenceTransformerTrainer(
    model=model,
    args=args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    loss=train_loss,
    evaluator=eval_dataset,
)
trainer.train()
# Error occurs here
model2 = SentenceTransformer("working_dir/checkpoint-39")
```

- Step 2: Try loading the model in SentenceTransformers
```python
model = SentenceTransformer("/path/to/checkpoint-1500")
model.encode("test")
```
# Expected Behavior:

```python
>>> model = SentenceTransformer("/path/to/checkpoint-1500")
>>> model.encode("test")
array([-1.8156642 , -0.8060007 ,  6.0228686 , ...,  1.5834119 ,
        3.6425464 , -0.10119231], dtype=float32)
```

# Actual Behavior:

The following error occurs:

```python
>>> model = SentenceTransformer("/path/to/checkpoint-1500")
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /path/to/checkpoint
```

# Root Cause

When using a model fine-tuned with Peft, the model only includes [the differences in the adapter part from the base model](https://huggingface.co/blog/peft) and does not contain config.json or the model files. In contrast, in transformers, AutoModel uses [find_adapter_config_file](https://github.com/huggingface/transformers/blob/698b36da72ae8377fb08ade92b131069898007c2/src/transformers/models/auto/auto_factory.py#L499-L514C21) to locate the base_model_name_or_path written in adapter_config.json and assigns it to the base model. However, in SentenceTransformers, the __init__ method of the Transformer class tries to find config.json without [checking adapter_config.json](https://github.com/UKPLab/sentence-transformers/blob/78553270abc74f44c1504db0e29f79591af6b697/sentence_transformers/models/Transformer.py#L57). Since there is no config.json or model file, the following error occurs:

# Environment:

- Python: 3.8.19
- SentenceTransformers: 3.1.1

**Comment by tomaarsen** [comment]
Thanks for closing! Feel free to verify whether it works now since v3.3.0.

- Tom Aarsen
