### ISSUE TITLE
StaticEmbedding forces tokenizers dependency

### ISSUE THREAD

**Issue by rasmi** [UKPLab/sentence-transformers#2986]
In the latest release [StaticEmbedding.py](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/models/StaticEmbedding.py) adds a `tokenizers` dependency. Before this, there was no such dependency. The library now fails to build unless `tokenizers` is installed (it is not declared in [pyproject.toml](https://github.com/UKPLab/sentence-transformers/blob/master/pyproject.toml)). It would be great to keep `tokenizers` as an optional dependency rather than force its installation.

**Comment by rasmi** [comment]
@tomaarsen FYI!

**Comment by tomaarsen** [comment]
Hello!

You're right - I didn't realise this might be a problem because `transformers` has `tokenizers` as a mandatory dependency (I think?)
Is there a situation where someone might not have it installed? If so, I can wrap the `tokenizers` import so that it's okay if it's not installed.

- Tom Aarsen

**Comment by rasmi** [comment]
Thanks Tom! `tokenizers` is optional in `transformers`, it just defaults to the built-in slow `PreTrainedTokenizer` if the fast ones are not available. I know it's an edge case!

**Comment by tomaarsen** [comment]
I'm looking into it now, and I can't find `tokenizers` being optional. Maybe it was optional in the past?
If I uninstall `tokenizers`, then this starts failing:
```
from transformers import AutoModel
```

- Tom Aarsen

**Comment by rasmi** [comment]
You are correct, my sincerest apologies. I had seen tokenizers listed under [extras["tokenizers"]](https://github.com/huggingface/transformers/blob/main/setup.py#L289) but did not notice it is also under the [core dependencies](https://github.com/huggingface/transformers/blame/main/setup.py#L431). In the codebase, models/imports that require it are wrapped in a lot of `is_tokenizers_available` calls (which raises `OptionalDependencyNotAvailable` errors), so `transformers` does work with the built-in slow `PreTrainedTokenizer` in cases where the fast ones are not available. Would you welcome a PR that does this?

**Comment by tomaarsen** [comment]
I spoke with the `transformers` team and they're moving towards `tokenizers` being a strong required dependency, i.e. moving away from the `is_tokenizers_available` calls. As a result, I'll keep `tokenizers` as a mandatory dependency in `sentence-transformers` via `transformers`, and I'll close the PR and this issue.

I hope this doesn't disrupt your usage too much!

- Tom Aarsen
