### ISSUE TITLE
Feature request: add MCC to `BinaryClassificationEvaluator`

### ISSUE THREAD

**Issue by umarbutler** [UKPLab/sentence-transformers#3027]
I'd like to request having `BinaryClassificationEvaluator` output [Matthews correlation coefficient](https://en.wikipedia.org/wiki/Phi_coefficient) given its popularity as a metric for evaluating binary classifiers. It is generally preferred over F1 because it takes the entirety of confusion matricies into account.

**Comment by tomaarsen** [comment]
Hello!

Thanks for opening this. I'm open to adding this feature, although I'm currently busy taking care of other issues and PRs, so I won't be able to prioritize this for a while.

- Tom Aarsen

**Comment by rafaelgpaves** [comment]
Hi! I'm new to this project, but can I try working on this issue?

**Comment by JINO-ROHIT** [comment]
Hi @rafaelgpaves are you working on this? or @tomaarsen id like to take this up

**Comment by reissaavedra** [comment]
Hi @JINO-ROHIT  @tomaarsen,

I would like to work on this issue if it's still open and no one else has taken it. Please let me know if there are any specific requirements or guidelines I should follow. Looking forward to contributing!

**Comment by rafaelgpaves** [comment]
@JINO-ROHIT @tomaarsen @reissaavedra feel free to work on this!

**Comment by JINO-ROHIT** [comment]
@rafaelgpaves sure ill take this up

**Comment by fkdosilovic** [comment]
@tomaarsen Looks like this issue can be closed.

**Comment by tomaarsen** [comment]
It can indeed, thanks for pinging @fkdosilovic

- Tom Aarsen
