### ISSUE TITLE
You should probably activate truncation and/or padding

### ISSUE THREAD

**Issue by aRookieMan** [UKPLab/sentence-transformers#308]
When run the code on chinses dataset (already converted to chinese bert), it shows:

> <ipython-input-24-64d1585986b7> in <module>
      4          evaluation_steps=1000,
      5          warmup_steps=2,
----> 6          output_path='./save'
      7          )
~/anaconda3/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in fit(self, train_objectives, evaluator, epochs, steps_per_epoch, scheduler, warmup_steps, optimizer_class, optimizer_params, weight_decay, evaluation_steps, output_path, save_best_model, max_grad_norm, fp16, fp16_opt_level, local_rank)
    385 
    386                     try:
--> 387                         data = next(data_iterator)
    388                     except StopIteration:
    389                         #logging.info("Restart data_iterator")
~/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    613         if self.num_workers == 0:  # same-process loading
    614             indices = next(self.sample_iter)  # may raise StopIteration
--> 615             batch = self.collate_fn([self.dataset[i] for i in indices])
    616             if self.pin_memory:
    617                 batch = pin_memory_batch(batch)
~/anaconda3/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in smart_batching_collate(self, batch)
    247 
    248             for text in paired_texts[idx]:
--> 249                 sentence_features = self.get_sentence_features(text, max_len)
    250 
    251                 for feature_name in sentence_features:
~/anaconda3/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in get_sentence_features(self, *features)
    185 
    186     def get_sentence_features(self, *features):
--> 187         return self._first_module().get_sentence_features(*features)
    188 
    189     def get_sentence_embedding_dimension(self):
~/anaconda3/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py in get_sentence_features(self, tokens, pad_seq_length)
     59         """
     60         pad_seq_length = min(pad_seq_length, self.max_seq_length) + 3 #Add space for special tokens
---> 61         return self.tokenizer.prepare_for_model(tokens, max_length=pad_seq_length, pad_to_max_length=True, return_tensors='pt', truncation=True)
     62 
     63     def get_config_dict(self):
~/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py in prepare_for_model(self, ids, pair_ids, add_special_tokens, padding, truncation, max_length, stride, pad_to_multiple_of, return_tensors, return_token_type_ids, return_attention_mask, return_overflowing_tokens, return_special_tokens_mask, return_offsets_mapping, return_length, verbose, prepend_batch_axis, **kwargs)
   2096 
   2097         batch_outputs = BatchEncoding(
-> 2098             encoded_inputs, tensor_type=return_tensors, prepend_batch_axis=prepend_batch_axis
   2099         )
   2100 
~/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py in __init__(self, data, encoding, tensor_type, prepend_batch_axis)
    157         self._encodings = encoding
    158 
--> 159         self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
    160 
    161     @property
~/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py in convert_to_tensors(self, tensor_type, prepend_batch_axis)
    513             except:  # noqa E722
    514                 raise ValueError(
--> 515                     "Unable to create tensor, you should probably activate truncation and/or padding "
    516                     "with 'padding=True' 'truncation=True' to have batched tensors with the same length."
    517                 )
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length.

How to fix this problem?

**Comment by nreimers** [comment]
Can you post some example code that leads to this error?

**Comment by aRookieMan** [comment]
`word_embedding_model = models.Transformer('../BERT_pretrain')`
`pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)`
`model = SentenceTransformer(modules=[word_embedding_model, pooling_model])`
`train_data = SentencesDataset(point_reader.get_examples('point_train.txt'), model=model)`
`train_loss = losses.SoftmaxLoss(model=model, sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=2)`

It is following your demo, and I re-write the reader for chinese dataset, it turn the data into your InputExample, like:

`point_reader.get_examples('point_train.txt')[0].__dict__`
`{'guid': 'point_train.txt-0',
 'texts': ['多功能切菜神器', '这个切菜神器太好用了'],
 'label': 1}`

../BERT_pretrain is downloaded from huggingface, it is not problem in tokenizing/embedding

**Comment by aRookieMan** [comment]
word_embedding_model = models.Transformer('../BERT_pretrain')

pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])

point_reader = PointWiseReader('./')

train_data = SentencesDataset(point_reader.get_examples('point_train.txt'), model=model)
dev_data = SentencesDataset(point_reader.get_examples('point_test.txt'), model=model)

train_dataloader = DataLoader(train_data, shuffle=True, batch_size=64)
dev_dataloader = DataLoader(dev_data, shuffle=False, batch_size=64)

evaluator = EmbeddingSimilarityEvaluator(dev_dataloader)

train_loss = losses.SoftmaxLoss(model=model, sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=2)

model.fit(train_objectives=[(train_dataloader, train_loss)],
         evaluator=evaluator,
         epochs=50,
         evaluation_steps=1000,
         warmup_steps=2,
         output_path='./save'
         )

this is my code, and I re-write the reader for chinese dataset, it turn the data into your InputExample, like:

`point_reader.get_examples('point_train.txt')[0].__dict__
{'guid': 'point_train.txt-0', 'texts': ['多功能切菜神器', '这个切菜神器太好用了'], 'label': 1}`

**Comment by aRookieMan** [comment]
> Can you post some example code that leads to this error?

word_embedding_model = models.Transformer('../BERT_pretrain')

pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
pooling_mode_mean_tokens=True,
pooling_mode_cls_token=False,
pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])

point_reader = PointWiseReader('./')

train_data = SentencesDataset(point_reader.get_examples('point_train.txt'), model=model)
dev_data = SentencesDataset(point_reader.get_examples('point_test.txt'), model=model)

train_dataloader = DataLoader(train_data, shuffle=True, batch_size=64)
dev_dataloader = DataLoader(dev_data, shuffle=False, batch_size=64)

evaluator = EmbeddingSimilarityEvaluator(dev_dataloader)

train_loss = losses.SoftmaxLoss(model=model, sentence_embedding_dimension=model.get_sentence_embedding_dimension(), num_labels=2)

model.fit(train_objectives=[(train_dataloader, train_loss)],
evaluator=evaluator,
epochs=50,
evaluation_steps=1000,
warmup_steps=2,
output_path='./save'
)

this is my code, and I re-write the reader for chinese dataset, it turn the data into your InputExample, like:

point_reader.get_examples('point_train.txt')[0].__dict__ {'guid': 'point_train.txt-0', 'texts': ['多功能切菜神器', '这个切菜神器太好用了'], 'label': 1}

**Comment by aRookieMan** [comment]
I get the problem. Because latest transformer(huggingface) introduces "tensor.ndim" but my torch version is 1.0.1 which did not contain this attribute.
Thanks for your quick reply!

**Comment by aRookieMan** [comment]
Which version is suitable for transformer 2.x? Because I can not upgrade my pytorch

**Comment by aRookieMan** [comment]
0.2.x is worked for transformer 2.x
