### ISSUE TITLE
AttributeError: 'BertTokenizer' object has no attribute 'unique_added_tokens_encoder'

### ISSUE THREAD

**Issue by saipavanmeruga** [UKPLab/sentence-transformers#309]
I have run into this error, 

> AttributeError: 'BertTokenizer' object has no attribute 'unique_added_tokens_encoder'

hoping it has something to do with environment variables

package | version
------------ | -------------
torch | 1.5.1
transformers| 2.11.0
sentence-transformers|0.2.6.1
python|3.7.6

**Comment by nreimers** [comment]
How does your code look like?

Have you tried the most recent version (0.3.0) of sentence-transformers, that works with transformers version 3?

**Comment by saipavanmeruga** [comment]
No i did not install the most recent version  of sentence-transformers(0.3.0)..

I will try and let you know. 

Speaking of code, i think it is more like a dependencies issue.... so let me try with the earliest possible versions.....

**Comment by saipavanmeruga** [comment]
Yaa installing latest version of sentence-transformers worked......

thanks for the help @nreimers
