### ISSUE TITLE
multiplingual sentence embedding: Do I need to preprocess training data?

### ISSUE THREAD

**Issue by Brucewuzhang** [UKPLab/sentence-transformers#315]
Thanks for making this repo.

I want to fine-tune an en-zh sentence embedding model. My question is: Do I need to preprocess the training data beforehand?
I read the multilingual sentence embedding readme file and found that it looks like, for English and German, you didn't do preprocess like tokenization.

I want to know whether I need to preprocess the Chinese training sentences. Is it necessary to do word segmentation for Chinese training sentences? If yes, what segmentation should I use? if not, do I need to remove whitespaces between Chinese characters?

**Comment by nreimers** [comment]
Hi,
No preprocessing is required when you use XLM-R. XLM-R uses Sentencepiece, which is also able to segment chinese.

For mBERT, you wold need to tokenize the text. 

In my experience, XLM-R works better than mBERT. 

Best 
Nils Reimers

**Comment by Brucewuzhang** [comment]
> Hi,
> No preprocessing is required when you use XLM-R. XLM-R uses Sentencepiece, which is also able to segment chinese.
> 
> For mBERT, you wold need to tokenize the text.
> 
> In my experience, XLM-R works better than mBERT.
> 
> Best
> Nils Reimers

Got it. Thanks a lot.
