### ISSUE TITLE
README, Model Training from Scratch

### ISSUE THREAD

**Issue by antgr** [UKPLab/sentence-transformers#32]
You mention models variable, but it is nowhere instantiated. What is this variable?
```
# Use BERT for mapping tokens to embeddings
word_embedding_model = models.BERT('bert-base-uncased')
```

**Comment by nreimers** [comment]
See
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training_nli_bert.py


Line 8

models is package, that contains the different available models.

Best regards 
Nils Reimers

**Comment by antgr** [comment]
Thanks a lot!
