### ISSUE TITLE
train transformer on indonesian

### ISSUE THREAD

**Issue by AjiNugroho** [UKPLab/sentence-transformers#325]
hi @nreimers 

can i make this transformer trained in indonesian,just by changing the datasets ? 
or maybe i need to change some configurations ?
i want to make similarity task.
please tell me how to make it done, i am very beginner in this.
thanks

**Comment by nreimers** [comment]
Hi @AjiNugroho 
You must select a multilingual transformer model like mBERT or XLM-R. In the best case, that base model was trained for Indonesian.

Here is an example how you can extend existing sentence embeddings methods to new languages:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training_multilingual/make_multilingual.py

There, you only need to change the language code ( / the datasets).

Best
Nils Reimers

**Comment by AjiNugroho** [comment]
great thanks @nreimers
