### ISSUE TITLE
Is it possible to encode by using multi-GPU?

### ISSUE THREAD

**Issue by z307287280** [UKPLab/sentence-transformers#33]
Thanks for this beautiful package, it saves a lot of work to do semantic embedding. I am running a large size data base trying to transform docs into embedding matrix. When I was running with the code, it seemed only using single GPU to encode the sentence. Is there any way that I could do this by multi-GPU?

**Comment by nreimers** [comment]
Hi,
It is not directly implemented in the package, but as the model is a simple pytorch nn.module, achieving a multi GPU version should be quite easy:
https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#create-model-and-dataparallel

Just wrap the sentence embeddings model in the DataParallel module and it should run on multiple GPUs

Best regards 
Nils Reimers

**Comment by z307287280** [comment]
> Hi,
> It is not directly implemented in the package, but as the model is a simple pytorch nn.module, achieving a multi GPU version should be quite easy:
> https://pytorch.org/tutorials/beginner/blitz/data_parallel_tutorial.html#create-model-and-dataparallel
> 
> Just wrap the sentence embeddings model in the DataParallel module and it should run on multiple GPUs
> 
> Best regards
> Nils Reimers

Thank you very much, Sir! I also come up with another framework, but I am not sure if it is able to work. I would like to create different embedder and use multiprocessing package to parallel the processing. Do you think this will have the same effect as after wrapping the sentence embeddings model in the DataPrallel module?

**Comment by nreimers** [comment]
Sorry, I am not sure completely what you mean / want to achieve.

You should be careful how to paralize your processing. Each pipeline should take about the same time. 

Assume you have 4 encoders and paralize along the encoders dimension. You have an issue if one encoder takes much longer, because the other 3 pipelines will stay idle.

If you parallize along the data dimension, then you ensure that each mini batch will tack roughly the same time.

**Comment by z307287280** [comment]
> Sorry, I am not sure completely what you mean / want to achieve.
> 
> You should be careful how to paralize your processing. Each pipeline should take about the same time.
> 
> Assume you have 4 encoders and paralize along the encoders dimension. You have an issue if one encoder takes much longer, because the other 3 pipelines will stay idle.
> 
> If you parallize along the data dimension, then you ensure that each mini batch will tack roughly the same time.

Thanks for your patient, Sir. I'm trying to use this package to encode a large size database into semantic embeddings. I have four GPU available and only one is running on the processing stage. This is not efficient, therefore, I would like to use all my GPUs to speed up the entire processing.

**Comment by chaochaoSZ** [comment]
@z307287280 Have you solved this problem? Can you please share your modification?

**Comment by z307287280** [comment]
Yes.

chaochaoSZ <notifications@github.com>于2020年1月7日 周二05:30写道：

**Comment by z307287280** [comment]
> @z307287280 Have you solved this problem? Can you please share your modification?

Try using multiprocessing in python and start several threads to create different models. 
You are able to assign different cuda to your models respectively. But remember the multiprocessing
can only deal with dataset smaller than 4GB, if you have larger dataset you should also use a minibatch processing to handle it.

**Comment by chaochaoSZ** [comment]
Thank you for your response. A little complex, I don't know why DataParallel can't work.

**Comment by z307287280** [comment]
I believe the initial training structure determined how the model would
process, our  model is a pre-trained model whose structure has been shaped
already. But my statement could be wrong.

**Comment by XiaomoWu** [comment]
Wrapping `SentenceTransformer` with `nn.DataParallel` won't enable multiple GPU because `SentenceTransformer` explicitly send the features to a *single* device. See line 140 of the source code, notice there's a `.to(device)` and the end of the line.

I make `SentenceTransformer` utilize multiple GPUs by refactoring the source code. Unfortunately, however, that will break the original logics and make other methods in `SentenceTransformer` incompatible, so I didn't submit a pull request. 

By refactoring I gained a ~1.5x improvement on two 2080 Ti.

Hope the following code help (suppose you only need inference):
```python
model_path = "%userprofile%/.cache/torch/sentence_transformers/public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_roberta-large-nli-stsb-mean-tokens.zip"

with open(os.path.join(model_path, 'modules.json')) as fIn:
    contained_modules = json.load(fIn)
    
sbert_modules = OrderedDict()
for module_config in contained_modules:
    module_class = sentence_transformers.util.import_from_string(module_config['type'])
    module = module_class.load(os.path.join(model_path, module_config['path']))
    sbert_modules[module_config['name']] = module

# enable parallelism by `nn.DataParallel`
sbert_model = nn.Sequential(sbert_modules)
sbert_model = nn.DataParallel(sbert_model)
sbert_model.to(cuda0);

# one example
text = 'John eats apples with chopsticks.'
text_tokenized = sbert_modules[next(iter(sbert_modules))].tokenize(text)
text_features = sbert_modules[next(iter(sbert_modules))].get_sentence_features(text_tokenized, len(text_tokenized))
sbert_model(one_sample)['sentence_embedding'] # tensor([[ 1.4187, -0.2005, -0.0884,  ..., -1.4601,  1.3423,  0.7136]], device='cuda:0', grad_fn=<GatherBackward>)
```

You may want to use a `Dataset` and `DataLoader` to prepare the data.

**Comment by alexgtom** [comment]
So I think I was able to get multi GPU working by doing the following:

```nn.DataParallel(SentenceTransformer(modules=modules, device="cuda:0" if torch.cuda.is_available() else "cpu"))```

And then instead of calling `model.get_sentence_embedding_dimension()`, you do `model.module.get_sentence_embedding_dimension()` instead.

**Comment by rjurney** [comment]
@XiaomoWu How do you call the encode() method on a GPU using a list of strings, which SentenceTransformers.encode() takes.

**Comment by farhaanbukhsh** [comment]
hey @nreimers Just wanted your opinion on the approach,

I have multiple GPUs and I wanted to parallelize generation of embeddings for bert. Since sentence transformer doesn't have multi GPU support.
We thought we would use python's multiprocessing and for each of the process we will instantiate `SentenceTransformer` and pass a different device name for it to use.

That way we will have multiple instances that can use 1 GPU each, and then we divided the data and pass it to each instance. For some odd reason after a while we don't get embeddings back.

Sample Code:

```

def embed_tokens_with_gpu(tokens: List[str]):
      number_of_devices = len(devices())
      device_names = _get_device_names()
      pool = mp.get_context("spawn").Pool(number_of_devices)
      total_chunks = split_lists(tokens, number_of_devices)
      for index, chunk in enumerate(total_chunks):
           device_name = device_names[index]
           pool.apply_async(embed_chunks, args=(device_name, chunk), callback=call_back_function)
      pool.close()
      pool.join()

def embed_chunks( device_name: str, chunk: List[str]) -> Dict[str, np.ndarray]:
      embedding_map = {}
      model = SentenceTransformer(self._sentence_transformer_model_name(), device=device_name)
      embeddings = model.encode(chunk, 1028, show_progress_bar=True)
      for token, embedding in zip(chunk, embeddings):
          embedding_map[token] = embedding
      return embedding_map
```

Here in ` embed_tokens_with_gpu` we divide the tokens that we want to embed and then create multiple processes and pass the batch of tokens to the process with device name to be used.

Ideally this should embed and return back the embedding, but there are times where it doesn't return anything and the `call_back_function` is not called at all. Are we missing something can we do it in some better way?

We even tried @z307287280 way to limit the tokens on the basis of data size but that also didn't help us much.

Any help will be appreciated, thanks in advance.

**Comment by z307287280** [comment]
Try to use starmap instead of apply_async. If I remember it correctly,
apply_async only accepts one argument but in your function there are multi.
Hope it could help

Farhaan Bukhsh <notifications@github.com>于2020年7月14日 周二21:39写道：

**Comment by farhaanbukhsh** [comment]
@z307287280 it's a function call, IMHO I don't think that can be an issue, and it does give back data for few iteration only after few iteration it stops giving back data.

**Comment by nreimers** [comment]
Hi @farhaanbukhsh
Are you maybe running out of memory?

```
embeddings = model.encode(chunk, 1028, show_progress_bar=True)
```

Here you specify a batch size of 1028, which will lead to an out-of-memory on all GPUs as soon as your sentences get a few more tokens.

Try instead:
embeddings = model.encode(chunk, 8, show_progress_bar=True)

and see if it works then.

**Comment by farhaanbukhsh** [comment]
> Hi @farhaanbukhsh
> Are you maybe running out of memory?
> 
> ```
> embeddings = model.encode(chunk, 1028, show_progress_bar=True)
> ```
> 
> Here you specify a batch size of 1028, which will lead to an out-of-memory on all GPUs as soon as your sentences get a few more tokens.
> 
> Try instead:
> embeddings = model.encode(chunk, 8, show_progress_bar=True)
> 
> and see if it works then.

Okay @nreimers let me try that :smile: thanks for the help

**Comment by farhaanbukhsh** [comment]
> Hi @farhaanbukhsh
> Are you maybe running out of memory?
> 
> ```
> embeddings = model.encode(chunk, 1028, show_progress_bar=True)
> ```
> 
> Here you specify a batch size of 1028, which will lead to an out-of-memory on all GPUs as soon as your sentences get a few more tokens.
> 
> Try instead:
> embeddings = model.encode(chunk, 8, show_progress_bar=True)
> 
> and see if it works then.

Tired this and again the same behaviour it ran fine for few chunks but then it stopped returning back the embeddings

**Comment by vijender412** [comment]
Hi,
 I have 59k lines to embed. It takes 1-2 hr on CPU. Is there any other way to use multiple GPU excluding **nn.DataParallel**

**Comment by nreimers** [comment]
Hi @vijender412 
Multi-GPU support is currently not implemented.

Embedding 59k lines on a recent (single) GPU should take about 59 seconds, maybe even less.

I can recommend to use the DistilBERT models. They are faster and the performance is quote on par to the BERT / RoBERTa models.

**Comment by vijender412** [comment]
@nreimers Thanks for updating so quick. 
For single GPU what changes need to be done in default parameters. model.encode(59k_data).

**Comment by nreimers** [comment]
Hi @vijender412 
No changes is needed. If pytorch can access you GPU, the model will run on the GPU.

You can test with:
import torch
torch.cuda.is_available()

**Comment by vijender412** [comment]
@nreimers Thanks very much. I got superb results now. I thought I was using gpu but due to pytorch lower version issue it was not using GPU. Now working.
JYI: For my usecase Distilbert is taking 9sec for 10k data and Bert is taking 16 sec for 10k data.

**Comment by rjurney** [comment]
I’ve done this recently and used multiprocessing.Pool or pytorch.multiprocessing.Pool. The trick was that you can’t pass large datasets via Pool.map. I had to partition the data and load it inside each map function and have the GPU encode it there. I pre-encoded the sentences as BERT tokens using the embedding I was Pooling into SentenceBERT using Dask to scale it but would use transformers/encoders on a second try.

**Comment by PetreanuAndi** [comment]
Hey guys. I get no benefit from batching (no speedup whatsoever) Sentence-Transformer.
I would love your opinion on the following situation : 

I run inferences on 'bert-base-nli-mean-tokens' model with fake input, for the sake of bench-marking : 
'text ' * 512 ( basically i want to make sure the batches always have 512 tokens ) 'text text text .... text '

If I run with **128 batch-size**, I get inference speed of about **1.82 seconds** (on average) for the whole batch.
I'm only timing the model.encode method.

If i run with **32 batch-size**, I get inference speed of about **0.46 seconds** (on average) for the whole batch.
Now, 0.46 * 4 = 1.84 ==> batching does nothing to help me with optimisation / paralelisation of inference etc.

I was expecting better results, in terms of inference speed, with higher batches.
Locally, I am on a 2080Ti GPU machine, with "544 tensor cores" as per NVidia documentation.
I have replicated the same exact behavior on a K80 device in the cloud.(much lower inference speeds overall, but the same no-speedup efect)

Why is Sentence-Transformer behaving this way?
Thank you, I would really appreciate some insights.

**Comment by bwang482** [comment]
To answer the original question, is `start_multi_process_pool()` not made for this purpose?

**Comment by nreimers** [comment]
@bwang482 Yes, it was added to enable multi GPU encoding.

**Comment by bwang482** [comment]
Thanks @nreimers !

However, looking at the source code for [encode_multi_process](https://github.com/UKPLab/sentence-transformers/blob/6225f780fb7c04a9224d0b75e46dc5157f229cac/sentence_transformers/SentenceTransformer.py#L282). It has `chunk_size` for param which is defined as:

>  :param chunk_size: Sentences are chunked and sent to the individual processes. If none, it determine a sensible size.

My corpus contains only multi-word expressions (MWEs) and I really don't want to chunk any of the MWEs. My `CUDA out of memory` error only occurs during `all_embeddings = torch.stack(all_embeddings)`. How do I set this `chunk_size` param or do I not need to worry about it?

**Comment by nreimers** [comment]
You don't need to worry about that

**Comment by andreabac3** [comment]
Good morning everyone,
do you know if it is possible to train on more gpus?

Kind regards,
Andrea Bacciu

**Comment by jonhilgart22** [comment]
> Wrapping `SentenceTransformer` with `nn.DataParallel` won't enable multiple GPU because `SentenceTransformer` explicitly send the features to a _single_ device. See line 140 of the source code, notice there's a `.to(device)` and the end of the line.
> 
> I make `SentenceTransformer` utilize multiple GPUs by refactoring the source code. Unfortunately, however, that will break the original logics and make other methods in `SentenceTransformer` incompatible, so I didn't submit a pull request.
> 
> By refactoring I gained a ~1.5x improvement on two 2080 Ti.
> 
> Hope the following code help (suppose you only need inference):
> 
> ```python
> model_path = "%userprofile%/.cache/torch/sentence_transformers/public.ukp.informatik.tu-darmstadt.de_reimers_sentence-transformers_v0.2_roberta-large-nli-stsb-mean-tokens.zip"
> 
> with open(os.path.join(model_path, 'modules.json')) as fIn:
>     contained_modules = json.load(fIn)
>     
> sbert_modules = OrderedDict()
> for module_config in contained_modules:
>     module_class = sentence_transformers.util.import_from_string(module_config['type'])
>     module = module_class.load(os.path.join(model_path, module_config['path']))
>     sbert_modules[module_config['name']] = module
> 
> # enable parallelism by `nn.DataParallel`
> # you only need to send the model to one device (here in the example, 'cuda:0'),
> # and pytorch will automatically copy the model to every available GPU
> sbert_model = nn.Sequential(sbert_modules)
> sbert_model = nn.DataParallel(sbert_model)
> sbert_model.to('cuda:0');
> 
> # one example
> text = 'John eats apples with chopsticks.'
> text_tokenized = sbert_modules[next(iter(sbert_modules))].tokenize(text)
> text_features = sbert_modules[next(iter(sbert_modules))].get_sentence_features(text_tokenized, len(text_tokenized))
> sbert_model(one_sample)['sentence_embedding'] # tensor([[ 1.4187, -0.2005, -0.0884,  ..., -1.4601,  1.3423,  0.7136]], device='cuda:0', grad_fn=<GatherBackward>)
> ```
> 
> You may want to use a `Dataset` and `DataLoader` to prepare the data.

For anyone else running into bus errors with `start_multi_process_pool()`, this code worked for me. The only difference is `Transformer` no longer has a `get_sentence_features` method. The updated code looks like this. 
> # one example
> text = 'John eats apples with chopsticks.'
> text_tokenized = sbert_modules[next(iter(sbert_modules))].tokenize(text)
> sbert_model(text_tokenized)['sentence_embedding'] # tensor([[ 1.4187, -0.2005, -0.0884,  ..., -1.4601,  1.3423,  0.7136]], device='cuda:0', grad_fn=<GatherBackward>)

I saw inference time drop about 15% with this
