### ISSUE TITLE
BERT models performing poorly in semantic similarity

### ISSUE THREAD

**Issue by Remorax** [UKPLab/sentence-transformers#330]
BioBERT, and in general, BERT models are giving me poor performance in semantic similarity tasks.

For instance, for the following snippet of code,
```
from sentence_transformers import  models, SentenceTransformer
from scipy import spatial

def cos_sim(a,b):
    return 1 - spatial.distance.cosine(a, b)

model_name = "emilyalsentzer/Bio_ClinicalBERT"

word_embedding_model = models.Transformer(model_name)

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
cos_sim(*model.encode(["fastigial nucleus", "playing guitar"]))

```
I get `0.72` similarity for the words "fastigial nucleus" and "playing guitar". Universal Sentence Encoder gives me 0.028 similarity, which makes sense.

I have observed this for other examples as well. BERT seems to blindly give high similarity scores regardless of the input.

Is there something wrong with the way I am loading the model? Or do BERT models just perform poorly in semantic similarity tasks?

Any help would be greatly appreciated. Thank you!

**Comment by nreimers** [comment]
Hi @Remorax 
yes, BERT out of the box does not give good results. Hence, you must train it on suitable data.

Second, absolute scores are in general not that meaningful (for any sentence embedding model). Instead, you should always look at ratios, e.g. is cos(a,b) > cos(a, c)?

Best
Nils Reimers

**Comment by Remorax** [comment]
Thanks for responding @nreimers. I closed the issue because the bioBERT model I am using is from huggingface, and therefore I realized, not suited for semantic similarity. The pre-trained models given on this repository definitely seem to work better, however I am more interested in the biomedical domain specifically. 

If you have any suggestions for pre-trained BERT-like models that can compute semantic similarity in the biomedical domain, do let me know!

**Comment by nreimers** [comment]
Hi @Remorax 
You could try Specter:
https://arxiv.org/abs/2004.07180

**Comment by Remorax** [comment]
Specter seems to be for embedding papers and documents. Actually, I am more interested in the embeddings of phrases, entities etc in the biomedical domain. Perhaps I should've been clearer :)

**Comment by usamayaseen-veeva** [comment]
@Remorax Just curious, what did you end up using? I am facing the same problem in 2023 :D.

**Comment by Remorax** [comment]
Hi @usamayaseen-veeva , i remember trying [https://github.com/ncbi-nlp/BioSentVec](BioSentVec) but i can't remember what kind of results it gave. Maybe you should check that out, and compare it with a standard Universal sentence encoder baseline which was (then, at least) a strong semantic similarity model
