### ISSUE TITLE
Much faster than Transformers when encoding text

### ISSUE THREAD

**Issue by stevewyl** [UKPLab/sentence-transformers#333]
Hi, thanks fo this fantastic repo and its documentation!
I have trained an SBERT model on my own dataset. But I found SentenceTransformer is much faster than Transformers when encoding text. 
Environment info: 
- GTX 1080 Ti
- Docker Image: nvcr.io/nvidia/pytorch:20.06-py3
- Torch Version: 1.6.0a0+9907a3e
- transformers Version: 3.0.2
- sentence_transformers: 0.3.2

Following codes for testing inference speed
```python
from transformers import AutoModel, AutoTokenizer
from sentence_transformers import SentenceTransformer

model_dir = "/bert_models/ssc_pairwise_roberta"
sent = "今天天气不错" # The weather is nice today

model_sbert = SentenceTransformer(model_dir)
model_pt = AutoModel.from_pretrained(model_dir + "/0_Transformer")
tokenizer = AutoTokenizer.from_pretrained(model_dir + "/0_Transformer")

# 6.63 ms ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit vec_a = model_sbert.encode([sent], output_value="token_embeddings")[0]
 
features = tokenizer.encode_plus(sent, add_special_tokens=True, return_tensors="pt") 
# 23.2 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit vec_b = model_pt(features["input_ids"])[0]
```
I have checked the value of `vec_a` and `vec_b` is the same. So I'm curious why SentenceTransformer (which is build on Transformers) is almost 4x faster than Transformers?

Appreciate any response!

**Comment by nreimers** [comment]
This is strange. model_sbert.encode() should be slower, as it tokenizes the text each time, while for model_pt(), you already pass the tokenized text.

Reasons could be: 
- In your code, model_pt  was not moved to the GPU. By default, it runs on the CPU. SentenceTransformer automatically detects a GPU and uses it, if available
- Sometimes GPU needs to "get warm", i.e., the first few iterations are a bit slow. So maybe swap the execution of the two codes and see if the difference persists

**Comment by stevewyl** [comment]
@nreimers Yes, you're right! I'm new to Pytorch, not familiar with Pytorch syntax

I must specify the device to the model and features. And then the inference speed goes to be normal.

```python
model_pt.to("cuda")
features = features.to("cuda")
```
Thanks for your reply！:D
