### ISSUE TITLE
add feature for setting custom tokenizer

### ISSUE THREAD

**Issue by yuwon** [UKPLab/sentence-transformers#338]
Some pre-trained HF transfomers models like KoBERT do not support 3.X tokenizer APIs and there are wrappers e.g. kobert-transformers to support 3.X tokenizer APIs.

When training, in order to use those pre-trained models with sentence-transformers, I'm explicitly setting tokenizer like below.
```python
word_embedding_model = models.Transformer('monologg/kobert')
word_embedding_model.tokenizer = get_tokenizer() # Here, we set tokenizer explicitly

pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model], device=device)
```

For encoding, i'm setting the tokenizer like below after loading the fine-tunned model.
```python
model = SentenceTransformer(path, device=device)
model._first_module().tokenizer = get_tokenizer()
```

As you can notice in the above code, i'm calling "private" method `_first_module()` to set the custom tokenizer to transformer model.

Is this the only way for setting the custom tokenizer? or there is any other way?

If this is the only option, would please add @setter method to SentenceTransformer so that I can set the tokenizer explicitly?

**Comment by nreimers** [comment]
Hi @yuwon 
Thank you for pointing this out. I was not aware that there are models that do not work with the tokenizer APIs.

I while try to make it easier to use a custom tokenizer.

**Comment by nreimers** [comment]
Hi @yuwon 
Just added the needed code to my local branch. It will be available in the next version.

Then, you can use:
```
model.tokenizer = TheTokenizerYouNeed()
```

**Comment by yuwon** [comment]
Hi @nreimers! Thanks for super fast response!!
