### ISSUE TITLE
Which version of CUDA is required to train this model?

### ISSUE THREAD

**Issue by vibhormalik97** [UKPLab/sentence-transformers#339]
I am using CUDA version 10.0 and torch version 1.5.0. However, torch.cuda.is_available() returns False. Any idea why this might be happening?

**Comment by nreimers** [comment]
Have a look here:
https://pytorch.org/get-started/locally/

Pytorch does not support CUDA 10.0, only 9.2, 10.1 and 10.2

**Comment by vibhormalik97** [comment]
Thanks!
