### ISSUE TITLE
fp16 Opt level typo?

### ISSUE THREAD

**Issue by pertschuk** [UKPLab/sentence-transformers#34]
Hi - 
```
RuntimeError: Unexpected optimization level 01. Options are 'O0', 'O1', 'O2', 'O3'.  Note that in `O0`, `O1`, etc., the prefix O is the letter O, not the number zero.
```
see https://github.com/NVIDIA/apex/issues/339 😓

in SentenceTransformer.fit (default kwargs).

**Comment by nreimers** [comment]
Thank you for reporting. I fixed it and it will be part of the next release.
