### ISSUE TITLE
Examples are broken since evaluator change.

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#344]
Hi,
since the evaluator change (`Change Evaluators so that these directly accepts sentences & labels/scores instead of a dataloader`): https://github.com/UKPLab/sentence-transformers/commit/0481ece42d614f162fa4cab9106a52f7118fa2d4

.. the examples are broken. They are getting an `DataLoader`instead of `sentences1: List[str], sentences2: List[str], labels: List[int]`.

This should be fixed...

If you would tell me how to use `SentencesDataset` and `DataLoader` with the new implementation - I would provide a PR for the examples.

**Comment by PhilipMay** [comment]
Well I found it. https://github.com/UKPLab/sentence-transformers/blob/master/examples/training_transformers/training_nli.py#L60

If you agree I would prepare a PR to fix the other examples.

**Comment by nreimers** [comment]
Hi @PhilipMay 
Thanks for pointing this out. I didn't have the updates commited.

Now all examples should work with the new structure. Please let me know if you find further instances where the old evaluators code is used with a DataLoader.

Best
Nils

**Comment by PhilipMay** [comment]
Great! Thanks @nreimers

**Comment by PhilipMay** [comment]
Will close this for now. I I find a problem I will just reopen.
