### ISSUE TITLE
TypeError: prepare_for_model() got an unexpected keyword argument 'truncation'

### ISSUE THREAD

**Issue by amloewi** [UKPLab/sentence-transformers#345]
I followed a very simple example for using a pretrained model, and got the error above -- assuming it's a bug, but could also be a dependency version issue etc perhaps? Didn't see anyone mention it in the open issues.

```
from sentence_transformers import SentenceTransformer
roberta = SentenceTransformer("roberta-large-nli-stsb-mean-tokens")
out = roberta.encode(["A very simple sentence"])
```
=> `TypeError: prepare_for_model() got an unexpected keyword argument 'truncation'`

**Comment by nreimers** [comment]
Hi @amloewi 

I think your transformers library is outdated. Currently, version >= 3.0.2 is needed.

You can update it with:
pip install -U transformers

Best
Nils Reimers

**Comment by amloewi** [comment]
Fixed, thank you so much!
