### ISSUE TITLE
Feature Request: DistilBERT

### ISSUE THREAD

**Issue by 0x01h** [UKPLab/sentence-transformers#35]
Hi,

Encoding large corpora takes really long time using current pretrained models. Could you please add a light model like *DistilBERT* especially for *STS* tasks.

Thank you!

**Comment by nreimers** [comment]
Hi @0x01h 
This will be part of the next release, which I expect to release mid November.

**Comment by claeyzre** [comment]
Hi, will this release include the new transformers repo instead of the pytorch  transformers ? 
Thanks

**Comment by nreimers** [comment]
Yes, that is the plan
