### ISSUE TITLE
Post-training/Transfer Learning

### ISSUE THREAD

**Issue by pashok3d** [UKPLab/sentence-transformers#363]
I've been working on a clustering task using sentence-transformers. Now, I'm going to start working on a classification task for the same/similar domain. I wonder if I can use my fine-tuned sentence-transformers model (as a post-train step), or is it better to fine-tune base model directly via huggingface?

**Comment by nreimers** [comment]
Internally a BERT or similar network is used. This model can be used directly by huggingface transformers and can be used for further downstream tasks. Starting from scratch would not be needed.
