### ISSUE TITLE
Error during running Faiss example

### ISSUE THREAD

**Issue by Adarsh1999** [UKPLab/sentence-transformers#366]
When I was running Faiss example of yours in examples folder and the file name was :- `semantic_search_quora_faiss.py `.  I got an error after indexing all 12500 questions in the corpus and then when it asked to input question and after which it occurred:
`Traceback (most recent call last):
  File "semantic_search_quora_faiss.py", line 118, in <module>
    distances, corpus_ids = index.search(question_embedding, top_k_hits)
  File "/usr/local/lib/python3.7/site-packages/faiss/__init__.py", line 160, in replacement_search
    n, d = x.shape
ValueError: too many values to unpack (expected 2)`.
Can anyone help me out here how to resolve this error?

**Comment by nreimers** [comment]
Hi,
I will check it later the example.

What is the shape of question_embedding you pass to index.search().

It looks like it has the wrong shape. I think it must have the shape 1 x 768. It might be, that it just a vector of 768 dimensions. In that case, you can try:
```
index.search([question_embedding], top_k_hits)
```

**Comment by nreimers** [comment]
Hi @jainal09 @Adarsh1999 

I just pushed a new version (0.3.4). Can you re-try the faiss example? It works for me with the most recent versions pytorch / sentence-transformers / faiss.

Best
Nils Reimers

**Comment by Adarsh1999** [comment]
Ya the example is working fine thank you..
