### ISSUE TITLE
comparable similarity scores in semantic search ? 

### ISSUE THREAD

**Issue by ironllamagirl** [UKPLab/sentence-transformers#368]
Hi. 
I have a question related to the semantic search example application. 

if similarity_score(sentence1, sentence2) > similarity_score(sentence3, sentence2)   could we say that sentence2  is closer in meaning to sentence1 then sentence2 is to sentence3? 

or are the scores only comparable if we have have the same query sentence. 

Thank you.

**Comment by nreimers** [comment]
Hi @ironllamagirl 
Yes, you can say that.

Best
Nils Reimers

**Comment by ironllamagirl** [comment]
Thanks!
