### ISSUE TITLE
Epoch count for training_nli.py

### ISSUE THREAD

**Issue by nandinib1999** [UKPLab/sentence-transformers#370]
Hi,

I was working with training_nli.py and I saw that by default, the number of epochs is set to 1. I want to train the model for the task of semantic similarity. 

How many training epochs do you recommend?

**Comment by nreimers** [comment]
In my experience 3-4 epochs are a good value for semantic similarity.

**Comment by nandinib1999** [comment]
Thanks for your quick reply. 

I am also planning to continue the training with sts benchmark dataset to train nli-stsb model. How many epochs are suitable for training_stsbenchmark_continue_training.py?

**Comment by nreimers** [comment]
Just try it out and you will see what works best

**Comment by nandinib1999** [comment]
Okay, thanks.
