### ISSUE TITLE
Failed to run quickstart code.   IndexError: Dimension out of range

### ISSUE THREAD

**Issue by WangHexie** [UKPLab/sentence-transformers#377]
Running the quickstart code with latest transformers and sentence-transformers repo.

```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distilbert-base-nli-mean-tokens')

sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown fox jumps over the lazy dog.']
sentence_embeddings = model.encode(sentences)
```

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-7-8a9f91e648da> in <module>()
----> 1 sentence_embeddings = model.encode(sentences, convert_to_tensor=True)

7 frames
/usr/local/lib/python3.6/dist-packages/transformers/modeling_distilbert.py in forward(self, input_ids)
    106             The embedded tokens (plus position embeddings, no token_type embeddings)
    107         """
--> 108         seq_length = input_ids.size(1)
    109         position_ids = torch.arange(seq_length, dtype=torch.long, device=input_ids.device)  # (max_seq_length)
    110         position_ids = position_ids.unsqueeze(0).expand_as(input_ids)  # (bs, max_seq_length)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```

**Comment by nreimers** [comment]
Are you sure that this is exactly the code you run? It works without issues for me and the error message indicates that different code is run.

**Comment by WangHexie** [comment]
@nreimers The code to reproduce the error [https://colab.research.google.com/gist/WangHexie/9e158605f3d25820ebb87de358a9ce0e/-testsentencebertforshare.ipynb](https://colab.research.google.com/gist/WangHexie/9e158605f3d25820ebb87de358a9ce0e/-testsentencebertforshare.ipynb)

**Comment by nreimers** [comment]
Hi @WangHexie 
The issue is that you git-clone transformers and install it from sources. 

When installing sentence-transformers, it already installs the correct version of transformers (3.0.2). Cloning from transformers GIT and installing the master is always experimental, as you don't know if the transformers master branch is in a running condition. So it it always better to install a stable release of the different packages e.g. via pip.

So instead of all this git close just do:
```
!pip install sentence-transformers
```

and you are good to go.

**Comment by WangHexie** [comment]
Thanks a lot, problem solved.
