### ISSUE TITLE
EmbeddingSimilarityEvaluatorFromList doesn't exist 

### ISSUE THREAD

**Issue by bartlomiej-matejczy** [UKPLab/sentence-transformers#379]
Hi 
Great repo! I think there is a minor  problem  with the make__multilingual.py 

 File "make_multilingual.py", line 207, in <module>
    test_evaluator = evaluation.EmbeddingSimilarityEvaluatorFromList(data['sentences1'], data['sentences2'], data['scores'], batch_size=inference_batch_size, name=filename, show_progress_bar=False)
AttributeError: module 'sentence_transformers.evaluation' has no attribute 'EmbeddingSimilarityEvaluatorFromList'

It can be fixed by changing the line  206
test_evaluator = evaluation.EmbeddingSimilarityEvaluatorFromList(data['sentences1'], data['sentences2'], data['scores'], batch_size=inference_batch_size, name=filename, show_progress_bar=False)
    evaluators.append(test_evaluator)

 to 

test_evaluator = evaluation.EmbeddingSimilarityEvaluator(data['sentences1'], data['sentences2'], data['scores'], batch_size=inference_batch_size, name=filename, show_progress_bar=False)
    evaluators.append(test_evaluator)

Cheers!

**Comment by nreimers** [comment]
Hi @bartlomiej-matejczy 

Thanks for pointing this out. Fixed it.
