### ISSUE TITLE
GPU multi processing does not encode all documents

### ISSUE THREAD

**Issue by kYann** [UKPLab/sentence-transformers#381]
Hello,

When using GPU multi processing (like here https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/computing_embeddings_mutli_gpu.py) the number of documents in the output does not match the number of documents in input : 

![image](https://user-images.githubusercontent.com/101720/91325983-17601300-e7c4-11ea-81f1-0cdc36555177.png)

I gave 359147 documents in input and on the output I have 355000 embeddings.

Thanks,

**Comment by nreimers** [comment]
Thanks for pointing this out.

It was a bug in the code, that the last chunk was not encoded.

Fixed it with:
https://github.com/UKPLab/sentence-transformers/commit/3f663e369d1e0f366fa9ab9c572634f370c5db9c

It will be part of the next release or else you can install it from source.

Best
Nils Reimers
