### ISSUE TITLE
[question] a way to decode embeddings

### ISSUE THREAD

**Issue by lefnire** [UKPLab/sentence-transformers#382]
Feel free to close if "nah", wondering if there's a way to decode after encode? Turn back into a sentence. Might be some cool experiment to encode say a corpus, mean the embeddings, then decode it as an alternative approach to summarizing very large documents. Longformer for summarization (which isn't yet supported in transformers) limit is 4096 tokens, but if this works (maybe I'm naive) it could summarize with no limit?

**Comment by nreimers** [comment]
Hi @lefnire 
This idea is quite common. Have a look at Autoencoders or at sequence2sequence (encoder-decoder) architectures. This is also used for summarization.

Summarization without limit is not possible. If you have only e.g. 500 dimensions for your text embeddings, you will not be able to squeeze a long doc into that vector. 

In machine translation this approach is quite often used. Before transformers, LSTM2LSTM was used and a 4096 dimensional vector was produces, from which the translation was then generated.

**Comment by lefnire** [comment]
Thanks for the info!

**Comment by Bk073** [comment]
Do you have any implementation for auto-encoder based on transformers?
