### ISSUE TITLE
using model from transformer as teacher model

### ISSUE THREAD

**Issue by acul3** [UKPLab/sentence-transformers#385]
hello

if i have monolingual model that trained on huggingface transformer
and
i want to extend my model using your method https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/multilingual

can i use my monolingual model as teacher model? 
cause it looks like the teacher model must train on SentenceTransformer first (https://github.com/UKPLab/sentence-transformers/blob/3f663e369d1e0f366fa9ab9c572634f370c5db9c/examples/training/multilingual/make_multilingual_sys.py#L101)

do i need to train my monolingual model in SentenceTransformers first so it can be use as teacher model?

thank you

**Comment by nreimers** [comment]
Hi @acul3 
Yes, that example is specifically for SentenceTransformer.

The idea might only work for specific huggingface transformer models. If you have a single sentence classification task, where you have a head on the CLS token, I think the same approach might work.

If you have a more complex task, like sequence tagging or question answering, I think the approach might not work. The idea is to map sentences in different languages to the same point in vector space. This works for single text classification tasks (and sentence embeddings, as shown in the paper), but for NER it is not that helpful that the mean of the tokens map to the same point in vector space independent of the language.

Converting your huggingface model to a SentenceTransformer model is easy, you just add the right pooling on top of it (e.g. mean pooling or using the CLS token):
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

**Comment by acul3** [comment]
okay got it,,thank you for the answer
