### ISSUE TITLE
ES negative score issue!

### ISSUE THREAD

**Issue by gavishpoddar** [UKPLab/sentence-transformers#389]
I am so sorry to ask for support again and again. but there seems to be some other issue. 

Issue:

elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'script_score script returned an invalid score [-0.0033164802] for doc [240]. Must be a non-negative score!')

I checked ES is working properly and all the dummy data is present.

and once again thanks for #387

**Comment by nreimers** [comment]
Can you try to add + 1.0 add line 119:
```
                   "source": "cosineSimilarity(params.queryVector, doc['question_vector']) + 1.0",
```

CosineSim. can have negative scores, but it appears ES does not like that.

**Comment by gavishpoddar** [comment]
Thank you
