### ISSUE TITLE
Model didn't converge when fine-tuning with my own dataset

### ISSUE THREAD

**Issue by WangHexie** [UKPLab/sentence-transformers#391]
I use the summarization dataset and keywords of the content to fine tune the model for search.
But by checking out the evaluation result, the model seems it didn't change before and after.
I've tried different learning rate and loss function, still the same situation. Even use super high learning rate, the evaluation result still keep same.
[https://colab.research.google.com/gist/WangHexie/42089737a5f17f6c4ee173e92bdebea4/sentencebertforfinetuningdebug.ipynb](https://colab.research.google.com/gist/WangHexie/42089737a5f17f6c4ee173e92bdebea4/sentencebertforfinetuningdebug.ipynb)

(And another question: Other than trying different parameters, do you have any trick, process or tool to debug neural network when construct such a project?)

**Comment by WangHexie** [comment]
I misunderstand the formation of InputExample. I thought all input with the same label should be put in the same InputExample. 
Though still confused about how to disguise different  label in BatchHardTripletLoss, I'll try to fix Input and see if problem solved.
`triplets.append(InputExample(texts=[anchor.texts[0], positive.texts[0], negative.texts[0]]))
`

**Comment by WangHexie** [comment]
`triplets.append(InputExample(texts=[anchor.texts[0], positive.texts[0], negative.texts[0]]))
`
This sample code from [here](https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/other/training_batch_hard_trec_continue_training.py) would raise an error. Label is required?

```
/usr/local/lib/python3.6/dist-packages/sentence_transformers/datasets/SentencesDataset.py in __getitem__(self, item)
     30 
     31     def __getitem__(self, item):
---> 32         label = torch.tensor(self.examples[item].label, dtype=self.label_type)
     33         if self.examples[item].texts_tokenized is None:
     34             self.examples[item].texts_tokenized = [self.model.tokenize(text) for text in self.examples[item].texts]

TypeError: must be real number, not NoneType
```

**Comment by nreimers** [comment]
Could you explain a bit more how your data looks like and what you try to achieve?

**Comment by WangHexie** [comment]
data:
[
 [news_`1`, keyword_of_news_`1`, summarization_of_news_`1`],
 [news_`2`, keyword_of_news_`2`, summarization_of_news_`2`],
  ....,
 [news_`n`, keyword_of_news_`n`, summarization_of_news_`n`]
]

I hope I can use the data to fine tune the model for semantic search.

**Comment by WangHexie** [comment]
I also tried assigning  different label to different InputExample, and enlarge margin. But still same result.

**Comment by nreimers** [comment]
I can recommend to use the MultipleNegativesRankingLoss
https://www.sbert.net/docs/package_reference/losses.html#multiplenegativesrankingloss

It is used as an example here:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/quora_duplicate_questions/README.md


Your input pair`s could be `(news_i, keyword_i)` or `(news_i, summarization_i)`. In the first case, the news and the keyword will come close in vector space. In the second case, the news and the summarization will become close in vector space.
