### ISSUE TITLE
Multilingual models on hugging face

### ISSUE THREAD

**Issue by lucaventurini** [UKPLab/sentence-transformers#392]
Hi,

thanks for sharing your models on https://huggingface.co/sentence-transformers ! Do you plan to share also the multilingual ones?

**Comment by nreimers** [comment]
Hi @lucaventurini 
just uploaded the three main multilingual models:
https://huggingface.co/sentence-transformers

The DistilUSE model uses a dense layer on top that projects the 768 dimension to 512 dimensions. Sadly, this custom layer cannot be uploaded to the huggingface model repository.

Best
Nils Reimers

**Comment by lucaventurini** [comment]
Wow! Thank you!
