### ISSUE TITLE
STS training, score normalization [0,1] vs [-1,1]

### ISSUE THREAD

**Issue by cccntu** [UKPLab/sentence-transformers#393]
https://github.com/UKPLab/sentence-transformers/blob/cfd4e3d4d4ac38f2d06438af783f36c94a571bd1/examples/training/sts/training_stsbenchmark.py#L68

The scores are normalized to [0,1], but cosine similarity is in the range of [-1, 1].
Is this a bug, or is this intended?

**Comment by nreimers** [comment]
It tested both back in 2019 and normalizing to 0...1 worked a bit better.

But you could also test easily both and see what works better.
