### ISSUE TITLE
Error downloading dataset in examples

### ISSUE THREAD

**Issue by Adarsh1999** [UKPLab/sentence-transformers#395]
When we run the example/application scripts like `semantic_search_quora_elasticsearch.py` and `semantic_search_quora_faiss.py`  very first time before downloading model to the path we get an error like this:-
`Download dataset
Traceback (most recent call last):
  File "semantic_search_quora_elasticsearch.py", line 37, in <module>
    util.http_get(url, dataset_path)
  File "/home/jainal09/anaconda3/lib/python3.8/site-packages/sentence_transformers/util.py", line 187, in http_get
    os.makedirs(os.path.dirname(path), exist_ok=True)
  File "/home/jainal09/anaconda3/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''`

Which denotes the model is not correctly downloaded into the given path.

**Comment by Adarsh1999** [comment]
I have created a PR for the same https://github.com/UKPLab/sentence-transformers/pull/396
if you want to merge  you can or else can suggest better approach

**Comment by nreimers** [comment]
Thanks for pointing this out.

I fixed the issue in util.http_get and it works now. It will be part of the next release (v0.3.6).

**Comment by nreimers** [comment]
Fixed in the newest version
