### ISSUE TITLE
Can we specify the dimension of the embeddings? 

### ISSUE THREAD

**Issue by WanzhengZhu** [UKPLab/sentence-transformers#397]
Can we specify the dimension of the embeddings? Say, 100-dimension, 200-dimension...

**Comment by nreimers** [comment]
When you create a new model from scratch:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

You can add a Dense layer with a desired number of output dimensions. But you would need to fine-tune this network on suitable data.

Best
Nils Reimers

**Comment by githubrandomuser2017** [comment]
@nreimers I would like to generate 4096-D embeddings to do an apples-to-apples comparison with InferSent, which generates embeddings of that size.

1. When you say that we should add another Dense layer and fine-tune, do you mean that we should fine-tune on the SNLI data (as you did in your paper) or on our custom downstream application?
2. During fine-tuning, does your model freeze the BERT model, or do BERT parameters get updated?

**Comment by nreimers** [comment]
Hi @githubrandomuser2017 
1) Yes, you would need to fine-tune on some data. If you want to compare it with the results in the paper, fine-tuning on NLI and maybe STSb is needed.
2) All BERT parameters are updated

**Comment by githubrandomuser2017** [comment]
@nreimers Thank you.
