### ISSUE TITLE
How to train Semantic Textual Similarity on a dataset without a score entry? 

### ISSUE THREAD

**Issue by abozanona** [UKPLab/sentence-transformers#399]
In [Semantic Textual Similarity](https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/sts) training, you're using `STSbenchmark` dataset, which has two narratives and a score from 0 to 5 to indicate the similarity between the two narratives.

I have a [large dataset](https://www.reddit.com/r/MLQuestions/comments/hbbwvh/what_are_possible_algorithms_i_can_use_for/) that contains only two narratives. The two narratives are considered to be talking about the same idea(They all score 5 out of 5).

How can I train the model on a dataset where all entries have the score 5?

**Comment by nreimers** [comment]
See:
https://www.sbert.net/docs/package_reference/losses.html#multiplenegativesrankingloss
https://www.sbert.net/examples/training/quora_duplicate_questions/README.html
