### ISSUE TITLE
The understanding of training_stsbenchmark..

### ISSUE THREAD

**Issue by guotong1988** [UKPLab/sentence-transformers#4]
The two sentence are NOT concat and input into BERT to get two representation.
And then use cosine loss to train.
Am I right?

I read
![image](https://user-images.githubusercontent.com/4702353/62434976-1bf6fb00-b76d-11e9-9b28-b4dc5d38f1c9.png)
and
![image](https://user-images.githubusercontent.com/4702353/62435044-64aeb400-b76d-11e9-84ba-17a9e9aff307.png)

Am I right?

**Comment by nreimers** [comment]
Yes, you are right. This allows you to generate idenpendet sentence embeddings at inference time.
