### ISSUE TITLE
Do you change weights of word embedding model during training?

### ISSUE THREAD

**Issue by K-Mike** [UKPLab/sentence-transformers#40]

**Comment by nreimers** [comment]
Depends on the model.

If you use word embeddings like GloVe, you can set the parameter if they should be updated. My advise would be not to update them, just add a custom DAN layer on top. 

If you use BERT etc., all layers are updated. Here, also the token embedding layer is updated (I think). 

Best regards 
Nils Reimers

**Comment by K-Mike** [comment]
thanks!
