### ISSUE TITLE
public.ukp.informatik.tu-darmstadt.de Unreachable

### ISSUE THREAD

**Issue by Ganners** [UKPLab/sentence-transformers#403]
It looks like the server which hosts the pre-trained models (https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/) has been unavailable for a few hours now.

**Comment by nreimers** [comment]
Yes, there is currently a power outage which should be fixed soon.

Several pre trained models can also be found here:
https://huggingface.co/sentence-transformers

**Comment by tho-clare-ai** [comment]
Looking forward when the server up again

**Comment by n7n7d** [comment]
omg, same problem! And I was working on my thesis!!  T_T with submission date this weekend.

**Comment by n7n7d** [comment]
Can you confirm how much time it will take to repair the power outage?

**Comment by nreimers** [comment]
sys-admins sadly mention that this might take longer, as it looks like that the power adapter needs to be replaced.

I currently upload the models here:
https://sbert.net/models/

You can download them from there, unzip and use it like this
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('path/to/unzipped/distilbert-base-nli-mean-tokens')
```

**Comment by n7n7d** [comment]
> sys-admins sadly mention that this might take longer, as it looks like that the power adapter needs to be replaced.
> 
> I currently upload the models here:
> https://sbert.net/models/
> 
> You can download them from there, unzip and use it like this
> 
> ```
> from sentence_transformers import SentenceTransformer
> model = SentenceTransformer('path/to/unzipped/distilbert-base-nli-mean-tokens')
> ```

Thanks!

**Comment by nreimers** [comment]
I just pushed a new version (0.3.5.1) that uses the new download server.

It can be installed via:
```
pip install -U sentence-transformers
```


Not all models are up yet, but I hope the most important models are already online.

**Comment by cliffordgreen** [comment]
which models are available? seem to be getting error when i tried a couple. also i get permission denied when i try to download the zip

**Comment by n7n7d** [comment]
> which models are available? seem to be getting error when i tried a couple. also i get permission denied when i try to download the zip

url = 'https://sbert.net/models/distilbert-base-nli-mean-tokens.zip'
this one is working and I just downloaded it.

```
import wget
url = 'https://sbert.net/models/distilbert-base-nli-mean-tokens.zip'
wget.download(url, '/directory')


mkdir '/content/model'
!unzip 'distilbert-base-nli-mean-tokens.zip' -d /content/model

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('/content/model')
```

**Comment by PhilipMay** [comment]
> 
> 
> Yes, there is currently a power outage which should be fixed soon.
> 
> Several pre trained models can also be found here:
> https://huggingface.co/sentence-transformers

And here: https://huggingface.co/T-Systems-onsite/bert-german-dbmdz-uncased-sentence-stsb ;-)

**Comment by nreimers** [comment]
> which models are available? seem to be getting error when i tried a couple. also i get permission denied when i try to download the zip

Thanks for pointing this out. Some files did not have the right permission. I fixed that and now all the uploaded zips should be accessible.

**Comment by georgenv** [comment]
Hi @nreimers 

Coud you, please, upload the model **_distiluse-base-multilingual-cased_** too?

Thanks in advance!

**Comment by DGaffney** [comment]
Ditto @georgenv - I depend on distiluse-base-multilingual-cased and our deployment is currently broken

**Comment by datashinobi** [comment]
Same here /reimers/sentence-transformers/v0.2/bert-base-nli-stsb-mean-tokens.zip

**Comment by ankitkr3** [comment]
HI @nreimers 
PLEASE upload distiluse-base-multilingual-cased model too.

**Comment by nreimers** [comment]
Hi @ankitkr3 @DGaffney @georgenv 

distiluse-base-multilingual-cased is now uploaded and can be used as before.

**Comment by nandinib1999** [comment]
Hi, I am not able to download the datasets for running training_nli. I was wondering if you could upload the datasets as well?

Previous links to the dataset: 
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/AllNLI.tsv.gz & https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/stsbenchmark.tsv.gz

Thanks a lot!

**Comment by nreimers** [comment]
Hi @nandinib1999 
I am currently uploading them here:
https://sbert.net/datasets/

**Comment by ankitkr3** [comment]
@nreimers thanks for uploading these models, can you please help with the pretrained **roberta-large-nli-stsb-mean-tokens** model also, at the huggingface it says deprecated. Also can you give an update when the power outage would be resolved.
Thanks in advance.

**Comment by nreimers** [comment]
Hi @ankitkr3 

I uploaded the two roberta models to sbert.net/models.

The power outage might take a bit longer. It appears that the server power supply was damaged during the outage and our system admins might need to get a new power supply for that server before it can come back online :/

**Comment by nreimers** [comment]
The server is back online :)
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/

**Comment by DGaffney** [comment]
Glad to see you put this to bed, @nreimers - must have been not too fun! Thanks for being in touch about it throughout.
