### ISSUE TITLE
IndexError when used with latest release of transformers (3.1.0)

### ISSUE THREAD

**Issue by raaupr** [UKPLab/sentence-transformers#406]
Hi, I would like to use sentence-transformers for my project, but I also need to use the latest `transformers` release, v3.1.0. I encounter the error below when using the latest transformers (and possible fix?). I can create a pull request if you want, but this is quite minor, so I thought you might want to do a quick fix & release so we can use the library with the latest `transformers`.  

Thank you!

**Problem**: 
Received the following error when encoding sentences:
```
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
```
Example test script to reproduce:
```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('distilbert-base-nli-mean-tokens')
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.', 
    'The quick brown fox jumps over the lazy dog.']
sentence_embeddings = model.encode(sentences)
```

**Cause**:
`transformers`' [`BatchEncoding.convert_to_tensors`](https://github.com/huggingface/transformers/blob/4b3ee9cbc53c6cf6cee6bfae86cc2c6ec0778ee5/src/transformers/tokenization_utils_base.py#L515) no longer automatically transforms tensors into at least 2d. 

**Possible Solution**:
The argument `prepend_batch_axis` should be set to `True` for function `PreTrainedTokenizerBase.prepare_for_model`, i.e. [line 71 of `sentence_transformers.models.Transformer`](https://github.com/UKPLab/sentence-transformers/blob/448d7d030135308b91a911f1cc2f7b9ba488ad4d/sentence_transformers/models/Transformer.py#L71):
```python
return self.tokenizer.prepare_for_model(tokens, max_length=pad_seq_length, pad_to_max_length=True, return_tensors='pt', truncation=True, prepend_batch_axis=True)
```

**Comment by nreimers** [comment]
Thanks for pointing this out. It was / is on my agenda to fix it and to release a new version, compatible with transformers 3.1.0

**Comment by nreimers** [comment]
Thanks for the detailed explanation and fix.

I pushed the fix to master. Version 0.3.6, that is compatible with (and requires) transformers 3.1.0 will be released soon.
