### ISSUE TITLE
Why do you need random initiated linear transformer?

### ISSUE THREAD

**Issue by K-Mike** [UKPLab/sentence-transformers#41]
https://github.com/UKPLab/sentence-transformers/blob/3fcae031813100c51de93417d098381dea2f0ffb/sentence_transformers/losses/SoftmaxLoss.py#L30

I don't understand why you create this and than just use it like transformater from one feature space to final result space.

**Comment by nreimers** [comment]
For this idea, see the infersent paper:
https://arxiv.org/abs/1705.02364

You need this classifier only for training on NLI data. At inference, when you use the sentence embeddings, this classifier is not used. Instead, what you use, is the input of this classifier as your sentence embeddings. Experiments have shown, that these sentence embeddings can be used quite universal. Further, you can compare them with e.g. cosine similarity to measure their similarity.

Best regards
Nils Reimers

**Comment by K-Mike** [comment]
So you use it classifier only reduce dimention, right?

**Comment by nreimers** [comment]
Hi @K-Mike 
No. The classifier is a softmax classifier, used to label a pair with the three labels: entailment, contradiction, neutral.

It has no influence on the later sentence embeddings. As mentioned, it is only used to training.
