### ISSUE TITLE
Is there any Tensorflow model?

### ISSUE THREAD

**Issue by CHOCO-LEO** [UKPLab/sentence-transformers#415]
It seems all the models are trained in Pytorch frameworks.
How can I get it using Tensorflow?

(due to a technical issue I am not able to use Pytorch )

**Comment by nreimers** [comment]
Currently, there are none.

But converting the models to TF is quite easy:
https://huggingface.co/transformers/model_sharing.html#make-your-model-work-on-all-frameworks

You can find most models also on HF models repo:
https://huggingface.co/sentence-transformers

**Comment by CHOCO-LEO** [comment]
> Currently, there are none.
> 
> But converting the models to TF is quite easy:
> https://huggingface.co/transformers/model_sharing.html#make-your-model-work-on-all-frameworks
> 
> You can find most models also on HF models repo:
> https://huggingface.co/sentence-transformers

Thanks so much. The issue for me is that I am not able to install Pytorch.
And it requires both Tensorflow and Pytorch installed to convert the model.
Anyways, I am trying to convert on google colab and use save_pretrained to export a tf version model but it takes a long time to download the .h5 file from colab.
It should work?

**Comment by nreimers** [comment]
Yes, that should work.

**Comment by iknoorjobs** [comment]
Hi @nreimers 

I tried to convert sentence-transformers Pytroch model to TF but I am getting different output when I try to fetch the embeddings from both the models,

Here is the sample when I use SentenceTransformer,

```
embedder = SentenceTransformer('LaBSE')
embedder.encode("This is sample sentence")
Output: [ 2.44220495e-02,  5.14884386e-03, -6.26970828e-02,..........-2.24853326e-02, -1.52691668e-02,  1.16386525e-02]
```

But when I try in TF,

```
tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/LaBSE", from_pt=True)
model = TFAutoModel.from_pretrained("sentence-transformers/LaBSE", from_pt=True)
t = tokenizer.encode_plus("This is sample sentence", padding='max_length', truncation=True, return_tensors="tf")
m = model(input_ids=t["input_ids"], attention_mask=t["attention_mask"], token_type_ids=t["token_type_ids"])[0]
tf.keras.layers.GlobalAveragePooling1D()(m)
Output: [ 3.82371873e-01,  2.18691856e-01, -6.92396015e-02,..............2.78364211e-01,  3.96330029e-01, -5.08999050e-01]
```
Any idea why there is difference in output for same sample sentence?

Many thanks
Iknoor

**Comment by nreimers** [comment]
LaBSE model does not use average pooling. It uses the pooler_output value from the BERT model

**Comment by iknoorjobs** [comment]
Thanks, @nreimers for the prompt response.
