### ISSUE TITLE
Find synonyms

### ISSUE THREAD

**Issue by seregadgl** [UKPLab/sentence-transformers#416]
I'm new to this question, please tell me how to get synonyms of words in a sentence using SBERT.

**Comment by Shafi2016** [comment]
I have asked a similar question(https://github.com/UKPLab/sentence-transformers/issues/411) like you. I hope we will get some feedback. There is example for semantic search (https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/semantic_search.py) Where we can find a similar text to the given query. I am comfortable with this example codes but I want to find context and synonyms of words to given query sentences and query words. I have given a sample output in my question. I am still scratching my head.

**Comment by nreimers** [comment]
You can try to get the token embeddings from model.encode() instead of the sentence embedding. Just change the parameter what you like to have returned.

See
https://github.com/UKPLab/sentence-transformers/issues/408

Then you can search for the most similar token embeddings

**Comment by seregadgl** [comment]
> Я задал такой же вопрос ([№411](https://github.com/UKPLab/sentence-transformers/issues/411)), как и вы. Я надеюсь, что мы получим некоторую обратную связь. Есть пример для семантического поиска (https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/semantic_search.py) где мы можем найти аналогичный текст для данного запроса. Мне удобен этот пример кода, но я хочу найти контекст и синонимы слов для заданных предложений запроса и слов запроса. Я привел пример вывода в своем вопросе. Я все еще чешу в затылке.

**Comment by seregadgl** [comment]
> Вы можете попробовать получить встраивания токенов из модели.encode () вместо вложения предложения. Просто измените параметр, который вы хотели бы вернуть.
> 
> Смотрите
> #408
> 
> Затем вы можете искать наиболее похожие вложения токенов

Thanks for the advice, but can you give me an example? For example, show synonyms of words for this sentence: "This structure generates attachments for each input sentence"
Thanks again.

**Comment by seregadgl** [comment]
> You can try to get the token embeddings from model.encode() instead of the sentence embedding. Just change the parameter what you like to have returned.
> 
> See
> #408
> 
> Then you can search for the most similar token embeddings

Thanks for the advice, but can you give me an example? For example, show synonyms of words for this sentence: "This structure generates attachments for each input sentence"
Thanks again.
