### ISSUE TITLE
Training with Triplet Loss

### ISSUE THREAD

**Issue by joseph-macraty** [UKPLab/sentence-transformers#419]
Hi, 
I was thinking of finetuning-SBERT with triplet loss. I was wondering whether the semantics of the negative sentence made a difference. For example lets say we have 2 different examples: 

1) Anchor: The boy is playing football. 
    Positive: The boy is playing soccer in a park. 
    Negative: The boy is studying 

2) Anchor: The boy is playing football. 
    Positive: The boy is playing soccer in a park. 
    Negative: Las Vegas is in the US. 

Is the first example better than the second since it is much more on the topic and brings out the difference while in the second example it's completely random?

**Comment by nreimers** [comment]
Yes, it makes a difference. This is known in literature as hard negatives.

By choosing he the negative, you influence what the model will learn

**Comment by joseph-macraty** [comment]
Thank you!
