### ISSUE TITLE
Can pretrained models be used to get embedding of german sentences ?

### ISSUE THREAD

**Issue by ereday** [UKPLab/sentence-transformers#42]
Hi,

Can pre-trained models be used to get embedding of german sentences (end goal is to cluster sentences) or does it only make sense to use them with English input? If the latter is the case, are you planning to release pretrained models for german as well?

**Comment by nreimers** [comment]
Hi,
Currently the pre-trained models work for English only. 

Do you know suitable datasets for German, like NLI or STS? 

Best regards 
Nils Reimers

**Comment by ereday** [comment]
I am afraid, I don't know a german dataset for either of those tasks.

**Comment by nreimers** [comment]
There are now models available for multiple languages, including German. Further, the is now an example how to make models multi-lingual.
