### ISSUE TITLE
View subword tokens

### ISSUE THREAD

**Issue by hetryn** [UKPLab/sentence-transformers#422]
Is there a function to view subword tokens using sentence-transformers?

I want to link the token-embeddings back to the subword tokens.

**Comment by nreimers** [comment]
The encode function, with output_value ='token_embeddings' returns the word piece embeddings.

**Comment by hetryn** [comment]
> The encode function, with output_value ='token_embeddings' returns the word piece embeddings.

Thanks for the prompt response Neil! 

Actually, I would like to get the subword tokens together with the embeddings. I understand output_value = 'token_embeddings' will return an array with shape (number of sentences passed, longest sequence length, hidden_size).

I would like to get the associated subwords tokens such as ['[CLS]', 'This', 'is', 'an', 'example' ,'[SEP]', '[PAD]', '[PAD]'], so that I can link the token embeddings to their respective tokens. Is there a way to get the tokens (not embeddings) out using sentence-transformers or I would have to use huggingface's tokenizer.encode_plus on my sentences.

**Comment by nreimers** [comment]
It is based on Huggingface tokenizers. You can see their documentation how to tokenize the text into word pieces.

**Comment by hetryn** [comment]
> It is based on Huggingface tokenizers. You can see their documentation how to tokenize the text into word pieces.

Thank you. I guess doing `model.encode(sentences)` will add special tokens such as [CLS] and [SEP] automatically into the sentences before tokenizing?

**Comment by nreimers** [comment]
It call the respective huggingface transformer tokenization code, which will add the special tokens needed for the respective model.

**Comment by hetryn** [comment]
awesome thanks neil
