### ISSUE TITLE
Does the multi-task training improve performance.

### ISSUE THREAD

**Issue by ashutosh-dwivedi-e3502** [UKPLab/sentence-transformers#431]
Does the recently added multitask training improve performance? 

training_script : https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/other/training_multi-task.py

**Comment by nreimers** [comment]
It is just an example.

In that specific example, training on NLI+STS, an improvement is not achieved compared to first training on NLI and then training on STS.

**Comment by ashutosh-dwivedi-e3502** [comment]
Thanks for the info
