### ISSUE TITLE
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'

### ISSUE THREAD

**Issue by stellaywu** [UKPLab/sentence-transformers#44]
load pretrained weights 
```from sentence_transformers import SentenceTransformer
model = SentenceTransformer('bert-base-nli-mean-tokens')
```
got this error No module named 'fused_layer_norm_cuda' . 
Is it because I am using CPU?

**Comment by nreimers** [comment]
Have a look here
https://github.com/NVIDIA/apex/issues/161

Appears some issues with dependencies with Cuda. Gpu / Cuda is not required for this package to work, a CPU is sufficient.
