### ISSUE TITLE
Document embedding

### ISSUE THREAD

**Issue by gevezex** [UKPLab/sentence-transformers#440]
What would be the best practise to elevate this framework to create document embeddings similar to sentence embeddings? And even better document embeddings for large documents (even books)?

**Comment by nreimers** [comment]
For document, especially long documents, you usually don't need these embeddings methods. They excel for short texts / sentences.

For long docs, you get great results with BM25 / TF-IDF. Maybe you can extend it by using LSA or LDA. 

These methods usually  give much better results than any of the more complex embedding methods.

**Comment by gevezex** [comment]
Thnx for your great advise @nreimers!
