### ISSUE TITLE
Some doubts regarding Faiss Search..

### ISSUE THREAD

**Issue by Adarsh1999** [UKPLab/sentence-transformers#441]
Hi, I am working on indexing texts from pdfs and other documents in Faiss search using your amazing code base but I am going through 2 difficulties in which I need your help: 

1. I want to add meta data to like name of the file to the sentences which are to be indexed in FAISS.
![image](https://user-images.githubusercontent.com/28682167/93687880-0ebade00-fadf-11ea-99a7-e710b028a76a.png)
example like this so when I get a search input, results which come from the pdf indexed sentence should also include the file name from where they are extracted but by default the output only contains the sentences which are given in form of python list. I need this feature as I want to add data from many diff files so that I can find files too during search.

So how can I additional data including the normal results from Faiss Search...?

**Comment by Adarsh1999** [comment]
2. So the next difficulty I am facing is the in the code : 
>         print("Store` file on `disc")
        with open(embedding_cache_path, "wb") as fOut:
            pickle.dump({'sentences': item_lists, 'embeddings': corpus_embeddings}, fOut)
    else:
        print("Load pre-computed embeddings from disc")
        with open(embedding_cache_path, "rb") as fIn:
            cache_data = pickle.load(fIn)
            item_lists = cache_data['sentences']
            corpus_embeddings = cache_data['embeddings']


here as I want to add more data from other pdf files once the indexed is generated in pickle file it is not updated with new data so when the search is ran it will use the old pickle file and to index new data I have to delete old pickle file and have to add new pickle file and reindex the whole corpus.

So how can I update the indexes rather than reindex it with new data..?

Thanks for reading hope you help me...

**Comment by nreimers** [comment]
Hi @Adarsh1999 
Faiss can only index embeddings and gives you the index of the matching embedding. For your meta data, you would need a second data structure like a regular Python list or dict.

So the lookup looks then like this
Faiss ---> gives ID of matching embedding
metadata[ID] ---> gives you the metadata. Metadata is either a list or dict.

Updating the index depends on the index you use with faiss. Some indices allow this, other don't allow to add more examples and you need to re-index when adding new data. You can find more info in the faiss documentation.

Btw: I quite like this project for Approximate Nearest Neighbor:
https://github.com/nmslib/hnswlib/

It has a great performance, maps hits to ids (like ids from a database), and it is easy to add new elements to an index.

**Comment by finardi** [comment]
From data lilke Pandas DataFrame you could use encoding your metadata like this:

```
def map_index_to_docs(dataframe):
  # Dict com k: index --> v: docid: doc
  index_map_docs = {}
  for tup in dataframe.itertuples():
    index_map_docs[tup[0]] = {
                        'docid': tup[2],
                        'doc': tup[4],
                        }
  return index_map_docs

index_map = map_index_to_docs(df)
def index_to_doc(indexes):
    for i, idx in enumerate(indexes,1):
        print(f'{i:4}. {index_map[idx]["docid"]:>4} -- {index_map[idx]["doc"]}')

def do_faiss(model, faiss_index, query_text, top_k=10):
    embedding_q = compute_embeddings(model, query_text) # use sentence_transformers in this function compute_embeddings
    matched_em, matched_indexes = faiss_index.search(embedding_q, top_k) 
    return matched_indexes[0]

indexes_faiss = do_faiss(model, faiss_index, [question], top_k=10)
index_to_doc(indexes_faiss) 
```

**Comment by Adarsh1999** [comment]
Thanks @finardi for such an amazing insight as I was very confuse on its implementation but now I have nice clear sight and hope that will work in one run will add more to this thread if I face any complication ...Thanks
