### ISSUE TITLE
Unable to trace distilbert-multilingual-nli-stsb-quora-ranking

### ISSUE THREAD

**Issue by ruichernob** [UKPLab/sentence-transformers#445]
Last line throws an error: "TypeError: DistilBertModel object argument after ** must be a mapping, not Tensor"

`model = SentenceTransformer('distilbert-multilingual-nli-stsb-quora-ranking')`
`tokenizer = DistilBertTokenizer.from_pretrained('sentence-transformers/distilbert-multilingual-nli-stsb-quora-ranking')`

`dummy = tokenizer("A man is eating pasta.", return_tensors='pt')`

`t = torch.jit.trace(model, {'input_ids': dummy['input_ids'], 'attention_mask':dummy['attention_mask']})`

When attempt passing **dummy it throws another error: "TypeError: trace() got an unexpected keyword argument 'input_ids'"

`t = torch.jit.trace(model, **dummy)`

Instruction `t = torch.jit.trace(model, example_inputs=dummy)` gives error: "RuntimeError: Type 'Tuple[str, str]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced"

Statement `t = torch.jit.trace(model, example_inputs=(dummy['input_ids'], dummy['attention_mask']))` gives "TypeError: forward() takes 2 positional arguments but 3 were given"

**Comment by nreimers** [comment]
Never used jit.trace, so I sadly cannot help

**Comment by ruichernob** [comment]
As far as I understand sentence transformer built on appropriate transformer model like Bert, DistilBert etc. It is possible to [trace](https://pytorch.org/tutorials/prototype/graph_mode_dynamic_bert_tutorial.html#evaluation) Bert, but due to wrapper I cannot figure out the workaround for that issue. I've looked the encode method in SentenceTransformer.py. It just calls forward() of the appropriate model. Am I correct?

**Comment by nreimers** [comment]
It is a torch sequential model, that call as first layer huggingface AutoModel (or BERTModel etc.), and as second layer the models.Pooling model

**Comment by ruichernob** [comment]
Could you kindly light a shed what exactly Pooling model does in the context of Bert? I'm aware that Bert outputs a tensor and that the only 'first' slice represents CLS or sentence embedding. But wonder how works sentence transformer wired with models.Poling layer?

**Comment by nreimers** [comment]
There are different pooling mechanism available. The most common is to perform mean pooling, i.e. taking all BERT output embeddings and to average them.
