### ISSUE TITLE
Error trying to load multilingual model

### ISSUE THREAD

**Issue by DebanjanaKar** [UKPLab/sentence-transformers#447]
Whenever I am trying to load any of these 3 pre-trained models (`distilbert-multilingual-nli-stsb-quora-ranking, xlm-r-100langs-bert-base-nli-mean-tokens, xlm-r-100langs-bert-base-nli-stsb-mean-tokens`), I get the following error:

`ValueError: invalid literal for int() with base 8: 'ils\n_reb'`

How can this be resolved?

**Comment by nreimers** [comment]
For these models, you need pytorch version 1.6.0 (or higher).

**Comment by DebanjanaKar** [comment]
Yes that worked! Thanks a lot!! :)
