### ISSUE TITLE
error while downloading

### ISSUE THREAD

**Issue by anonymous297** [UKPLab/sentence-transformers#45]
![Capture](https://user-images.githubusercontent.com/43982672/68021005-39812580-fcc6-11e9-8156-556161b56048.PNG)

I am getting the above error.
OS: windows 10
Python 3.6

**Comment by pidugusundeep** [comment]
This is the zip file which it's trying to download `https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/bert-large-nli-mean-tokens.zip` and i am able to download and extract the same.

The model file will be downloaded and saved at `HOMEDIR/.cache/torch/sentence_transformers/` Try deleting the model and then rerun the code for a fresh download, Hope it works.

**Comment by anonymous297** [comment]
thanks. It worked.
