### ISSUE TITLE
Missing documentation in "Multi-Process / Multi-GPU Encoding"

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#451]
There is missing text here: https://github.com/UKPLab/sentence-transformers/blame/master/docs/usage/computing_sentence_embeddings.md#L99

Maybe you want to add it...

Thanks
Philip

**Comment by nreimers** [comment]
Thanks, updated the docs.

**Comment by PhilipMay** [comment]
Thanks. :-)
