### ISSUE TITLE
Questions on experiment results

### ISSUE THREAD

**Issue by kwonmha** [UKPLab/sentence-transformers#457]
What is the input format of Avg. BERT Embeddings on STS task?
Did you feed a pair of 2 sentences to BERT or feed each sentence individually?

And Avg. BERT "Embeddings" makes me think you used embedding layer of BERT on experiment.

**Comment by nreimers** [comment]
The output of BERT is used (which is also known as BERT embeddings).

**Comment by kwonmha** [comment]
Thanks for reply.

My questions is about input format to get the output of BERT; whether you fed 2 sentences together to BERT and averaged, or fed each sentence, averaged output individually.

**Comment by nreimers** [comment]
Every sentence individually

**Comment by kwonmha** [comment]
Thank you very much
