### ISSUE TITLE
How to use GPU to accelerate training?

### ISSUE THREAD

**Issue by working12** [UKPLab/sentence-transformers#460]
What is the method of using GPU while training a model from scratch?

**Comment by nreimers** [comment]
fit() will automatically detect if a GPU is available and use it.

See pytorch documentation, how to install pytorch with GPU / CUDA support and how to check if pytorch can access the GPU.

**Comment by PhilipMay** [comment]
Even when you have multiple GPUs it will detect and use them. ;-)

Installation must match your CUDA Version. See here: https://pytorch.org/get-started/locally/#start-locally

**Comment by working12** [comment]
Thanks @PhilipMay
