### ISSUE TITLE
Issue in handling queue in multiprocessing

### ISSUE THREAD

**Issue by ayushidalmia** [UKPLab/sentence-transformers#464]
https://github.com/UKPLab/sentence-transformers/blob/1e6227f6825be8de252e74d21352d3b238c570f5/sentence_transformers/SentenceTransformer.py#L277

should be modified as:
 
`input_queue.put([last_chunk_id, is_pretokenized, chunk])`

Otherwise, the last pool throws `ValueError: not enough values to unpack (expected 3, got 2)`

**Comment by nreimers** [comment]
Thanks for reporting this. It is fixed and will be part of the next quick patch, that I will release today.
