### ISSUE TITLE
Time for Inferencing

### ISSUE THREAD

**Issue by ayushidalmia** [UKPLab/sentence-transformers#465]
I am not sure how to put example for replication, however when I try to do inferencing for generating sentence embeddings, the last batch, sort of hangs. 

I am running it on CPU and there is sufficient memory and cpu available. 

Any recommendation on where should I look for potential bug?

**Comment by nreimers** [comment]
Can you post some code? Do the examples on generating embeddings work?

**Comment by ayushidalmia** [comment]
```
data = [list of long sentences, another list of long sentence,...]
model = SentenceTransformer('bert-base-nli-stsb-mean-tokens')
model.encode(data, show_progress_bar=True, convert_to_numpy=True,num_workers=4)
```

This works in general, but for some reason, when it reaches the last batch the progress bar doesn't end and it hangs in there for quite some time, much longer than the time needed to process each iteration.

**Comment by PhilipMay** [comment]
I do

```python
import pandas as pd
from sentence_transformers import SentenceTransformer

if __name__ == '__main__':
    df = pd.read_csv(
        '<data>',
    )

    texts = df['key'].tolist()

    model = SentenceTransformer('./<mymodel>_bert')

    pool = model.start_multi_process_pool(encode_batch_size=2000)
    embeddings = model.encode_multi_process(texts, pool)
    model.stop_multi_process_pool(pool)
```

**Comment by nreimers** [comment]
Hi @ayushidalmia 
Is data actually two lists? Like this?
```
data = [ ['sent1', 'sent2'], ['sent3', 'sent4', 'sent5']]
```

If yes, ensure that data is actually a single list of string, i.e.:

```
data = ['sent1', 'sent2', 'sent3', 'sent4', 'sent5']
```


Further, that the last batch takes longer is expected. The encode method sorts the list you pass and the first sentences are encoded first. The last batch will contain the longest sentences in the data you pass.

BERT has a quadratic runtime with the sentence length. E.g., if you mainly have sentences with 10 tokens and one sentence with 100 tokens, this sentence will be encoded at the end. It is 10 times larger than the other, i.e., it takes 100 times longer to encode this than any other sentence.

You could try to reduce the max sequence length:
https://www.sbert.net/docs/usage/computing_sentence_embeddings.html#input-sequence-length

This will truncate long sentences to shorter length.

**Comment by ayushidalmia** [comment]
Hi @nreimers , I finally got around to try this out. 

My data looks like this:
`data = ['sent1', 'sent2', 'sent3', 'sent4', 'sent5']`

Regarding the time taken by the last/last few batches:

It is indeed true that due to sorting, the longer sentences end up in last batches

Some of my sentences were really long ~600k and it was taking forever to encode. However, when I manually trim them and pass them to them model, the sentence encoding is fast. I was expecting the model to trim the size and encode automatically, since the default max_sequence_length= 128.

I am not sure if this is expected but just wanted to let you know.

**Comment by nreimers** [comment]
Hi @ayushidalmia 
Thanks for the observation.

This is an "issue" with the tokenizer in Huggingface. It first tokenizes the complete sentences, and then truncates it to the max length.

Assume you have long doc, then HF tokenizer tokenizes it resulting in e.g. 20k tokens, which takes quite a long time. Only after this step is the list of tokens truncated to e.g. 512 (or 128) tokens. 

The tokenizer could stop after it has max_length tokens, however, this is sadly not implemented in huggingface. So there is quite a wast and unneeded text is tokenized.

However, it you truncate your text before it is passed to the tokenizer, only the shorter text is tokenized. So if you do something like text = text[0:128*10], the text is truncated to 1280 characters, which are then tokenized (maybe resulting in 300 word pieces). This word pieces are then truncated to only 128 word pieces.

**Comment by ayushidalmia** [comment]
Yes. That's exactly what I did. I truncated the text before passing to tokenizer and it works fine now. 

Appreciate your time and help in answering all the queries. I now have a better understanding of things! 👍
