### ISSUE TITLE
Question: How do I set a useful boundary for "similarity"?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#466]
Hi,
I have a big set of sentences and want to "tag" or "classify" them with sentence embeddings. The user can enter different "sentences" and the systems calculates "similarity". All similar datasets are "tagged". Now I am thinking of:

> "How can I set a useful boundary where I do the cut between similar and not similar?"

Do you have an idea on how to find a meaningful general cutoff value? Is there anything like a systematic approach to do this?

Thanks
Philip

**Comment by nreimers** [comment]
If you have some evaluation data, you can compute the optimal threshold based on that.

If you don't have such data, what is the more common case: In that case, I just experiment with some thresholds and try to get an understanding what makes sense. At the end, the threshold is based on some tests + subjective feeling what works well.

I am not aware of any systematic approach for the case where you don't have any evaluation data.

**Comment by PhilipMay** [comment]
Yeah - that was what I also thought. Although I hoped there could be a trick or something. :-)

Thanks for the super quick answer, you are awsome!
