### ISSUE TITLE
Model download from HF does not work.

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#467]
As far as I understood models should be automaticaly downloaded from HF. So this should work:

```python
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('T-Systems-onsite/bert-german-dbmdz-uncased-sentence-stsb')
```

But it does not (on colab):

![grafik](https://user-images.githubusercontent.com/229382/94933310-823ef100-04ca-11eb-9901-42a355484822.png)

**Comment by nreimers** [comment]
There is currently an issue with the / in the same. The server returns a 403. However, it only falls back to HF when there was a 404 error.

Have to fix the .htaccess on the server so that it returns a 404 message for models that include a '/'.

**Comment by nreimers** [comment]
It should be fixed now.

**Comment by PhilipMay** [comment]
I can confirm that it works now.
