### ISSUE TITLE
Collaboration on a utils library: a usable API a la your examples/*

### ISSUE THREAD

**Issue by lefnire** [UKPLab/sentence-transformers#468]
I've used sentence-transformers across various projects, and end up needing the same common bits: clustering, cosine similarity, etc. I've found the code in `utils.py` (`pytorch_cosine_sim`, `paraphrase_mining`, `semantic_search`) very valuable. I do end up usually modifying things; eg, for cosine I need absolute value `dist = (sims-1).abs()` for downstream agglomorative-clustering (can't handle `<0` vals). Because of that, I'd love there to be a more robust/tweakable library around (a) utils.py, (b) actual simple/callable API wrappers around examples/*. I know y'all probably prefer to keep sentence_transformers on topic, and your examples are examples, but maybe I / community could collaborate with y'all on package? 

To show what I mean, I've started one myself https://github.com/lefnire/ml-tools. It allows chained methods like `Similars(sentences_a, sentences_b).embed().normalize().cosine().cluster(algo='agglomorative')`. And I like to normalize columns `normalize( np.vstack([a, b]), axis=0 )` then split (is that naiive?). You'll see in that code (buggy/incomplete) I have tf-idf, spacy+lemmatization, etc; said module would be good to have pretty much all the getting-started NLP needs to prevent users needing stackoverflow copy-pasta,  spending days tweaking their text-cleanup stuff, etc.  I'm using it in [Gnothi](https://github.com/lefnire/gnothi), and will maintain it along with that project. **OR** (preferred) y'all could make a repo (ukplab/nlp-utils or something), consider adding me as contrib, I'll move all this code over there and the I+community can start contrib'ing. Thoughts?

**Comment by lefnire** [comment]
Btw, in wouldn't want it to compete with gensim or others; just starter NLP utils with an emphasis on sentence_transformers, and some quick start options for other libraries (text clean up and such)

**Comment by lefnire** [comment]
actually, I'll just keep up with that repo for my stuff & not bother y'all with it. If people find it useful, yay!

**Comment by nreimers** [comment]
Hi @lefnire 
Thanks for open sourcing this project. I think in the long run it can become useful.

I sadly do not have free capacities for another project. But I wish good luck with your project.

Best
Nils

**Comment by lefnire** [comment]
Np, thanks!
