### ISSUE TITLE
When training multi-task model, scheduler step invoked for one model only.

### ISSUE THREAD

**Issue by prempv** [UKPLab/sentence-transformers#470]
I noticed that within SentenceTransformer fit function, when training for multi-task model, the scheduler step is being invoked for one model alone at below line:
https://github.com/UKPLab/sentence-transformers/blob/dc84bb7644946d8217fa2ea5211a75c53be89101/sentence_transformers/SentenceTransformer.py#L578

This line is outside the model level forward and optimizer step for loop. Is this intentional? When not using AMP, I do notice that one of them model's `lr` does not change.

Am I missing something here?

**Comment by nreimers** [comment]
Thanks for reporting. Looks like a bug, will fix it.

**Comment by prempv** [comment]
Thanks 👍 . Looks good
