### ISSUE TITLE
RunTimeError on pre-trained model loading in cpu-only machine (average_word_embeddings_glove.840B.300d)

### ISSUE THREAD

**Issue by preinh** [UKPLab/sentence-transformers#475]
Dear all,

When trying to load the `average_word_embeddings_glove.840B.300d` on a cpu-only machine, even passing `device='cpu'` is raising a RunTimeError:

> RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with `map_location=torch.device('cpu')` to map your storages to the CPU.

By including the suggested parameter on the following line I could workaround the issue:
- https://github.com/UKPLab/sentence-transformers/blob/4c20cccd4900f22cd6db0d92d16b81c3e1524b16/sentence_transformers/models/WordEmbeddings.py#L80

**Comment by nreimers** [comment]
Thanks for pointing this out. I added the fix to WordEmbeddings and it will be part of the next release.
