### ISSUE TITLE
save model error

### ISSUE THREAD

**Issue by wbqtac** [UKPLab/sentence-transformers#476]
Hi There,

I have an error when saving model in local drive, and will appreciate your attention.:

**version**: 0.3.7.2
**error message**: 
    the error message shows several exceptions. In the beginning, it shows exception from tarfile.py, while during handling this exception, some other exception occurs. 
    Eventually, in the bottom of the error message:
     OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**code:** 

name = 'distiluse-base-multilingual-cased'
print(name)
sentTransFormModel = SentenceTransformer(name)
sentTransFormModel.save('local-' + name)

**other**:
other models such as "distilbert-base-nli-stsb-mean-tokens" look fine for saving. But models for multiligual "xlm-r-100langs-bert-base-nli-stsb-mean-tokens" appear not saving correctly.

Is there any function specifically used for saving models of multilingual?
It looks that the error occurs in sentTransFormModel = SentenceTransformer(name)
**this statement download the model to some default local drive in conda or virtual environment, but did not load successfully.**

Thank you for your attention.

**Comment by nreimers** [comment]
I think the issue is with loading the model (at least from the short error message you posted).

The multilingual models require Pytorch 1.6.0

Pytorch 1.6.0 introduced a new file format to store models, based on a zip format. Models stored with Pytorch 1.6.0. can sadly not be loaded with older pytorch versions.

Best
Nils

**Comment by wbqtac** [comment]
Hi Nils,

Thank you for your help. Yes, my old pytorch is version 1.3.1. After upgrading to 1.5.0, it can load/save the model correctly. 

Best

Bingqing
