### ISSUE TITLE
Number of Training Examples

### ISSUE THREAD

**Issue by joseph-macraty** [UKPLab/sentence-transformers#478]
Hi, 
I was wondering whether there is a number/estimate to the number of training examples required to fintune SBERT? The field we are focusing on is medicine (but not very technical). We have our dataset in this format - 
```
sentence1, sentence2, simlarity score
```
I understand that there is no number as such but what amount of training examples can be considered a good start? 500?

**Comment by nreimers** [comment]
It is hard to tell. Depends how difficult your task is and how much performance you need.

But 500 appears to be a good start.

We soon (in October) present a new method that reduces  the required numbers of labeled data. 

Here an image on STS benchmark with different training set sizes. Bi-encoder is SBERT, cross-encoder is a BERT cross-encoder.
![bi-vs-cross](https://user-images.githubusercontent.com/10706961/95423993-3f55a100-0942-11eb-8f0e-9a90e408e51d.PNG)

**Comment by joseph-macraty** [comment]
Looking forward to it! Had another question. Let's say we fine-tune a BERT on our corpus which we then use for SBERT, does it make sense to first use STS/NLI or just train with our ow labelled data? Does training a "Medical" BERT on standard sentences of STS/NLI reduce performance?

**Comment by nreimers** [comment]
I made quite good experience to have it first fine-tuned on NLI + STS, before going to a specific task. Works quite well.

**Comment by joseph-macraty** [comment]
Ok. Thanks a lot!

**Comment by PhilipMay** [comment]
@nreimers thanks for sharing this grafic. Did you do an Hyperparameter Tuning each time you changed the size? Or is it all with the same HPs?

**Comment by nreimers** [comment]
Same hyperparameters for all dataset sizes. We didn't evaluate if HP make a big difference with changing dataset sizes.
