### ISSUE TITLE
Does increasing max_seq_length will affect the quality of the embeddings?

### ISSUE THREAD

**Issue by koren-v** [UKPLab/sentence-transformers#491]
I found that the max_seq_length of the encoder is hardcoded to 128. Does it's mean that most of the train data in STS and MNLI have a length lower than 128 tokens or it was done simply for performance?
How do you think, increasing this argument will affect the quality of the embeddings?

**Comment by nreimers** [comment]
Yes, most sentences are shorter, I think only a handful of the 500k sentences in the NLI dataset were longer.

So for training it will not make a difference. 

For inference it could make a difference. However, as the training data did not have any really long sentences (or paragraphs), the embeddings for these might not be that good.

**Comment by koren-v** [comment]
Thanks!
