### ISSUE TITLE
What happened to xlm-r-100langs-bert-base-nli-stsb-mean-tokens?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#508]
Hi,

what happened to the model `xlm-r-100langs-bert-base-nli-stsb-mean-tokens`?
It got deleted in the documentation...

https://github.com/UKPLab/sentence-transformers/blame/a57e7ec15182ecbe50a9b96ca2509ca03965d73c/docs/pretrained_models.md#L39

**Comment by PhilipMay** [comment]
Ahh I see - it has the same performance as `xlm-r-bert-base-nli-stsb-mean-tokens`. My guess is that it just got renamed?

**Comment by nreimers** [comment]
It was renamed to `xlm-r-bert-base-nli-stsb-mean-tokens`, i.e., removing 100langs from the name.

The old model is still online and both are the same model.

**Comment by PhilipMay** [comment]
Ok great. Thanks.
Closing this.
