### ISSUE TITLE
How to use Transformers to load `distiluse-base-multilingual-cased` for fine tuning purpose

### ISSUE THREAD

**Issue by kechxu** [UKPLab/sentence-transformers#513]
Hi UKPLab folks, I found distiluse-base-multilingual-cased performs very well. And I am doing something to fine tune this encoder in my multi-classification task. As mentioned in https://github.com/UKPLab/sentence-transformers/issues/350, you recommend to use `Transformers` package to fine tune multi-classification tasks. Then I went to this website to search the UKPLab encoders that `Transformers` package supports https://huggingface.co/sentence-transformers. But I did not find `distiluse-base-multilingual-cased`. So my question is how can I load `distiluse-base-multilingual-cased` by Transformers package?

Thanks a lot!

**Comment by nreimers** [comment]
It is sadly not in the huggingface repository as it uses a custom linear layer on top of DistilBERT to scale the embeddings down to 512. Sadly, custom layers cannot be uploaded to to HF.

You can download the  model from here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

After unzipping, you have a 0_Transformer folder which is the huggingface transformer model that can be loaded with AutoModel. I think that should be sufficient and the 2_Dense layer is not needed if you want to use it for classification.

**Comment by kechxu** [comment]
> It is sadly not in the huggingface repository as it uses a custom linear layer on top of DistilBERT to scale the embeddings down to 512. Sadly, custom layers cannot be uploaded to to HF.
> 
> You can download the model from here:
> https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/
> 
> After unzipping, you have a 0_Transformer folder which is the huggingface transformer model that can be loaded with AutoModel. I think that should be sufficient and the 2_Dense layer is not needed if you want to use it for classification.

Thanks a lot for your suggestion! I found on HF there is `distilbert-multilingual-nli-stsb-quora-ranking` https://huggingface.co/sentence-transformers/distilbert-multilingual-nli-stsb-quora-ranking. Is this the same structure as 0_DistilBERT in `distiluse-base-multilingual-cased`?

**Comment by nreimers** [comment]
Yes, both are distilbert-multilingual models. However, they  were trained differently.

**Comment by kechxu** [comment]
> Yes, both are distilbert-multilingual models. However, they were trained differently.

Thanks for your prompt reply. In this case, which one do you recommend?

**Comment by nreimers** [comment]
distiluse works nice on noisy data and covers a wider range.

I can also recommend 'xlm-r-distilroberta-base-paraphrase-v1', it is based on XLM-R and was trained on large scale paraphrase data, yielding quite good results for general as well as specialized domains.

**Comment by kechxu** [comment]
> distiluse works nice on noisy data and covers a wider range.
> 
> I can also recommend 'xlm-r-distilroberta-base-paraphrase-v1', it is based on XLM-R and was trained on large scale paraphrase data, yielding quite good results for general as well as specialized domains.

That's very helpful. Thanks a lot for your information.
