### ISSUE TITLE
Change to use module logger instead of the root logger

### ISSUE THREAD

**Issue by josemarcosrf** [UKPLab/sentence-transformers#514]
In `SentenceTransformer.py` mesages are being logged using the root logger as `logging.info` is used.

If a logger specific to the library were to be used would be easier to change the level or formatting of the logger only of SentenceTransformer without having to affect the root logger.

Right now the logging looks like (ignore the formatting as this is specific to my application - just to illustrate it's using the root logger):
```
INFO     root                                         :  38 - Load pretrained SentenceTransformer: distilbert-base-nli-mean-tokens
INFO     root                                         :  42 - Did not find folder distilbert-base-nli-mean-tokens. Assume to download model from server.
INFO     root                                         :  92 - Load SentenceTransformer from folder: /home/jose/.cache/torch/sentence_transformers/sbert.net_models_distilbert-base-nli-mean-tokens
INFO     root                                         : 116 - Use pytorch device: cpu 
```

Instead of `logging.info` doing:

```python
logger = logging.getLogger(__name__)
...
logger.info(....)
```

Should solve the issue.

Happy to submit a PR if this is of interest.

**Comment by nreimers** [comment]
Yes, a PR would be nice.

**Comment by jmrf** [comment]
Oh I missed your reply sorry. Sure, I will submit a PR then!

**Comment by jmrf** [comment]
Quick update on my side. I am still planing to do this, just haven't had the chance to do it yet but will be coming shortly.

**Comment by nreimers** [comment]
Great @jmrf 
thanks for the update

**Comment by jmrf** [comment]
Sorry for the delay! Finally there's a PR for it: https://github.com/UKPLab/sentence-transformers/pull/623

**Comment by Martins6** [comment]
I was trying to debug an issue with the logger and I found this issue. But it seems that the PR was merge and the issue stayed open. Just a friendly reminder that the admin can close it if ti wants to! @nreimers

**Comment by nreimers** [comment]
Thanks @Martins6
