### ISSUE TITLE
How do I find German synonyms?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#515]
@nreimers I want to find synonym words on German language. What do you think is better:

Use fasttext embeddings and their distance or use german sentence embeddings on word level to find similar words?
What do you think? Did you ever do somthing like that?

Or are there classical manual German synonym lists somewhere in the internet?

Thanks
Philip

**Comment by nreimers** [comment]
Depends on what you need them for.

What can be interesting is Word in Context:
https://pilehvar.github.io/wic/
https://pilehvar.github.io/xlwic/

For regular synonyms, I think traditional word embeddings (Glove, word2vec etc.) work fine. In my experience, they work better than fasttext.

I have some german word2vec embeddings here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/embeddings/reimers_german_embeddings.gz

What can also be nice is GermaNet:
https://uni-tuebingen.de/en/142806

**Comment by PhilipMay** [comment]
I will try the GermaNet way and found this which supports it:
https://github.com/hdaSprachtechnologie/odenet

Just fyi - will close this now and as always - many thanks for the answer.
