### ISSUE TITLE
GPU not found

### ISSUE THREAD

**Issue by FaresAh** [UKPLab/sentence-transformers#516]
Hey!

I've been trying to load and fine-tune a pretrained model on a GPU, but for some reasons it doesn't seem to find the available gpu device.

Doing the following 
```
model = SentenceTransformer('distilbert-base-nli-mean-tokens', device='cuda')
print(model.device)
```
prints out `device(type='cpu')`, even though `print(torch.cuda.is_available())` yields True.

I have the following versions installed
``` 
torch==1.6.0
sentence-transformers==0.3.8
```

Do you have an idea where that issue could be coming from ?

Thanks!

**Comment by nreimers** [comment]
The model will be moved to the GPU once you start training or encoding.

```
model = SentenceTransformer('distilbert-base-nli-mean-tokens', device='cuda')
model.encode("test")
print(model.device)
```

should solve it

**Comment by FaresAh** [comment]
That was it indeed, thank you for your quick answer!

**Comment by zhouhuhq** [comment]
> The model will be moved to the GPU once you start training or encoding.
> 
> ```
> model = SentenceTransformer('distilbert-base-nli-mean-tokens', device='cuda')
> model.encode("test")
> print(model.device)
> ```
> 
> should solve it

I would like to ask how to set up to use the GPU you want for training, for example, cuda: 7. Because the model defaults to 0.thank you

**Comment by nreimers** [comment]
You can pass the device you like to use to SentenceTransformer

Or you call your script like this
```
CUDA_VISIBLE_DEVICES=7 python train.py
```

Then only cuda:7 is visible to the script (it will be cuda:0 then in the script)
