### ISSUE TITLE
Data quality of stsb

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#520]
Hi @nreimers 
I observed some data quality issues in stsb. Did you ever think of cleaning it up? What do you think would be the effect?

Most often strange `--` and `US30YT=RR` signs occur... examples here:

```
police stated that-- chung has been on the run.
Israel doesn't give a ****, accept it.
That Israel doesn't giva a **** what anybody else thinks.
------ ----------- What do we get in return for doing the fighting for them?
The 30-year bond US30YT=RR firmed 31/32, taking its yield to 4.16 percent -- another record low -- from 4.22 percent.
Likewise, the 30-year bond <US30YT=RR> slid 1-11/32 for a yield of 4.38 percent, up from 4.30 percent.
```

**Comment by nreimers** [comment]
Interesting, thought that it would be rather clean. But yes, sometimes the source for sentences can be noisy.

But I think the effect of cleaning would be rather low and for most applications, you also have noisy data. So it can be good to have some noisy in its own training / eval data to test for that.

**Comment by PhilipMay** [comment]
Closing it.
