### ISSUE TITLE
New Model: xlm for English and German - multilingual finetuning with language-crossing

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#521]
Hi @nreimers 
I just wanted to let you know of my new work about something we call _multilingual finetuning with language-crossing_:
- [Model card](https://github.com/PhilipMay/transformers/tree/mc-cross-en-de-st/model_cards/T-Systems-onsite/cross-en-de-roberta-sentence-transformer)
- [Model on HF](https://huggingface.co/T-Systems-onsite/cross-en-de-roberta-sentence-transformer)
- Demo and Test Code: https://colab.research.google.com/drive/1gtGnKq_dYU_sDYqMohTYVMVpxMJjyH0M?usp=sharing

The model outperforms your best dedicated nli-stsb large English model `roberta-large-nli-stsb-mean-tokens` (see model card).

I wanted to ask for your feedback and if you would agree to link from your page to these models as "3rd party models".

**Comment by nreimers** [comment]
Hi @PhilipMay 
Thanks for sharing, happy to see work on German 👍 

I will add an entry to the pre-trained models page and will add a link to the model card on HF (once it is merged).

Best
Nils

**Comment by PhilipMay** [comment]
I am looking forward to your paper about the `xlm-r-distilroberta-base-paraphrase-v1` training. When will it be released? Will you open source the training data and the training code? And will there bie a v2 Version? ;-)

**Comment by nreimers** [comment]
- I hope it will be released Januar 2021.
- Yes, training code will be made available. The datasets are publicly available and most can be shared without issues
- I hope there will be a v2 Version. Currently the project is a bit on-ice for other research projects, hence, I decided what I have so far (v1). But I have ideas for an improved version which will then be released as v2

**Comment by PhilipMay** [comment]
Thanks for the link. Closing this now.
