### ISSUE TITLE
GPU running OOM when doing predictions

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#522]
Hi,
we are doing predictions on about 4,000,000 texts. We observe that the GPU memory usage goes up and up and then runs OOM.

We checked the code and have the impression that the results remain on GPU until the full prediction on all batched is done.
Then the results are moved to CPU. Could you please check that?

Here are the critical lines:

Prediction loop on batches:
https://github.com/UKPLab/sentence-transformers/blob/3f6655c0ee7cbbc3153a9628ff32bd5f44429846/sentence_transformers/SentenceTransformer.py#L175

Move results to CPU:
https://github.com/UKPLab/sentence-transformers/blob/3f6655c0ee7cbbc3153a9628ff32bd5f44429846/sentence_transformers/SentenceTransformer.py#L197

IMO a fix would be to move the results back to CPU after each batch of prediction. As an optimization you could do that each configurable number of iteration.

PS: If you want to I can work on a PR tonight...

**Comment by nreimers** [comment]
Yes, this is a know thing:
https://github.com/UKPLab/sentence-transformers/issues/487

The issue is that there are different use cases. For some downstream use cases, it make sense to keep the tensors on GPU, for example, if you continue using them (e.g. to compute cosine similarities. There it is better to compute them on the GPU).

What could be done is to check if convert_to_tensors is True and then moving them within the loop to CPU instead of moving them at the end.

**Comment by PhilipMay** [comment]
> What could be done is to check if convert_to_tensors is True and then moving them within the loop to CPU instead of moving them at the end.

I think you mean: _"check if **convert_to_numpy** is True and then moving them within the loop to CPU instead of moving them at the end."_ - right?

**Comment by nreimers** [comment]
Yes, right

**Comment by PhilipMay** [comment]
I started a PR: https://github.com/UKPLab/sentence-transformers/pull/525

**Comment by PhilipMay** [comment]
Fixed - so closing it.

**Comment by Quetzalcohuatl** [comment]
@PhilipMay Your PR only works if convert_to_numpy == True. I just made a PR that allows it when convert_to_numpy == False. Sometimes we want to keep the embeddings still as a tensor. (Or sometimes we want to offload to cpu when we also want to save token embeddings). Check it out
