### ISSUE TITLE
BERT models during fine-tuning. 

### ISSUE THREAD

**Issue by Lukecn1** [UKPLab/sentence-transformers#526]
Hi there,

During fine-tuning for the SBERT model, are you using separate BERT models for Sentence A and Sentence B, and updating the parameters separately for each, or are you passing each sentence sequentially to a single BERT model?

**Comment by nreimers** [comment]
All sentences are passed through a single BERT model.

**Comment by Lukecn1** [comment]
Perfect, thanks for the quick answer :)
