### ISSUE TITLE
revisit item #350 - Fine Tuning Models

### ISSUE THREAD

**Issue by philopaszoon** [UKPLab/sentence-transformers#532]
Would like to reopen this if I could.  I have this same use case, so I'm trying to run this:
    https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/other/training_batch_hard_trec_continue_training.py.)

I get an error on this line:
`     dev_evaluator = TripletEvaluator.from_input_examples(dev_set, name='dev')
`
which is trying to call this function in TripletEvaluator.py:
```
    def from_input_examples(cls, examples: List[InputExample], **kwargs):
        anchors = []
        positives = []
        negatives = []

        for example in examples:
            anchors.append(example.texts[0])
            positives.append(example.texts[1])
            negatives.append(example.texts[2])
        return cls(anchors, positives, negatives, **kwargs)

```
 
It produces a "'TripletEvaluator' has no attribute 'from_input_examples'", which makes sense to me, but I'm afraid I don't know what to do about it.

Would love any help.

Thanks

**Comment by nreimers** [comment]
Which version of sentence-transformers are you using? This method was added in a more recent version of it.

**Comment by philopaszoon** [comment]
Downloaded yesterday.  0.3.2

**Comment by philopaszoon** [comment]
Sorry.  3.8

**Comment by philopaszoon** [comment]
Sorry again.  Had a pyenv mixup.  That problem occurred in 3.2, but does not in 3.8.
