### ISSUE TITLE
TypeError: 'InputExample' object does not support indexing when using LabelAccuracyEvaluator

### ISSUE THREAD

**Issue by blueberry-cake** [UKPLab/sentence-transformers#537]
When using the LabelAccuracyEvaluator 

`train_data = SentencesDataset(ukp_reader.get_examples('train.csv'), model)
train_dataloader = DataLoader(train_data, shuffle=True, batch_size=train_batch_size)
train_loss = losses.SoftmaxLoss(model=model,sentence_embedding_dimension=model.get_sentence_embedding_dimension(),num_labels=4)
evaluator = LabelAccuracyEvaluator(dev_dataloader,"dev",train_loss)`

I end up with an 

> TypeError: 'InputExample' object does not support indexing

I think this is the case because there is no "from_input_examples" class method for the LabelAccuracyEvaluator? Could be wrong though.

**Comment by nreimers** [comment]
You have to provide a dataloader to this evaluator.

**Comment by blueberry-cake** [comment]
Thank you very much for your answer @nreimers !
I provided a Dataloader to the evaluator, but didn't wrap the data into a SentenceDataset.. I now found the error. Should have seen this before..
