### ISSUE TITLE
model_distillation.py

### ISSUE THREAD

**Issue by haoyongfei** [UKPLab/sentence-transformers#544]
sentence-transformers     0.3.4
torch                     1.6.0+cu92
teacher_model_name = 'roberta-base-nli-stsb-mean-tokens'
teacher_model = SentenceTransformer(teacher_model_name)

run model_distillation.py
I1103 18:56:49.467106 140505860925248 SentenceTransformer.py:34] Load pretrained SentenceTransformer: /root/workspace/bertviz/sentence_transformers/v0.2_roberta-base-nli-stsb-mean-tokens
I1103 18:56:49.468462 140505860925248 SentenceTransformer.py:72] Load SentenceTransformer from folder: /root/workspace/bertviz/sentence_transformers/v0.2_roberta-base-nli-stsb-mean-tokens
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-aa5a9901b30f> in <module>
     40 # teacher_model_name = 'roberta-base-nli-stsb-mean-tokens'
     41 teacher_model_name = '/root/workspace/bertviz/sentence_transformers/v0.2_roberta-base-nli-stsb-mean-tokens'
---> 42 teacher_model = SentenceTransformer(teacher_model_name)
     43 
     44 output_path = "output/model-distillation-" + datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

~/.virtualenvs/nlp_torch/lib/python3.6/site-packages/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device)
     84                 for module_config in contained_modules:
     85                     module_class = import_from_string(module_config['type'])
---> 86                     module = module_class.load(os.path.join(model_path, module_config['path']))
     87                     modules[module_config['name']] = module
     88 

~/.virtualenvs/nlp_torch/lib/python3.6/site-packages/sentence_transformers/models/Transformer.py in load(input_path)
     85         with open(os.path.join(input_path, 'sentence_bert_config.json')) as fIn:
     86             config = json.load(fIn)
---> 87         return Transformer(model_name_or_path=input_path, **config)
     88 
     89 

TypeError: __init__() got an unexpected keyword argument 'do_lower_case'
why?

**Comment by nreimers** [comment]
Can you try it with the most recent version of sentence transformers?

**Comment by haoyongfei** [comment]
ok,thank you

**Comment by haoyongfei** [comment]
@nreimers ok,thank you
