### ISSUE TITLE
wandb automatically initialized on import

### ISSUE THREAD

**Issue by sauln** [UKPLab/sentence-transformers#550]
Is it possible to turn this off?  Every time I import something from this package, wandb creates a `wandb` directory in my working directory.  I don't use wandb and don't plan to any time soon, so this is a particularly annoying side effect.  

Can this be turned off?

**Comment by nreimers** [comment]
Yes, it is horrible by wandb.

This package does not use wandb. Transformers package has an optional import for it: If it is installed, it is imported by transformers and the wandb folder is created. 

Solution: Uninstall wandb package and complain at the wandb repository for the horrible behavior they have.

**Comment by sauln** [comment]
oh dang. Sorry, it sounds like it's not this package that is causing the problem.  My bad!
