### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by thesby** [UKPLab/sentence-transformers#551]
```python
import sentence_transformers
```
output:
```
Segmentation fault
```
I tried some versions: 0.3.5, 0.3.5.1, 0.3.6, 0.3.7, 0.3.7.1, 0.3.7.2, 0.3.8. All these versions give same error. But 0.3.4 is OK.

python version: 3.7.5rc1
gcc: 4.9.2
OS: centos 7

**Comment by nreimers** [comment]
This might be helpful:
https://stackoverflow.com/questions/10035541/what-causes-a-python-segmentation-fault

**Comment by thesby** [comment]
Missing separate debuginfo for /usr/local/lib/python3.7/site-packages/torch/lib/libgomp-7c85b1e2.so.1
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/0c/0cf5452435739ebddf30a881ede53634718e67.debug
Missing separate debuginfo for /home/admin/work_dir/.local/lib/python3.7/site-packages/sklearn/__check_build/../../scikit_learn.libs/libgomp-3300acd3.so.1.0.0
[New Thread 0x7fff542a3700 (LWP 2655)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fff00000005 in ?? () from /usr/local/lib/python3.7/site-packages/torch/lib/libtorch.so
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.1.alios7.x86_64 glibc-2.17-260.alios7.x86_64 keyutils-libs-1.5.8-3.4.alios7.x86_64 krb5-libs-1.15.1-37.2.alios7.x86_64 libcom_err-1.43.5-8.alios7.x86_64 libffi-3.0.13-18.1.alios7.x86_64 libselinux-2.5-14.1.1.alios7.x86_64 libuuid-2.23.2-61.2.alios7.x86_64 nss-softokn-freebl-3.16.2.3-13.1.alios7.x86_64 openssl-libs-1.0.2k-19.alios7.x86_64 pcre-8.32-15.1.alios7.x86_64 xorg-x11-drv-nvidia-libs-418.87.00-1.el6.x86_64 xz-libs-5.2.2-1.alios7.x86_64 zlib-1.2.7-16.2.alios7.x86_64

**Comment by nreimers** [comment]
Looks like some issue with Pytorch. Maybe you can try different versions and different ways of installing pytorch.

**Comment by thesby** [comment]
Yes, after upgrade pytorch to 1.6, there is no problem
