### ISSUE TITLE
SentenceTransformer partially ignores 'device' attribute

### ISSUE THREAD

**Issue by Rexhaif** [UKPLab/sentence-transformers#56]
Hi, thanks for awesome research!)
I'm currently experimenting with large-scale similarity search. I'm using our institute's shared machine with two 2080ti gpus. Sometimes, gpu-0 is used by someone else, so i've loaded SentenceTransformer with device argument "cuda:1". I've noticed(via gpustat) that while model is correctly loaded into gpu-1 memory(consuming around 980+ mb)
![image](https://user-images.githubusercontent.com/5154447/68546737-c7f25700-03ea-11ea-8ec4-844344e3594b.png)
calling model.encode() leads to allocating small amount of memory on the gpu-0 
![image](https://user-images.githubusercontent.com/5154447/68546748-ece6ca00-03ea-11ea-877e-496d9454ce01.png)
It is not big problem for now, but it looks like incorrect behavior.

**Comment by nreimers** [comment]
I think this is quite common behavior for pytorch.

I can recommend to use the environment variable CUDA_VISIBILE_DEVICES to control which GPUs are visible to the process.

If you set this var to 1, only GPU1 will be used. 

Best regards 
Nils Reimers
