### ISSUE TITLE
encoder without share parameter

### ISSUE THREAD

**Issue by whu20122015** [UKPLab/sentence-transformers#562]
Thank you for your great work in semantic representation. But I find the model sent two sentence to one bert model. Is there any solution that sent two sentence to two bert model?

**Comment by nreimers** [comment]
Hi @whu20122015 
Currently this is not implemented.

You would need to create a new model and pass along the sentence some identifier (sent_A, sent_B) and than choose the right sub-model to process it.

**Comment by whu20122015** [comment]
Is the token_type_ids can work as the identifier?

**Comment by nreimers** [comment]
Yes, if you use BERT.

Have a look here.
https://github.com/UKPLab/sentence-transformers/issues/560

**Comment by whu20122015** [comment]
I'm a little confused with the texts, why the texts with two-dimensional？
InputExample(texts=[['My first sentence', ''], ['', 'My second sentence']], label=0.8)
previous texts is InputExample(texts=['My first sentence', 'My second sentence'], label=0.8)

**Comment by nreimers** [comment]
They are then inputted as sentence A and sentence B to BERT.
