### ISSUE TITLE
train_script.py

### ISSUE THREAD

**Issue by EquatorSavage** [UKPLab/sentence-transformers#566]
distiluse-base-multilingual-cased\train_script.py

1.
"#Multilingual base model we use to imitate the teacher model
student_model_name = 'input_models/distilmuse-no-tatoeba'
Where to download?

2.
from USEModel import USEModel
from Normalize import Normalize

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-7552e9a07502> in <module>
----> 1 from USEModel import USEModel
      2 from Normalize import Normalize
ModuleNotFoundError: No module named 'USEModel'

Which module to install?

**Comment by nreimers** [comment]
It is some custom class to wrap the USE model:

USEModel.py
```
import tensorflow_hub as hub
import numpy as np
import tensorflow_text
import tensorflow as tf
import torch


class USEModel:
    def __init__(self, model_name):
        self.embed_model = hub.load(model_name)

    def encode(self, sentences, **kwargs):
        sentences = [sent[0:500] for sent in sentences]
        batch_size = 16
        embeddings = []
        for start_idx in range(0, len(sentences), batch_size):
            batch_emb = self.embed_model(sentences[start_idx:start_idx + batch_size]).numpy()
            embeddings.extend(batch_emb)
        embeddings = torch.tensor(np.asarray(embeddings))
        return embeddings
```

**Comment by EquatorSavage** [comment]
@nreimers Thanks for your response!
