### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by chaochaoSZ** [UKPLab/sentence-transformers#57]
RuntimeError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 10.91 GiB total capacity; 9.52 GiB already allocated;
17.56 MiB free; 776.30 MiB cached)

I used a roberta model
When I used batch size=16.

**Comment by nreimers** [comment]
What was your max token length? Bert base or large?

BERT has a quadratic memory requirement with the sentence length. Especially with the large model, you run quickly our of memory.
