### ISSUE TITLE
OSError: Can't load config for 'xlm-r-100langs-bert-base-nli-mean-tokens'. 

### ISSUE THREAD

**Issue by Etris** [UKPLab/sentence-transformers#573]
Hi, I'm using SentenceTransformers on local env, pytorch 1.7.0, sentence-transformers 0.3.8, transformers 3.3.1. Yesterday I was also struggling with SSL Error, but after mirror changes mentioned at #571 i'm getting following error.

**Code line**:
`self._local_model = SentenceTransformer('xlm-r-100langs-bert-base-nli-mean-tokens')`

**Error:** (only end of it)
First error:
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://sbert.net/backup/models/xlm-r-100langs-bert-base-nli-mean-tokens.zip

(And that's a fact - this model is not available in backup/models)

And second, that is following this one:
OSError: Can't load config for 'xlm-r-100langs-bert-base-nli-mean-tokens'. Make sure that:

- 'xlm-r-100langs-bert-base-nli-mean-tokens' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'xlm-r-100langs-bert-base-nli-mean-tokens' is the correct path to a directory containing a config.json file

**Comment by nreimers** [comment]
The name of the model has changed to:
```
xlm-r-bert-base-nli-stsb-mean-tokens
```

It is the same model, but without the '100langs' in the name. On the primary server, the model is available under both names, but on the mirror server, only the model is only stored under the most recent name `xlm-r-bert-base-nli-stsb-mean-tokens`
