### ISSUE TITLE
[Feature] add BERTweet to list of models

### ISSUE THREAD

**Issue by Jbollenbacher** [UKPLab/sentence-transformers#585]
Please add [BERTweet](https://github.com/VinAIResearch/BERTweet) to the list of supported models.  

Thanks

**Comment by nreimers** [comment]
Any Huggingface Model can be loaded like this, including BERTweet:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

However, BERT model produce out-of-the-box rather bad sentence embeddings and sentence pair training data is needed to derive a good sentence embedding model

**Comment by Jbollenbacher** [comment]
Thanks for your quick and clear reply.  Closing this issue.
