### ISSUE TITLE
Got NaN when using `util.pytorch_cos_sim`

### ISSUE THREAD

**Issue by Zero0one1** [UKPLab/sentence-transformers#589]
Hi, @nreimers . Thank you for this great tool first.
I met an issue when applying the semantic search example code to my scenario. I load the `word2vec` embedding that I trained using `gensim`, then use `np.mean` to calculate the average word vectors as sentence embedding and transform `np array` to `tensor.Tensor`. Next, I use `util.pytorch_cos_sim` and `torch.topk` to get the most similar sentence-sentence pairs.
At first, the output is ok. Then I don't know why the scores of top 3~10 similar results are all NaN(the score of the most similar pair should be 1, right?)

**Comment by nreimers** [comment]
Some of your embeddings consists of only zeros, which is the case if the input text does not contain any words that are in the word embeddings vocab.

For zero embeddings cos Sim is not defined. 

Before you use topk, use numpy to replace NaN with e.g. 0 or -1

**Comment by Zero0one1** [comment]
Yes, that's the reason! Thank you for your explanation and suggestion : )
