### ISSUE TITLE
Model Distillation - Number of attention heads

### ISSUE THREAD

**Issue by hrsmanian** [UKPLab/sentence-transformers#595]
Thanks for the amazing piece of work. Very useful.
I am trying to use the model distillation to get a smaller sentence transformer model. Like something that would have an output embedding size of 128 and only two attention heads. Is it possible to specify the embeddings size and number of attention heads for the student model? Kindly let me know

Thanks in advance

**Comment by nreimers** [comment]
Hi @hrsmanian 
What you can specify as student is a model that has these properties. I.e. in 
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/distillation/model_distillation.py

You set
`use_layer_reduction = False`

In Line 76 you specify the model you like to have as student.

I have uploaded various small models with fewer dimensions and attention heads here:
https://huggingface.co/nreimers

Other, a lot of tensorflow BERT models are available here, which can be converted to Huggingface Pytorch models:
https://github.com/google-research/bert

**Comment by hrsmanian** [comment]
Thanks for the reply. Before you replied, I tried the following approach by changing the student model's transformer config as below

auto_model.config.num_attention_heads = 2
auto_model.config.hidden_size = 128
auto_model.config.intermediate_size = 512

This yielded a much bigger model than expected at 121 Mb.

I will try as you suggested. Just for experimentation, I am interested in a model with single layer and 2 attention heads. Not sure if one can create one

**Comment by nreimers** [comment]
Just changing these values will likely not work, as the respective weight matrices must be re-sized / dropped etc.

You would need to dig deeper in the transformers implementation to see which parameters can simply be dropped and where you need to resize weight matrices.

**Comment by hrsmanian** [comment]
Thanks, I will take a look.

**Comment by thesby** [comment]
@nreimers I distill the xlm-100 model from 12 layers to 4 layers, but the model size just reduces about 30%, and it's inference speed improves 40%. But since layers reduces to its 1/3,  I expect the model reduces to 1/3, and its speed improves 200%. Why is there big difference? Please help me, thank you.

**Comment by nreimers** [comment]
@thesby 

The largest layer is the first layer (the word embedding layer). It has 128k x 768 parameters. It is substantially larger than any other layer.

Regarding the speed:
The Python based tokenizer can be an issue, as it can be quite slow. XLM uses SentencePiece tokenizer, I don't know if Huggingface offers a fast version for it.

But using the fast tokenizer (if available) can speed up the things:
https://www.sbert.net/examples/applications/information-retrieval/README.html#pre-trained-cross-encoders-re-ranker

You can also try to run the tokenization using multiple workers, by setting num_workers = 2  in the encode function. But this is only sensible for larger datasets to encode, as creating new threads for tokenization as some overhead.

**Comment by thesby** [comment]
I got it. Actually, I don't need such big embedding layer, because I just use it for one or two language. And 50k words are enough for me.

Should I use the tokenizer to choose top 50k words for my dataset, and split the embedding layer columns from the big embedding matrix? This may be the most easiest way to keep the pretrained model parameters.

**Comment by nreimers** [comment]
@thesby This could be an option. Other tokens could then be replaced by the UNK token.

Not sure how complicated this change is. You have to update the embedding layer and have to examine the tokenizer how so that removed tokens are correctly mapped to the UNK token.

**Comment by thesby** [comment]
@nreimers Another option is to distill the embedding layer with my dataset and my bpe tokenizer. But I don't know how to get the embedding layer output.

**Comment by thesby** [comment]
I think use the first encoder layer is also ok for distillation.

**Comment by thesby** [comment]
@nreimers The tokenizer is very fast, whose qps reaches about 7000 article/second. Which layer is the most expensive for computation if my model max sequence length is 2048 with `Longformer`? All transformer layers should be the same computation complexity, I think.
