### ISSUE TITLE
What is the classical loss for doc ranking problem? Thank you.

### ISSUE THREAD

**Issue by guotong1988** [UKPLab/sentence-transformers#6]
Based on my understanding, Multiple Negatives Ranking Loss is a better loss for doc ranking problem.
What is the former classical loss for doc ranking problem?
Thank you very much.

**Comment by nreimers** [comment]
Not sure if I understand your question. See #5 for more info on multiple negative ranking loss

**Comment by guotong1988** [comment]
Thank you! I mean, are there any other loss function for doc ranking problem?
