### ISSUE TITLE
clusting

### ISSUE THREAD

**Issue by sixmilesroad** [UKPLab/sentence-transformers#600]
Thank you for your project. If I want to cluster Chinese phrases, which pre training model should I use. thank you.

**Comment by nreimers** [comment]
You can try xlm-r-distilroberta-base-paraphrase-v1 and distiluse-base-multilingual-cased-v2

**Comment by sixmilesroad** [comment]
I found only disuse base multilingual cased, but I didn't find disuse base multilingual cased v2. Can you provide a link? thank you.

**Comment by nreimers** [comment]
https://www.sbert.net/docs/pretrained_models.html

**Comment by sixmilesroad** [comment]
emmm,I only found these text, but I couldn't find the download link。
“distiluse-base-multilingual-cased-v2: Multilingual knowledge distilled version of multilingual Universal Sentence Encoder. While the original mUSE model only supports 16 languages, this multilingual knowledge distilled version supports 50+ languages.”

**Comment by nreimers** [comment]
Models are automatically downloaded.

Otherwise you can access
https://www.sbert.net/models

**Comment by sixmilesroad** [comment]
ohhhhhhhhhhh,that is what i need  ! thanks a lot!  have a nice day !
