### ISSUE TITLE
Finetuning Bert on unlabeled text

### ISSUE THREAD

**Issue by datistiquo** [UKPLab/sentence-transformers#601]
Thank you for your awesome work! I just looked briefly in to the issues and sections and I find literally almost everything what I tried before without knowing that it is already done here.

I have fine tuned a base model on my sentence pair task (for semantic searching). Now next I wanted to try to finetune the LM model just on my plain text to compare both finetuned models. My hope is that I just need to fine tune th eLM model on text to get comparable or even better results than finetuning on labeled data.

Do you have any examples for finetuning a LM BERT on unlabeldd text? My text is also relatively small. Do you have any hints on the hyperparameters for small text? I suppose I need just 1 epoch.

**Comment by nreimers** [comment]
Hi @datistiquo 
We are currently working on this an plan to release the paper and code soon.

Sadly it is not that easy to just tune the language model. BERT and other transformer models that were just trained with language models produce rather bad sentence embeddings. 

What you can do ist first to fine-tune the language model (as shown in  the hugging face repository) and then tune it on your labeled data.

**Comment by datistiquo** [comment]
> We are currently working on this an plan to release the paper and code soon.

What are referring to my 1. post?

Yes, that was the question if just finetuning the LM would get proper results without finetuning anymore on labeled data.

**Comment by nreimers** [comment]
Yes, we are currently working on ways how to tune models by tuning the language model. It is sadly not that easy and needs some special tricks and twists, which we are currently evaluating.

But tuning with labeled data will always yield the better results than the unsupervised approaches.

**Comment by datistiquo** [comment]
Ok, now I understadnd what you meant. That is right. Cool. I wait for it. :)
