### ISSUE TITLE
"overflow encountered in reduce" in the parallel-sentence-mining

### ISSUE THREAD

**Issue by LukeTu** [UKPLab/sentence-transformers#607]
Thank you for providing the great application for parallel-sentence-mining！

I tried the code you kindly provide and it worked perfectly well for the bucc corpora.

However, when I tried the code with two corpora with only a few lines of sentences and it got an overflow in numpy.

The detail is as follow:

4it [00:00, 4673.32it/s]
2it [00:00, 1120.27it/s]Read source file
Read target file
Source Sentences: 4
Target Sentences: 2
Encode source sentences

Batches: 100%
1/1 [00:00<00:00, 4.28it/s]

Encode target sentences
Batches: 100%
1/1 [00:00<00:00, 16.39it/s]

Perform approx. kNN search
Done: 0.03 sec
Perform approx. kNN search
Done: 0.00 sec
Write sentences to disc
Done. 0 sentences written
/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:151: RuntimeWarning: overflow encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims)

I'm thinking perhaps there might be some parameters that I can adjust for corpora that has less content? 

It would be much appreciated if anyone could give me some pointers!

Thanks again for your amazing code!

**Comment by nreimers** [comment]
The margin approach uses 4 nearest neighbors to determine the score. If you only have 2 sentences, it cannot find 4 nearest neighbors.

Please try it with more lines (I would suggest at least 100).

**Comment by LukeTu** [comment]
> The margin approach uses 4 nearest neighbors to determine the score. If you only have 2 sentences, it cannot find 4 nearest neighbors.
> 
> Please try it with more lines (I would suggest at least 100).

Thank you so much, it works perfectly now!
