### ISSUE TITLE
About bert-base-nli-stsb-mean-tokens model 

### ISSUE THREAD

**Issue by xuanzebi** [UKPLab/sentence-transformers#61]
bert-base-nli-stsb-mean-tokens: First fine-tuned on AllNLI, then on STS benchmark training set. Performance: STSbenchmark: 85.14 

It says first fine-tuned on ALLNLI,but in training_stsbenchmark_bert.py file 
`word_embedding_model = models.BERT('bert-base-uncased')`

It use the AllNLI data for fine tune?

**Comment by xuanzebi** [comment]
sts-models.md  writes 
For a training example, see examples/training_stsbenchmark.py. 
i think if the file is training_stsbenchmark_continue_training.py  ?

**Comment by nreimers** [comment]
Thanks for pointing this out, I updated the sts-models.md file.

training_stsbenchmark_continue_training.py  uses the fine-tuned model that was trained on AllNLI data and then trains it on STS data.
