### ISSUE TITLE
Pre-processing / cleaning

### ISSUE THREAD

**Issue by SeanPedersen** [UKPLab/sentence-transformers#610]
Hey,
I could not find any issue / documentation on recommended pre-processing for the pre-trained transformer models? I am using following code to clean my sentences (with NLTK), is this recommended? Thanks for any tips.
```
def clean_up(text):
    # Split book in sentences
    sentences = sent_tokenize(text)
    # Clean up sentences from puctuation
    cleaned = []
    for sentence in sentences:
        # split into words
        tokens = word_tokenize(sentence)
        # remove all tokens that are not alphabetic
        clean_sentence = " ".join(word for word in tokens if word.isalpha())
        cleaned.append(clean_sentence)
    return cleaned
```
Results in:

dirty = "What's up --ma;n?? this is sooo dirt___y."

clean_up(dirty) == ["Whats up man", this is sooo dirty"]

**Comment by nreimers** [comment]
I don't use any pre-processing, but I usually have more clean data.

What you show sounds reasonable.
