### ISSUE TITLE
T-Systems-onsite/cross-en-de-roberta-sentence-transformer Model not found

### ISSUE THREAD

**Issue by ChristineBuh** [UKPLab/sentence-transformers#613]
Hello,

currently I am working on my Master Thesis and would like to use the T-Systems-onsite/cross-en-de-roberta-sentence-transformer model for sentence similarity task. I am following the instructions on https://huggingface.co/T-Systems-onsite/cross-en-de-roberta-sentence-transformer to install the sentence transformer and to load the model. Sadly, I get this error:
Error:
Exception when trying to download https://sbert.net/models/T-Systems-onsite/cross-en-de-roberta-sentence-transformer.zip. Response 404
WARNING:root:SentenceTransformer-Model https://sbert.net/models/T-Systems-onsite/cross-en-de-roberta-sentence-transformer.zip not found. Try to create it from scratch
WARNING:root:Try to create Transformer Model T-Systems-onsite/cross-en-de-roberta-sentence-transformer with mean pooling

my code for loading the model is:
Code:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('T-Systems-onsite/cross-en-de-roberta-sentence-transformer')

I am new to programming and would really like to use this model. I already checked on https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/ to find it and download it, but I can't find it there. I also checked the evaluation code on colab, but there is the same issue. 

I would really appreciate if someone could help me with my issue. Thanks in advance!

**Comment by nreimers** [comment]
The warning is expected and can be ignored. The model is not hosted by us (hence the 404 error), instead it is hosted at huggingface model repository.

You can load it and use it as described.

**Comment by ChristineBuh** [comment]
Thank you so much for your fast responds!

**Comment by PhilipMay** [comment]
Hey @ChristineBuh 
I am the creator of the model and very interested in an exchange about your experience with the embeddings. 
If you are also interested in exchange and networking please feel free to contact me.

Thanks
Philip

**Comment by ChristineBuh** [comment]
Hey @PhilipMay ,

I would really appreciate an exchange about the embeddings. I am currently doing some more research on this field. As soon as I start programming again, I would be gladly accept your offer.  

Thank you so much, 
Christine

**Comment by typoworx-de** [comment]
Well... in the mean-time I luckily figured out the correct python-code to use is behind the huggingface website button "use in Transformers", at least to get the model downloading still having some issues to resolve now.

**Comment by nreimers** [comment]
@typoworx-de You must install the protobuf package via pip

**Comment by SameerAdavani** [comment]
@PhilipMay I am currently using your model to get embeddings for German Language sentences. The model is yielding good results. In this project, I need to develop an End to End Recommender system and deploy it on a server. As of now, I am able to get good results on my machine, and now it's time to put this into the server. As I am new to this web-client and server-related things. Would you guide me  on how to deploy a ML model into the server to get inputs from the user

**Comment by PhilipMay** [comment]
Well, that is a topic one could write a book about.

IMO the most simple way would be to add a REST api to the model by using FastAPI
and then dockerize it.

If you want to have it more scalable you could use Kubernetes and Seldon:

https://www.seldon.io/
