### ISSUE TITLE
Feature Importance

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#619]
Hi @nreimers 
do you have any experience on how to answer the following question:

Which words (tokens) do have the most influence on the direction (semantic) of the embedding vector of a certain text?

Thanks
Philip

**Comment by nreimers** [comment]
You could compute the vector length for each embedding. The vectors with the largest l2 norm should have the most impact.

**Comment by PhilipMay** [comment]
> You could compute the vector length for each embedding. The vectors with the largest l2 norm should have the most impact.

That would be on token layer and not on word layer but I get what you mean. Nice idea - thanks!
I would have to add up the token vectors that belong to a word...

**Comment by PhilipMay** [comment]
closing
