### ISSUE TITLE
Loading a Custom Sentence-Transformers Model

### ISSUE THREAD

**Issue by jonsaadfalcon** [UKPLab/sentence-transformers#620]
Hello, I am trying to load a custom sentence-transformers model that was created using the documentation [here](https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch) but when I load the model, I get the following error with the version:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-a06f55dd99c4> in <module>
      1 from sentence_transformers import SentenceTransformer
----> 2 model = SentenceTransformer('skiff_files/apps/example/0_Transformer')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sentence_transformers/SentenceTransformer.py in __init__(self, model_name_or_path, modules, device)
    102                     with open(os.path.join(model_path, 'config.json')) as fIn:
    103                         config = json.load(fIn)
--> 104                         if config['__version__'] > __version__:
    105                             logging.warning("You try to use a model that was created with version {}, however, your version is {}. This might cause unexpected behavior or errors. In that case, try to update to the latest version.\n\n\n".format(config['__version__'], __version__))
    106 

KeyError: '__version__'

---------------------------------------------------------------------------

Any ideas on how to address this issue? I am currently using the latest version of sentence-transformers.

**Comment by nreimers** [comment]
You have to load the parent folder.

A SentenceTransformer consists of multiple modules. In the most basic case it is 0_Transformer and 1_Pooling.

Loading 0_Transformer is wrong. You have to load the parent folder where there is a config.json and a modules.json that define which modules your SentenceTransformer has
