### ISSUE TITLE
Cannot reproduce bert-base-uncased of the paper 

### ISSUE THREAD

**Issue by leerumor** [UKPLab/sentence-transformers#621]
hi, I use the pretrained model of in https://huggingface.co/bert-base-uncased/tree/main, but cannot reproduce the score in the paper. Do you use the same version of BERT?

here is my result:
| STS-B | SICK-R | STS-12 | STS-13 | STS-14 | STS-15 | STS-16
bert_base_mean(SBERT) | 0.4635 | 0.584 | 0.3878 | 0.5798 | 0.5798 | 0.6315 | 0.6106
my_result | 0.4729 | 0.5822 | 0.3087 | 0.5989 | 0.4773 | 0.6029 | 0.6373

**Comment by nreimers** [comment]
Hi @leerumor 
I used in the paper for the BERT mean pooling BERT-as-a-service:
https://github.com/hanxiao/bert-as-service

As it was pointed out later, the "mean pooling" operation is actually a mean pooling operation over the last few layers of BERT.

**Comment by leerumor** [comment]
Okay, thanks very much ;)
