### ISSUE TITLE
Loading Custom SentenceTransformer Models

### ISSUE THREAD

**Issue by gianfilippo** [UKPLab/sentence-transformers#624]
Hi,

I would lie to load a bert based model, but I do not see the modules.json file. I am new to this, so I am not sure why this is missing.
Anyway, when I try to load the model, pointing at the parent directory, I get an error message.
Is there a way from me to load the model in the other package and save it so that it generates the modules.json file ?

Thanks

**Comment by nreimers** [comment]
Hi,
have a look here:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

After you created the sentence transformer from the different sub components, you can call save on the model object to store it to disc.

**Comment by gianfilippo** [comment]
Hi,
thanks. I am actually trying to use a model developed by someone else. It is also based on BERT. I would not want to create the network from scratch, at the moment. 
I want is to be able to load his model and use the embeddings for downstream processing.
I am not very experienced and the environment you created is something I would like to try

**Comment by nreimers** [comment]
Yes, in the linked code you can load any huggingface transformer model and use it to produce sentence embeddings

**Comment by gianfilippo** [comment]
I could load the model. Thanks!
