### ISSUE TITLE
 Are all models quantified?

### ISSUE THREAD

**Issue by EquatorSavage** [UKPLab/sentence-transformers#627]
Are all models quantified?

**Comment by nreimers** [comment]
What do you mean with quantified models?

**Comment by EquatorSavage** [comment]
@nreimers 
Quantization refers to a technique that uses fewer bits than floating-point precision for calculation and storage. A quantized model uses integer tensor instead of floating-point tensor to perform some or all of the operations. This is a more compact model representation and can take advantage of high-performance vector operations on many hardware platforms.

**Comment by nreimers** [comment]
Hi @EquatorSavage 
Thanks for the explanation. No, quantization is not performed. Models are stored as floats.

Do you know if there is good code available to quantify Huggingface Transformer models?

**Comment by EquatorSavage** [comment]
@nreimers 
Thanks.
I have no idea.
I want to convert model to ONNX and then quantified the ONNX model.But, I failed when I converted the model to ONNX.

**Comment by nreimers** [comment]
@EquatorSavage 
Have a look here:
https://github.com/UKPLab/sentence-transformers/pull/386

**Comment by EquatorSavage** [comment]
@nreimers 
Thanks,I will try.
