### ISSUE TITLE
sbert.net is down. Where can I view list of pretrained models?

### ISSUE THREAD

**Issue by mani-rai** [UKPLab/sentence-transformers#635]

**Comment by nreimers** [comment]
Hi. I can access the website without issues.

**Comment by mani-rai** [comment]
sbert.net is area restricted. Only using VPN I could access the doc.

**Comment by nreimers** [comment]
Otherwise you can find all models here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/

**Comment by mani-rai** [comment]
Thanks man... That's helpful BTW. Using VPN slows down the internet.

**Comment by nreimers** [comment]
The respective site is also here in git
https://github.com/UKPLab/sentence-transformers/blob/master/docs/pretrained_models.md
