### ISSUE TITLE
Question about the size of model

### ISSUE THREAD

**Issue by sammloo** [UKPLab/sentence-transformers#637]
Comparing the size of senetenceBert models and original models, like

bert-base-nli-cls-token => 400M, bert-base => 110M
distilbert-base-nli-mean-tokens.  => 200M,  distilbert-base => 66M

The models proposed in sentence-transformers are actually more than double to the size of original models.

So why ? Is it because you are using Siamese structure ? If yes, can we just use only one Bert model in Siamese to get vectors, since the two bert models should be identical.

Thanks,

**Comment by nreimers** [comment]
Hi
according to here
https://huggingface.co/bert-base-uncased/tree/main

Bert-base has a size of 420 MB. 110M are the number of parameters, not the model size. 

Only a single BERT model is stored in sentence Transformers

**Comment by sammloo** [comment]
Thanks for your quick reply. You are right. 1 parameter, float32, needs 4 bytes to store, 110M parameters will take over 400MB.
