### ISSUE TITLE
How to change the default models download directory?

### ISSUE THREAD

**Issue by echatzikyriakidis** [UKPLab/sentence-transformers#638]
I see that models are downloaded here:

~/.cache/torch/sentence_transformers

I want to be able to change it in code.

The transformers library gives ability to change it using TRANSFORMERS_CACHE.

Does Sentence Tranaformers has a similar way?

**Comment by nreimers** [comment]
Hi @echatzikyriakidis 
If you use the version here from git (or the upcoming version 0.4.0), you can use:
SENTENCE_TRANSFORMERS_HOME

Otherwise, with version 0.3.9, the only way would be to change:
$TORCH_HOME

Note, you can load sentence transformers models also from disc:
```
model = SentenceTransformer('/path/zo/unzipped/model')
```

Models are available at https://sbert.net/models

**Comment by echatzikyriakidis** [comment]
@nreimers I understand, I don't want to pre-download them and use a different path. I want to jist override the cache path so that they are downloaded in the path I specify. Also, later on when I load them to be loaded from the cached directory.

I have seen you commit: https://github.com/UKPLab/sentence-transformers/commit/5e5968eca4b5b7330f6aa31483bfe246e191f379

Super! When is this going to be released in PyPI as 0.4.0?

Thank you.

**Comment by nreimers** [comment]
@echatzikyriakidis 
Version 0.4.0 was released today.

**Comment by echatzikyriakidis** [comment]
Thank you!

**Comment by sinban04** [comment]
FYI, I'm using `sentence-transformers==3.2.1`. and i've been through the same issue.

I was trying to run sentence-transformers on Pyspark, and
I figured out something from the log
```
There was a problem when trying to write in your cache folder (/home/.cache/huggingface/hub). You should set the environment variable TRANSFORMERS_CACHE to a writable directory.
2025-04-07 18:36:53.769581: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-07 18:36:53.772029: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-07 18:36:53.828081: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
```
- It seems that `TRANSFORMERS_CACHE` is used for  now

AND

```
/opt/python/python3.8/lib/python3.8/site-packages/transformers/utils/hub.py:128: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
```
`HF_HOME` is recommended,,
