### ISSUE TITLE
About provided pre-trained models.

### ISSUE THREAD

**Issue by HyeyeonKoo** [UKPLab/sentence-transformers#645]
Hello, I have a question about provided pre-trained models.
In the sentence-transformers documentation, I found some pre-trained models(https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/) like xlm-r-base-en-ko-nli-ststb.zip, xlm-r-large-en-ko-nli-ststb.zip.
I know what xlm-r-base, xlm-large, nli and stsb mean, but I am not sure what en-ko means.
Does it mean that it was trained by English and Korean?
I couldn't find about this in your documentation. Please let me know or give me the page where I can find about it.
Thank you very much.

**Comment by nreimers** [comment]
Yes, this model was trained on English and Korean.

Models that are not that useful / good are not documented, but they are still on the server in case someone needs it

**Comment by HyeyeonKoo** [comment]
That models are helpful for me. And, your answer is also helpful.
Thank you very much.
