### ISSUE TITLE
tokenizer is slow even if using Fast tokenizer

### ISSUE THREAD

**Issue by thesby** [UKPLab/sentence-transformers#647]
I find that the tokenizer is using only one CPU core for `encode`, even if I use the `XLMRobertaTokenizerFast`. And I test the 
`tokenize()` and `batch_encode_plus()`:
`tokenize()` qps: 760, cpu: 100%
`batch_encode_plus()` qps: 9980, cpu: 2450%.

Maybe `tokenize` in `encode` can use batch encode, not one by one.

**Comment by nreimers** [comment]
Hi, this is currently implemented in the v0.4.1 branch.

**Comment by thesby** [comment]
@nreimers That's great, 1000+ thanks. Looking forward to releasing.
