### ISSUE TITLE
about papers

### ISSUE THREAD

**Issue by sixmilesroad** [UKPLab/sentence-transformers#651]
Merry Christmas！！
in the paper says that bert can not produce good sentence embedding,so i can't use the sentence embedding from the bert to compute  cosin similarity directly。so s-bert use a siamese net work to fine-tune bert , what i want say is that after use a siamese net work to fine-tune bert , it's time to generate sentence embedding,the sentence embedding is generated by the fine-tuned bert ? in other words, the  sentence-embedding is genrated by the single bert in the siamese net work ? 
My English is not  good, I hope I can express it clearly

**Comment by nreimers** [comment]
Correct.

Note, in the siamese setup, both Bert networks are identical

**Comment by sixmilesroad** [comment]
got it.thank you! have a nice day!
