### ISSUE TITLE
using sbert in sagemaker

### ISSUE THREAD

**Issue by pidugusundeep** [UKPLab/sentence-transformers#653]
I would like to know if there is a way to use sbert with AWS sagemaker to generate sentence embeddings?

**Comment by nreimers** [comment]
I sadly never used Sagemaker, so I cannot help here.

**Comment by pidugusundeep** [comment]
I got the solution in this repo https://github.com/aws-samples/aws-sagemaker-text-based-product-search, tagging it here as someone might find this useful.
