### ISSUE TITLE
Siamese architecture

### ISSUE THREAD

**Issue by working12** [UKPLab/sentence-transformers#654]
I am reading the source code but I don't understand one simple thing. Where are those duplicate networks? Can you just tell that portion? The duplicate network portion and where exactly we are getting those two outputs and combining them to calculate as per this diagram?

![image](https://user-images.githubusercontent.com/12879472/103211874-aa8f8d80-4909-11eb-8b48-b8e373cf9e20.png)

1. Where exactly do we have the two models? 
2. Where exactly do we calculate `u` and `v`?

**Comment by nreimers** [comment]
The two models are just in the image. For efficiency, you just have one model.

Your InputExample has two texts, like InputExample(texts=['Sent A', 'Sent B'], label=0.8)

Sent A and Sent B are send through the same transformer network.

The embeddings are calculated in the pooling layer.

**Comment by working12** [comment]
@nreimers  Thanks a lot for so nice reply. So `embeddings[0]`, `embeddings[1]` are `u` and `v` right? And also in Siamese the weights are tied up so obviously you can just do it like that.(Sharing the network like it is done here right?)

**Comment by nreimers** [comment]
@working12 Correct

**Comment by working12** [comment]
@nreimers Once again thanks.

**Comment by LeenaShekhar** [comment]
Hi Nils,

Do you know what would be the easiest way to extend the code such that two separate towers (either complete or only separate final dense layers) can be used? Currently, if my understanding is correct then both the channels have weight sharing.

**Comment by nreimers** [comment]
@LeenaShekhar 
This was added in the latest version:
https://github.com/UKPLab/sentence-transformers/releases/tag/v0.4.1
Asymmetric Models

**Comment by LeenaShekhar** [comment]
Brilliant. Thank you so much. Let me check it out.
