### ISSUE TITLE
some promble of SentenceTransformer.py 

### ISSUE THREAD

**Issue by charlesfufu** [UKPLab/sentence-transformers#663]
![屏幕快照 2021-01-04 下午8 22 44](https://user-images.githubusercontent.com/33311822/103534945-d04d0180-4eca-11eb-8dd7-78ce55164de4.png)
Can you tell me what's the useful of  "np.argsort"?
In my opinion, If i use the function of "np.argsort", the result of embedidngs can't  match source sentences.

**Comment by nreimers** [comment]
Later in the encode method, the original order will be restored.

By sorting the sentences by length, sentences with the similar length will be in the same batch => fewer padding is needed => encoding is faster.

**Comment by charlesfufu** [comment]
> Later in the encode method, the original order will be restored.
> 
> By sorting the sentences by length, sentences with the similar length will be in the same batch => fewer padding is needed => encoding is faster.

sorry, that's the encode function

**Comment by charlesfufu** [comment]
> Later in the encode method, the original order will be restored.
> 
> By sorting the sentences by length, sentences with the similar length will be in the same batch => fewer padding is needed => encoding is faster.

Another question,If i have a sentence 'I like it'. and i want the token embedding of 'I' 、'like'、'it'. because of bert wordpiece, the output of token embedding length may be is over three. how can i just want three token embedding of  'I' 、'like'、'it' without wordpiece token embedding

**Comment by nreimers** [comment]
You have to do this by yourself.

You have to find the matching word pieces for your tokens. Then you can average the word pieces that belong to the same token or just use the first word piece of every token

**Comment by charlesfufu** [comment]
> You have to do this by yourself.
> 
> You have to find the matching word pieces for your tokens. Then you can average the word pieces that belong to the same token or just use the first word piece of every token

OK， thanks for your reply
