### ISSUE TITLE
Range of labels for CosineSimilarityLoss

### ISSUE THREAD

**Issue by huhk-sysu** [UKPLab/sentence-transformers#665]
Hi,

What's the range of labels for CosineSimilarityLoss? [-1, 1] or [0, 1]?
The cosine similarity may have a range between [-1, 1], but my dataset have a label(score) between [0, 1]. Should I manually adjust the label?

Thanks.

**Comment by nreimers** [comment]
Hi @huhk-sysu 
I used it with labels in the range [0, 1] and it worked fine.

I also tested rescaling it to [-1, 1] but (if I remember correctly, it is 2 years ago) the was no improvement back then.
