### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by aszhanghuali** [UKPLab/sentence-transformers#67]
Hi, nice work and thanks for sharing the code.
I have some questions.First of all,can I use my own Chinese datasets? Secondly,What format should my data be？
Looking forword your reply!

**Comment by nreimers** [comment]
Hi @aszhanghuali 
You can use this also for Chinese.

The format of you data depends which loss you use. See: https://github.com/UKPLab/sentence-transformers#loss-functions

Which loss you can use depends what data you have available and what your specific use-case is. Sadly there are many different ways to setup data to learn sentence embeddings and there is not the one golden way. It always depends on your use case + available data.

Best
Nils Reimers
