### ISSUE TITLE
MRR in CERerankingEvaluator

### ISSUE THREAD

**Issue by svjack** [UKPLab/sentence-transformers#678]
I think should replace “ mrr_score = 1 / (rank+1)” by “ mrr_score += 1 / (rank+1)”
the former only save the last mrr_score (the biggest in one sample),
but when i have multi positives it will omit the previous.
If use this to save model may induce some problems. 
For example, it does not measure the totally num that the model can recall.

**Comment by nreimers** [comment]
Thanks for pointing this out. There must be a break after `mrr_score = 1/(rank+1)`

It is fixed now.

**Comment by svjack** [comment]
> Thanks for pointing this out. There must be a break after `mrr_score = 1/(rank+1)`
> 
> It is fixed now.

Why use only one (the top score) rather than sum it ?

**Comment by nreimers** [comment]
Because this is how MRR is defined.

The other option is MAP, that takes precision and recall for multiple relevant docs into account.

**Comment by svjack** [comment]
> Because this is how MRR is defined.
> 
> The other option is MAP, that takes precision and recall for multiple relevant docs into account.

The recall task mainly performed by bi_encoder, when it comes to cross_encoder because it only use
query answer concat to do inference, it seems like this structure is not maintain the recall construction as
bi_encoder do, so use MAP for cross_encoder seems unadvisable.
But i think the final conclusion combine bi_encoder and cross_encoder need both high MRR and MAP.
Sometimes, cross_encoder score sort may maintain the top-one as the truly positive (because use MRR),
but when it comes to others (second third and so on), this sometimes may destroy some good orders produced
by bi_encoder, because the latter may take MAP as valid consideration but former only use MRR.
How to deal with this ?

**Comment by nreimers** [comment]
Training of the bi-encoder / cross-encoder does not use MRR / MAP as training signal. MRR / MAP is just used to evaluate models, i.e., to measure how well they performance.

Here the choice of MRR / MAP depends on you. In general:
- You only care for the first, relevant hit: You can use MRR
- You data has only one hit that is annotated as relevant: MRR and MAP are the same
- You have multiple hits annotated as relevant and you care also for the positions after the first relevant hit: Use MAP

**Comment by svjack** [comment]
> Training of the bi-encoder / cross-encoder does not use MRR / MAP as training signal. MRR / MAP is just used to evaluate models, i.e., to measure how well they performance.
> 
> Here the choice of MRR / MAP depends on you. In general:
> - You only care for the first, relevant hit: You can use MRR
> - You data has only one hit that is annotated as relevant: MRR and MAP are the same
> - You have multiple hits annotated as relevant and you care also for the positions after the first relevant hit: Use MAP

so also can use MAP as evaluation to save cross_encoder. for my perpose.

**Comment by nreimers** [comment]
Yes. Currently I think it is not implemented in that class. But you can derive your own class and use it as evaluator. There, you can compute MAP then instead of MRR

**Comment by svjack** [comment]
> Yes. Currently I think it is not implemented in that class. But you can derive your own class and use it as evaluator. There, you can compute MAP (or NDCG) then instead of MRR

if i want to save different model by different best evaluation measurements, i must edit the fit function in cross_model.

**Comment by nreimers** [comment]
No, no need to change it.

Just copy the code from CERerankingEvaluator , change where MRR is computed to the computation of MAP / NDCG and use this changed evaluator and pass it to the fit function.

**Comment by svjack** [comment]
> No, no need to change it.
> 
> Just copy the code from CERerankingEvaluator , change where MRR is computed to the computation of MAP / NDCG and use this changed evaluator and pass it to the fit function.

dose fit function support multi evaluation class in list format

**Comment by nreimers** [comment]
Not directly. But you can use this:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/evaluation/SequentialEvaluator.py

and wrap it around a list of evaluators
