### ISSUE TITLE
How can I freeze the training of particular modules of SentenceTransformer as I just want to train the added layers to the pre-trained model? E.g. freezing all Transformer module layers in the SentenceTransformer.

### ISSUE THREAD

**Issue by AmitChaulwar** [UKPLab/sentence-transformers#680]

**Comment by nreimers** [comment]
On your model, you can call: ` model._first_module()` to get the models.Transformer model. There, you can all auto_model to get the Huggingface AutoModel

The following should roughly work
```python
model = SentenceTransformer(...)
auto_model = model._first_module().auto_model
for param in auto_model .parameters():
    param.requires_grad = False
```

**Comment by AmitChaulwar** [comment]
Thanks for the reply. I did try similar thing. But, then (also with the above code) I get the following error.

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn.

**Comment by AmitChaulwar** [comment]
<img width="1270" alt="Screenshot 2021-01-11 at 16 00 48" src="https://user-images.githubusercontent.com/69140048/104198161-2fa89580-5426-11eb-9437-6d2f8d8e8fd6.png">

More info in this image.

**Comment by nreimers** [comment]
If your model only consists of a Transformer and a Pooling layer, then there are not trainable parameters.

**Comment by AmitChaulwar** [comment]
Right, I added the dense layer and it works now.  Thanks!

**Comment by AmitChaulwar** [comment]
I still face another issue. I want to keep the auto_model.pooler.dense layer from Transformer layer as trainable. I tried following things:
auto_model.pooler.dense.requires_grad = True
auto_model.pooler.dense.weight.requires_grad = True

But it doesn't work. Can you tell me how can I do that?

**Comment by nreimers** [comment]
This is roughly the code  I use in that case:
```python
model = SentenceTransformer(...)
auto_model = model._first_module().auto_model
for name, param in auto_model.named_parameters():
    if name == : #Add you check here which layer to freeze / to not freeze
        param.requires_grad = False
```

**Comment by weijiangfaire** [comment]
> If your model only consists of a Transformer and a Pooling layer, then there are not trainable parameters.

Why do you say there are no trainable parameters? The following are parameters from 'clip-ViT-B-32'. What is the proper way to do it if we want to fine-tune these parameters in the encoder layers? Thank you!

> text_model.encoder.layers.10.mlp.fc1.weight torch.Size([2048, 512])
> text_model.encoder.layers.10.mlp.fc1.bias torch.Size([2048])
> text_model.encoder.layers.10.mlp.fc2.weight torch.Size([512, 2048])

**Comment by imatiasmb** [comment]
> On your model, you can call: ` model._first_module()` to get the models.Transformer model. There, you can all auto_model to get the Huggingface AutoModel
> 
> The following should roughly work
> 
> ```python
> model = SentenceTransformer(...)
> auto_model = model._first_module().auto_model
> for param in auto_model.parameters():
>     param.requires_grad = False
> ```

Hi, I've tried this but it says that auto_model method doesn't exists. Is there a new version for doing this?

**Comment by tomaarsen** [comment]
The first module cannot be `SentenceTransformer`. To rely on a transformers model, use `Transformer` instead. So, instead of
```python
model = SentenceTransformer(modules=[SentenceTransformer(config.MODEL_PATH), dense_layer, l2_normalization])
```
consider using
```python
from sentence_transformers.models import Transformer, Pooling

transformer = Transformer(config.MODEL_PATH)
pooling = Pooling(transformer.get_word_embedding_dimension())
model = SentenceTransformer(modules=[transformer, pooling, dense_layer, l2_normalization])
```
Note that I also added a Pooling layer. That is necessary to convert the token-level embeddings from the Transformer into sentence-level embeddings.

- Tom Aarsen

**Comment by imatiasmb** [comment]
@tomaarsen I was trying the solution proposed by Nils Reimers but I don't see an improvement of the training speed after freezing the pretrained model params. What I'm doing is the following:

```python
auto_model = model._first_module().auto_model
for param in auto_model.parameters():
    param.requires_grad = False

train_loss = config.CRITERION(model=model)

model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    optimizer_class = type(optim.Adam(model.parameters())),
    optimizer_params =  {'lr': config.LEARNING_RATE_1},
    epochs=config.EPOCHS_1
)
```
Is it ok to do it this way?

**Comment by tomaarsen** [comment]
That looks fine at a glance, yes. I think only the dense model will train, then.
I do want to preface that this does not necessarily speed up training by that much, because the forward pass still needs to go through the entire model. Only the backward pass will be faster as it does not have to update the weights of the big transformer model.

- Tom Aarsen
