### ISSUE TITLE
pyo3_runtime.PanicException: no entry found for key

### ISSUE THREAD

**Issue by happygirlzt** [UKPLab/sentence-transformers#681]
Hi there,
Many thanks for your amazing work! I met some errors when I tried to fine-tune roberta-base-nli-stsb-mean-tokens on GeForce RTX 2080 Ti. I run exactly the same code on Tesla P100-PCIE-12GB and this error wasn't raised up. Do you happen to meet this exception before? Many thanks in advance.
<img width="940" alt="截屏2021-01-11 18 12 37" src="https://user-images.githubusercontent.com/15061984/104168167-96cf4580-5438-11eb-98b1-f67f0ecc98e4.png">

**Comment by nreimers** [comment]
Use the stsb-roberta-base model.

It is the same as roberta-base-nli-stsb-mean-tokens, but it uses the most recent version of the tokenizer config file format from huggingface.

**Comment by happygirlzt** [comment]
Oh, okay, many thanks for the quick reply. I'll try it now. BTW, maybe it will be great if you can update the corresponding models in https://www.sbert.net/#performance 👍

**Comment by nreimers** [comment]
Thanks for pointing this out. Names are update in git and will be pushed to the website soon.

**Comment by happygirlzt** [comment]
You're welcome. However, I met another error. For the format of the InputExamples, I followed your example: `sample = InputExample(texts=[row['question1'], row['question2']], label=int(row['is_duplicate']))`. Mine is `
cur_label = int(row['label'])
sample = InputExample(texts = [str(row['first_br']), str(row['second_br'])], label = cur_label)
train_samples.append(sample)`
<img width="942" alt="截屏2021-01-11 18 31 24" src="https://user-images.githubusercontent.com/15061984/104169943-4f968400-543b-11eb-91d3-993ec31d96f7.png"> Should I use another InputExample format? Many thanks again!

**Comment by nreimers** [comment]
.texts_tokenized was removed in version 0.4.1 from InputExample and SentencesDataset.py was also updated accordingly.

Looks like that there are some files are messed up in your installation? That you have the InputExample class from version 0.4.1, but SentencesDataset.py from a previous version?

**Comment by happygirlzt** [comment]
Many thanks! The cause is that I installed 0.4.0 before, and mixed different versions of sentence_transformers within different docker containers.
