### ISSUE TITLE
Some insights into the performace tricks

### ISSUE THREAD

**Issue by working12** [UKPLab/sentence-transformers#684]
This excellent paper had provided us with two things:
1. Better results in similarity tasks and ways to handle these sets of problems. (The methods are clearly shown in the paper).
2. There is a huge performance gain. It takes minutes to train this, So this is efficient. 

Is it possible to mention the code blocks and the associated tricks employed to achieve this great result? (I guess this was not possible to describe too much in the paper because it is quite the implementation?)

**Comment by nreimers** [comment]
Hi @working12 
Thanks, happy to hear this :)

Which paper are you specifically referring to?

Otherwise, the code is available here and it should be quite easy to understand (I hope). Otherwise, if you have specific questions regarding the implementation, feel free to ask them here.

**Comment by working12** [comment]
@nreimers I mean the paper you wrote regarding Sentence Bert. https://arxiv.org/abs/1908.10084

**Comment by working12** [comment]
I will close this thread now and maybe open new one in case of specific questions. Thanks.
