### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by SeanPedersen** [UKPLab/sentence-transformers#686]
Hey, I am trying to use Sentence Transformers for sentiment analysis. But I am having issues training (fine tuning).

Here is my code: https://colab.research.google.com/drive/12uq1dCjN1tJy8OsnBnNGQ7Fjog9Z9vZL#scrollTo=Jiq6G99EeAmG

What confuses me is that the size of the data set has influence on whether training works or fails with an CUDA out of memory error, while using the same batch size. Is the DataLoader transferring all data to GPU memory? I thought that is only done per batch...

Hope to get some tips how to use the whole training data.

**Comment by PhilipMay** [comment]
Which version of the pip package are you using?
There once was a bug causing GPU memory issues but it was fixed.

**Comment by SeanPedersen** [comment]
> Which version of the pip package are you using?
> There once was a bug causing GPU memory issues but it was fixed.

sentence-transformers in /usr/local/lib/python3.6/dist-packages (0.4.1.2)

**Comment by nreimers** [comment]
Hi @SeanPedersen 
No, the data loader does not transfer the complete data to the GPU.

BERT has a quadratic memory requirement with the length of the input: Double the length will require 4 times more GPU memory. This can lead quickly to out-of-memory exceptions.

How to address this:
- Ensure that there are not other objects currently on the GPU when you train it
- Set the max sequence length: https://www.sbert.net/examples/applications/computing-embeddings/README.html#input-sequence-length
- Reduce the batch size

**Comment by SeanPedersen** [comment]
@nreimers ok I will try shorter max seq length and report back. Thanks for the tips!

**Comment by SeanPedersen** [comment]
@nreimers Ok so lowering model.max_seq_length to 20 definitely helped but it's still only working up to 2000 training samples, above that it crashes again with CUDA out of memory... so there must be something fishy going on since the training data size causes the crashes. I made sure that GPU is free from other objects and batch size is set to 1. Hope we can find out why this weird behavior occurs.

I am also curious if it is planned to add models that improve on quadratic memory usage (e.g. n*logn or ideally n) wrt max_seq_len?

**Comment by nreimers** [comment]
This is strange.

Can you create a clean and self contained example, i.e. no other code only the minimal code required to re-produce your crash when training.

**Comment by SeanPedersen** [comment]
@nreimers DONE. See: https://colab.research.google.com/drive/1bOWx3_LBoRWIP5EzvHP4HhBCyrhZh02O?usp=sharing

**Comment by nreimers** [comment]
@SeanPedersen I sadly cannot access it (access restricted). Send you an access request for it

**Comment by SeanPedersen** [comment]
@nreimers Access is public now, sorry. https://colab.research.google.com/drive/1bOWx3_LBoRWIP5EzvHP4HhBCyrhZh02O?usp=sharing

**Comment by nreimers** [comment]
@SeanPedersen 
I found your issue:
```
train_examples = [InputExample(texts=positive_reviews[:keep], label=1.0),
    InputExample(texts=negative_reviews[:keep], label=0.0)]
```

Here you create a single InputExample which consists of 4k sentences. This leads to OOM, as all 4k examples are encoded simoultanously. The correct way is:
```
train_examples = []
for sentence in positive_reviews[:keep]:
   train_examples.append(InputExample(texts=[sentence], label=1.0))

for sentence in negative_reviews[:keep]:
   train_examples.append(InputExample(texts=[sentence], label=0.0))
````

**Comment by SeanPedersen** [comment]
@nreimers Thank you very much! It is *working great* now, just got confused by the API apparently and misused it.
