### ISSUE TITLE
about models

### ISSUE THREAD

**Issue by sixmilesroad** [UKPLab/sentence-transformers#689]
in https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/avg_word_embeddings。

you put a bilstm on the bert-embedding ,then put a pooling on the bilstm。

you use bilstm layer maybe can get better character embedding ,so after pooling ,can get bert sentence-embedding.

Is that the reason you did it ?

**Comment by nreimers** [comment]
These are just examples how to design different architectures.

In terms of embedding quality, the best performance is achieved by having a Transformer layer + mean pooling. More complex architectures like a BiLSTM or CNN layer on top is not needed.

**Comment by sixmilesroad** [comment]
chinese bert is different from english bert ,english bert embedding word,but chinese bert embedding character,so, if i use word infomation  to enhance the chinese bert character embedding ,then i add a pooling layer on the enhance charcter embedding, do you think it is a worth doing work ? or my thought is totally wrong.

**Comment by nreimers** [comment]
I think it is not worth it.  The right multilingual / chinese-BERT can handle Chinese quite well, no need to change anything.

**Comment by sixmilesroad** [comment]
OK，can you delete this issue?
