### ISSUE TITLE
How to disable the progress bar during training?

### ISSUE THREAD

**Issue by huhk-sysu** [UKPLab/sentence-transformers#691]
Hi, I'm logging output to a file, and when I call `SentenceTransformer.fit`, the program would keep printing the progress bar for many times and make the log file into a mess like this.
![image](https://user-images.githubusercontent.com/14769033/104687384-0fd0e480-573a-11eb-8412-fc5efc2db4f7.png)

Is there any way to disable it? I find there's a `show_progress_bar` parameter on `encode` but `fit` doesn't have one.

**Comment by nreimers** [comment]
Hi @huhk-sysu 
Thanks for this suggestion.

I just added it. It will be part of  the release 0.4.2

But you can clone this repository and install from sources (`pip install -e .`) if you need it right now.

**Comment by Samarthagarwal23** [comment]
Hi Nils, may i check if "show_progress_bar" parameter will be available on CrossEncoder fit as well?

**Comment by nreimers** [comment]
Hi @Samarthagarwal23 
Just pushed a commit that adds show_progress_bar to CrossEncoder.fit as well.
