### ISSUE TITLE
What is 'Spearman’s rank correlation between the cosine-similarity of the sentence embeddings and the gold labels.' ?

### ISSUE THREAD

**Issue by Gpwner** [UKPLab/sentence-transformers#693]
In your paper,you mention this 
`we compute the Spearman’s rank
correlation between the cosine-similarity of the
sentence embeddings and the gold labels.`
in **section 4.1**

Here is my question,what is the `gold labels` mean ,and can you provide a example to explain how to calculate the Spearman’s rank correlation in your paper?Any help will be appreciate!

**Comment by nreimers** [comment]
See
https://github.com/UKPLab/sentence-transformers/blob/master/examples/evaluation/evaluation_stsbenchmark.py
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/sts/training_stsbenchmark.py

Gold labels are provided by the dataset and were created by humans looking at the pairs and assigning a score between 0 and 5 on the similarity

**Comment by Gpwner** [comment]
I got it.Thanks.
