### ISSUE TITLE
How to get the inferred value?

### ISSUE THREAD

**Issue by working12** [UKPLab/sentence-transformers#697]
We use the binary classification evaluator to get the classification of a question pair into "duplicate" or "not duplicate" and then we calculate the metric like accuracy etc. Is there any interface associated with this model API that I can use to get just the output. Not the calculated accuracy or any other metric.

Thanks in advance. (Thanks for the awesome repo).

**Comment by working12** [comment]
@nreimers  Thanks for the response. How do you get this predefined threshold? From validation?(So suppose I have 10 such threshold for 10 epochs in validation. should I choose whichever gave me highest score for validation?)

**Comment by nreimers** [comment]
Yes, that is one way. Otherwise you can check different values and see what works for your specific case.

**Comment by working12** [comment]
@nreimers  Once again thanks for your response. (But it's test data so I won't know the label). That's why asked. When you said check different values and what works you meant validation data right?

**Comment by working12** [comment]
I guess I will close this issue. If I said something wrong in the last comment let me know. Thanks.

**Comment by working12** [comment]
Sorry I accidentally closed the issue. Can you please explain the last part once?

**Comment by nreimers** [comment]
When you need a good precision, you select a higher threshold. When recall is more important, you select a lower threshold.

When you want to balance recall and precision 50:50, you can use the threshold found by the evaluator.

**Comment by working12** [comment]
Thanks @nreimers . Makes sense now.
