### ISSUE TITLE
training Cross Encoder

### ISSUE THREAD

**Issue by ReySadeghi** [UKPLab/sentence-transformers#699]
I got this in use of training Cross Encoder :

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at model_bertAlisafaya_base/0_Transformer/ and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

what does it mean?

**Comment by nreimers** [comment]
As the rest of the message says, you can ignore it when you train the model
