### ISSUE TITLE
Can we do the training using GPU?

### ISSUE THREAD

**Issue by drocobeth** [UKPLab/sentence-transformers#70]
Hello, I have fine-tuned the large-base-uncased BERT model, updated its weight according to my domain requirement. Now I want to train this BERT model using training-nli-bert.py to generate sBERT of this model. I have successfully managed to achieve this. However, the training will take around 24 days to complete on CPU. Thus, I tried using GPu but still the 'use pytorch device 'is showing cpu. How can I change my device from cpu to GPU as it is not provided in your readme documentation?

**Comment by nreimers** [comment]
Hi @drocobeth 
This code detects automatically if a GPU is available. If a GPU is available, then training will performed on the GPU.


Can you check this code:
```
import torch
print(torch.cuda.is_available())
```

Pytorch requires CUDA. I think that maybe not the correct CUDA version is installed / configured to be used with pytorch.

If torch.cuda.is_available() returns false, this code falls back to CPU and trains on the CPU.

Best
Nils Reimers

**Comment by drocobeth** [comment]
Thanks for the help @nreimers. There was a version issue as you have mentioned.
