### ISSUE TITLE
Idea behind smart batching

### ISSUE THREAD

**Issue by working12** [UKPLab/sentence-transformers#706]
I don't get the idea behind smart batching. If we are feeding something into BERT. It always expects in 512 token in input sequence right? (that's the max it allows and we should always provide sentences in that length). So no matter how you group one batch you will always end up appending them to be in the same length of 512?

Maybe I am getting it wrong.

**Comment by nreimers** [comment]
No, BERT works up to 512 word pieces, but it does not require that you pass inputs of 512 word pieces. You can pass shorter sequences, which will be substantially faster in computing (runtime increases quadratically with the input length)

**Comment by working12** [comment]
Thanks, I got it. @nreimers
