### ISSUE TITLE
Adam optimizer

### ISSUE THREAD

**Issue by tide90** [UKPLab/sentence-transformers#707]
Hi,

is there a way to use the classic Adam optimizer in eg cross encoder? I just found out that the transformer library only has the AdamW.

**Comment by nreimers** [comment]
The fit method has the parameter optimizer_class, where you can pass any optimizer class, including Adam from pytorch

**Comment by tide90** [comment]
@nreimers I assume that AdamW for pytorch and the AdamWeightDecay (TensorFlow) in transformers are the same? 

But why they have obvisously differnt default parameters?

**Comment by nreimers** [comment]
I don't know.

**Comment by tide90** [comment]
@nreimers But are those two optimizer the same at least implement the same?

**Comment by nreimers** [comment]
As mentioned, I don't know. I never used tensorflow.
