### ISSUE TITLE
Retrive syntactically similar sentences

### ISSUE THREAD

**Issue by sarves** [UKPLab/sentence-transformers#711]
Hi

Does any of your models find syntactical similarities? which one?
I tried xlm-r-distilroberta-base-paraphrase-v1 and paraphrase-distilroberta-base-v1. However, not getting required results.
BTW, I work on Tamil language.

Sarves

**Comment by nreimers** [comment]
What are syntactical similarities sentences? Can you not simply do a lexical search? This should yield syntactically similar sentences?

**Comment by sarves** [comment]
What I meant by syntactical similarities is to find sentences which have similar syntactical structures. For instance, I expect to see similarity among sentences which have ADJ N.NOM N.ACC ADV V structure or sentences which have a SUBJ+ OBJ+PRED. 
Lexical search would not work for Tamil, because a same lexical term can be an OBJ / SUBJ / PRED. Therefore, even morphology, at times, less useful. Apart from that free word ordering adds more complexity.

I also understand that these models are trained without feeding any information about POS, Morphology or Dependency. However, I thought POS, Morph, and Dependency information are captured during the modelling in some way.  That is why I was wondering whether I can use these models to find syntactical similarities.
Does that make sense?
Else is there any other way I can do find syntactical similarities?

**Comment by nreimers** [comment]
I don't think this is possible with sentence embeddings. They were not trained in any way for this.

A better way appears to map the sentences to POS tag or to use dependency parsing and then searching for similar sentences with similar pos tags / parse tree

**Comment by sarves** [comment]
Thank you for your response. 
Yes, I have been doing as you suggested.
However, wanted to check whether embedders learn these in any way. Got the point.
