### ISSUE TITLE
unsupported argument output_path_ignore_not_empty not updated in examples 

### ISSUE THREAD

**Issue by sid-sundrani** [UKPLab/sentence-transformers#716]
In the examples of sentence transformers, the fit methods are still taking in `output_path_ignore_not_empty` as input. This argument has been deprecated and removed previously- [commit](https://github.com/UKPLab/sentence-transformers/commit/0babd8bf6872daf02b4c02d4e0690db6fe2f8472) 

It would be great if the fit method in many of the [examples](https://github.com/UKPLab/sentence-transformers/tree/de558ab054f38f7dac30845f04683cf18b447750/examples/training) ([1](https://github.com/UKPLab/sentence-transformers/blob/de558ab054f38f7dac30845f04683cf18b447750/examples/training/data_augmentation/train_sts_seed_optimization.py), [2](https://github.com/UKPLab/sentence-transformers/blob/de558ab054f38f7dac30845f04683cf18b447750/examples/training/quora_duplicate_questions/training_OnlineContrastiveLoss.py) are some) would remove this argument to avoid errors

**Comment by nreimers** [comment]
Thanks for fixing it :)
