### ISSUE TITLE
Dependencies out-of-date: pytorch-transformers

### ISSUE THREAD

**Issue by essandess** [UKPLab/sentence-transformers#72]
The `transformer` dependency is out-of-date:

* pytorch-transformers* → transformers

For reference, see code edits at this MacPorts PR, https://github.com/macports/macports-ports/pull/5944

These `sed` edits produce a working `sentence-transformer` package with the latest `transformer` release:
https://github.com/macports/macports-ports/blob/d05b9836a283154ec31bf01aa01a04936284a7d8/python/py-sentence-transformers/Portfile#L57-L81

**Comment by nreimers** [comment]
Hi @essandess 
I updated the transformer dependency in the v2.0.4 branch:
https://github.com/UKPLab/sentence-transformers/tree/v0.2.4

The code is nearly finished and will be released to pip soon (today or starting next week), together with several new modules.

Best
Nils

**Comment by essandess** [comment]
@nreimers Great! Thank you very much!

Also, a feature request when you have a chance: some basic tests so that running pytest in the repo verifies basic functionality.

**Comment by nreimers** [comment]
Will try to add some tests to one of the next versions.

**Comment by essandess** [comment]
Thank you for 0.2.4!
