### ISSUE TITLE
Paraphrase model

### ISSUE THREAD

**Issue by RobertHua96** [UKPLab/sentence-transformers#720]
Hi @nreimers very excited about the paraphrase-distilroberta-base-v1 : it gets really good results for my downstream task.

Hope I'm not annoying but noticed "better versions and more details will be released in future" I'm wondering what the timelines are for that?

**Comment by nreimers** [comment]
Happy to hear you find the model useful :)

Currently I have two research papers in front of the "paraphrase model" paper. So I am afraid that it will still take some time until I can work on it again and create a better version.
