### ISSUE TITLE
SBERT Baseline Model

### ISSUE THREAD

**Issue by umairspn** [UKPLab/sentence-transformers#722]
A really quick question, the SBERT paper indicates the "SBERT-NLI-base" model. 
Where exactly can I find this exact model and replicate results for comparison? 

And please correct my understanding if I'm wrong:
....SBERT-NLI-base is a bert-base-uncased model trained further on ALLNLI dataset with a mean-token pooling strategy. 
And if that is so, I can train one using the following SBERT code? 

`_model_name = 'output/bert-base-uncased'
batch_size = 16
word_embedding_model = models.Transformer(model_name)
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)
model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
logging.info("Read AllNLI train dataset")
train_data = SentencesDataset(nli_reader.get_examples('train.gz'), model=model)
....... (and so on)
num_epochs = 1
warmup_steps = math.ceil(len(train_dataloader) * num_epochs / batch_size * 0.1)
.... (and so on)_
`

Please correct me if I'm wrong. Also, If I am to cite the SBERT results and my results on SentEval tasks vary by 2-3 on a 100 scale, is that considered as an acceptable comparison? 
Thank You.

**Comment by nreimers** [comment]
You can find the code here:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/nli/training_nli.py

Note: The results in the paper (and the released NLI models), where trained with pytorch-pretrained-bert (which was the name for the first version of transformers).

With version 1 (or 2?) of transformers, many people reported that their performance dropped. It is sadly the same case when you run the linked file, that you get weaker results than what is reported in the paper.

When you use the original training code with the old pytorch-pretrained-bert package, you get the same results as in the paper.


Regarding SentEval:
Note, in their code example they use different hyperparameters then what they recommend and what they used in the SentEval paper. The recommended hyperparameters for SentEval can be found in their documentation. Changing these can make quite a difference.
In SBERT, I used the recommended SentEval parameters (the parameters the SentEval paper used)

**Comment by umairspn** [comment]
Thank You @nreimers, it was really helpful. 
One more question, the model "bert-base-nli-mean-tokens" from [pretrained models](https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/), is it or how is it different from the SBERT-NLI-Base model mentioned in the SBERT paper ?

**Comment by nreimers** [comment]
It is the model from the paper

**Comment by umairspn** [comment]
Okay Thank You @nreimers
