### ISSUE TITLE
Bug in triplets hard batch loss example 

### ISSUE THREAD

**Issue by milmin** [UKPLab/sentence-transformers#724]
In the following example
https://github.com/UKPLab/sentence-transformers/blob/62c536a12eddae997ff977f7a2e58903d65d444c/examples/training/other/training_batch_hard_trec.py#L169
the fit should be done on a set of `InputExample` (sentence, label) pairs in order to learn with any of `BatchHardTripletLoss`, `BatchHardSoftMarginTripletLoss`, `BatchSemiHardTripletLoss` or `BatchAllTripletLoss`. In the example `train_dataloader` is made of pre-computed triplets, thus the model will not learn anything out of it.

**Comment by nreimers** [comment]
Triplets are only pre-computed for dev & test, but not for the test set in that example

**Comment by milmin** [comment]
My bad, I did not notice that for the train set it was actually (sentence, label) pairs
