### ISSUE TITLE
Any way to control verbosity while finetuning (model.fit) ? 

### ISSUE THREAD

**Issue by Samarthagarwal23** [UKPLab/sentence-transformers#728]

**Comment by nreimers** [comment]
What do you mean with verbosity?

**Comment by Samarthagarwal23** [comment]
i think "show_progress_bar'" should work for me.

May i check if i can print the output metric from evaluator function running after every X steps?
Or is it stored somewhere?

**Comment by nreimers** [comment]
When you pass an output folder path to the fit method, then the evaluator create a .csv file inside this folder and store the results there.

Otherwise you can configure the logging level in Python and tell python from which modules you like to see logging information and from which not.

**Comment by Samarthagarwal23** [comment]
Thanks.
May i check what does the last row of column "Steps" having value -1 indicate?

**Comment by nreimers** [comment]
It stands for the evaluation at the end of an epoch
