### ISSUE TITLE
BioBERT

### ISSUE THREAD

**Issue by Mahmedturk** [UKPLab/sentence-transformers#73]
Hi,
Does this code work with BioBERT or Clinical BERT too?

**Comment by nreimers** [comment]
Are they using Huggingface transformers? Then you can load them out of the box from disc.

If they are in a tensorflow format, you must first convert them to a pytorch format. See the documentation on this in the Huggingface transformers repository.

**Comment by chocolocked** [comment]
I was trying to work with BioBert and Scibert to extract sentence embedding too, can you give a bit more details on how this works?

**Comment by nreimers** [comment]
Every community model available here:
https://huggingface.co/models

Can now be loaded with the models.Transformer class. This include scibert and biobert.
