### ISSUE TITLE
max_lenght for Sentence Transformer

### ISSUE THREAD

**Issue by tide90** [UKPLab/sentence-transformers#730]
Hey,

is it just possible to give the max_lenght parameter for not building models from huggingface via Transformer Class?
 Or why is there no possibility to give a max_lenght in model = SentenceTransformer('model_name') whereas in CrossEncoders you can do?

Thank you!

**Comment by nreimers** [comment]
https://sbert.net/examples/applications/computing-embeddings/README.html#input-sequence-length

**Comment by tide90** [comment]
Ah! Thankys again. :-)
