### ISSUE TITLE
Is 'stsb-roberta-base' already fine-tuned or just a structure?

### ISSUE THREAD

**Issue by happygirlzt** [UKPLab/sentence-transformers#735]
Dear there, many thanks for your amazing work.

According to the models listed on README, I have trouble understanding 'stsb-roberta-base'. Is this already fine-tuned on STSbenchmark? Now, I have my own dataset, duplicate and non-duplicate sentence pairs from another domain. I wonder whether it works if I further fine-tune on this model (i.e., 'stsb-roberta-base'). Or I build my own Siamese BERT structure to fine-tune the Siamese BERT on my own data. Many thanks in advance!

**Comment by nreimers** [comment]
It is fine-tuned on NLI and STSb. You can use it as start for your training
