### ISSUE TITLE
margin in batch hard losses

### ISSUE THREAD

**Issue by tide90** [UKPLab/sentence-transformers#737]
Hi,

[In ](https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/losses/BatchHardTripletLoss.py) you write that the margin is computed automatically. But the loss is still initialized with a margin which is also used for further calculations.

Now, is still this margin parameter a real parameter? So I can tune this parameter for tuning?

**Comment by nreimers** [comment]
Yes, it is a parameter to tune. Not sure why it is mentioned there

**Comment by tide90** [comment]
Thanks...

> Not sure why it is mentioned there

Yes, me either.
