### ISSUE TITLE
HTTPError: 403 Client Error:

### ISSUE THREAD

**Issue by tide90** [UKPLab/sentence-transformers#738]
I get a request error and I do not know why.
```

[W 2021-02-02 18:43:15,951] Trial 0 failed because of the following error: HTTPError('403 Client Error: Forbidden for url: https://sbert.net/models/bert-base-german-dbmdz-uncased.zip',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/_optimize.py", line 211, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-6-af5cb77f5b44>", line 40, in objective
    model = SentenceTransformer(model_name)  # distiluse-base-multilingual-cased-v2  distilbert-multilingual-nli-stsb-quora-ranking
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/SentenceTransformer.py", line 92, in __init__
    raise e
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/SentenceTransformer.py", line 75, in __init__
    http_get(model_url, zip_save_path)
  File "/usr/local/lib/python3.6/dist-packages/sentence_transformers/util.py", line 201, in http_get
    req.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://sbert.net/models/bert-base-german-dbmdz-uncased.zip

HTTPError: 403 Client Error: Forbidden for url: https://sbert.net/models/bert-base-german-dbmdz-uncased.zip
```

**Comment by tide90** [comment]
It seems that there is a limit of maximal requests within a certain time window?

**Comment by nreimers** [comment]
Yes, if a model is downloaded too often on a single day from an IP, that IP is blocked to prevent wrongly configured setups.

Note, for the mentioned model it is better to follow the setup here an create it from scratch, as it is not an SBERT model
https://sbert.net/docs/training/overview.html#creating-networks-from-scratch

**Comment by tide90** [comment]
But it does create the model from scratch already automatically...From sratch also downlaods from huggingface? Soit should be the same problem with blocking?
Can't I  just load it from local?

> that IP is blocked to prevent wrongly configured setups.

What do you mean by that?

**Comment by nreimers** [comment]
When you create it as described in the linked page, it does not check if there is an SBERT model with that name (which does not exist) and instead load it from huggingface directly

**Comment by tide90** [comment]
> and instead load it from huggingface directly

But the requests would be still limited like when requesting your url?

**Comment by nreimers** [comment]
No, there is no limit

**Comment by tide90** [comment]
Ok, good to know.But nevertheless it would be possible to save this model and load it from local if you need multiple request within a short time (like for Tuning...)?

**Comment by nreimers** [comment]
Yes you can call model.save() and later load it from the folder.

Existing Sbert models are cached on disc

**Comment by tide90** [comment]
> Existing Sbert models are cached on disc

Loading from huggingface too I thought?

**Comment by DirkWW** [comment]
I have a similar error although it was the first time I requested it today. Is there another limit?
>>> model2 = SentenceTransformer('all-mpnet-base-v2')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 84, in __init__
    ignore_files=['flax_model.msgpack', 'rust_model.ot', 'tf_model.h5'])
  File "C:\Python36\lib\site-packages\sentence_transformers\util.py", line 460, in snapshot_download
    user_agent=user_agent,
  File "C:\Python36\lib\site-packages\huggingface_hub\file_download.py", line 351, in cached_download
    r.raise_for_status()
  File "C:\Python36\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/sentence-transformers/all-mpnet-base-v2/resolve/86eb780758622d085bac2d7f6aea99c157a5ee28/.gitattributes

**Comment by nreimers** [comment]
There is currently an issue with the huggingface model hub, that specific files cannot be accessed. This affects each model and each user.

We currently look into this.

Have a look at:
https://github.com/UKPLab/sentence-transformers/issues/1297

Current work-around is to access https://sbert.net/models and to download the needed model from there, unzip it and load it from disc.

**Comment by s4sarath** [comment]
Yes, same issue.

**Comment by SETIADEEPANSHU** [comment]
Steps:
1. Download the required models from https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.2/
2. Unzip the models into any directory, for example 'models'
3. Load the downloaded models from models directory 

`MODELS_DIR = os.path.join(ROOT_DIR, 'models')`

`self.model = SentenceTransformer(os.path.join(MODELS_DIR, 'distilbert-base-nli-stsb-mean-tokens'), device='cpu')`

**Comment by s4sarath** [comment]
Its not just for Sentence Transformers, for many custom models and associated hubs.

**Comment by nreimers** [comment]
The download from the hub should be working again.

Let me know if you still have issues.
