### ISSUE TITLE
Model architecture 

### ISSUE THREAD

**Issue by aclifton314** [UKPLab/sentence-transformers#74]
I was wondering if there were any references somewhere that expand on the model architecture found in the paper (https://arxiv.org/pdf/1908.10084.pdf)? I see Figures 1 and 2 outline the model, but it's somewhat unclear to me what's happening. 

For instance, it would appear that, for a given sentence, averaging the BERT would produce the same embeddings as using the MEAN pooling operation from the paper. This is clearly not true, as seen by Table 1, but I am having a hard time grasping what could cause the difference.

Much love for this project, btw!

**Comment by nreimers** [comment]
Hi @aclifton314 
The model is rather straight forward: You compute BERT,  take the outputs, and average them.

The "magic" happens in the fine-tuning. Using the BERT models out-of-the-box does not produce the best sentence representations. However, if you fine-tune BERT on appropriate data, you get quite well performing sentence representations.

So all the magic is in the correct fine-tuning (correct loss + correct data).

Best
Nils Reimers

**Comment by aclifton314** [comment]
Ahhh I see now. That makes sense. Thanks for the response!
