### ISSUE TITLE
How to encode pretokenized sentences?

### ISSUE THREAD

**Issue by antonioFlavio** [UKPLab/sentence-transformers#742]
Hey there,

I was using the version 0.3.3 before, and I have a code that I use to encode just the first 510 tokens of the sentence. So, at first step I tokenize the sentence then encode it using 'is_pretokenized=True'. But, is_pretokenized parameter is now deprecated. How should I encode a vector of tokens? There is a new way to encode sentences truncating using the 'max_seq_length' value?

My current version now is 0.4.1.2.

**Comment by antonioFlavio** [comment]
I've found an example from [sbert website.](https://sbert.net/examples/applications/computing-embeddings/README.html#sentence-embeddings-with-transformers). Something like this:

```python
model = SentenceTransformer('distiluse-base-multilingual-cased')
model ._first_module().max_seq_length = 512

encoded_input = embedder.tokenizer(sentences, padding=True, truncation=True, max_length=512, return_tensors='pt')

with torch.no_grad():
    model_output = embedder(**encoded_input)
```
But I got the error:
TypeError: forward() got an unexpected keyword argument 'input_ids'

**Comment by nreimers** [comment]
Why would you want this feature?

You can set the max_seq_length as described here:
https://www.sbert.net/examples/applications/computing-embeddings/README.html#input-sequence-length

Then, the text you pass to encode() is tokenized and truncated automatically.

So there is not really a need to tokenize it yourself and trying to encode it yourself.


Otherwise, I think this code will work:
```
with torch.no_grad():
    model_output = embedder(encoded_input)
```

Remove **

**Comment by antonioFlavio** [comment]
To set max_seq_length, I was using a code from previous version. I changed to the new way.

About the tokenizer, some time ago I've tried just encode large sentences and was gotting error. So this code remained with manual trucate. That's why I was using like this.

Thanks Nils!

**Comment by nreimers** [comment]
Encoding large sentences should not be an issue, as mentioned, it will be truncated to the specified length.

**Comment by antonioFlavio** [comment]
Taking advantage of this thread, do you have any new suggestions to long document representation or some recent approach?

I've created a gold label dataset comparing similarity between long documents, and now I evaluating some methods.

**Comment by nreimers** [comment]
No new suggestion: What works best for me so far is to break down a longer doc into paragraphs and encoding them independently.

**Comment by antonioFlavio** [comment]
Thank you Nils!!

**Comment by masalha-alaa** [comment]
> I've found an example from [sbert website.](https://sbert.net/examples/applications/computing-embeddings/README.html#sentence-embeddings-with-transformers). Something like this:
> 
> ```python
> model = SentenceTransformer('distiluse-base-multilingual-cased')
> model ._first_module().max_seq_length = 512
> 
> encoded_input = embedder.tokenizer(sentences, padding=True, truncation=True, max_length=512, return_tensors='pt')
> 
> with torch.no_grad():
>     model_output = embedder(**encoded_input)
> ```
> 
> But I got the error: TypeError: forward() got an unexpected keyword argument 'input_ids'

You just need to pop `offset_mapping` before passing the encodings to the model:  
```
encoded_input.pop('offset_mapping')
```

Then continue normally as you did:  
```
with torch.no_grad():
    model_output = embedder(**encoded_input)
````
