### ISSUE TITLE
Is there a way to use sentence transformers paraphrase_mining function to compare one sentence to a big list (over 20,000) of sentences?

### ISSUE THREAD

**Issue by erinmacf** [UKPLab/sentence-transformers#750]
I am new to using sentence transformers but I'm interested in finding the similarities of one sentence with a big list of sentences.

For example with this data:

sentence = ['The cat sits outside']

sentences = ['A man is playing guitar',
             'I love pasta',
             'The new movie is awesome',
             'The cat plays in the garden',
             'A woman watches TV',
             'The new movie is so great',
             'Do you like pizza?']

I would like to compare the sentence 'The cat sits outside' to each of the sentences in the sentences list.

(except my sentences list would have over 20k elements)

**Comment by nreimers** [comment]
You can use the code from here:
https://www.sbert.net/examples/applications/semantic-search/README.html

Your query is "The cat sits outside" and the corpus are your 20k sentences.
