### ISSUE TITLE
Unbound local variable

### ISSUE THREAD

**Issue by minyoung90** [UKPLab/sentence-transformers#756]
Because of #721 , I cloned latest branch and re-installed sentence-transformers.
but, When I create a SentenceTransformer()
I got this:

File "/home/workspace/sentence-transformers/sentence_transformers/SentenceTransformer.py", line 135, in __init__
    if save_model_to is not None:
UnboundLocalError: local variable 'save_model_to' referenced before assignment

I just moved 'save_model_to' variable out of if statement. and solved it.

**Comment by minyoung90** [comment]
I also found, When evaluation step,

/opt/conda/lib/python3.7/site-packages/scipy/stats/stats.py:3508: PearsonRConstantInputWarning: An input array is constant; the correlation coefficent is not defined. warnings.warn(PearsonRConstantInputWarning())
/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:2559: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:2560: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]

when I use lr == 1e-5 is fine, but I changed it to lr == 5e-3 then above warnning raised and mode was not saved.

**Comment by nreimers** [comment]
Thanks for reporting, I fixed the issue with save_model_to in the latest commit.

Regarding the warning: The issue is here that the model outputs constant numbers (or maybe even NaN). In that case, correlation is not defined. This is linked to the learning rate, it is too large and destroys the model.
