### ISSUE TITLE
Too many requests: Httperror 429

### ISSUE THREAD

**Issue by uk2804** [UKPLab/sentence-transformers#759]
Hi 
I got the following error.
requests.exceptions.httperror 429 client error too many requests for url http://sbert.net/models/bert-base-nli-mean-tokens.zip

**Comment by nreimers** [comment]
If a system downloads more than 500 times a day the same model, the system is blocked from any further downloads for that model for the month.

Models are usually cached on the local disc so that it must only be downloaded once. Do you know why your script downloaded the model so often?

**Comment by uk2804** [comment]
Hi @nreimers 

Thanks for the clarification. I don't know exactly why it happened but I downloaded the model on the local disc and called. 
So my problem was resolved.
