### ISSUE TITLE
STS and Small Training Data

### ISSUE THREAD

**Issue by valeitao** [UKPLab/sentence-transformers#761]
Hi Nils.

First of all, congratulations on developing this framework, really useful to train models and compare them. I'm a rookie when it comes to embeddings and transformers, and so I have a question regarding training models with small training data.

As stated in the [Training Examples section](https://www.sbert.net/examples/training/data_augmentation/README.html), sentence embedding models require substantial training data. I'm in the scenario of having a small dataset with only ~200 sentence pairs, and so I guess I'm in need of performing data augmentation over these. 

Before going on that path, I trained the models similarly as the example in the [Training Overview section](https://www.sbert.net/docs/training/overview.html#training-data). The results are quite interesting: I can achieve ~0.93 correlation with STSb-BERT-LARGE under the Embedding Similarity Evaluator. However, I am afraid the results are heavily influenced by the amount of training data. Is this assumption correct, even if the models were already trained and fine-tuned on NLI+STSb? 

Thank you.

**Comment by nreimers** [comment]
Hi @valeitao 
For low dataset scenarios, I can recommend our work:
https://www.sbert.net/examples/training/data_augmentation/README.html
https://arxiv.org/abs/2010.08240

0.93 correlation on a well designed dev. set sounds really good.

Continue training on the NLI+STSb model is of course helpful for a kick-start when you task is similar.

**Comment by valeitao** [comment]
Thank you!
