### ISSUE TITLE
Saving Model

### ISSUE THREAD

**Issue by PaulForInvent** [UKPLab/sentence-transformers#762]
I cannot save a model because of the slashs, it is a path like: A/B/C/D:

```
if '\\' in model_path or model_path.count('/') > 1:
                    raise AttributeError("Path {} not found".format(model_path))
```

in https://github.com/UKPLab/sentence-transformers/blob/c0b0125656019531a7e9f020b040d645639f244f/sentence_transformers/SentenceTransformer.py#L47

How I have to specify the save name?

Is the model via output_path in model.fit save with the save_pretrained() from huggingface?

Loading such a saved model works via SentenceTransformer(path)?

Can I save a model savely with save_pretrained from hugginface or how would I save a SentenceTransformer model outside of fit()?

**Comment by nreimers** [comment]
Having the slashs is not an issue. You can save it and the respective path is created.
You can also load it via SentenceTransformer(path)

The linke you linked throws only the exception if the passed path does not exists (is not a valid path on your file system).

**Comment by PaulForInvent** [comment]
@nreimers Strange that the path does not exist...

I asume you model.save() to save... and for loading this saved model? model.from_pretrained()?

**Comment by nreimers** [comment]
Yes, you call model.save('your/path') and then you can load it with SentenceTransformer('your/path')

**Comment by PaulForInvent** [comment]
Yes, I see. Thanks.
