### ISSUE TITLE
Unable to save fine-tuned model

### ISSUE THREAD

**Issue by scovail** [UKPLab/sentence-transformers#763]
I'm attempting to fine tune an existing model, save it, and reload it at a later time. To tune the model I'm using the following code:

   model = SentenceTransformer('stsb-roberta-base')
   train_dataloader = DataLoader(examples, shuffle=True, batch_size=16)
   train_loss = losses.CosineSimilarityLoss(model)
   model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=1, warmup_steps=100)

Everything works well and I'm able to use the updated model. However, when I attempt to save it using the statement "model.save('/output/path')," I receive the following errors:

thread '<unnamed>' panicked at 'no entry found for key', /Users/runner/work/tokenizers/tokenizers/tokenizers/src/models/mod.rs:36:66
---------------------------------------------------------------------------
PanicException                            Traceback (most recent call last)
<ipython-input-36-629472bbf816> in <module>
----> 1 model.save('/output/path')

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py in save(self, path)
    359             model_path = os.path.join(path, str(idx)+"_"+type(module).__name__)
    360             os.makedirs(model_path, exist_ok=True)
--> 361             module.save(model_path)
    362             contained_modules.append({'idx': idx, 'name': name, 'path': os.path.basename(model_path), 'type': type(module).__module__})
    363 

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/sentence_transformers/models/Transformer.py in save(self, output_path)
     88     def save(self, output_path: str):
     89         self.auto_model.save_pretrained(output_path)
---> 90         self.tokenizer.save_pretrained(output_path)
     91 
     92         with open(os.path.join(output_path, 'sentence_bert_config.json'), 'w') as fOut:

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py in save_pretrained(self, save_directory, legacy_format, filename_prefix)
   1967         file_names = (tokenizer_config_file, special_tokens_map_file)
   1968 
-> 1969         return self._save_pretrained(
   1970             save_directory=save_directory,
   1971             file_names=file_names,

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py in _save_pretrained(self, save_directory, file_names, legacy_format, filename_prefix)
    526                     f.write(out_str)
    527 
--> 528             vocab_files = self.save_vocabulary(save_directory, filename_prefix=filename_prefix)
    529             file_names = file_names + vocab_files + (added_tokens_file,)
    530         else:

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/transformers/models/gpt2/tokenization_gpt2_fast.py in save_vocabulary(self, save_directory, filename_prefix)
    170 
    171     def save_vocabulary(self, save_directory: str, filename_prefix: Optional[str] = None) -> Tuple[str]:
--> 172         files = self._tokenizer.model.save(save_directory, name=filename_prefix)
    173         return tuple(files)

PanicException: no entry found for key

As mentioned above, I'd like to be able to save the new model and retrieve it for use in other applications. Any help would be appreciated.

Scott

**Comment by scovail** [comment]
Quick update: I noticed that after the save command failed, there was a subdirectory named '0_Transformer' created under the output path.

**Comment by nreimers** [comment]
The issue is with Huggingface transformers, that the fast tokenizers throw this exception when a model with an older config format is tried to be saved.

However, the 'stsb-roberta-base' model should have the latest config format and the following works for me:
```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('stsb-roberta-base')
model.save('save/dir/stsb-model')
```


Maybe you have cached an old version of the STSb model with still the old file format. Try to delete the respective cache folder (~/.cache/torch/sentence-transformers/sbert.net_models_stsb_....)

**Comment by scovail** [comment]
It worked! Thanks for the help and the quick response.

Scott
