### ISSUE TITLE
MSEEvaluator (latest branch) has bug

### ISSUE THREAD

**Issue by minyoung90** [UKPLab/sentence-transformers#764]
Good morning from South Korea! I am using sentence-transformers latest branch for some reasons.

I got this error,
File "/home/workspace/sentence-transformers/sentence_transformers/evaluation/MSEEvaluator.py", line 38, in __init__
    self.write_csv
AttributeError: 'MSEEvaluator' object has no attribute 'write_csv'

so I checked the file, 'self.write_csv' have not assigned at all!
I re-installed version 0.4.1.2 (pip), It seems fine.

**Comment by nreimers** [comment]
Thanks for reporting. It is fixed and will be part of the next release
