### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './mymodel/modules.json'

### ISSUE THREAD

**Issue by mashagua** [UKPLab/sentence-transformers#766]
model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=10, warmup_steps=100, output_path='./mymodel') and the output is a null folder,why?

**Comment by nreimers** [comment]
Without an evaluator, the model is not saved. The model is only saved during training if the evaluator returns a higher (better) score than in the previous evaluation.

After fit, you can call:
model.save('./mymodel')

to save the model to that folder.

**Comment by mashagua** [comment]
> Without an evaluator, the model is not saved. The model is only saved during training if the evaluator returns a higher (better) score than in the previous evaluation.
> 
> After fit, you can call:
> model.save('./mymodel')
> 
> to save the model to that folder.

Thank you, solved
