### ISSUE TITLE
Expected object of backend CUDA but got backend CPU for argument #3 'index'

### ISSUE THREAD

**Issue by drocobeth** [UKPLab/sentence-transformers#77]
Hello,
I have fine-tuned the large-base-uncased BERT model, updated its weight according to my domain requirement. Now I am training this BERT model with the help of GPU and using training-nli-bert.py to generate sBERT of this model. I have given one epoch with 16 iterations to train. However, after the 1000 number of dataset is trained. The code throws the error "**Expected object of backend CUDA but got backend CPU for argument #3 _'index'_**". and the training is terminated. it would be really helpful if you tell me how to deal with this error? Thank You.

**Comment by nreimers** [comment]
Hi @drocobeth 
It appears that one of the tensors is still on the CPU, and not on the GPU. Does the training_nli_bert.py script without any modifications work for you?

Best
Nils Reimers

**Comment by drocobeth** [comment]
Okay, a few things which I have changed in training_nli_bert.py file:

- I am giving the models.BERT method my finetuned BERT location:
`word_embedding_model = models.BERT('../finetuned_lm/')`

- The fine tuned_lm contains the following files:
            - added_tokens.json
            - config.json
            - pytorch_model.bin
            - vocab.txt
            - special_tokens_map.json
            - tokenizer_config.json

- The python code successfully extracts all the required file which I can see from logs that I get on my linux terminal: 
<img width="964" alt="sbert" src="https://user-images.githubusercontent.com/29040887/70715436-4e62c700-1d10-11ea-91f6-80146c1ce1cc.PNG">

- The next thing which I have changed in the code is, I created pickle files for train_data,train_dataloader,train_loss,dev_data.dev_dataloader, and evaluator. Since every time I ran the script, it took time to convert the dataset like this: 
<img width="961" alt="sBert-2" src="https://user-images.githubusercontent.com/29040887/70715952-5c651780-1d11-11ea-9de0-6b42cd71cfac.PNG">

- So, once converted I made the pickle files of all of these and now I load them directly, then the model.fit command starts after the warmup_steps, and there is a parameter defined in model.fit in which we have given value 1000 to the evaluation_steps.

**_- After the 1000 steps, it gives the error which I have mentioned. Error starts from the line:
`output_path=model_save_path`_**

- This is my model_save_path:
`model_save_path = '../output/training_nli_bert-'+datetime.now().strftime("%Y-%m-%d_%H-%M-%S")`
<img width="959" alt="error" src="https://user-images.githubusercontent.com/29040887/70716878-3b052b00-1d13-11ea-83b5-828fb5203449.PNG">


Please tell me where I am going wrong, It would help me a lot.

**Comment by nreimers** [comment]
Could you posts which versions of the different frameworks (pytorch, transformers, sentence-transformers) you use?

You get the list using:
pip freeze

**Comment by drocobeth** [comment]
torch==1.2.0
transformers==2.2.1
sentence-transformers==0.2.4.1

There is no package named PyTorch. I guess you must be asking for torch only. Also, for your help, I am attaching the txt file of all the packages in my project environment. This project environment was solely created for the purpose of running sbert.
[pakckages.txt](https://github.com/UKPLab/sentence-transformers/files/3959258/pakckages.txt)

**Comment by nreimers** [comment]
Looks quite recent. Sadly without code I cannot tell where the problem is.

Maybe you can send me your code (with the BERT model and the pickle files for your datasets)? Then I can test if I'm able to run it on my machine.

You can send me a download link to my email address: info@nils-reimers.de
Please make it as simple as possible for me to run your experiment ;)

Best
Nils Reimers
