### ISSUE TITLE
how to solve "RuntimeError: Found dtype Double but expected Float"

### ISSUE THREAD

**Issue by mashagua** [UKPLab/sentence-transformers#770]
when I run these codes:
 
model.fit(train_objectives=[(train_dataloader, train_loss)], epochs=10, warmup_steps=100, evaluator=evaluator, evaluation_steps=500,output_path='drive/MyDrive/mymodel')

RuntimeError: Found dtype Double but expected Float

**Comment by nreimers** [comment]
Your labels should be of float32, but you passed a label of float64

**Comment by mashagua** [comment]
> Your labels should be of float32, but you passed a label of float64

Ok,thank you,it fixed
