### ISSUE TITLE
Is it possible to save both encoders separately?

### ISSUE THREAD

**Issue by umairspn** [UKPLab/sentence-transformers#773]
Hello @nreimers, 
I had a quick question. SBERT uses bi-encoders by passing each sentence to a separate encoder (say BERT) in case of Classification objective and then concatenates the embeddings u and v before applying the SoftMax Layer. 

For understanding, I wanted to ask:
1. The default scripts save the final model after training and evaluation. Which encoder does it save (E1 or E2)? 
I read your comments on other posts that SBERT saves the layers responsible for generating sentence embeddings, what does that imply? 
2.  Secondly, Is it possible to save both models/encoders separately?. i.e. I ask this because for Encoder1 I pass the sentence, while for Encoder 2, I am passing an input of a completely different nature, and would like to test both models to see how the information is passed to each encoder during the training phase, and test each of them further.  

Any other suggestions will be greatly appreciated. 
Thank You.

**Comment by nreimers** [comment]
There is no Encoder1 and Encoder2. Both encoder are completely identical, it is the same BERT model.

**Comment by umairspn** [comment]
Noted. 

![image](https://user-images.githubusercontent.com/41567552/109041290-dd9d9580-769c-11eb-85a5-de602de0165c.png)

Understanding this Bi-encoder architecture, SBERT passes each sentence through the same BERT model (i.e. same encoder), and saves the layer responsible for the sentence embeddings? 

Is it helpful/important to know which layers exactly it stores as the final trained model?

**Comment by nreimers** [comment]
Yes, these are identical BERTs.
The output from the last layer is used for pooling.

**Comment by umairspn** [comment]
okay, thanks!
