### ISSUE TITLE
Where can I find documentation or paper mentioning pre-trained distilbert-base-nli-mean-tokens model?

### ISSUE THREAD

**Issue by SayaliSonawane** [UKPLab/sentence-transformers#778]
I am trying to find documentation for pre-trained model  `distilbert-base-nli-mean-tokens` . Can someone please point me to it's paper or documentation?  Is it based on [DistilBERT, a distilled version of BERT: smaller, faster, cheaper and lighter](https://arxiv.org/abs/1910.01108) paper? This is published in March 2020. I am looking for links between this paper and Sentence-BERT paper.

**Comment by nreimers** [comment]
They were trained identical as the BERT / RoBERTa models, as described in our SBERT paper. Only  difference is that they use DistilBERT instead of BERT / RoBERTa. DistilBERT was described in the linked paper.

**Comment by SayaliSonawane** [comment]
Hi Nils thanks for your reply. I have a doubt about this model. I started using sentence-transformer package after reading sentence-bert paper (which is published in 2019) and  DistilBERT is published in March 2020. Was this model published recently?

**Comment by nreimers** [comment]
The DistilBERT paper was published in Oct 2019, and the DistilBERT model was released even earlier:
https://medium.com/huggingface/distilbert-8cf3380435b5

But none the less: The models here are constantly improved and extended. You find on our website www.sbert.net many new (better) models which were not described in the original SBERT paper. There, only the BERT / RoBERTa models trained on NLI and NLI+STSb are presented.

**Comment by SayaliSonawane** [comment]
Thanks for clarifying my doubt.
