### ISSUE TITLE
empty characters can lead to wrong results if they lead in the first sentence

### ISSUE THREAD

**Issue by martindkaz** [UKPLab/sentence-transformers#782]
Took us a while to figure out this issue, so just wanted to share - empty characters can lead to very wrong results if they lead in the first sentence:
(notice the empty space before "email")
ce_roberta_large_stsb....predict([['deleg email',' email delegation']]) ---> 0.95
ce_roberta_large_stsb.....predict([[' email delegation','deleg email']]) ---> 0.58

Thanks for making everything available!

**Comment by nreimers** [comment]
Will check this also.

But also note, that the Cross-Encoder architecture is not symmetric, i.e. CE(A,B) != CE(B, A)

During training, I made the training data symmetric (i.e. (A, B, Label) I added also (B, A, Label)), but this does not fully cover the issue that Cross-Encoders are not symmetric and that CE(A,B) can lead to different results than CE(B, A)

**Comment by NichitaDiaconu** [comment]
For model `cross-encoder/stsb-roberta-large`  
 - as @nreimers mentioned: `CE(['A', 'B']) !=  CE(['B', 'A'])`
 - spaces do influence the result: `CE(['A', 'B']) != CE([' A', 'B'])`

It does seem like some spaces matter more than others:
Spaces that make a big difference:
 - `CE(['A', 'A']  ) = 0.924  ||  CE([' A', 'A'] ) = 0.205` 
Spaces that make a small difference:
 - `CE(['B', 'B']  ) = 0.950  ||  CE([' B', 'B'] ) = 0.945`

As the following code shows

Code:
```
from sentence_transformers.cross_encoder import CrossEncoder
import numpy as np

# Pre-trained cross encoder
model = CrossEncoder('cross-encoder/stsb-roberta-large')

# With all sentences in the corpus
corpus = ['A', ' A', 'B', ' B']

# So we create the respective sentence combinations
sentence_combinations = [[s1, s2] for s2 in corpus for s1 in corpus]

# Compute the similarity scores for these combinations
similarity_scores = model.predict(sentence_combinations)

# Print the scores
for i in range(len(corpus)**2):
    print("|  CE({:12}) = {:.3f}  |".format(str(sentence_combinations[i]), similarity_scores[i]), end='')
    if (i+1) % len(corpus) == 0:
        print('')
```

Output:
```
|  CE(['A', 'A']  ) = 0.924  ||  CE([' A', 'A'] ) = 0.205  ||  CE(['B', 'A']  ) = 0.247  ||  CE([' B', 'A'] ) = 0.262  |
|  CE(['A', ' A'] ) = 0.815  ||  CE([' A', ' A']) = 0.412  ||  CE(['B', ' A'] ) = 0.292  ||  CE([' B', ' A']) = 0.302  |
|  CE(['A', 'B']  ) = 0.225  ||  CE([' A', 'B'] ) = 0.208  ||  CE(['B', 'B']  ) = 0.950  ||  CE([' B', 'B'] ) = 0.945  |
|  CE(['A', ' B'] ) = 0.285  ||  CE([' A', ' B']) = 0.300  ||  CE(['B', ' B'] ) = 0.918  ||  CE([' B', ' B']) = 0.922  |
```

**Comment by nreimers** [comment]
The Roberta tokenizer preserves whitespace, so "A" and " A" are different tokens and have different word embeddings. Hence, the results change as the inputs are different.

The STS training data did not have any preceeding spaces, hence, this can impact the results.

**Comment by NichitaDiaconu** [comment]
As far as I understand, this is expected. Can this be closed?

**Comment by nreimers** [comment]
As this is indeed a counter-intuitive behavior by RoBERTa, I added a strip in the cross-encoder class which removes white spaces at the start & end.

With the next release, spaces will no longer affect the output.

Thanks for reporting this.
