### ISSUE TITLE
Query regarding training cross-encoders

### ISSUE THREAD

**Issue by sbhttchryy** [UKPLab/sentence-transformers#784]
For training cross encoders, in case of negative examples, can we reuse the queries used as the positive example? What I mean by that is, say (Q1, A1, label=1) is a positive example. For Q1, I also have a couple of negative answers as well (A2, A3).
Can we use (Q1, A2, lable = 0) and  (Q1, A3, lable = 0) as negative examples?

Thank you so much.

**Comment by nreimers** [comment]
Sure you can do this
