### ISSUE TITLE
Dev-examples for training cross-encoders

### ISSUE THREAD

**Issue by sbhttchryy** [UKPLab/sentence-transformers#785]
For training cross encoders, in case of 'ms-marco',  the dev-samples are in the following format 

{'key': {'negative':}, {'positive: '}, {'query': }}. 

In order to use the CERankingEvaluator, is it necessary to have the key included? I have my own annotated set of queries, positive and negative answers. Can I just use the data in the following format?
{'query': '', 'positive': [], 'negative': []}

Thank you.

**Comment by nreimers** [comment]
No, you can also pass a list with the described format:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/cross_encoder/evaluation/CERerankingEvaluator.py#L15

**Comment by sbhttchryy** [comment]
Is there any reason why the key exists during the training of MS Marco?

**Comment by nreimers** [comment]
This is due to the file format which we read (one triplet per line).
