### ISSUE TITLE
How do I compare one sentence vector to 50 million?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#790]
Hi,

do you have an idea on how to compare one sentence vector to 50 million?
We have 50 million texts and want to search in them.

We found a paper that discusses this issue: https://wangzwhu.github.io/home/file/acmmm-t-part3-ann.pdf

They recommend to use a graph based aproach instead of "just the dot product".
How is your experience?

Is it possible to reduce the number of dimensions of the sentence vectors?

Thanks
Philip

**Comment by nreimers** [comment]
Have a look here:
https://www.sbert.net/examples/applications/semantic-search/README.html#approximate-nearest-neighbor

I personally like hnswlib: It is easy to use and also one of the fastest. FAISS is also worth a look, it provides more options but is harder to use (as the documentation is not so great and quite complex)

Dimension reduction: 
https://www.sbert.net/examples/training/distillation/README.html#dimensionality-reduction

FAISS also provides options to reduce the dimensionality / the size of an ANN index: First by reducing the number of by dimensions, second by using quantiziation (representing floats with smaller float or even ints):
https://github.com/facebookresearch/faiss/wiki/Guidelines-to-choose-an-index

**Comment by PhilipMay** [comment]
What about adding a fully connected layer with 100 outputs on the top of the model (xlm-r-distilroberta-base-paraphrase-v1) in my case) and then finetune it on stsb? is that something we could / should test?

**Comment by nreimers** [comment]
The easier option is to compute some embeddings with the existent model, perform  PCA and then add a 768x100 dense layer to your existent model with the weights from the PCA:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/distillation/dimensionality_reduction.py

So you don't have to do re-training and keep most of the performance of your 768 dim. model.

**Comment by PhilipMay** [comment]
Awesome. Thanks @nreimers
