### ISSUE TITLE
Training input response selection task.

### ISSUE THREAD

**Issue by Stupack** [UKPLab/sentence-transformers#797]
Hi,

Im trying to figure out what is the best course to train a model for input response selection task, similar to the USE paper. Im not sure if the multiple negatives ranking loss is enough for this scenario. The transformers library has a class for multiple-choice as well but Im not sure about the difference. Do you have any advice?

Regards

**Comment by nreimers** [comment]
Yes, the multiple negatives ranking loss  is the right choice.

**Comment by Stupack** [comment]
Thank you for the fast response. One little thing: is there an easy way to achieve an asymmetric siamese structure? I know the code is just a loop calling the model twice, but Im not sure how to go about it without making significant changes.

**Comment by nreimers** [comment]
Have a look at this release note for asymmetric models:
https://github.com/UKPLab/sentence-transformers/releases/tag/v0.4.1

It is not yet clear what is the best option to create asymmetric models. My intern is currently investigating this.

Another simple solution is to add two special tokens to your tokenizer and to prepend your input, e.g.:

[QRY] This is my input query
[RESPONSE] This is my response.
