### ISSUE TITLE
The Order of Factors Does Alter the Product

### ISSUE THREAD

**Issue by lrodrigues-at-navteca** [UKPLab/sentence-transformers#799]
Hi, first of all thanks for developing this amazing library.

I have been doing some tests with Cross-Encoders and I have observed that depending on the order in which the pair of sentences to be evaluated are introduced, different results are obtained, as we can see below:

```
from sentence_transformers import CrossEncoder
ce_quora1 = CrossEncoder('cross-encoder/quora-roberta-large')

cross_scores1 = ce_quora1.predict([
        ['Are polar bears affected by climate change?', 'How is climate change affecting polar bears?'],
        ['How is climate change affecting polar bears?', 'Are polar bears affected by climate change?']
]).tolist()

print(cross_scores1)

[0.5854335427284241, 0.9029921293258667]
```

I would expect a similar result. Is this expected behavior?

Thank you.

**Comment by nreimers** [comment]
CrossEncoder / Tramsformers are not symmetric, i.e. CrossEncoder(A,B) is different than CrossEncoder(B, A)

This effect was tried to be reduced during training by adding both pairs (A, B) and (B, A) to the train set. But this does not eliminate the problem entirely.

In contrast, the Bi-Encoder is symmetric. 

For the task of question similarity, the bi-encoder trained on quora yields also better results than the CrossEncoder. 

The CrossEncoder identifies just  the binary decision if two questions are duplicates, i.e., all scores above 0.5 would be judged as 'duplicate'. So in your above example, both pairs would be judged as 'duplicate'.

However, the CE does not provide good estimates how similar two questions are. E.g. 'How is climate change affecting polar bears? and 'How is climate change affecting penguin?' gets a really really low score .

**Comment by luis-at-navteca** [comment]
Thanks for your prompt response Nils, it has been completely clear to me.

Certainly what I need is to identify if two questions are duplicates.

I had thought to take all scores above 0.5 as "duplicates", but was not sure if it would be correct or not.

Again I appreciate your prompt response.

**Comment by nreimers** [comment]
> I had thought to take all scores above 0.5 as "duplicates", but was not sure if it would be correct or not.

This is mainly a recall-precision trade-off. With 0.5 as threshold, you get balanced recall & precision. With 0.9 as threshold, precision would be higher and recall would be lower.

But for a starting point, 0.5 makes sense.
