### ISSUE TITLE
It seems the official BERT file can not be load.

### ISSUE THREAD

**Issue by guotong1988** [UKPLab/sentence-transformers#8]
The model file in https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/v0.1/
is Ok.

I download the official BERT file from https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_bert.py#L36

```
Traceback (most recent call last):
  File "C:/Users/gt/Desktop/sentence-transformers-master/examples/training_nli.py", line 42, in <module>
    model = SentenceTransformer(model_name_or_path='bert-base-uncased/',sentence_transformer_config=sentence_transformer_config)
  File "C:\Users\gt\Desktop\sentence-transformers-master\sentence_transformers\SentenceTransformer.py", line 90, in __init__
    self.transformer_model.load_state_dict(torch.load(output_model_file, map_location='cuda' if torch.cuda.is_available() else 'cpu'))
  File "C:\Python36\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BERT:
	Missing key(s) in state_dict: 
```

**Comment by nreimers** [comment]
Can you provide more details / code?

Note, SentenceTransformer is a wrapper around the BERT model from pytorch-transformer, that adds new layers. If you load the BERT model from pytorch-transformers, you must ensure that it is loaded for SentenceTransformer.bert

**Comment by guotong1988** [comment]
I download the model file from pytorch_transformers.
I mkdir bert-base-uncased.
I put the downloaded file into bert-base-uncased.
I edit the code of training_nli.py to point to the path above.
I run training_nli.py

**Comment by nreimers** [comment]
This doesn't work. As mentioned, SentenceTransformer adds new layer for training, which are missing.

If you run the original train_nli.py script, the BERT model will be downloaded from pytorch-transformers. Otherwise I think you can also set the path in the config that is passed to SentenceTransformer (replace bert-base-uncased with your path)

**Comment by guotong1988** [comment]
I see,
The load methods from
https://github.com/huggingface/pytorch-transformers/blob/master/pytorch_transformers/modeling_utils.py
handle the missing layer.

![image](https://user-images.githubusercontent.com/4702353/62517478-0e6b6f00-b85a-11e9-86b7-a7fa70aa6ba6.png)
