### ISSUE TITLE
Evaluator for MultipleNegativesRankingLoss

### ISSUE THREAD

**Issue by piecurus** [UKPLab/sentence-transformers#803]
Hello, 

thanks for this amazing work, it is really great!

I wonder what's the best evaluator to use in combination with the MultipleNegativesRankingLoss. 
I'd personally consider the InformationRetrievalEvaluator but documentation there is a bit cryptic and I didn't get how to use it. An improvement on that documentation would be helpful.

Cheers

**Comment by nreimers** [comment]
Yes, that is the best evaluator.

How to use it you can have a look here:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/quora_duplicate_questions/training_OnlineContrastiveLoss.py#L171
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/ms_marco/train_bi-encoder.py#L129

**Comment by piecurus** [comment]
wonderful! 

thanks a lot for the swift answer
