### ISSUE TITLE
Need to preprocess sentences before sentence-transformer use for semantic similarity ?

### ISSUE THREAD

**Issue by mattvan83** [UKPLab/sentence-transformers#805]
Hi,

I would have two questions regarding the use of sentence transformer for estimating the similarity between two sentences:

1) If one of the two sentence would contain some punctuation, symbols or emoticons (from twitter from example), would it be necessary to clean the sentence before computing sentence embedding or is this managed by the model ?

2) If one of the two sentences would contain multiple phrases separated by dot punctuation, would the sentence embedding be calculated correctly taking account of the semantic of the whole sentence ?

Thanks !

**Comment by nreimers** [comment]
1) In principle this it not needed. For unclean data from e.g. twitter, I recommend to use the 'distiluse-base-multilingual-cased-v2' model as it was trained on noisy data
2) Yes, everything in the sentence is used.

**Comment by mattvan83** [comment]
Thank you for the feedback !
