### ISSUE TITLE
cannot import name 'MT5ForConditionalGeneration' from 'transformers' (/opt/conda/lib/python3.7/site-packages/transformers/__init__.py)

### ISSUE THREAD

**Issue by hasan-moni-321** [UKPLab/sentence-transformers#809]
When I try to import MT5ForConditionalGeneration from transformers it gives this error why?
When I import T5Model it works but not the previous one!

**Comment by nreimers** [comment]
This issue is not related to sentence-transformers. Check the discussion forum from huggingface transformers how to solve it.
