### ISSUE TITLE
What are the student/ teacher models of the multilingual models?

### ISSUE THREAD

**Issue by ursinabisang** [UKPLab/sentence-transformers#814]
Hi, I have a question concerning the multilingual models. I intend to use one of them in a university project and need to know which models were the teacher and student models for the following final models (I assume all multilingual models were trained according to this paper: https://arxiv.org/abs/2004.09813):
1) stsb-xlm-r-multilingual: For this one I guess based on description and name that s-BERT is the teacher and XLM-R is the student
2) paraphrase-xlm-r-multilingual-v1: It has xlm-r in its name, so I assume based on my guess above that the student network is XLM-R, but what is the teacher?

Are my guesses correct and if not what are the correct student/ teacher models? And would it be possible to add this kind of info somewhere into the documentation, for example into the list of pretrained models?

For completeness: the following model has the following teacher/ student models (I found the answer in another issue):
distiluse-base-multilingual-cased-v2: teacher: USE-multilingual, student: distilbert-multilingual

**Comment by nreimers** [comment]
Hi,
1) student: xlm-r, teacher:  bert-base-nli-stsb-mean-token (now called: stsb-bert-base...)
2) student: xlm-r, teacher: paraphrase-distilroberta-base-v1
3) student: distilbert-multilingual, teacher: USE-multilingual

**Comment by ursinabisang** [comment]
As a follow-up question: To which paper does paraphrase-distilroberta-base-v1 refer? Is it based on the sBERT paper (https://www.aclweb.org/anthology/D19-1410.pdf) or some other paper?

**Comment by nreimers** [comment]
It is based on: https://arxiv.org/abs/2004.09813

**Comment by ursinabisang** [comment]
But that paper doesn't really explain the training process for the teacher model paraphrase-distilroberta-base-v1, it only states that it is a RoBERTa model trained on 50 million English paraphrase pairs, while the name implies that it is connected to the Sentence-BERT paper, as does the fact that it is a sentence embeddings models. But I didn't really find any explanation for the training of RoBERTa models in the sentence BERT paper. So I was a bit insecure and wondering how the teacher model was trained.

**Comment by nreimers** [comment]
Indeed, the paper is not too specific on that.

The teacher was simply trained as explained here:
https://www.sbert.net/examples/training/paraphrases/README.html

**Comment by ursinabisang** [comment]
Thank you!
