### ISSUE TITLE
TypeError: No loop matching the specified signature and casting was found for ufunc add

### ISSUE THREAD

**Issue by sbhttchryy** [UKPLab/sentence-transformers#815]
Hello, 
On trying to finetune cross-encoder -  'amberoad/bert-multilingual-passage-reranking-msmarco'  
`model = CrossEncoder('amberoad/bert-multilingual-passage-reranking-msmarco', num_labels=2)
for the STS benchmark task, I get the following error on calling `model.fit()`

TypeError: No loop matching the specified signature and casting was found for ufunc add

The full stack trace is as follows:

/data/home/krystian/sentence-transformers/sentence_transformers/cross_encoder/CrossEncoder.py in fit(self, train_dataloader, evaluator, epochs, loss_fct, acitvation_fct, scheduler, warmup_steps, optimizer_class, optimizer_params, weight_decay, evaluation_steps, output_path, save_best_model, max_grad_norm, use_amp, callback)
    211 
    212             if evaluator is not None:
--> 213                 self._eval_during_training(evaluator, output_path, save_best_model, epoch, -1, callback)
    214 
    215 

/data/home/krystian/sentence-transformers/sentence_transformers/cross_encoder/CrossEncoder.py in _eval_during_training(self, evaluator, output_path, save_best_model, epoch, steps, callback)
    283         """Runs evaluation during the training"""
    284         if evaluator is not None:
--> 285             score = evaluator(self, output_path=output_path, epoch=epoch, steps=steps)
    286             if callback is not None:
    287                 callback(score, epoch, steps)

/data/home/krystian/sentence-transformers/sentence_transformers/cross_encoder/evaluation/CECorrelationEvaluator.py in __call__(self, model, output_path, epoch, steps)
     47 
     48 
---> 49         eval_pearson, _ = pearsonr(self.scores, pred_scores)
     50         eval_spearman, _ = spearmanr(self.scores, pred_scores)
     51 

/data/home/krystian/es_env/lib/python3.7/site-packages/scipy/stats/stats.py in pearsonr(x, y)
   3854         return dtype(np.sign(x[1] - x[0])*np.sign(y[1] - y[0])), 1.0
   3855 
-> 3856     xmean = x.mean(dtype=dtype)
   3857     ymean = y.mean(dtype=dtype)
   3858 

/data/home/krystian/es_env/lib/python3.7/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    158             is_float16_result = True
    159 
--> 160     ret = umr_sum(arr, axis, dtype, out, keepdims)
    161     if isinstance(ret, mu.ndarray):
    162         ret = um.true_divide(

TypeError: No loop matching the specified signature and casting was found for ufunc add

Could you please help me with this?

**Comment by nreimers** [comment]
The CECorrelationEvaluator only works with models that predict a single score, not multiple scores as it is the case with the model you load.

**Comment by sbhttchryy** [comment]
In case I want to continue my finetuning with the specified model, is there any evaluator I can use? Thank you so much for your response.

**Comment by nreimers** [comment]
You can just copy the code and modify the evaluator so that it e.g. always uses the score[1] for the computation of the correlation.

So you create a local version of that class, and then pass an object of that class to the fit method
