### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size

### ISSUE THREAD

**Issue by denlogv** [UKPLab/sentence-transformers#818]
Hello, 

I was using the 'token_embeddings' feature of SentenceTransformers.encode() and got the pytorch RuntimeError 

File "...\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 201, in encode
    all_embeddings = torch.stack(all_embeddings)

"amrs_sents" in the following code consists of 1866 STS-sentences (strings):

```
def precompute_embeddings(amr_file1, amr_file2):
    with open(amr_file1) as f1, open(amr_file2) as f2:
        amrs1 = f1.read().strip().split('\n\n')
        amrs2 = f2.read().strip().split('\n\n')
    
    amr_len = min(len(amrs1), len(amrs2))
    amrs_sents1 = [amr.split('\n')[1].strip()[len('# ::snt '):] for amr in amrs1[:amr_len]]
    amrs_sents2 = [amr.split('\n')[1].strip()[len('# ::snt '):] for amr in amrs2[:amr_len]]    
    
    amrs_sents = [None]*2*amr_len
    amrs_sents[::2] = amrs_sents1
    amrs_sents[1::2] = amrs_sents2
    
    sents_encoded = sbert_model.tokenize(amrs_sents)
    sents_embs = sbert_model.encode(sents_encoded, convert_to_tensor=True, 
                                     output_value='token_embeddings',
                                     is_pretokenized=True,
                                     show_progress_bar=False)
    
    return sents_embs, sents_encoded
```

I also tried to encode original sentences without pretokenizing them first but it failed, too. Could you please suggest a workaround or explain what I am doing wrong?

**Comment by denlogv** [comment]
I also found out that the code is working fine until the value `amr_len = 17`.

**Comment by nreimers** [comment]
Set convert_to_tensor=False and convert_to_numpy=False when you call encode.
The issue is that the sentences have different numbers of token embeddings, which cannot be represented as a single tensor.

**Comment by denlogv** [comment]
Oh, thanks a lot for a quick response! It helped me a lot!


So, for anyone wondering, how you can create a tensor of shape (num_sentences, max_token_len_in_corpus, 768):

```
sents_embs = sbert_model.encode(sents_encoded, convert_to_tensor=True, 
                                     output_value='token_embeddings',
                                     is_pretokenized=True,
                                     show_progress_bar=False)
```
Will give you a list of tensors of size (token_len, 768). Then you can simply use:

`sents_embs  = torch.nn.utils.rnn.pad_sequence(sents_embs, batch_first=True)`

To get such a tensor! 

@nreimers maybe make it standard functionality? Because I found it pretty confusing that the function works for some lengths and not for others.

**Comment by nreimers** [comment]
Hi @denlogv 
Thanks for the suggestion.

In the most recent commit I fixed this issue. Now, a list with tensors with the token embeddings are returned. The padding tokens are removed, i.e. each entry can have a different length.

Hence, convert_to_tensor and convert_to_numpy is ignored.

If you need one large tensor, you can pad the output and create a big tensor then out of it.
