### ISSUE TITLE
STSDataReader.py  :  IndexError: list index out of range 

### ISSUE THREAD

**Issue by chiragsanghvi10** [UKPLab/sentence-transformers#82]
Hi @nreimers ,

I am fine-tuning `roberta-base-nli-mean-tokens` with STS data + I have manually added few data.

This is how my data set looks (sentence1\tsentence2\tscore)

#### example:

> A plane is taking off.\tAn air plane is taking off.\t5

> A man is playing a large flute.\tA man is playing a flute.\t3.8

> A man is spreading shreded cheese on a pizza.\tA man is spreading shredded cheese on an uncooked pizza.\t3.8

I have changed this in `STSdataReader.py`

`def __init__(self, dataset_folder, s1_col_idx=0, s2_col_idx=1, score_col_idx=2, delimiter="\t",
                 quoting=csv.QUOTE_NONE, normalize_scores=True, min_score=0, max_score=5):`

### Result

~/venv/lib/python3.6/site-packages/sentence_transformers/readers/STSDataReader.py in get_examples(self, filename, max_examples)
     28         examples = []
     29         for id, row in enumerate(data):
---> 30             score = float(row[self.score_col_idx])
     31             if self.normalize_scores:  # Normalize to a 0...1 value
     32                 score = (score - self.min_score) / (self.max_score - self.min_score)

`IndexError: list index out of range`

Is there something that I am not doing it right?

**Comment by nreimers** [comment]
Looks like that one row does not consists of (at least) 3 columns. Maybe some noise in your data? Or some empty line in your data?

Check if all your lines actually have 3 columns and the the columns are separated by a tabulator.

**Comment by chiragsanghvi10** [comment]
Hi @nreimers,

I re-checked everything seems fine. I am adding my data to sts-train.csv.
I also set 
`df.to_csv(sts_reader.dataset_folder+'/sts-train.csv', index = False, header=None, sep="\t")`

I am still getting the same error message.

**Comment by working12** [comment]
@chiragsanghvi10  What was the solution?
