### ISSUE TITLE
semantic search error

### ISSUE THREAD

**Issue by aqsa27** [UKPLab/sentence-transformers#823]
I am trying to run the semantic search tutorial available 
and for corpus, i am specifying a column of a dataframe
and i keep getting the error:
KeyError: tensor(180)

I have all the necessary libraries installed.
Can anyone tell me what might be the issue?
Thank You

**Comment by nreimers** [comment]
Looks like that you pass the wrong data from you data frame.

Note, the encode method expects that you pass a list with strings. Other formats might not work. So convert your column first to a list of strings.

**Comment by aqsa27** [comment]
@nreimers thank you for the quick response. I will try this.

**Comment by aqsa27** [comment]
@nreimers it worked. Thank you so very much for your prompt help
