### ISSUE TITLE
What happened with xlm-r-distilroberta-base-paraphrase-v1 ?

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#828]
Hi @nreimers 
may I ask what happened with xlm-r-distilroberta-base-paraphrase-v1?
It got released here: https://github.com/UKPLab/sentence-transformers/releases/tag/v0.3.8

Did you delete or rename it?

Thanks
Philip

**Comment by PhilipMay** [comment]
Ahh - I found it - it got renamed to paraphrase-xlm-r-multilingual-v1 ?
Is that right?

**Comment by nreimers** [comment]
The model still exists. But a copy was also created following the new naming scheme:
paraphrase-xlm-r-multilingual-v1 

Both models are identical.

**Comment by PhilipMay** [comment]
Thanks
