### ISSUE TITLE
Optimal number of cluster

### ISSUE THREAD

**Issue by songlory** [UKPLab/sentence-transformers#83]
Hi,
Merry Xmas!
I am wondering how I can determine the optimal number of clusters via using your sentence-transfromer. Is there any code for elbow or silhouette analysis especially fitting your code? I will be highly appreciated if you could help me with this.
Best,

**Comment by nreimers** [comment]
Hi @songlory 
I haven't tested any of them, so sadly I don't have experiences if any method for this situation is especially suitable or not.

Personally I often use agglomerative clustering and then determine a threshold that is reasonable.

Best regards
Nils Reimers

**Comment by subham1** [comment]
For 10k sentences during inference, it will do at least 49995000 computations using any order Order(N*N) clustering algorithm. Can we do something better?

**Comment by nreimers** [comment]
Hi subham1,
not as far as I know

However, cosine similarity is basically a matrix multiplication of a 10k x embed-size matrix, which is a super fast and efficient operation. So you don't have to worry too much about it.

**Comment by lefnire** [comment]
```python
from kneed import KneeLocator  # pip install kneed

K = range(1, 40, 2)
scores = []
for k in K:
    # consider other clusterer; see https://github.com/UKPLab/sentence-transformers/issues/320#issuecomment-668708612
    km = KMeans(n_clusters=k).fit(x)
    scores.append(km.inertia_)
S = 1.  # fiddle this. Lower is stricter, higher is looser
kn = KneeLocator(list(K), scores, S=S, curve='convex', direction='decreasing')
print('knee', kn.knee)
```

FWIW in my use-cases on 40-80k rows, I find n_clusters=20-30 (aka 25 avg).
