### ISSUE TITLE
Stuck in MSE

### ISSUE THREAD

**Issue by minyoung90** [UKPLab/sentence-transformers#831]
My experiment was stopped because of unchanging MSE.

I trained teacher-student multilingual model.
I used Korean BERT as teacher, and stsb-xlm-r-multilingual as student.
So far, I got these MSE values.

KR-EN 11 ~ 12
KR-CN 10 ~ 11
KR-JP 10 ~ 11

but after more epoches, above MSE were not decreased under 9 point.
So what I did were that, I changed lr (2e-5 to 5e-5), warm-up rate (20% to 2%).
But, Nothing was happend.

is there any chance to optimize more?

**Comment by nreimers** [comment]
Hi @minyoung90 
Like any evaluation metric, achieving a 100% score (i.e. MSE of 0) is hardly possible. It similar to accuracy, where you never reach 100% accuracy on your dev set.

It it hard to judge if 10 MSE is good or bad. It depends on the quality of your parallel data and how well the distillation work. In my Experiments, I get for EN-KO scores of around 3. But this can change from setup to setup and model to model.

So it is good to find some other dataset where you can evaluate your embeddings on.

**Comment by minyoung90** [comment]
Thanks for sharing your experience! @nreimers 
But, promising point is translation metric is good (90~95%). so I will check using other dataset whether my model is useful.
