### ISSUE TITLE
Questions about TED2020 dataset

### ISSUE THREAD

**Issue by gowtham1997** [UKPLab/sentence-transformers#832]
Hello,

Thank you so much for creating the [TED 2020 dataset](https://github.com/UKPLab/sentence-transformers/blob/master/docs/datasets/TED2020.md?). 

I wanted to know:
1) What is the alignment method and the threshold you use to get parallel sentences from the ted-x transcripts?

I read [this paper](https://arxiv.org/pdf/2004.09813.pdf) but couldn't find more information on this dataset.

Regards, 
Gowtham

**Comment by nreimers** [comment]
Hi,
the code is included in this file:
https://public.ukp.informatik.tu-darmstadt.de/reimers/sentence-transformers/datasets/ted2020-source-files.zip

Alignment was made on the timestamps of the video. I.e. for each language we have the info about start and end time of a text & translated segment.

**Comment by gowtham1997** [comment]
Ok. Will take a look.
Thank you for the prompt response.
