### ISSUE TITLE
Add context to semantic similarity

### ISSUE THREAD

**Issue by fcggamou** [UKPLab/sentence-transformers#837]
Hi,

Consider the following scenario: I want to compare if two sentences are similar, by taking into account the context; but I don't want the context to fully determine the outcome either. Maybe I can clarify with an example:

1. In the store we bought some **big apples**.
2. The trees yielded a lot of fruits, **but the biggest were the apples**.
3. The trees yielded a lot of fruits, **and indeed very big oranges**.
4. The are many companies and some are big and some are small, **but none is bigger than Apple**.

(please ignore the casing, this is just a made up example, assume an uncased model is used).

I know this may be too specific, but I want to perform semantic similarity only on the bolded text, while having into consideration the context. My desired outcome would be:
1 == 2 (both mentions of big apple fruits)
2 != 3 != 4 (apples != oranges != Apple)
1 != 3 != 4 (apples != oranges != Apple)

So for example, if I take the whole sentence into consideration, it's very likely that 2 ≈ 3, but I would only want 2 ≈ 3 if the bolded text was "The trees yielded a lot of fruits".
If I take only the bolded part into consideration, then I will probably get 2 ≈ 4.  

Another way to put it is that I want to perform semantic similarity on these sentences, but somehow indicate that the bolded text is more important.

Would something like prefixing/suffixing a special token around the "important words" work?

Thanks a lot for any feedback.

**Comment by nreimers** [comment]
Do you have training data for this?

Then training a model like 
[query] [SEP] [context]

with CLS pooling would solve your issue.

**Comment by fcggamou** [comment]
Thank you for your answer Nils. I do have training data, not a huge dataset but in the thousands. 

Could you please elaborate on the CLS pooling approach or point me on the right direction in the documentation/papers to understand how to use it with sbert and why it solves my issue? Sorry if this is obvious but I'm fairly new with this.

Thank you

**Comment by nreimers** [comment]
See our paper on different pooling methods:
https://arxiv.org/abs/1908.10084

In the pooling layer, when you create a new Sentence Transformers model, you can choose the type of pooling:
https://www.sbert.net/docs/package_reference/models.html#sentence_transformers.models.Pooling

**Comment by fcggamou** [comment]
Thanks a lot!
