### ISSUE TITLE
T5 models for sentence transformers

### ISSUE THREAD

**Issue by e-ndrus** [UKPLab/sentence-transformers#84]
Thank you for a terrific project! Are you planning on integrating t5 models into sentence transformers (https://github.com/google-research/text-to-text-transfer-transformer/blob/master/README.md#released-model-checkpoints)?

**Comment by nreimers** [comment]
Hi @e-ndrus 

The underlying transformers project from hugging face will be updated soon to the newest version, which will include models for T5. I think I will release this new version until January 10th.

But as usual: Better performance in supervised tasks (like Glue dataset), does not equal better performances in generating sentence embeddings. In fact, several newer models for supervised tasks yielded rather disappointing results when be used for generating sentence representations (like XLNet or ALBert).

Best
Nils Reimers

**Comment by nreimers** [comment]
Hi @e-ndrus 
I updated the version of sentence transformers to include T5.

However:
- Due to a bug in transformers, T5 cannot be trained on the GPU. See https://github.com/huggingface/transformers/issues/2472
- Even after fixing this issue, it currently does not yield good results. Maybe there are still some bugs how T5 is called to produce a sentence representation.

**Comment by e-ndrus** [comment]
@nreimers, great. Thank you! Will check.

**Comment by jk2227** [comment]
Hi @nreimers 

Was curious if you had saved the sentence embeddings trained from the T5 models somewhere that we could use or if we need to train/save it ourselves : ) 

Also out of curiosity, which T5 model did you use in terms of number of parameters?  

Thanks!

**Comment by nreimers** [comment]
Hi @jk2227
I only did some simple tests with T5. But at that time, I think T5 was not yet well integrated into huggingface transformer code. 

Further, at that time, it was not clear how T5 can be used. For T5, you must first input a special token to specify the task and it was not yet clear how to input this token into the code.

In the latest version of huggingface there were a lot of improvements for T5. So I think it makes sense to re-run the experiment. Especially it would be interesting which task token would be useful to get good sentence embeddings.

Best
Nils Reimers

**Comment by lukemao** [comment]
Hi Nils,
Can further work or experiment on integrating T5 as based for generating sentence embeddings?

Many thanks,
Lu

**Comment by nreimers** [comment]
Hi @lukemao
Yes, if you like, you can run experiments with T5 and report the results here.

Best
Nils

**Comment by lukemao** [comment]
thanks @nreimers .

Does sentence transformer provide any functions for save/export the created embeddings in files or database(like redshift or google's bigquery).

**Comment by nreimers** [comment]
Have a look here
https://sbert.net/examples/applications/computing-embeddings/README.html#storing-loading-embeddings

There is no built in support for bigquery or redshift

**Comment by PhilipMay** [comment]
How do you plan to get a vector from those T5 models? They are text to text models.
Do you want to somehow strip them?
They read text and generate text. In contrast the "normal" BERT / RoBERTa / Electra models read
text and generate a tensor which can be passed to a prediction head...

**Comment by nreimers** [comment]
T5 is an encoder-decoder architecture. The encoder of T5 produces contextualized word embeddings just like BERT.

**Comment by lukemao** [comment]
@PhilipMay 
Here is an example:

```python
>>> from transformers import T5Tokenizer, TFT5Model

>>> tokenizer = T5Tokenizer.from_pretrained('t5-small')
>>> model = TFT5EncoderModel.from_pretrained('t5-small')

>>> input_ids = tokenizer("Studies have been shown that owning a dog is good for you", return_tensors="tf").input_ids  # Batch size 1
>>> outputs = model(input_ids)
```

**Comment by PhilipMay** [comment]
That is very interesting. Thanks for the example @lukemao
