### ISSUE TITLE
Fine-tuning CLIP

### ISSUE THREAD

**Issue by harisbinzia** [UKPLab/sentence-transformers#840]
Hi, thank you for this amazing repo!

Could you please point me to the script that guides how to fine-tune CLIP (clip-ViT-B-32) on my own image & text data?

If there isn't any dedicated script for that, could you please let me know how to modify [one of the recipes](https://github.com/UKPLab/sentence-transformers/tree/master/examples/training) to fine-tune CLIP?

Best Regards,
Haris Bin Zia

**Comment by nreimers** [comment]
There is no example yet. But in principle it works like any of the training recipes.

Also due to  #839, a fine tuned CLIP model currently cannot  be  saved.

This will be fixed in the next release, together with a recipe how to fine-tune the CLIP model

**Comment by nreimers** [comment]
Saving of the CLIP model is now possible with version 1.0.4

Will work on some tutorial how to fine-tune it

**Comment by sgaseretto** [comment]
Are there any guides on how to finetune a CLIP model? As I understand it is possible to do now

**Comment by thtang** [comment]
Same question~

**Comment by jpzhangvincent** [comment]
> Saving of the CLIP model is now possible with version 1.0.4
> 
> Will work on some tutorial how to fine-tune it

Is there a tutorial available now? Thanks a lot!

**Comment by gongshaojie12** [comment]
Same question

**Comment by Kllin0219** [comment]
Is there a tutorial available now?

**Comment by unmo** [comment]
I would like to do the same. Have you made any progress?

**Comment by bakshienator77** [comment]
Throwing my hat into this. Would love to see a finetuning tutorial.

**Comment by tomaarsen** [comment]
Hello!

As of a week ago, there is an example of how a CLIP model can be trained [here](https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/clip/train_clip.ipynb), courtesy of @unmo and myself. It's a tad simple, not exactly end-to-end, but it should give you an insight in how CLIP could be finetuned.
If you end up expanding it, I'm certainly open to a PR with a more end-to-end example that produces a finetuned model in the end.

I'll close this for now :)

- Tom Aarsen

**Comment by httplups** [comment]
Hello @tomaarsen . I tried to use the Trainer to train the jina-clip-v2, but I could not. I tried to pass the iterable dataset directly, not used InputExamples as in your example. Can we use trainer class as well?
