### ISSUE TITLE
ModuleNotFoundError: No module named 'sentence_transformers'

### ISSUE THREAD

**Issue by rishabh547** [UKPLab/sentence-transformers#843]
I am still getting this error , i tried everything from normal pip to U- install but still the same error. Can someone explain to me meaning of install from Source? .

![image](https://user-images.githubusercontent.com/59617133/112960685-45df0b80-9162-11eb-982d-33e55df97ebd.png)

Any Help regarding solving this module issue would really be appreciated!

**Comment by mutigaj1** [comment]
use this... conda install -c conda-forge sentence-transformers, it will take a while, but it works

**Comment by umair-195** [comment]
`pip install sentence-transformers==2.2.1`
This Solved my issue

**Comment by tomaarsen** [comment]
Hello!

This often occurs when `pip install -U sentence-transformers` refers to a different Python install than the `python`. Perhaps `python -m pip install -U sentence-transformers` will help, as then the `pip` will surely match with the `python` install. I'll close this for now.

- Tom Aarsen
