### ISSUE TITLE
Model summary

### ISSUE THREAD

**Issue by HariWu1995** [UKPLab/sentence-transformers#845]
I want to check the architecture of **distiluse-base-multilingual-cased-v2** so I use torchsummary library. Below is my code
`import torch`
`from torchvision import models`
`from torchsummary import summary`
`from sentence_transformers import SentenceTransformer`

`device = torch.device("cuda" if torch.cuda.is_available() else "cpu")`
`model = SentenceTransformer('distiluse-base-multilingual-cased-v2').to(device)`

`summary(model, input_size=(119547, 768)) # I check list(model.parameters())[0].shape = torch.Size([119547, 768])`

Here is the error
`IndexError                                Traceback (most recent call last)`
`<ipython-input-41-657fab7dc4b2> in <module>`
`----> 1 summary(model, input_size=(119547, 768))`

`/opt/conda/lib/python3.7/site-packages/torchsummary/torchsummary.py in summary(model, input_size, batch_size, device)`
`     70     # make a forward pass`
`     71     # print(x.shape)`
`---> 72     model(*x)`
`     73 `
`     74     # remove these hooks`

`/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)`
`    725             result = self._slow_forward(*input, **kwargs)`
`    726         else:`
`--> 727             result = self.forward(*input, **kwargs)`
`    728         for hook in itertools.chain(`
`    729                 _global_forward_hooks.values(),`

`/opt/conda/lib/python3.7/site-packages/torch/nn/modules/container.py in forward(self, input)`
`    115     def forward(self, input):`
`    116         for module in self:`
`--> 117             input = module(input)`
`    118         return input`
`    119 `

`/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)`
`    725             result = self._slow_forward(*input, **kwargs)`
`    726         else:`
`--> 727             result = self.forward(*input, **kwargs)`
`    728         for hook in itertools.chain(`
`    729                 _global_forward_hooks.values(),`

`/opt/conda/lib/python3.7/site-packages/sentence_transformers/models/Transformer.py in forward(self, features)`
`     32     def forward(self, features):`
`     33         """Returns token_embeddings, cls_token"""`
`---> 34         trans_features = {'input_ids': features['input_ids'], 'attention_mask': features['attention_mask']}`
`     35         if 'token_type_ids' in features:`
`     36             trans_features['token_type_ids'] = features['token_type_ids']`

`IndexError: too many indices for tensor of dimension 3`

I read SentenceTransformer.py and see that you modify a lot. Is there any way to summary the model? It'll be better if I can export the summary as picture.
Thanks in advance!

**Comment by nreimers** [comment]
Hi @HariWu1995 
I sadly don't have experiences with torch summary.

When you download and unzip the respective model from:
http://sbert.net/models/

You see the different layers.

For your mentioned model, it is a multilingual DistilBERT model, followed by a mean pooling operation, followed by a 768x512 linear layer.

Maybe from this information you can create your picture.

**Comment by HariWu1995** [comment]
@nreimers Thank you! I will try some ways, then.
