### ISSUE TITLE
Different results for inference on cpu vs gpu?

### ISSUE THREAD

**Issue by PaulForInvent** [UKPLab/sentence-transformers#848]
I trained a sbert model with multirankingnegatives loss on a gpu and load it on a cpu and get very different results. Mostly, the confidence scores are much lower as compared to when using a gpu.

Should this be normal? I know that maybe training on gpu vs cpu (also different system) might be different. But here, I just load a model and use it for inference. Maybe I forgot something to check. But it seems not.

In my case this is a critical issue, because of course normally one trains a model on gpu and then use it on a simple cpu for deployment.

**Comment by nreimers** [comment]
No, there shouldn't be much of a differences.

Do you experience this also with the pre-trained models we provide?

**Comment by PaulForInvent** [comment]
Hey @nreimers 

It was a very bad mistake. It was actually a whole different model I compared... ^^xD Sorry for that. So there is no issue...
