### ISSUE TITLE
Iteration on 0% but keep going

### ISSUE THREAD

**Issue by GefenPuravida** [UKPLab/sentence-transformers#85]
![image](https://user-images.githubusercontent.com/48918701/71559159-87669f80-2a63-11ea-8a0f-9dffc6633322.png)

is this normal ? is it iterating ?

**Comment by nreimers** [comment]
The screenshot shots, that the code is a training step 130 from 58880. The remaining time is 101 hours, 39 minutes. Per iteration step, it requires 6.23 seconds (s/it).

I assume you are training on a CPU? Transformer networks, like BERT, are extremely slow to train on CPU. Usage of a GPU is recommended.

If you have no GPU available, maybe one of the other include architectures (like DAN, CNN, LSTM), is more suitable for you?

Best
Nils Reimers

**Comment by GefenPuravida** [comment]
Thanks!
