### ISSUE TITLE
Preprocessing before using `model.encode(sentences)`

### ISSUE THREAD

**Issue by muhlbach** [UKPLab/sentence-transformers#851]
First, I'm a huge fan of this project and I use it very actively - thanks guys!

To my question. 

**1) Cased vs. uncased**
Assume I running the following code:
```
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('stsb-bert-base')

#Our sentences we like to encode
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.',
    'The quick brown fox jumps over the lazy dog.']

#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)
```
Since the underlying pre-trained model is uncased but the sentences are cased, is this code doing some "uncasing" under the hood? 

**2) Text preprocessing**
More generally, when I preprocess my sentences (lemmatize, remove stop words, remove special characters, ...), I tend to get different results compared to when I don't. As a rule-of-thumb, would you recommend that I preprocess the sentences myself (perhaps for consistency across methods) or should I leave this to your under-the-hood preprocessing because you shouldn't, say, remove stop words?

Looking forward to your answers!

**Comment by nreimers** [comment]
1) Yes, the text is lower cased before processing for uncased models

2) Specific preprocessing is not needed. Only when you have a lot of noise in your sentences, like URLs, it can make sense to remove them. Lemmatization and stop word removal is not needed

**Comment by muhlbach** [comment]
@nreimers thanks a lot for your quick answer! 

One clarifying question: I do experience that embeddings change when I lemmatize and remove stop words. Although I don’t **need** to preprocess according to your answer, are there any situations where such preprocessing could actually hurt performance and therefore it’s recommended **not** to preprocess? Or, say, if I want to compare the embeddings to those of Doc2Vec, would it be completely fine to preprocess to ensure consistency of the input sentences?

Thanks in advance!

**Comment by nreimers** [comment]
Yes, the embeddings will change because you input different text in that case.

I would recommend to input the original text. The models were not trained on lemmatized + stop-word removed examples.

**Comment by muhlbach** [comment]
@nreimers thanks! 

To me, the source of confusion is that in your example on "_Sentence Embeddings with Transformers_" (see [here](https://github.com/UKPLab/sentence-transformers/blob/master/examples/applications/computing-embeddings/README.md#sentence-embeddings-with-transformers)), you are using the **AutoTokenizer** and **AutoModel** from **transformers** to obtain the same sentence embeddings as by using **sentence_transformers**.

But reading the source code (see [here](https://huggingface.co/transformers/model_doc/auto.html#autotokenizer), it was not clear to me whether the AutoTokenizer actually does _any_ preprocessing at all or simply tokenize.

**Comment by nreimers** [comment]
AutoTokenizer just tokenizes without further pre-processing.

**Comment by muhlbach** [comment]
Thanks, this was really helpful!
