### ISSUE TITLE
How to set up a good threshold for top_k results in semantic search

### ISSUE THREAD

**Issue by jonas-nothnagel** [UKPLab/sentence-transformers#858]
Hi!

I am using `SentenceTransformer('nq-distilbert-base-v1')` for Semantic Search on documents with rather arbitrary lengths differing between 500 to 10000 tokens. For preprocessing, I  splitted  and re-indexed the documents to 256 tokens with 10 token split overlap. 

The semantic search works quite fine, but I am wondering how you would proceed in eliminating "non-relevant" results. If I query for instance for a specific term such as "beekeeping" I find 3-4 well fitting hits, but the user would also get useless results, if `top_k ` is not set very low. 

Baselining against ElasticSearch it returns only 3 results, so I assume that they use some sort of internal threshold to define relevance. How can I achieve something similar? 

Thanks!

**Comment by nreimers** [comment]
Hi,
ElasticSearch returns all docs that have the words in it. If beekeeping appears only in 3 docs, only 3 docs are returned. If beekeeping appears in 1k docs, all 1k docs are returned with likely many irrelevant docs.

For semantic search finding a threshold is difficult. What you could use as threshold is e.g. alpha * best_score.

So if your best score is 0.9 and you set alpha to 80%, you output all scores above 0.9 x 0.8 = 0.72

You can also try to find a fixed threshold, e.g. you observe that only passages with a score above 0.5 are relevant => output only those docs

**Comment by jonas-nothnagel** [comment]
Hi @nreimers. 

Okay I see. I will play around with the score - perhaps even give the user the option to do so with some disclaimers. 
Eventually I guess labelling the documents with relevant categories (such as beekeeping) will be the best solution since such "false positives" should really be avoided in my case. 

Thanks for the super quick answer!
