### ISSUE TITLE
Guideline for number of instances to generate when using Contrastive Loss

### ISSUE THREAD

**Issue by mjdall** [UKPLab/sentence-transformers#866]
Hi, I'm just wanting some input on number of instances to generate when using contrastive loss?
I get there's an aspect of the right number being problem specific but is there any sort of guideline?
Say I had 50k rows, is generating 50,000 * 8 (1 positive, 7 negative) instances a bad idea?

I'm getting varying results on different numbers of instances currently.

Thanks

**Comment by nreimers** [comment]
Hi @mjdall 
I have not used contrastive loss much, so I cannot say what a good value is for the positive to negative ratio.

But yes, the ratio will have an impact
