### ISSUE TITLE
cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler

### ISSUE THREAD

**Issue by kunaldahiya** [UKPLab/sentence-transformers#867]
Hi,

I am getting the following error with pytorch-1.8.0 and sentence-transformers-1.0.4:

```txt
cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/anaconda3/lib/python3.8/site-packages/torch/optim/lr_scheduler.py)
```

PyTorch might have removed 'SAVE_STATE_WARNING' in latest version. Can you please look into this issue?

Thanks!

**Comment by nreimers** [comment]
Hi @kunaldahiya 
This repository does not use SAVE_STATE_WARNING.

From the error message, it appears that it is used within torch. So I think the error is there (or with transformers).

Cannot help sadly, just recommend to try another pytorch version.

**Comment by kunaldahiya** [comment]
Thanks! I'll look into the transformers library.
