### ISSUE TITLE
Having a problem loading dev-set

### ISSUE THREAD

**Issue by Kramer19** [UKPLab/sentence-transformers#872]
Hello. I'm training a model to translation, and i have a dev-set like this:
A group of kids is playing in a yard and an old man is standing in the background	Um grupo de meninos em um quintal está brincando e um homem está parado ao fundo	4.5
A group of children is playing in the house and there is no man standing in the background	Um grupo de crianças está brincando no quintal e um velho está parado ao fundo	3.2
The young boys are playing outdoors and the man is smiling nearby	As crianças estão brincando ao ar livre perto de um homem com um sorriso	4.7
The kids are playing outdoors near a man with a smile	Um grupo de crianças está brincando no quintal e um velho está parado ao fundo	3.4
The young boys are playing outdoors and the man is smiling nearby	Um grupo de crianças está brincando no quintal e um velho está parado ao fundo	3.7

Sentence in english \t Another sentence in portuguese \t Semantic Similarity between then

I followed the tutorial in pypi and have done:
sts_reader = readers.STSDataReader('dataset/', s1_col_idx=0, s2_col_idx=1, score_col_idx=2)
dev_data = SentencesDataset(examples=sts_reader.get_examples('dev.txt'), model=model)
dev_dataloader = DataLoader(dev_data, shuffle=False, batch_size=train_batch_size)
evaluator_sts = evaluation.EmbeddingSimilarityEvaluator(dev_dataloader, name='dev')
evaluators.append(evaluator_sts)

but having the error:
evaluator_sts = evaluation.EmbeddingSimilarityEvaluator(dev_dataloader, name='dev')
TypeError: __init__() missing 2 required positional arguments: 'sentences2' and 'scores'

Some clue about what can be happening?

**Comment by nreimers** [comment]
The code for the evaluators changed during the versions, so that you pass to EmbeddingSimilarityEvaluator no longer a data loader.

Have a look here on the most recent examples how to use the evaluator:
https://github.com/UKPLab/sentence-transformers/tree/master/examples/training/sts

**Comment by Kramer19** [comment]
Thank you, did you know until which version It worked?

**Comment by nreimers** [comment]
You can check the release notes, it should be mentioned somewhere where it changed:
https://github.com/UKPLab/sentence-transformers/releases

**Comment by Kramer19** [comment]
Thank you very much, i will try It latter.. both, find the version ifnot migrate the code.
🥰👍
