### ISSUE TITLE
License for the model

### ISSUE THREAD

**Issue by Tatyana-jl** [UKPLab/sentence-transformers#878]
Hi! May I kindly ask you to clarify the license for the model paraphrase-xlm-r-multilingual-v1? Is it licensed with Apache2-0 like others (it does not have any tags in HuggingFace library)?

**Comment by PhilipMay** [comment]
Should be the same as the base Model https://huggingface.co/xlm-roberta-base

So MIT license.

**Comment by Tatyana-jl** [comment]
Thank you!

**Comment by PhilipMay** [comment]
Well - I would recommend to wait for an answer of @nreimers .
