### ISSUE TITLE
Set cache folder for downloaded models

### ISSUE THREAD

**Issue by gionapaolini** [UKPLab/sentence-transformers#879]
I load the model with:
```
modelUrl = "https://myurl.com/models/distiluse-base-multilingual-cased-v1.zip"
model = SentenceTransformer(modelUrl)
```
I tried setting `PYTORCH_TRANSFORMERS_CACHE`, `PYTORCH_PRETRAINED_BERT_CACHE`, `TRANSFORMERS_CACHE` but none of them worked, the models are still stored at `~/.cache/torch/sentence_transformers/...` 

How do I change the model cache directory?

**Comment by nreimers** [comment]
You need to set:
SENTENCE_TRANSFORMERS_HOME

**Comment by gionapaolini** [comment]
> 
> 
> You need to set:
> SENTENCE_TRANSFORMERS_HOME
Great, thanks for the quick replies, is this documented somewhere?
