### ISSUE TITLE
ImportError: Module "sentence_transformers.models" does not define a "CLIPModel" attribute/class

### ISSUE THREAD

**Issue by Shivam2JDS** [UKPLab/sentence-transformers#882]
I am trying to implement Image-search on local machine, but it give this error. On colab it do not give any error.

sentence_transformers==1.0.4

**Comment by nreimers** [comment]
Hmm, the error indicates that an old sentence transformer version is used.

Are you sure, that sentence_transformers==1.0.4 is used locally?

**Comment by Shivam2JDS** [comment]
yes I am 100% sure

**Comment by nreimers** [comment]
Can you run
```
from sentence_transformers.models.CLIPModel import CLIPModel
```

Also note that torchvision must be installed

**Comment by Shivam2JDS** [comment]
Thank you, it worked, the tourchvision library was not installed
