### ISSUE TITLE
Cannot tokenize all words for Spanish

### ISSUE THREAD

**Issue by HariWu1995** [UKPLab/sentence-transformers#883]
I use pretrained **distil-USE version 2** for **Spanish** but several keywords became [UNK].

> encoder.tokenizer.tokenize("la foresto de halalaj manĝaĵoj - eĉ ne por ĉambroservo")
> Result: ['la', 'forest', '##o', 'de', 'hala', '##la', '##j', '[UNK]', '-', '[UNK]', 'ne', 'por', '[UNK]']

My thinking is that some bug occurs in the preprocessing step of WordPiece Tokenizer because this one should remove accents in the sentence, if any. 

My project is for multi-lingual task, so hard-coding should be considered as a solution if and only if there is no other choice.

**Comment by nreimers** [comment]
Hi,
the model is based on the distilled multilingual BERT model.  mBERT does not cover all characters, there was a threshold to only keep xx% of the characters and to ignore infrequent (rare) characters which become [UNK]

Looks like that mBERT did not see many ĉ in its training.

Maybe you can try the other multilingual models. They are based on xlm-r and have a better coverage.

**Comment by HariWu1995** [comment]
@nreimers My first thinking was `ĉ` should be normalized as `c` but it seems that I was wrong. Because my models were already trained based on distil-USE word embeddings (training on English, but inference on multi-languages) so I think I will hardcode these cases (ĉ -> c) and see what'll happen.
Thanks for your explanation!
