### ISSUE TITLE
word embedding

### ISSUE THREAD

**Issue by dinani65** [UKPLab/sentence-transformers#884]
can S-BERT be employed to compute similarity between two words instead of two sentences?

**Comment by nreimers** [comment]
Yes
https://www.sbert.net/docs/package_reference/SentenceTransformer.html#sentence_transformers.SentenceTransformer.encode

You set output_value to 'token_embeddings'

**Comment by dinani65** [comment]
```
from sentence_transformers import SentenceTransformer, util


model_brt = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')
a = model_brt.encode('Apple Inc.',   convert_to_tensor=True, output_value= 'token_embeddings')
b = model_brt.encode('Steve Jobs',  convert_to_tensor=True, output_value= 'token_embeddings')
score = util.pytorch_cos_sim(a, b)
print(score)
```
how to compute only a value as the cosine similarity?

**Comment by nreimers** [comment]
This gives you the token embeddings for all the tokens. You then need to find which token embedding corresponds to your token your are interested in
