### ISSUE TITLE
About Explicit Semantic Ranking

### ISSUE THREAD

**Issue by loretoparisi** [UKPLab/sentence-transformers#885]
I recently came across a ESR model for named entities ranking, like [here](https://www.mdpi.com/2078-2489/10/2/39/htm)
I'm using SBERT for sentences ranking as detailed in

https://www.sbert.netexamples/applications/retrieve_rerank/README.html

And I was wondering if there is a straight way to adapt or train SBERT to ESR.

**Comment by nreimers** [comment]
I am not an expert for ESR. Just from scanning it I don't know if it is really that promising, BERT models are quite powerful and they can figure out a lot of this, i.e. explicit named entity recognition is not that useful for many scenarios (in my opinion).

Sadly I don't know if there is a simple way to integrate it into SBERT

**Comment by loretoparisi** [comment]
@nreimers thank you!
