### ISSUE TITLE
Not able to load dpr-ctx_encoder-multiset-base

### ISSUE THREAD

**Issue by christopherfeld** [UKPLab/sentence-transformers#886]
**System**: Windows 10
**sentence_transformers version**: 1.0.4
**torch**: 1.8.1
**Python**: miniconda 3.8.5
**Similar issue**: seems I'm doing it right: https://github.com/UKPLab/sentence-transformers/issues/371
**Approach**: Cloned the subdir via huggingface into my 'src' directory: 
```
git lfs install
git clone https://huggingface.co/facebook/dpr-ctx_encoder-multiset-base
```

**Python code**: 
```
from sentence_transformers import SentenceTransformer, util
passage_encoder = SentenceTransformer('scr/dpr-ctx_encoder-multiset-base') 
```

**error**:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-12-ad4965918aa1> in <module>
      1 from sentence_transformers import SentenceTransformer, util
----> 2 passage_encoder = SentenceTransformer('scr/dpr-ctx_encoder-multiset-base')

~\Desktop\scripting\apps\trajectory\lib\site-packages\sentence_transformers\SentenceTransformer.py in __init__(self, model_name_or_path, modules, device)
    110                     with open(os.path.join(model_path, 'config.json')) as fIn:
    111                         config = json.load(fIn)
--> 112                         if config['__version__'] > __version__:
    113                             logger.warning("You try to use a model that was created with version {}, however, your version is {}. This might cause unexpected behavior or errors. In that case, try to update to the latest version.\n\n\n".format(config['__version__'], __version__))
    114 

KeyError: '__version__'
```

Love what you all are working on!!!

**Comment by nreimers** [comment]
SentenceTransformer consists of multiple modules:
https://www.sbert.net/docs/training/overview.html#creating-networks-from-scratch

You cannot simply load a transformer model and use it. You need at least some pooling layer that creates a fixed sized embedding out of it.


We also provide the DPR model:
https://www.sbert.net/docs/pretrained_models.html#dpr-models

wrapped in the right SentenceTransformer module structure.

You can just pass these names and they are downloaded automatically.
