### ISSUE TITLE
Method fit does not save the model to the provided parameter output_path

### ISSUE THREAD

**Issue by sstojanoska** [UKPLab/sentence-transformers#887]
The method fit fails to save the model on the path given to the output_path. 
Saving works only with 'model.save(<PATH>)'.  I just read that there should be Evaluator provided for this to work, but it should be well documented, since this way  a model trained for a very long time just goes to waste.

**Comment by nreimers** [comment]
It is already changed and will be part of the next release (if it not already released in the last version. not sure)

**Comment by nreimers** [comment]
Just checked, it is implemented in 1.0.4:
https://github.com/UKPLab/sentence-transformers/blob/v1.0.4/sentence_transformers/SentenceTransformer.py#L589

Please re-open when there is still an issue that a model is not saved after calling fit()

**Comment by sstojanoska** [comment]
Great! Thanks.
