### ISSUE TITLE
Cannot find 'stsb-roberta-base' on the website

### ISSUE THREAD

**Issue by happygirlzt** [UKPLab/sentence-transformers#890]
Hi, I wonder whether `roberta-base-nli-stsb-mean-tokens` is `stsb-roberta-base`. As I did not find `stsb-roberta-base` on https://huggingface.co/sentence-transformers, but in the doc you shared, there is. Thanks in advance!

**Comment by nreimers** [comment]
Yes roberta-base-nli-stsb-mean-tokens  and stsb-roberta-base are the same models

**Comment by happygirlzt** [comment]
I see. Many thanks for your reply. :)
