### ISSUE TITLE
Fine-tuning with additional features

### ISSUE THREAD

**Issue by petulla** [UKPLab/sentence-transformers#892]
Hi 

I'm looking to do binary classification, where my inputs are text and some additional numeric/one-hot encoded features. Is there support in this library for a final layerset + fine-tuning that can take additional inputs?

**Comment by nreimers** [comment]
It is not directly supported.

If your don't have too many features, you can add them as special token. You extend the vocab of the tokenizer.

Then you have texts like
[feat_A] [feat_C]  Your sentence that has feature A and C
[feat_D] A sentence only with feature D
....
