### ISSUE TITLE
Confused about the time complexity using Bert for most similar sentence pairs (10K sentences) 

### ISSUE THREAD

**Issue by goodman1204** [UKPLab/sentence-transformers#893]
In the paper, `Sentence-BERT: Sentence embeddings using siamese BERT-networks`, the authors make the following argument: 
- Finding in a collection of n = 10 000 sentences the pair with the highest similarity requires with BERT n·(n−1)/2 = 49 995 000 inference computations. On a modern V100 GPU, this requires about 65 hours.

My question:  
Why not directly get the averaged embedding for each sentence (10K time inference on BERT), then computing the similarity based on the embeddings (In this step, the time complexity is n^2, but not including BERT)? 
  
Also, if using  the proposed 'SBERT' to compute the cosine similarity between 10K sentences. Then, there will be n^2  pairs of sentences for SBERT to compute, which means , we need to use BERT n^2 times.  Why its time consumption is only 5 seconds? 

Can someone help to clear  my doubts?

**Comment by nreimers** [comment]
With a BERT Cross encoder you must compute scores for all sentence pairs. Hence you must compute about n**2/2 pairs.

With SBERT you compute the embedding for 10k sentences and then do cos Sim on these 10k embeddings.

**Comment by goodman1204** [comment]
> With a BERT Cross encoder you must compute scores for all sentence pairs. Hence you must compute about n**2/2 pairs.
> 
> With SBERT you compute the embedding for 10k sentences and then do cos Sim on these 10k embeddings.

Thanks @nreimers.  My doubts is why not use BERT to compute the embedding for the 10K sentence first, then do the cosine similarity based on the 10K embeddings.  BERT can take as input either one or two sentences, right?

**Comment by nreimers** [comment]
That's what SBERT is about.

If you take BERT without further fine-tuning the sentence embeddings you get are rather bad as shown in the paper.

**Comment by goodman1204** [comment]
Thanks @nreimers

**Comment by xu-song** [comment]
> That's what SBERT is about.
> 
> If you take BERT without further fine-tuning the sentence embeddings you get are rather bad as shown in the paper.

BERT's embedding is bad, but it has nothing to do with time complexity and precomputation.
