### ISSUE TITLE
Looking for Papers: Quora Question Pairs Similarity

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#898]
Hi @nreimers ,
we are looking for good reference papers about the similarity task for [Quora Question Pairs](https://www.kaggle.com/c/quora-question-pairs) reference dataset. Do you have an overview of this topic? Maybe you could name or link some of them?

Best would be to have papers which use "cosine similarity" and others who use "siamese networks with a neural network for pairwise comparison".

Many thanks
Philip

**Comment by nreimers** [comment]
Hi @PhilipMay 
Sadly I don't know good overview paper over the QQP dataset. 

An older paper on a related task:
https://www.aclweb.org/anthology/D18-1131/

**Comment by PhilipMay** [comment]
Thanks - closing this again.
