### ISSUE TITLE
Looking for a recommendation to use TF-IDF / BM25

### ISSUE THREAD

**Issue by PhilipMay** [UKPLab/sentence-transformers#899]
Hi @nreimers ,
many times you talk about TF-IDF / BM25 as a baseline to compare sentences.
Can you recommend an easy (but good) to use library to use TF-IDF / BM25?

PS: Maybe even with preprocessing...? :-)

Many thanks
Philip

**Comment by nreimers** [comment]
TF-IDF is also implemented here, but not really documented :)

Otherwise Gensim offers support for TF-IDF

For BM25 I like to use ElasticSearch. 

Otherwise, for a quick python only solution I like:
https://pypi.org/project/rank-bm25/

**Comment by PhilipMay** [comment]
ok. thanks. :+1:
