### ISSUE TITLE
Getting bad results

### ISSUE THREAD

**Issue by sekhar14** [UKPLab/sentence-transformers#9]
I was trying this solution as a question to question matcher. But on my data the results are very bad. Do you think finetune would help ?

**Comment by nreimers** [comment]
Hi,
yes, I also made that experience that the performance out-of-the-box is quite bad when I tried to retrieve similar computer science questions. But this was not only limited to this code, but also most of the other sentence embeddings methods (like InferSent etc.) perform poorly on this task. BM25 is really hard to beat on that task.

Fine-tuning on your data will definitely help.

I will soon release version 2 of this framework, which adds many new features and many new models. 

I also plan to train some models for question retrieval, but this will take longer until I can release them.

Check the MultipleNegativesRankingLoss if you want to fine-tune your model for question retrieval.

Let me know if you have questions how to tune your model.

**Comment by sekhar14** [comment]
Thanks for the quick response. Will try MultipleNegativesRankingLoss . The question retrieval usecase you mentioned do you have any specific dataset in mind.

**Comment by nreimers** [comment]
My student is working on these datasets:
- AskUbuntu
- Quora duplicate questions retrieval
- StackOverflow (similar questions retrieval)
- CQADupStack - Data from 12 stack-exchange forums
- WikiNews - Newsheadline paraphrase selection (new corpus created by us)

Currently  we have mainly run baselines on these datasets. Next will be to tune models to get a better retrieval performance than BM25.

**Comment by sekhar14** [comment]
Thanks a lot
