### ISSUE TITLE
looking forward to a recommendation about entity disambiguation

### ISSUE THREAD

**Issue by dinani65** [UKPLab/sentence-transformers#903]
I have some phrases in the input sentence and each phrase has some candidates to be selected as the best match one. For example, the sentence input is : Apple comapny. The candidates for 'apple' are:
1- fruit of the apple tree
2- American technology company based in Cupertino, California
by useing S-BERR, the figures for cosine similarity are 0.7881 and 0.7744, respectively.
What is your suggestion about using Bert modifications for disambiguation?

**Comment by nreimers** [comment]
Do you have training data for your task?

**Comment by dinani65** [comment]
Yes, I do

**Comment by nreimers** [comment]
Then you can fine-tune your model with: MultipleNegativesRankingLoss

https://www.sbert.net/docs/package_reference/losses.html#multiplenegativesrankingloss

**Comment by dinani65** [comment]
I am using WikiData to extract the candidates and  use a NIF dataset which has employed Wikidata entity URIs for its annotations.
Does it make sense to train a model with MultipleNegativesRankingLoss?
Since my training dataset is not large, is there any way to apply pre-trained models?

**Comment by nreimers** [comment]
@dinani65 
I am sadly not familar with the task or the dataset. So I don't know if it make sense or if there are good pre-training datasets / models
