### ISSUE TITLE
Update transformers requirement

### ISSUE THREAD

**Issue by SebiSebi** [UKPLab/sentence-transformers#91]
Currently, `transformers==2.2.1` is required although `sentence-transformers` will likely work with version 2.2.2 or newer.

This leads to annoying pip warning messages like the following one:
```
ERROR: sentence-transformers 0.2.4.1 has requirement transformers==2.2.1, but you'll have transformers 2.2.2 which is incompatible.
```

1. Is `transformers==2.2.1` really required?
2. Can you upgrade the requirement to `transformers>=2.2.1`? (I can submit a PR for this one).

Thanks!

**Comment by nreimers** [comment]
Hi @SebiSebi 
transformers==2.2.1 is not really required. It also works with 2.2.2 and 2.3.0.

Updating the requirement  to transfroermers>=2.2.1: 
The issue are breaking changes, that might occur in future versions of transformers.

There were many breaking changes when transformers increase the major version (i.e. from 0 to 1 to 2), but also in minor versions had breaking changes (for example from v2.0.0 => 2.1.0). So code which had the requirements transformers>=2.0.0 might break once transformers 2.1.0 was released.

The only option would be to have a requirement dependency like 2.2.* and hoping that there are no breaking changes between two x.x.* versions. But so far, transfomers used only seldom the latest part of the version number.

Im not sure if there are any got solutions to this issue?


In general, I can recommend to create virtual environments for different experiments. You often see certain incompatibilities, e.g., some code only works with tensorflow 1, while other code requires tensorflow 2.
