### ISSUE TITLE
Clarification on Loss function for document retrieval

### ISSUE THREAD

**Issue by aditya-malte** [UKPLab/sentence-transformers#919]
Hi,
So I was using SBERT, a great tool indeed but had a hard time deciding the ideal loss function for my particular case.
My dataset is basically list of tuples of format:
```
[ (<job description>, <resume>, <relevance_score>),
  (<job description>, <resume>, <relevance_score>),
......]
```
(relevance_score ranging from 0 to 5, could also be converted to discrete classes like “relevant”, “not relevant”, “slightly relevant,etc. if needed)

What would you suggest would be an optimal way to use SBERT? 

P.S. As suggested by @nreimers, I have also gone through MultipleNegativesRankingLoss as shown on [this link](https://www.sbert.net/examples/training/nli/README.html#multiplenegativesrankingloss). 
However, in my dataset there may be cases where i!=j but is relevant (eg. a recruiter going through N good matching candidates)

**Comment by nreimers** [comment]
You could try also CosineSimilarityLoss and ConstrativeLoss

At the end I recommend to test different losses and see what works on your dev dataset

**Comment by aditya-malte** [comment]
Yeah, it makes sense to try out different approaches than hypothesizing about them. 
One specific question regarding your reply though; for _**asymmetric**_ search would the other loss functions you mentioned pose a problem? Or should it be fine..
Thanks in advance.
Aditya

**Comment by nreimers** [comment]
It should be fine

**Comment by aditya-malte** [comment]
Great, thanks
