### ISSUE TITLE
Using existing hugging-face model

### ISSUE THREAD

**Issue by Jobu08** [UKPLab/sentence-transformers#92]
Hi, Thanks for you work.

I had following issue: I already had trained mulitlingual model from hugging-face, fine-tuned on my data and I needed to get embeddings from it for different purpose. I tried to use your library to get those embeddings from my model. I run into issues when I wanted to load already existing model. Is it possible to load not "raw" but existing fine-tuned model? 
I think it should be possible after changing your init method in BERT class. Maybe passing both model and tokenizer as parameters when intializing model. E.g.: `word_embedding_model = models.BERT('path  to existing model', tokenizer='bert-base-multilingual-cased')`

Let me know what you think and if my assumptions are correct.

**Comment by nreimers** [comment]
Hi @Jobu08 
This use case is already implemented. To get a mean pooling with your BERT weights:
```
# Use BERT for mapping tokens to embeddings
word_embedding_model = models.BERT('path/to/your/bert/transformers/model')

# Apply mean pooling to get one fixed sized sentence vector
pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])
```

This will load the model from disc and use it for mean pooling.

Note: The path should contain your model as well as the  tokenizer. You can the save-methods from huggingface-transformers to store you model / tokenizer to some folder.

Best
Nils Reimers

**Comment by Jobu08** [comment]
Well, I had my model saved but not the tokenizer, since I used the default one. That might be the issue.  Thanks for clarification
