### ISSUE TITLE
why SBERT is so fast?

### ISSUE THREAD

**Issue by Soulscb** [UKPLab/sentence-transformers#924]
I know the SBERT is fast, but  i think the structure cant reduce the matching number. so  hope you can teach me

**Comment by nreimers** [comment]
Not sure what you mean in specific? Fast in comparison to what?

**Comment by Soulscb** [comment]
65 hours to 5 seconds

**Comment by nreimers** [comment]
Details are in the paper.

Cosine similarity is extremely quick to compute. On a GPU, you can compute it in a fraction of seconds for thousands of pairs.

**Comment by Soulscb** [comment]
The main reason is that I think Sbert also needs to match 100,000 * 100,000 times
