### ISSUE TITLE
RuntimeError: The size of tensor a (532) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by hjing100** [UKPLab/sentence-transformers#929]
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default uncation.
RuntimeError: The size of tensor a (532) must match the size of tensor b (512) at non-singleton dimension 1

Maybe the sentence is too long, and not truncated ？

**Comment by nreimers** [comment]
Yes, the sentence is too long and your model has not specified what the max length is.

See:
https://www.sbert.net/examples/applications/computing-embeddings/README.html#input-sequence-length

**Comment by hjing100** [comment]
Thank you very much. Now it's ok.
