### ISSUE TITLE
model.encode embedding is always different when load albert from local

### ISSUE THREAD

**Issue by bamtercelboo** [UKPLab/sentence-transformers#931]
model.encode embedding is always different when load albert from local

word_embedding_model = models.Transformer('./Model/albert_tiny_zh_google_pytorch')

pooling_model = models.Pooling(word_embedding_model.get_word_embedding_dimension(),
                               pooling_mode_mean_tokens=True,
                               pooling_mode_cls_token=False,
                               pooling_mode_max_tokens=False)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])

emb1 = model.encode("pos机推广")
emb2 = model.encode("销售代表")

cos_sim = util.pytorch_cos_sim(emb1, emb2)
print(cos_sim)

tensor([[0.9603]])
tensor([[0.9652]])
tensor([[0.9629]])
tensor([[0.9477]])

give some advice please.

**Comment by nreimers** [comment]
This should not happen.

Does your model might have not all layers initialized? Transformers will then init them randomly.

You can check this by setting your logging level to info and see if you get some relevant log messages.

**Comment by bamtercelboo** [comment]
Thanks @nreimers 

1. when load albert local model

`word_embedding_model = models.Transformer('./Model/albert_tiny_zh_google_pytorch')
`

log info：

`Some weights of the model checkpoint at ./Model/albert_tiny_zh_google_pytorch were not used when initializing AlbertModel: ['bert.encoder.transformer.group.0.inner_group.0.attention.output.dense.weight', 'bert.encoder.transformer.group.0.inner_group.0.LayerNorm.weight', 'bert.encoder.transformer.group.0.inner_group.0.ffn.intermediate.dense.bias', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.key.bias', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.query.bias', 'bert.pooler.dense.weight', 'bert.encoder.transformer.group.0.inner_group.0.attention.output.dense.bias', 'bert.encoder.transformer.group.0.inner_group.0.LayerNorm_1.bias', 'cls.predictions.transform.dense.weight', 'bert.embeddings.position_embeddings.weight', 'bert.pooler.dense.bias', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.query.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'bert.embeddings.word_embeddings.weight', 'bert.encoder.transformer.group.0.inner_group.0.LayerNorm_1.weight', 'bert.encoder.transformer.group.0.inner_group.0.ffn.intermediate.output.dense.bias', 'bert.encoder.embedding_hidden_mapping_in.weight', 'cls.predictions.bias', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.value.bias', 'bert.embeddings.token_type_embeddings.weight', 'bert.encoder.transformer.group.0.inner_group.0.ffn.intermediate.output.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.value.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.embedding_hidden_mapping_in.bias', 'bert.encoder.transformer.group.0.inner_group.0.LayerNorm.bias', 'bert.embeddings.LayerNorm.weight', 'cls.predictions.decoder.weight', 'bert.encoder.transformer.group.0.inner_group.0.ffn.intermediate.dense.weight', 'bert.encoder.transformer.group.0.inner_group.0.attention.self.key.weight']`

2. when load bert_chinese local model

`word_embedding_model = models.Transformer('./Model/bert_chinese_pytorch')`

log info:
`Some weights of the model checkpoint at ./Model/bert_chinese_pytorch were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias']
`

As can be seen from the log, there are many encoders that are not initialized when Albert is loaded, and there are also few encoders when Bert is loaded. Therefore, the result of Albert's encode will change, while the result of Bert will remain the same

Is this a problem with the downloaded model, or is the local model not compatible with Albert in the sentence-transformer library? What's a good way to deal with it, thanks

**Comment by nreimers** [comment]
Sentence-transformers uses AutoModel from huggingface transformers:
````
from transformers import AutoModel
model = AutoModel.from_pretrained(your_name_or_path)
```

So it appears an issue with the downloaded model, that it is not compatible with AutoModel from huggingface transformers.

**Comment by bamtercelboo** [comment]
ok ,I get, thanks
