### ISSUE TITLE
Questions on Multilingual Knowledge Distillation and Problem running make_multilingual.py script

### ISSUE THREAD

**Issue by zerocstaker** [UKPLab/sentence-transformers#940]
Hi,
First of all, thank you so much for the well written code and the papers that show extremely good results with very elegant solutions! I am trying to use the knowledge distillation technique for multilingual and tried to run the script and have some questions regarding the loss for this task.

From the paper, it seems that the training loss is the sum of the MSE loss between student embedding on the source language and the teacher embedding, and that on the target language and the teacher embedding.

However, reading the code, It seems the ParallelSentencesDataset only returns an InputExample consisting of target sentence and the teacher embedding. The source sentence seems to be missing to calculate the total loss, and the MSELoss only calculates the loss between the the student embedding on target language sentence and the teacher embedding. Could you clarify how the models presented in the paper are actually trained and whether the script would calculate the loss between the source sentence and teacher embedding?

I wanted to run the script on my end to find out, but it seems I am getting errors when creating the [DataLoader](https://github.com/UKPLab/sentence-transformers/blob/a061e733b5f5399809b45c72792cac4186261f19/examples/training/multilingual/make_multilingual.py#L148), as it returns:

```
raise TypeError(default_collate_err_msg_format.format(elem_type))
TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'sentence_transformers.readers.InputExample.InputExample'>
```
I am using Pytorch 1.8.1 and have tried both sentence-transformers 1.1.1 (from pip install -U sentence-transformers) as well as 1.2.0 from install from source. Of course, this is definitely coming from Pytorch's DataLoader, but I notice this style of passing through Dataset to DataLoaders is present in many of the scripts in the examples folder, and so I wonder if I missed anything on my end.

**Comment by nreimers** [comment]
Thanks, I will have a look on the error.

It is correct, it just computes the MSE loss between the student embedding and the teacher embedding for individual sentences. But in the batch there are multiple sentences, e.g. eight English sentences, three German sentences, two Spanish sentences, five Chinese sentences....

These MSE scores are averaged for all sentence embedding pairs in a batch

**Comment by nreimers** [comment]
Hi,
I tried to run make_multilingual.py on my computer and in Colab and it works without issues.

Do you get the script when you start it or sometime later after certain number of steps?

Did you change something on the code?

**Comment by zerocstaker** [comment]
Hi, Thank you for the response. I finally understand the ParallelSentencesDataset and how it also contains the Engilsh sentences. I missed the part that for add_dataset, it also adds the original source  language to sentence_map, and thus will be treated as a sentence for student model.

As for the error, the only changes to the code is that the target_languges is set to `set(['de'])` instead of the entire list of languages to save time, and commenting out everything beyond the call to create DataLoader. The error occurs at that specific line when the DataLoader is generated, and so I wasn't able to get to the actual training steps.

I just tried to run it in on Colab and it worked, which leads me to generating a new environment on my local computer as well as updating pytorch. With the cache pytorch and the newly updated PyTorch I am still receiving the same error, and so I believe it must have something to do with the Pytorch or Pip and Anaconda cache stuff, which is a problem on my end.

Thank you so much for the help!
