### ISSUE TITLE
margin in OnlineContrastiveLoss?

### ISSUE THREAD

**Issue by ScottishFold007** [UKPLab/sentence-transformers#944]
What is the best value for the parameter margin for OnlineContrastiveLoss?Or how does the parameter margin, large or small, affect the training of OnlineContrastiveLoss?

**Comment by nreimers** [comment]
It is a value you need to tune for your task. If the margin is too small, the model will at some point not learn anymore. If it is too large, training becomes unstable.

**Comment by ScottishFold007** [comment]
> It is a value you need to tune for your task. If the margin is too small, the model will at some point not learn anymore. If it is too large, training becomes unstable.

I know it, thanks a lot!
