### ISSUE TITLE
TSDAE link is not found. 

### ISSUE THREAD

**Issue by ninasujit2016** [UKPLab/sentence-transformers#945]
Dear creators, 

I tried a few times to check out the TSDAE page, but it shows "Not found" . It is ok for other pages. 

Can you check what is the problem?

Thanks

**Comment by nreimers** [comment]
Thanks for pointing this out. Will fix it.

You can find the page here:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/unsupervised_learning/TSDAE/README.md

**Comment by ninasujit2016** [comment]
Thanks very much ! This link works.
