### ISSUE TITLE
Where do you tokenize your input examples?

### ISSUE THREAD

**Issue by Punchwes** [UKPLab/sentence-transformers#946]
Hi, I just want to ask a question about where the tokenization happens..

https://github.com/UKPLab/sentence-transformers/blob/25169a38676781cf60ac6db9a4823d7ac727f954/sentence_transformers/SentenceTransformer.py#L550

I noticed it is after this line... you obtain the input features from input examples.. but I cannot find where it directs to... could you give me some information on this... especially where should I modify when I want to have more inputs features...

Best,

**Comment by nreimers** [comment]
Here is the function to tokenize:
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/models/Transformer.py#L57
