### ISSUE TITLE
Multilingual Model Distillation Issue

### ISSUE THREAD

**Issue by hrsmanian** [UKPLab/sentence-transformers#948]
Hi,
  Am not sure if this is an issue with the code or something I am doing incorrectly. I want to do distillation on multilingual model 'distiluse-base-multilingual-cased-v1' and hence used the script 'model_distillation.py' from the examples section. Made the relevant changes to use Opus dataset instead of wiki and AllNLI etc. However, the script fails when loading the teacher model 'distiluse-base-multilingual-cased-v1' with the following error 

2021-05-22 17:39:14 - Remove layers from student. Only keep these layers: [1, 4, 5]
Traceback (most recent call last):
  File "model_distillation_modified.py", line 73, in <module>
    new_layers = torch.nn.ModuleList([layer_module for i, layer_module in enumerate(auto_model.encoder.layer) if i in layers_to_keep])
  File "/home1/rasundar/venv/sbert_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'DistilBertModel' object has no attribute 'encoder'

This happens for both v1 and v2 model. I am using
sentence-transformers==1.1.1
sentencepiece==0.1.91
tokenizers==0.10.2
torch==1.6.0
torchvision==0.7.0
tqdm==4.53.0
transformers==4.6.0

Any help is appreciated.

Thanks in advance
Ram

**Comment by nreimers** [comment]
For a DistilBERT model, you must change the `auto_model.encoder` to `auto_model.transformer` in the code.

Huggingface transformers sadly does not have a consistent naming in their different classes.

**Comment by hrsmanian** [comment]
Thanks a lot, that seemed to work. I also had to change num_hidden_layers to n_layers as mentioned in config.json.

 # auto_model.config.num_hidden_layers = len(layers_to_keep)                                                                                                                                              
    auto_model.config.n_layers = len(layers_to_keep)
