### ISSUE TITLE
train_mlm.py tokenizer files being overwritten?

### ISSUE THREAD

**Issue by JoshuaPlacidi** [UKPLab/sentence-transformers#949]
Hi, I have been using the train_mlm.py script and I believe the saved tokenized files are being overwritten when the model is saved.

When train_mlm.py is run it generates the dir:
```
bert-base-uncased-(date)
 |--> special_tokens_map.json
 |--> tokenizer_config.json
 |--> tokenizer.json
 |--> vocab.txt
```

However I believe these files get overwritten by `model.save_pretrained(output_dir)`:
```
print("Save tokenizer to:", output_dir)
tokenizer.save_pretrained(output_dir)

trainer.train()

print("Save model to:", output_dir)
model.save_pretrained(output_dir)
```

**Comment by nreimers** [comment]
No, they are not overwritten by that command. And even if, the tokenizer is static, ie it does not change during the training.

**Comment by JoshuaPlacidi** [comment]
I re-ran tests on this and it appears not to overwrite files and functions as intended.

For some reason the first time I used train_mlm.py the tokenized files were deleted when training concluded.
