### ISSUE TITLE
Regression objective function for the label with the range of [0,5]

### ISSUE THREAD

**Issue by ddehun** [UKPLab/sentence-transformers#95]
Hello!

I read the original paper of sentence-BERT, and I'm just not sure how to calculate the mean squared error loss for the objective function with the AFS dataset (range of [0,5]) and cosine similarity (range of [-1,1]). 

Is there any scaling to match the range of them (such as AFS 0 score -> -1, AFS 5 score-> +1 and interpolation), or is it okay to use the original values for loss calculation?

Thanks!

**Comment by nreimers** [comment]
Hi @ddehun 
The scores are normalized in the range 0...1 (i.e., divide the AFS score by 5).

I also experimented with normalizing the scores to -1...1, but that yielded worse results.

Best
Nils Reimers

**Comment by ddehun** [comment]
Thanks for your reply!
