### ISSUE TITLE
Update latest version on pip (1.2.0)

### ISSUE THREAD

**Issue by jkhalsa-arabesque** [UKPLab/sentence-transformers#951]
I can see that 1.2.0 isn't currently available via pip and only if I build from source.

If the pip version could be bumped up that would be amazing!

**Comment by nreimers** [comment]
Thanks for pointing this out. The pip version is updated.

Note, the previous version on pip (1.1.1) is identical to 1.2.0. I accidentally gave the version the wrong name version number on pypi (1.1.1 instead of 1.2.)
