### ISSUE TITLE
[feature request] max score for util.semantic_search

### ISSUE THREAD

**Issue by mathislucka** [UKPLab/sentence-transformers#955]
For the semanticsearch implementation in util.py I would find it useful to be able to pass in a maximum score for the resulting items. Sometimes I only want to find items below a certain cosine similarity. Of course I can strip extra results later, but I would have to set top-k higher than actually needed. From the implementation in util.py I can see that all items in the corpus are scored anyways, so it would be trivial to only return items below a certain score.

I'd be happy to try and provide a PR if you think this is a useful feature.

**Comment by nreimers** [comment]
Hi @mathislucka 
I think this feature would be a bit too special to be integrated into the library.

For implementation, the functions uses torch.topk so quickly find the largest topk functions. Your use case would make it more complex, as you would need to skip an unspecific number of elements. 

Not sure what the fastest implementation would be. Sorting the scores with Python is extremely slow compared to topk. Maybe sorting with Pytorch would be an option. Then you could run a binary search to find the section where the scores are just below your threshold and return the topk element from there.

Hope these comments help for your task.

Best
Nils

**Comment by mathislucka** [comment]
I would have thought the following approach would yield the desired result:

```python
# util.py ln 211
cos_scores = score_function(query_embeddings[query_start_idx:query_start_idx+query_chunk_size], corpus_embeddings[corpus_start_idx:corpus_start_idx+corpus_chunk_size])

cos_scores = np.sort(cos_scores)
cut_off = np.searchsorted(cos_scores, max_score)
cos_scores = cos_scores[:cut_off]

#....
```
According to this: https://towardsdatascience.com/surprising-sorting-tips-for-data-scientists-9c360776d7e numpy would be almost as fast as torch sort on gpu.

Still, I understand that this is too specific for your library.

**Comment by nreimers** [comment]
Yes, np.sort is faster than python, that is a good option.

In my experiments pytorch.topk was way faster than np.argpartition (which is faster than np.sort). It has also the advantage that you don't need the transfer to CPU & numpy, which can be quite slow. 

But np.sort and np.searchsorted appears a good solution for your case

**Comment by mathislucka** [comment]
Alright, thanks for your input. You always give very nice explanations! My dataset is not too large and I'm on CPU anyways so I guess np.sort will be ok for me.

Closing this now.
