### ISSUE TITLE
 how to understand next(data_iterator) ?

### ISSUE THREAD

**Issue by tiexi** [UKPLab/sentence-transformers#958]
please tell me why 

next(data_iterator) 

can let real word change to id
the examples has this 
try:
    data = next(data_iterator)
how to understand this code?
thank you

**Comment by nreimers** [comment]
Pytorch data loader has a collate function that is called before a batch is returned. The function transformers the input to token ids

**Comment by tiexi** [comment]
thank you 
and the one more thing i want to ask 
can i change the huggingface model inside architecture in the code?
if could where i need to change?

**Comment by nreimers** [comment]
Have a look here
https://sbert.net/docs/training/overview.html

Training of such a model is then needee

**Comment by tiexi** [comment]
thank you 
i will look 
thank you
