### ISSUE TITLE
How does SentenceTransformer from word embeddings work?

### ISSUE THREAD

**Issue by lambdaofgod** [UKPLab/sentence-transformers#963]
I'm interested in using a word embedding model that is not included yet.
I've read SentenceTransformer class code and I'm not sure how the ones using word embeddings work.

Are they just using WordEmbeddings module and then stacking another pooling layer on top of that, like the ones in benchmarks?

Also, what format does WordEmbeddings.from_text_file use? If it's not word2vec format, how do I convert my word embeddings into that?

**Comment by nreimers** [comment]
Hi,
for the format you can have a look at the files here:
https://public.ukp.informatik.tu-darmstadt.de/reimers/embeddings/

It is basically a raw text format file. First column is the word, followed by the numbers (floats) for the different dimensions.

Yes, if you combine a WordEmbeddings layer with a PoolingLayer, you just get a mean of all the word embeddings in a sentence.

**Comment by lambdaofgod** [comment]
> Yes, if you combine a WordEmbeddings layer with a PoolingLayer, you just get a mean of all the word embeddings in a sentence.
Is that what SentenceTransformer from word embeddings does by default?

**Comment by nreimers** [comment]
It uses a modular approach, where you can stack multiple layers:
https://www.sbert.net/docs/training/overview.html

**Comment by lambdaofgod** [comment]
so what happens for word embedding models?
If I do 

`model = SentenceTransformer(modules=[word_embedding_model, pooling_model])`

Then the pooling is explicit. But for 
`model = SentenceTransformer(<WORD_EMBEDDING_MODEL_NAME>)` 

what is the pooling? Does it use mean pooling by default?

**Comment by nreimers** [comment]
Yes, it uses mean pooling by default.
