### ISSUE TITLE
Question: unsupervised STS

### ISSUE THREAD

**Issue by AprilSongRits** [UKPLab/sentence-transformers#970]
Hi! Thanks a lot for this great library!

I have a question about the experiments on Section 4.1 Unsupervised STS in the paper Sentence-BERT.

Is it fair to compare BERT without fine-tuning and SBERT after fine-tuning with labeled data?
You know, the BERT can also be fine-tuned with NLI data, and then use [CLS] or Avg. BERT embeddings to represent Sentence.

Could you please share your thoughts on it?

**Comment by nreimers** [comment]
Hi @AprilSongRits 
The results for BERT without fine-tuning is primarily for showing that BERT, without fine-tuning, does not work well.

Taking avg. GloVe embeddings is a popular method, as it works quite good. So there I wanted to show that you cannot do this with BERT and take the CLS token or just do avg. BERT embeddings, but some type of fine-tuning is needed. Here of course you could compare training SBERT vs. a BERT Cross-Encoder trained on NLI data.

**Comment by AprilSongRits** [comment]
Thank you so much for your explanation!

Do you have any experience in comparing SBERT-NLI vs. a BERT Cross-Encoder trained on NLI data on unsupervised STS?
I'm just wondering that will these two kinds of fine-tuning methods have a big difference.

**Comment by nreimers** [comment]
Hi,
no experiences on this. But you can try and evaluate the BERT Cross-Encoder NLI on that task.

**Comment by AprilSongRits** [comment]
Thanks for your reply!
