### ISSUE TITLE
why cls_token = output_token[:,0,:] ?

### ISSUE THREAD

**Issue by tiexi** [UKPLab/sentence-transformers#972]
in Trabsformer class

  def forward(self, features):
          
         """Returns token_embeddings, cls_token"""
          trans_features = {'input_ids': features['input_ids'], 'attention_mask': features['attention_mask']}
          if 'token_type_ids' in features:
              trans_features['token_type_ids'] = features['token_type_ids']
          output_states = self.auto_model(**trans_features, return_dict=False)
          output_tokens = output_states[0]
  
          cls_tokens = output_tokens[:, 0, :]  # CLS token is first token
          features.update({'token_embeddings': output_tokens, 'cls_token_embeddings': cls_tokens, 'attention_mask': features['attention_mask']})

when i use pycharm debug i see output_states have two element 

![060101](https://user-images.githubusercontent.com/19373120/120279234-c946e580-c2e8-11eb-93cb-05935fb5b1db.png)
![060102](https://user-images.githubusercontent.com/19373120/120279254-cd730300-c2e8-11eb-8f7a-f5d5d173ad06.png)
![060103](https://user-images.githubusercontent.com/19373120/120279264-cf3cc680-c2e8-11eb-9dc3-9822b4620865.png)

4 is batch_size

is 0 element token and 1 element cls ?

cls_tokens = output_tokens[:, 0, :]  is correct?

if not what's the 1 element meaning?

**Comment by nreimers** [comment]
0 contains the contextualized word embeddings from BERT, while 1 contains the pooler output that BERT used for the next sentence prediction task.

**Comment by tiexi** [comment]
thanks for your response i understand

thank you
