### ISSUE TITLE
Different Parameters for 2 BERT Networks / Different processing after the BERT output in S-BERT

### ISSUE THREAD

**Issue by GMago123** [UKPLab/sentence-transformers#974]
Hi,
The scene of our problem is: 
We have Questions set Q and Answers set A. For every q in set Q, we want to find the correct answer a in set A. The q, a in correct question-answer pair have some common semantic features but their own semantic features are different. **So we want to let the 2 BERT in S-BERT do not share their parameters, or the BERT's output of two sentences (q and a) can be fed into different dense layer.**
However, the code of SentenceTransformer for compute sentence similarities implies that the the first sentence and the second sentence must be fed into same network to get their feature vectors.
Is there any better solution for this problem without changing the source code for SentenceTransformer?

**Comment by nreimers** [comment]
In version 0.4.1 asymmetric models were introduced:
https://github.com/UKPLab/sentence-transformers/releases/tag/v0.4.1

The code is still experimental.

In my experiments (and also others report similar results), using the same BERT network for both Q and A works better than using independent networks.

**Comment by GMago123** [comment]
Thanks. By the way, if I use this asymmetric model, how can I freeze the parameters of BERT in the training of SentenceTransformer?

> In version 0.4.1 asymmetric models were introduced:
> https://github.com/UKPLab/sentence-transformers/releases/tag/v0.4.1
> 
> The code is still experimental.
> 
> In my experiments (and also others report similar results), using the same BERT network for both Q and A works better than using independent networks.

**Comment by nreimers** [comment]
Just have a look at the pytorch (or maybe transformers) documentation how to freeze layers.

**Comment by GMago123** [comment]
Thank you very much for your response. I have solved my problems here.
