### ISSUE TITLE
Multilingual MiniLM error

### ISSUE THREAD

**Issue by sersoage** [UKPLab/sentence-transformers#975]
Hi, I am trying to train a cross encoder using Multilingual MiniLM but i am facing this issue while loading it

stat: path should be string, bytes, os.PathLike or integer, not NoneType

Seems like it is not related to sentence_transformers but with the model card, the AutoTokenizer is not working, now that sentence_transformers is "part" of HF ;) could it be fixed?
Thanks

**Comment by nreimers** [comment]
Hi @sersoage 
Yes, the Multilingual MiniLM has the issue that the authors did not create a clean config version. You must use an xlm-roberta-base tokenizer, with a BERT architecture of MiniLM. The authors did not specify the tokenizer that should be used for the multilingual MiniLM model, hence, you must do this by yourself.

You can load it like this:
```
from sentence_transformers import CrossEncoder

model = CrossEncoder('microsoft/Multilingual-MiniLM-L12-H384', tokenizer_args={'tokenizer_class':  'XLMRobertaTokenizerFast'}, num_labels=1)
print(model.predict(["Hello World", "A test"]))
```

When saved on disc, you can check the config.json. It must have an entry 'tokenizer_class' with the value 'XLMRobertaTokenizerFast'

**Comment by sersoage** [comment]
Great solution  I had changed the CrossEncoder class, but like yours better :).
Thanks as usual for the quick reply!
