### ISSUE TITLE
Strategy on using Sentence Transformers downstream- Train from scratch or from trained? 

### ISSUE THREAD

**Issue by sid-sundrani** [UKPLab/sentence-transformers#979]
The task is to find semantic similarity of pairs of very short text. Numerous trained sentence transformers are available for semantic similarity such as `paraphrase-mpnet-base-v2` , `paraphrase-TinyBERT-L6-v2`, `paraphrase-distilroberta-base-v2`  etc. 

In what kinds of tasks would it be advisable to train on the custom dataset by continuing training of the above trained models? which have already been trained on sentence similarity tasks. Or would it be better to train from scratch, from a pretrained bert or so? 

@nreimers thoughts?

**Comment by nreimers** [comment]
Hi @sid-sundrani 
Continue training from these models will usually be better, especially when your task is related to what these models have been trained for.
