### ISSUE TITLE
Bug in Pooling module if using concatenation of representations

### ISSUE THREAD

**Issue by trangham283** [UKPLab/sentence-transformers#98]
Hello,

First of all, thank you for this beautiful codebase! Everything is really easy to understand and follow. 

I believe this [line](https://github.com/UKPLab/sentence-transformers/blob/b307063782ae2f1014a73262e1d29c910f9b4cf3/sentence_transformers/models/Pooling.py#L33) is buggy when setting all pooling modes to true, and if the LSTM or CNN is used on top of word embeddings. The issue is that cls_token keeps the same dimension as the input word embeddings, but max/mean pooling of representations has the dimension resulting from LSTM's hidden dimension or CNN's out_channels*len(kernel_sizes). 

I think the following should fix it, but would require adding both input_embedding_dimension and word_embedding_dimension as pooling model's inputs. I'm not sure how standard it is to use cls_token_embedding with other token embeddings though, so maybe it's not even that useful to fix. 

`pooling_mode_multiplier = sum([pooling_mode_max_tokens, pooling_mode_mean_tokens, pooling_mode_mean_sqrt_len_tokens])`
`self.pooling_output_dimension = (pooling_mode_multiplier * input_embedding_dimension) + int(pooling_mode_cls_token) * word_embedding_dimension`

where
`word_embedding_dimension = word_embedding_model.get_word_embedding_dimension()`
`input_embedding_dimension = net.get_word_embedding_dimension()`

and net is LSTM() or CNN() etc.

**Comment by nreimers** [comment]
Hi @trangham283 
Thanks for pointing this out.

The LSTM and CNN models do not have a CLS token.

CLS token is something special that was added in BERT, that is added in-front of the sentence. The network output for the CLS token can then be used for example for classification. In BERT / a transformer network, each output depends on all inputs, i.e., the CLS token output can encode all the information from a sentence.



Applying the same idea to LSTM / CNN networks and adding a CLS token would not make so much sense:
CNN-Networks: The CLS token would only depend on the first 1 or 2 words of the sentence, all other words would be ignored.
Bidirectional-LSTM-Networks: The output would depend only on the first token for the forward pass and on all tokens for the backward pass.

For this reason, I did not add a CLS token output for the LSTM / CNN modules.

Best
Nils Reimers
