### ISSUE TITLE
display loss in progressbar while training

### ISSUE THREAD

**Issue by sid-sundrani** [UKPLab/sentence-transformers#983]
What do you think about displaying the training loss in the progress bar? @nreimers 

Currently, with the `model.fit` method, there is no logging of training loss/metrics afaik, so they training statistics cannot be seen during, except for eval. Maybe just adding training loss to the progress bar might be helpful?

**Comment by nreimers** [comment]
Currently this is not supported.

It is planned for one of the next versions to include better logging of different train and eval metrices.

**Comment by viveksck** [comment]
Has there been any update on this feature request?

**Comment by nreimers** [comment]
@viveksck Sadly no progress so far.
