### ISSUE TITLE
Question about ANCE Pretrained Model Name

### ISSUE THREAD

**Issue by Yu-Shi** [UKPLab/sentence-transformers#985]
Hello,

I'm recently using the ANCE checkpoint. I find the name "msmarco-roberta-base-ance-fristp" weird. "fristp" seems to be a typo.

Shi Yu

**Comment by nreimers** [comment]
Hi @Yu-Shi 
It follows the name from the authors:
https://github.com/microsoft/ANCE/

FirstP stands for FirstParagraph, i.e. for longer documents they just encode the first paragraph of the document.

**Comment by Yu-Shi** [comment]
I know FirstP, but the checkpoint name is msmarco-roberta-base-ance-**fristp**!

**Comment by nreimers** [comment]
Thanks, didn't notice the flip of the characters. Will update it.
