### ISSUE TITLE
Extract the training parameters of a trained model

### ISSUE THREAD

**Issue by gregskol** [UKPLab/sentence-transformers#986]
Hi,
I am fine-tuning a few pre-trained models on my own dataset and then saving them. 

Now, I am trying to find if the training parameters, like number of epochs, batch size, are stored anywhere and I couldn't see anything inside the folder of the model.

Is it possible to extract these parameters?

Thank you in advance

**Comment by nreimers** [comment]
They are not saved. You would need to save it your

**Comment by gregskol** [comment]
Ok, thank you for your swift response.
