### ISSUE TITLE
TextCNN on token_embeddings ?

### ISSUE THREAD

**Issue by huubinh49** [UKPLab/sentence-transformers#996]
I am trying to finetune to extract more information from BERT model. Can I use SentenceTransformer for returning token_embbedings and apply sentence_transformers.models.CNN as TextCNN on this token embeddings?

**Comment by nreimers** [comment]
Yes, here is an example:
https://github.com/UKPLab/sentence-transformers/blob/master/examples/training/avg_word_embeddings/training_stsbenchmark_cnn.py

However, I would not expect an improvement from this. BERT is already a powerful model, adding a CNN will not really help.
