### ISSUE TITLE
load sentence transformer model using huggingface `AutoModel`

### ISSUE THREAD

**Issue by rakesh4real** [UKPLab/sentence-transformers#997]
Can we load saved sentence transformer using hugging face's AutoModel?

```python
AutoModel.from_pretrained('/path/to/trained-sentence-transformer/output')

# or using `AutoModel.from_config(...)`
```

Main purpose for which I intend to do this is to test zero-shot-classification pipeline from Hf using the embedding model trained. The embedding model is trained similar to quora-duplicate-questions binary classification task using

**Comment by nreimers** [comment]
Yes, you can load it. But the zero-shot-classification pipeline from HF will not work, as it uses a different approach.

But you can use this model for zero shot classification.

What you do:
- You encode all your labels (label sentences)
- You encode your input
- You compute the cosine similarity between the input and the label embeddings
- The label sentence with the highest cosine similarity is your predicted label for the input

**Comment by rakesh4real** [comment]
Thankyou for the imformation. But, I trained `stsb-distilbert-base`  using online contrastive loss. But I cannot load the model as Hf model using `Automodel.from_pretrained(output/training_OnlineContrastiveLoss-date)`. Script I used very similar to `examples/training/quora_duplicate/questions/training_online ContrastiveLoss.py`

**Comment by nreimers** [comment]
You need to load the 0_Transformer folder you find in your output folder
