### ISSUE TITLE
question on how certain text-similarity datasets were trained on

### ISSUE THREAD

**Issue by sid-sundrani** [UKPLab/sentence-transformers#998]
The pre-trained `Sentence Embedding Models` have been trained on several datasets. I wanted to know how datasets such as coco_captions, flipkr_30k captions, and StackExchange duplicate questions were used for training? Since they do not come with labeled similar question pairs, how were the labels generated?

coco_captions and flipkr_30k captions data don't seem to have text pairs defined indicating semantic similarity, so how were these used? Same with the  StackExchange duplicate questions- the duplicate questions can be retrieved but I don't think a pair of duplicate questions can be queried so how was this used? 

Would be great if you could shed some light on these

**Comment by sid-sundrani** [comment]
Got it, thanks 

For the StackExchange pairs, there would've been only binary labels though. I'm curious if the pairs were only trained on positive examples? Or negative examples as well? It seems to be the case that training on negative examples in the binary fashion with MSE loss could lead to the model not learning meaningful representations in cases where the negative samples are somewhat similar but labelled as negative (0)

**Comment by nreimers** [comment]
They were trained on positives pairs and all other examples in a batch were used as negatives examples.
